### ISSUE TITLE
ensure parameter listings are sequences and fail if they are single use iterators

### ISSUE THREAD

**Issue by n1ywb** [pytest-dev/pytest#1398] opened 2016-02-18 20:15 UTC
I set `@fixture(params=some_iterator)` and only the first test function using the fixture was executed while the others were skipped without explanation. Eventually I realized that params had to be a list.

It would be great if the fixture decorator type-checked params and threw an exception if it's an iterator, or at least explained why it was skipping the tests.

**Comment by The-Compiler** [comment] 2016-02-19 06:05
Can you show a reproducer?

This works:

```python
import pytest

def gen():
    yield 1
    yield 2

@pytest.fixture(params=gen())
def fixt(request):
    return request.param

def test_foo(fixt):
    print(fixt)
```

```
$ py.test x.py  -s
=============== test session starts ================
platform linux -- Python 3.5.1, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/florian/tmp, inifile: 
plugins: mock-0.10.1
collected 2 items 

x.py 1
.2
.

============= 2 passed in 0.01 seconds =============
```

```
$ py.test2 x.py -s
=============== test session starts ================
platform linux2 -- Python 2.7.11, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/florian/tmp, inifile: 
collected 2 items 

x.py 1
.2
.

============= 2 passed in 0.00 seconds =============
```

**Comment by RonnyPfannschmidt** [comment] 2016-02-19 07:27
Add a second test using the same generator instance

**Comment by n1ywb** [comment] 2016-02-19 15:21
```
@pytest.fixture(params=xrange(3))
def myfixture(request):
    return reqeust.param

def test_1(myfixture):
    print myfixture

def test_2(myfixture):
    print myfixture
```


On Fri, Feb 19, 2016 at 2:27 AM, Ronny Pfannschmidt <
notifications@github.com> wrote:

> Add a second test using the same generator instance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pytest-dev/pytest/issues/1398#issuecomment-186102455>.
>



-- 
73 de n1ywb

**Comment by n1ywb** [comment] 2016-02-19 21:14
The best fix is probably to just use params to construct a new list; if it's already a list it will be a no-op, if it's an iterator it will be iterated once and turned into a list which can then be iterated any number of times.

Or change it so it only has to iterate params once.

**Comment by nicoddemus** [comment] 2016-02-19 21:21
Thanks @n1ywb for the reproducible example.

**Comment by nicoddemus** [comment] 2016-02-20 16:53
@n1ywb I tried your example and it works for me:

```python
import pytest

@pytest.fixture(params=xrange(3))
def myfixture(request):
    return request.param

def test_1(myfixture):
    print myfixture

def test_2(myfixture):
    print myfixture
```

```
platform win32 -- Python 2.7.11, pytest-2.8.6, py-1.4.31, pluggy-0.3.1 -- X:\pytest\.env27\Scripts\python.exe
cachedir: .cache
rootdir: X:\pytest, inifile: tox.ini
collected 6 items

foo.py::test_1[0] PASSED
foo.py::test_1[1] PASSED
foo.py::test_1[2] PASSED
foo.py::test_2[0] PASSED
foo.py::test_2[1] PASSED
foo.py::test_2[2] PASSED

========================== 6 passed in 0.02 seconds ===========================
```

Using a generator like @The-Compiler suggested also produces the same results. Any hints?

**Comment by n1ywb** [comment] 2016-02-20 20:42
shit... I didn't actually test that before I sent it, I just assumed it
would fail... I'll try again.

On Sat, Feb 20, 2016 at 11:53 AM, Bruno Oliveira <notifications@github.com>
wrote:

> @n1ywb <https://github.com/n1ywb> I tried your example and it works for
> me:
>
> import pytest
> @pytest.fixture(params=xrange(3))def myfixture(request):
>     return request.param
> def test_1(myfixture):
>     print myfixture
> def test_2(myfixture):
>     print myfixture
>
> platform win32 -- Python 2.7.11, pytest-2.8.6, py-1.4.31, pluggy-0.3.1 -- X:\pytest\.env27\Scripts\python.exe
> cachedir: .cache
> rootdir: X:\pytest, inifile: tox.ini
> collected 6 items
>
> foo.py::test_1[0] PASSED
> foo.py::test_1[1] PASSED
> foo.py::test_1[2] PASSED
> foo.py::test_2[0] PASSED
> foo.py::test_2[1] PASSED
> foo.py::test_2[2] PASSED
>
> ========================== 6 passed in 0.02 seconds ===========================
>
> Using a generator like @The-Compiler <https://github.com/The-Compiler>
> suggested also produces the same results. Any hints?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pytest-dev/pytest/issues/1398#issuecomment-186650623>.
>



-- 
73 de n1ywb

**Comment by RonnyPfannschmidt** [comment] 2016-07-19 09:33
xrange is not an iterator

switching it for iter(xrange(...)) should be sufficient tho

**Comment by Zac-HD** [comment] 2019-06-24 05:23
Now fixed: if `params` is cast to `list` unless it is None or an instance of list or tuple.

https://github.com/pytest-dev/pytest/blob/3d01dd3adf56abecfda4b785ef280217b615c527/src/_pytest/fixtures.py#L1030-L1035

**Comment by RonnyPfannschmidt** [comment] 2019-06-24 05:53
a setup like that breask the parameterize marker when given iterators and reusing

**Comment by Zac-HD** [comment] 2019-06-24 05:58
How does it break?  The test case works perfectly for me: `6 passed in 0.04 seconds`

```python
import pytest

@pytest.fixture(params=iter(range(3)))
def myfixture(request):
    return request.param

def test_1(myfixture):
    print(myfixture)

def test_2(myfixture):
    print(myfixture)
```

**Comment by RonnyPfannschmidt** [comment] 2019-06-24 06:10
sorry, i mixed up the issue,

`fixture(params)` is indeed fine, the trouble starts when using it with the `parametrize` marker

**Closed by RonnyPfannschmidt** 2019-06-24 06:10 UTC
Labels: topic: parametrize, type: backward compatibility, type: bug
