### ISSUE TITLE
linux下，快速多次运行pytest后，pytest在运行会失败

### ISSUE THREAD

**Issue by huangceshi** [pytest-dev/pytest#8206] opened 2020-12-30 05:55 UTC
```
[2020-12-30 12:58:26,833] [log.py:5] [log:recordlog] [INFO]- Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 265, in wrap_session
    config._do_configure()
  File "/usr/local/lib/python3.6/site-packages/_pytest/config/__init__.py", line 982, in _do_configure
    self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 308, in call_historic
    res = self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/terminal.py", line 228, in pytest_configure
    reporter = TerminalReporter(config, sys.stdout)
  File "/usr/local/lib/python3.6/site-packages/_pytest/terminal.py", line 332, in __init__
    self._tw = _pytest.config.create_terminal_writer(config, file)
  File "/usr/local/lib/python3.6/site-packages/_pytest/config/__init__.py", line 1530, in create_terminal_writer
    tw = TerminalWriter(file=file)
  File "/usr/local/lib/python3.6/site-packages/_pytest/_io/terminalwriter.py", line 68, in __init__
    if hasattr(file, "isatty") and file.isatty() and sys.platform == "win32":
ValueError: I/O operation on closed file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/python/testPT/api/util/util.py", line 49, in nowrun
    pytest.main(['--alluredir',f'result/{route}'])
  File "/usr/local/lib/python3.6/site-packages/_pytest/config/__init__.py", line 163, in main
    config=config
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 289, in wrap_session
    config.notify_exception(excinfo, config.option)
  File "/usr/local/lib/python3.6/site-packages/_pytest/config/__init__.py", line 1040, in notify_exception
    sys.stderr.write("INTERNALERROR> %s\n" % line)
ValueError: I/O operation on closed file.
```

**Comment by huangceshi** [comment] 2020-12-30 05:55
pytest 版本号 6.2.1

**Comment by Zac-HD** [comment] 2021-01-01 07:45
Hi @huangceshi - unfortunately we can't help without a **reproducing example of the bug**.

Please report the exact input file(s) and command(s) you ran to get this error, and we'll see what we can do.  Even better, a *minimal* example - where you've removed as much irrelevant code as possible - will make our work easier and faster 🙂

**Comment by Zac-HD** [comment] 2021-02-01 06:59
I'm closing this issue because we can't fix it without a reproducing example.  If anyone can provide a short script that we can run to demonstrate this error, we'll be happy to reopen the issue!

**Closed by Zac-HD** 2021-02-01 06:59 UTC
Labels: status: needs information

**Comment by cnlydia** [comment] 2023-01-10 07:40
I meet the same error, the reason is run pytest.main in one process and different thread :(
