### ISSUE TITLE
Pytest silently ignores python packages named "build"

### ISSUE THREAD

**Issue by Danon** [pytest-dev/pytest#8310] opened 2021-02-02 13:56 UTC
Create such structure
```
project
├── __init__.py
└── project
    └── __init__.py
└── build
    └── __init__.py
test
├── __init__.py
└── project
    ├── __init__.py
    └── test_foo.py
└── build
    ├── __init__.py
    └── test_bar.py
```

- [x] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [x] minimal example if possible

```
pytest~=6.2.2
```

When I run `pytest` tests in `test/` folder, it detects the tests in `test/` folder as well as `test/project/` folder, but not in `test/build/` folder. If I rename the package to something like `test/builder/` it works.

**Comment by nicoddemus** [comment] 2021-02-02 14:12
Hi @Danon,

That's by design, `build` is part of the default values for the [`norecursedirs`](https://docs.pytest.org/en/stable/reference.html#confval-norecursedirs) option. You can tweak it to suit your needs.

Looking at the list, seems this could be improved because a few of them (`build`, `dist`, `node_modules`, `venv`) could probably only be ignored if found near the root directory, but there's no way currently to distinguish between them.

**Comment by Danon** [comment] 2021-02-02 14:29
@nicoddemus Thank you for a blazing fast answer.

Well, I supposed I just need to rename my packages.

**Comment by nicoddemus** [comment] 2021-02-02 14:50
Also works! Hehehe.

Closing for now then. 👍

**Closed** 2021-02-02 14:50 UTC
Labels: type: question
