### ISSUE TITLE
OSError: [WinError 87] The parameter is incorrect

### ISSUE THREAD

**Issue by Nitin4994** [pytest-dev/pytest#7630] opened 2020-08-08 14:51 UTC
```
C:\Users\hp>pytest --version
Traceback (most recent call last):
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37-32\Scripts\pytest.exe\__main__.py", line 9, in <module>
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\config\__init__.py", line 180, in console_main
    code = main()
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\config\__init__.py", line 136, in main
    config = _prepareconfig(args, plugins)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\config\__init__.py", line 314, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\helpconfig.py", line 99, in pytest_cmdline_parse
    config = outcome.get_result()  # type: Config
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\config\__init__.py", line 932, in pytest_cmdline_parse
    self.parse(args)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\config\__init__.py", line 1204, in parse
    self._preparse(args, addopts=addopts)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\config\__init__.py", line 1108, in _preparse
    early_config=self, args=args, parser=self._parser
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 182, in _multicall
    next(gen)  # first yield
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\capture.py", line 154, in pytest_load_initial_conftests
    _py36_windowsconsoleio_workaround(sys.stdout)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\capture.py", line 145, in _py36_windowsconsoleio_workaround
    sys.stdin = _reopen_stdio(sys.stdin, "rb")
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\capture.py", line 138, in _reopen_stdio
    open(os.dup(f.fileno()), mode, buffering),  # type: ignore[arg-type]
OSError: [WinError 87] The parameter is incorrect
```

```
C:\Users\hp>pytest -v
Traceback (most recent call last):
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37-32\Scripts\pytest.exe\__main__.py", line 9, in <module>
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\config\__init__.py", line 180, in console_main
    code = main()
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\config\__init__.py", line 136, in main
    config = _prepareconfig(args, plugins)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\config\__init__.py", line 314, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\helpconfig.py", line 99, in pytest_cmdline_parse
    config = outcome.get_result()  # type: Config
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\config\__init__.py", line 932, in pytest_cmdline_parse
    self.parse(args)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\config\__init__.py", line 1204, in parse
    self._preparse(args, addopts=addopts)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\config\__init__.py", line 1108, in _preparse
    early_config=self, args=args, parser=self._parser
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\pluggy\callers.py", line 182, in _multicall
    next(gen)  # first yield
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\capture.py", line 154, in pytest_load_initial_conftests
    _py36_windowsconsoleio_workaround(sys.stdout)
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\capture.py", line 145, in _py36_windowsconsoleio_workaround
    sys.stdin = _reopen_stdio(sys.stdin, "rb")
  File "c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\capture.py", line 138, in _reopen_stdio
    open(os.dup(f.fileno()), mode, buffering),  # type: ignore[arg-type]
OSError: [WinError 87] The parameter is incorrect
```

- [x] a detailed description of the bug or suggestion
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

**Comment by nicoddemus** [comment] 2020-08-08 18:18
Hi @Nitin4994,

Can you please post your `pip list`, as was noted in the template description?

n general try to acknowledge the template description, not only for pytest but open source projects in general, as that list is there for a reason. 👍

**Comment by Nitin4994** [comment] 2020-08-09 01:46
C:\Users\hp>pip list
Package                Version
---------------------- ---------
appdirs                1.4.4
atomicwrites           1.4.0
attrs                  19.3.0
certifi                2020.6.20
cffi                   1.14.1
click                  7.1.2
colorama               0.4.3
cryptography           3.0
distlib                0.3.1
Django                 2.2.7
ecdsa                  0.15
filelock               3.0.12
Flask                  1.1.2
funcy                  1.14
future                 0.18.2
importlib-metadata     1.7.0
iniconfig              1.0.1
itsdangerous           1.1.0
Jinja2                 2.11.2
langdetect             1.0.8
MarkupSafe             1.1.1
more-itertools         8.4.0
mysql-connector-python 8.0.18
mysqlclient            1.4.6
packaging              20.4
pip                    20.2.1
pluggy                 0.13.1
prettytable            0.7.2
py                     1.9.0
pycparser              2.20
pylibscrypt            1.8.0
PyMySQL                0.10.0
pyparsing              2.4.7
pytest                 6.0.1
pytz                   2020.1
scrypt                 0.8.15
setuptools             40.8.0
six                    1.15.0
SQLAlchemy             1.3.18
sqlparse               0.3.1
toml                   0.10.1
toolz                  0.10.0
ujson                  3.1.0
urllib3                1.25.10
virtualenv             20.0.25
voluptuous             0.11.7
w3lib                  1.22.0
Werkzeug               1.0.1
zipp                   3.1.0

C:\Users\hp>

**Comment by nicoddemus** [comment] 2020-08-15 15:29
Not really sure how to investigate this, I cannot reproduce the problem.

**Comment by Zac-HD** [comment] 2021-02-01 06:48
I'm closing this issue because we can't fix it without a reproducing example.  If anyone can provide a short script that we can run to demonstrate this error, we'll be happy to reopen the issue!

**Closed by Zac-HD** 2021-02-01 06:48 UTC
Labels: plugin: capture, status: needs information
