### ISSUE TITLE
Add support for pyproject.toml

### ISSUE THREAD

**Issue by mrh1997** [pytest-dev/pytest#6398] opened 2020-01-03 17:57 UTC
With [PEP-518](https://www.python.org/dev/peps/pep-0518/) python tools are starting to switch over to ``pyproject.toml``. 

As pytest is a very widespread tool used in a lot of python projects, it would make a lot of sense if it also follows this strategy. I understand that this is not as easy as it sound on a first glance, as ``pyproject.toml`` has a different file format. But pytest could follow the same approach as  [tox](https://tox.readthedocs.io/en/latest/config.html)) and add the feature in two steps:
 1. Add ``pyproject.toml`` to the list of scanned files (like ``setup.cfg`` and ``tox.ini``) but interpret it as a .ini file (this would be make a lot of projects work with little effort)
 2. Add real TOML-file support

**Comment by The-Compiler** [comment] 2020-01-03 18:17
Duplicate of #1556

**Closed by The-Compiler** 2020-01-03 18:17 UTC
