### ISSUE TITLE
Bug: `filterwarnings` doesn't work for `pytest` plugins

### ISSUE THREAD

**Issue by jamesbraza** [pytest-dev/pytest#12756] opened 2024-08-30 17:13 UTC
In https://github.com/pytest-dev/pytest-asyncio/commit/c74d1c3fba1afac0b8316763257c915bfba5f5e3, `pytest-asyncio==0.24.0` (which is a  `pytest` plugin) added a `PytestDeprecationWarning` that I am now trying to silence.

I have noticed this `PytestDeprecationWarning` is different from normal dependencies' `DeprecationWarning` because it's emitted _before_ `pytest` loads, instead of at test time.

I have configured [`filterwarnings`](https://docs.pytest.org/en/4.6.x/reference.html#confval-filterwarnings) for many normal packages, but I can't get it to work for this "pre-`pytest` loaded" `PytestDeprecationWarning`:

```toml
[tool.pytest.ini_options]
filterwarnings = [
    'ignore:configuration option "asyncio_default_fixture_loop_scope" is unset',
]
```

I have concluded that `filterwarnings` doesn't seem to work on `pytest` plugins.

Thus, I think this is a sort of bug, so I am requesting to apply `filterwarnings` also to `pytest` plugins, not just normal test time dependencies.

**Comment by dongfangtianyu** [comment] 2024-09-04 09:37
Looks the same as #12697 .

Pytest will intercept and capture warnings in the collection of use cases.
Prior to this, if wanted to filter specified warnings, couldn't rely on pytest but on python.


for example

```
python -W ignore::DeprecationWarning    -m pytest
```

However, due to this line of code, doing so is actually ineffective:
https://github.com/pytest-dev/pytest/blob/main/src/_pytest/config/__init__.py#L1116

---
It may be necessary a new  feature :capture warnings when the plugin is loaded.

**Comment by bluetech** [comment] 2024-09-04 12:44
Thanks @dongfangtianyu for the reference, closing as a duplicate of #12697.

**Closed by bluetech** 2024-09-04 12:44 UTC
