### ISSUE TITLE
Error in arguments to `pytest.mark.parameterize` fails all tests

### ISSUE THREAD

**Issue by alphaCTzo7G** [pytest-dev/pytest#3674] opened 2018-07-09 13:21 UTC
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [x] Include a detailed description of the bug or suggestion
- [ ] `pip list` of the virtual environment you are using
- [x] pytest and operating system versions
- [x] Minimal example if possible

If I have a tests case say 

	@pytest.mark.parametrize(
		"foo_dict1, expected",
		[
			data_search_foo.second
		]
	)
	def test_convert_foo_df(self, foo_instance, foo_dict,
								expected):
		foo_df = foo_instance.convert_foo_df(foo_dict)
		assert foo_df == expected

and all other tests, are correctly specified, this will crash the entire
`pytest` test.

The error in the above is that `foo_dict1` should be `foo_dict`. However, if I
didnt use `pytest.mark.parametrize`, it seems typographical errors in one
test(`test1`) only results in the failure of `test1`, but other tests in the
series of tests can still go on.

Can this be rectified?

Pytest version: 3.4.1
Operating System: Windows 10

**Comment by Zac-HD** [comment] 2018-10-19 04:52
Closing as duplicate of #3645, which proposes improving the error in this case.

**Closed by Zac-HD** 2018-10-19 04:52 UTC
Labels: topic: parametrize, type: bug, type: question
