### ISSUE TITLE
Pytest 5 fails when creating Flask app

### ISSUE THREAD

**Issue by singingwolfboy** [pytest-dev/pytest#5542] opened 2019-07-03 09:29 UTC
When writing tests with Pytest 4, I was able to create a [Flask](http://flask.pocoo.org/) app in the test without any problems. When running these tests with Pytest 5, I get an exception. I don't know if the problem is with Flask or with Pytest.

Pytest 5.0.0, macOS Mojave 10.14.5

<details>
  <summary>output of "pip list"</summary>
<pre>
Package            Version
------------------ -------
atomicwrites       1.3.0  
attrs              19.1.0 
Click              7.0    
Flask              1.0.3  
importlib-metadata 0.18   
itsdangerous       1.1.0  
Jinja2             2.10.1 
MarkupSafe         1.1.1  
more-itertools     7.1.0  
packaging          19.0   
pip                19.1.1 
pluggy             0.12.0 
py                 1.8.0  
pyparsing          2.4.0  
pytest             5.0.0  
setuptools         41.0.1 
six                1.12.0 
wcwidth            0.1.7  
Werkzeug           0.15.4 
wheel              0.33.4 
zipp               0.5.1
</pre>
</details>

I was also able to make [a minimal example of this failure](https://gist.github.com/singingwolfboy/5f57bccc293cbf8f352dbaea6d7ee537).

**Comment by RonnyPfannschmidt** [comment] 2019-07-03 10:19
Duplicate of #5532

**Comment by RonnyPfannschmidt** [comment] 2019-07-03 10:20
for context, the issue is with flask, and has gotten fixed upstream

**Closed** 2019-07-03 10:20 UTC

**Comment by asottile** [comment] 2019-07-06 00:00
The latest version of flask (released yesterday) contains the fix (1.0.4 / 1.1.0)
