### ISSUE TITLE
Unwanted warning for method as parameter

### ISSUE THREAD

**Issue by benjaminleon** [pytest-dev/pytest#8532] opened 2021-04-08 15:47 UTC
The following piece of code triggers the warning `'ParameterSet' object is not callable` and highlights `my_method()` in the test case below, although the method is used in the test as I expect it to.

Observed on Windows 10 in Pycharm 2020.3.5, (build #PC-203.7717.81) and with pytest 6.3.2, all the way down to (but not including) pytest 5.4

```
import pytest


def print_hello():
    print("hello")


@pytest.mark.parametrize("my_method", [pytest.param(print_hello)])
def test_minimal_example(my_method):
    my_method()  # <-- highlighted warning when using pytest 6.0 or higher
```

`pip list` outputs:
```Package         Version
--------------- ----------
appdirs         1.4.3
atomicwrites    1.4.0
attrs           19.3.0
awscli          1.19.23
bitstruct       8.11.0
boto3           1.17.23
botocore        1.20.23
CacheControl    0.12.6
canmatrix       0.9.2
certifi         2019.11.28
chardet         3.0.4
click           7.1.2
colorama        0.4.3
configobj       5.0.6
contextlib2     0.6.0
distlib         0.3.1
docutils        0.15.2
ecdsa           0.16.0
et-xmlfile      1.0.1
flake8          3.8.4
flake8-polyfill 1.0.2
future          0.18.2
html5lib        1.0.1
idna            2.9
iniconfig       1.0.1
intelhex        2.2.1
jdcal           1.4.1
jmespath        0.10.0
lockfile        0.12.2
lxml            4.5.0
mccabe          0.6.1
more-itertools  8.7.0
msgpack         1.0.0
numpy           1.19.0
openpyxl        3.0.5
ordered-set     3.1.1
packaging       20.3
pathlib2        2.3.5
pep517          0.8.2
pep8-naming     0.11.1
pip             20.0.2
pluggy          0.13.1
progress        1.5
prompt-toolkit  1.0.18
py              1.9.0
pyasn1          0.4.8
pycodestyle     2.6.0
pycparser       2.20
pycryptodome    3.9.8
pycryptodomex   3.9.8
pyelftools      0.26
pyflakes        2.2.0
Pygments        2.8.1
pyparsing       2.4.7
pytest          6.0.0rc1
python-dateutil 2.8.1
pytoml          0.1.21
PyYAML          5.3.1
requests        2.23.0
retrying        1.3.3
rsa             4.7.2
s3transfer      0.3.4
setuptools      47.1.1
six             1.15.0
toml            0.10.1
urllib3         1.25.9
wcwidth         0.2.5
webencodings    0.5.1
xlrd            1.2.0
XlsxWriter      1.3.6
xlwt            1.3.0
```

**Comment by RonnyPfannschmidt** [comment] 2021-04-08 19:05
At first glance i think this is a bug in the ide (presuming you talk about a warning in its ux)

**Comment by The-Compiler** [comment] 2021-04-08 19:56
Agreed that this sounds like a PyCharm bug. I don't think normal mypy type annotations can handle something like the parametrize decorator, and indeed mypy is fine with this as well, as it assumes `my_method` to be `Any` (with pytest `main`).

**Comment by RonnyPfannschmidt** [comment] 2021-11-07 10:00
closing since no further informations where provided

**Closed by RonnyPfannschmidt** 2021-11-07 10:00 UTC
Labels: status: needs information

**Comment by antoni-szych-rtbhouse** [comment] 2022-06-06 12:01
Just so you know, the issue is not limited to just the above example, but still it's Pycharm fault (Pycharm tracker: https://youtrack.jetbrains.com/issue/PY-48144).

It seems that Pycharm does not unpack `pytest.param` into separate variables at all:

![image](https://user-images.githubusercontent.com/84847001/172156245-f4c5285b-7cd4-4ac1-98b5-2f6bc7a9bb2a.png)

Workaround: annotate the params in the test definition:

![image](https://user-images.githubusercontent.com/84847001/172156498-a1d43469-0494-43b8-8893-4c1cbf385aaf.png)
