### ISSUE TITLE
Possible error in documentation

### ISSUE THREAD

**Issue by marcosanchotene** [pytest-dev/pytest#8501] opened 2021-03-30 19:41 UTC
The other day I was having a look at [this StackOverflow question](https://stackoverflow.com/questions/66832406/how-to-organize-tests-in-a-class-in-pytest) and I got confused with the [documentation mentioned](https://docs.pytest.org/en/stable/getting-started.html):

```
# content of test_class_demo.py
class TestClassDemoInstance:
    def test_one(self):
        assert 0

    def test_two(self):
        assert 0
```
```
$ pytest -k TestClassDemoInstance -q
FF                                                                   [100%]
================================= FAILURES =================================
______________________ TestClassDemoInstance.test_one ______________________

self = <test_class_demo.TestClassDemoInstance object at 0xdeadbeef>

    def test_one(self):
>       assert 0
E       assert 0

test_class_demo.py:3: AssertionError
______________________ TestClassDemoInstance.test_two ______________________

self = <test_class_demo.TestClassDemoInstance object at 0xdeadbeef>

    def test_two(self):
>       assert 0
E       assert 0

test_class_demo.py:6: AssertionError
========================= short test summary info ==========================
FAILED test_class_demo.py::TestClassDemoInstance::test_one - assert 0
FAILED test_class_demo.py::TestClassDemoInstance::test_two - assert 0
2 failed in 0.12s
```

As each test has a unique instance of the class, shouldn't each test_class_demo.TestClassDemoInstance object be at a different memory address, like the first at 0xdeadbeef and the second at something like 0xlivebeat instead of both at 0xdeadbeef?

**Comment by The-Compiler** [comment] 2021-03-30 20:12
Duplicate of #7646

**Closed by The-Compiler** 2021-03-30 20:12 UTC
