### ISSUE TITLE
Can't filter ImportWarning during tests run

### ISSUE THREAD

**Issue by oerp-odoo** [pytest-dev/pytest#10448] opened 2022-10-30 07:15 UTC
I tried setting this config:

```ini
[pytest]
filterwarnings =
    ignore::Warning
    ignore::ImportWarning
```
Running as `docker-compose run --rm odoo pytest -s --odoo-database=odoodb my/path/to/test`

`ignore::Warning` ignores all exceptions, except ImportWarning. Not sure why. `ignore::ImportWarning` does nothing.

I get:

```
2022-10-30 07:11:57,869 1 WARNING ? py.warnings: <frozen importlib._bootstrap>:914: ImportWarning: AddonsHook.find_spec() not found; falling back to find_module()
  File "/opt/odoo/venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/opt/odoo/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 190, in console_main
    code = main()
  File "/opt/odoo/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 167, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/opt/odoo/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/opt/odoo/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/odoo/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/opt/odoo/venv/lib/python3.10/site-packages/_pytest/main.py", line 317, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/opt/odoo/venv/lib/python3.10/site-packages/_pytest/main.py", line 266, in wrap_session
    config._do_configure()
  File "/opt/odoo/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1037, in _do_configure
    self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
  File "/opt/odoo/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 277, in call_historic
    res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
  File "/opt/odoo/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/opt/odoo/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/opt/odoo/venv/lib/python3.10/site-packages/_pytest/faulthandler.py", line 27, in pytest_configure
    import faulthandler
```

Ubuntu `22.04` (docker image)

```
platform linux -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0
rootdir: /opt/odoo, configfile: pytest.ini
plugins: odoo-0.8.1.dev1+g98f01ca
collected 7 items 
```

`pip list`:

```
Package            Version
------------------ ---------------------
Package            Version
------------------ ---------------------
anthem             0.13.1.dev18+g46a07a2
appdirs            1.4.4
attrs              22.1.0
Babel              2.9.1
beautifulsoup4     4.11.1
build              0.9.0
cached-property    1.5.2
certifi            2022.9.24
cffi               1.15.1
chardet            3.0.4
click              8.1.3
click-odoo         1.6.0
click-odoo-contrib 1.16.0
cryptography       3.4.8
decorator          4.4.2
defusedxml         0.7.1
docutils           0.16
ebaysdk            2.1.5
exceptiongroup     1.0.0
freezegun          0.3.15
future             0.18.2
gevent             21.8.0
greenlet           1.1.2
idna               2.8
iniconfig          1.1.1
isodate            0.6.1
Jinja2             2.11.3
libsass            0.18.0
lxml               4.6.5
manifestoo_core    0.10.2
marabunta          0.10.6
maraplus           0.3.0
MarkupSafe         1.1.0
mergedeep          1.3.4
num2words          0.5.6
ofxparse           0.21
packaging          21.3
passlib            1.7.3
pep517             0.13.0
pexpect            4.8.0
Pillow             9.0.1
pip                22.0.2
pip-tools          6.9.0
pluggy             1.0.0
polib              1.1.0
psutil             5.6.7
psycopg2           2.8.6
ptyprocess         0.7.0
pyasn1             0.4.8
pyasn1-modules     0.2.8
pycparser          2.21
pydot              1.4.1
pyOpenSSL          19.0.0
pyparsing          3.0.9
PyPDF2             1.26.0
pyserial           3.4
pytest             7.2.0
pytest-odoo        0.8.1.dev1+g98f01ca
python-dateutil    2.7.3
python-ldap        3.4.0
python-stdnum      1.13
pytz               2019.3
pyusb              1.0.2
PyYAML             6.0
qrcode             6.1
reportlab          3.5.59
requests           2.25.1
requests-toolbelt  0.10.1
ruamel.yaml        0.17.21
ruamel.yaml.clib   0.2.7
setuptools         59.6.0
six                1.16.0
soupsieve          2.3.2.post1
tomli              2.0.1
unicodecsv         0.14.1
urllib3            1.26.5
vobject            0.9.6.1
watchdog           2.1.9
Werkzeug           2.0.2
wheel              0.37.1
xlrd               1.2.0
XlsxWriter         1.1.2
xlwt               1.3.0
zeep               3.4.0
zope.event         4.5.0
zope.interface     5.5.0

```

**Comment by asottile** [comment] 2022-10-30 14:58
can you show a reproducible example and the exact unedited output?  the output above does not look like normal pytest output -- it's likely that your `ImportWarning` happens too early on for pytest's warnings plugin to be set up (you could probably use `python -W ... -m pytest` to hook in earlier

**Comment by oerp-odoo** [comment] 2022-10-31 05:59
@asottile hm, there is nothing else in an output. It only repeats same warning multiple times.

And then it ends with:

```
platform linux -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0
rootdir: /opt/odoo, configfile: pytest.ini
plugins: odoo-0.8.1.dev1+g8276861
collected 7 items                                                                                                             

opt/odoo/projects/myproject/mymodule/tests/test_context_utils.py .......
```

Though I can try recreating sample repository without all the private source code and so on, to see if same issue can be reproduced. Would that help?

Also running with `python -W ignore::ImportWarning -m pytest`, did not change anything.

**Comment by akhilramkee** [comment] 2022-11-01 06:49
Could it be that `ImportWarning` is getting thrown in `pytest_configure` ? 

If so, it looks to be related to `warnings` filter not  respected in `pytest_configure` - https://github.com/pytest-dev/pytest/issues/10128

**Comment by oerp-odoo** [comment] 2022-11-04 06:26
@akhilramkee do you have a fix for that?

**Comment by RonnyPfannschmidt** [comment] 2022-11-04 07:09
I believe we need more details, this looks like the warning is also redirected to logging

Does odoo reconfigure warnings to be logged?

**Comment by oerp-odoo** [comment] 2022-11-04 07:31
@RonnyPfannschmidt maybe this would be of help? https://github.com/odoo/odoo/blob/16.0/odoo/netsvc.py


Though when I run `odoo` tests using `unittest` package (odoo standard tool for tests), it does not show any warnings (don't even need to ignore warnings), only if I run it with pytest.

**Comment by RonnyPfannschmidt** [comment] 2022-11-04 07:43
@oerp-odoo yup,that one wrecks mayham

I recommend disabling the warnings plugin, the logging plugin and capture

**Comment by oerp-odoo** [comment] 2022-11-04 07:52
@RonnyPfannschmidt you mean modify source code? Cause I don't want to modify external code I depend (as this is framework we use) or it will go out of sync. 

But regarding warning itself, I'm not familiar with pytest internals, but does it originate from pytest itself (something outdated, because I use Python 3.10?)? Cause ideally I would expect to not even see such warnings and not need to use filters.

**Comment by RonnyPfannschmidt** [comment] 2022-11-04 08:13
I mean pytest plugins

It's not clear to me what triggers the warning as it happens on a stdlib import and the odoo logging setup is not exactly safe

**Comment by RonnyPfannschmidt** [comment] 2022-11-04 08:14
Also the output is incomplete, so it's unclear if its the root errors or a overly visible bystander

**Comment by oerp-odoo** [comment] 2022-11-04 08:48
Do I need to disable it like this?

```
[pytest]
addopts =
    -p no:warnings
    -p no:logging
    -p no:capture
```
Using it, suppresses all warnings except that `ImportWarning` one.. So basically works the same as `filterwarnings`. Or maybe im disabling plugins incorrectly? Not sure how can I see a list of all plugins being used.

**Comment by RonnyPfannschmidt** [comment] 2022-11-04 09:07
I just googled odoo and addonshook

Seems like odoo is missing the apis, nothing pytest can do about odoo not implementing the required stuff

**Comment by oerp-odoo** [comment] 2022-11-04 11:38
@RonnyPfannschmidt well Odoo does not support pytest officially. I am only using this community plugin: https://github.com/camptocamp/pytest-odoo

**Comment by RonnyPfannschmidt** [comment] 2022-11-04 11:51
@oerp-odoo this is a warning about odoo not supporting standard python specs, so pytest can't help it

**Comment by oerp-odoo** [comment] 2022-11-04 11:55
@RonnyPfannschmidt oh I see. Thats a bummer. Thanks for clarification.

**Comment by RonnyPfannschmidt** [comment] 2022-11-04 18:02
Closing as upstream issue in the odoo addon hook

**Closed** 2022-11-04 18:02 UTC
Labels: status: needs information, plugin: warnings

**Comment by oerp-odoo** [comment] 2022-11-05 06:14
@RonnyPfannschmidt by the way, can you link an article you found about Odoo and addons hooks?

**Comment by RonnyPfannschmidt** [comment] 2022-11-05 06:15
There is no article, just the code of it in odoo

**Comment by oerp-odoo** [comment] 2022-11-05 08:33
As a workaround, to suppress such warnings from Odoo, it is possible to use this kind of option in Odoo config:

```
log_handler = :INFO,py.warnings:ERROR
```
Because its a `WARNING`, if we set higher level, it will be ignored. Currently don't see cleaner way to workaround it without changing Odoo code..:)

Though, of course it will filter all `py.warnings`
