### ISSUE TITLE
test case name can be chinese?

### ISSUE THREAD

**Issue by EtheriousNatsu** [pytest-dev/pytest#2996] opened 2017-12-03 09:21 UTC
i want my testcase name in html report and xml report can convert to chinese. here is my system info.
 
platform darwin -- Python 2.7.10, pytest-3.2.3, py-1.4.34, pluggy-0.4.0 -- /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
cachedir: .cache
metadata: {'Python': '2.7.10', 'Platform': 'Darwin-16.0.0-x86_64-i386-64bit', 'Packages': {'py': '1.4.34', 'pytest': '3.2.3', 'pluggy': '0.4.0'}, 'JAVA_HOME': '/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home', 'Plugins': {'html': '1.16.0', 'metadata': '1.5.1'}}
rootdir: /Users/john/Desktop/gabbi-1.30.1, inifile:
plugins: html-1.16.0, metadata-1.5.1

![image](https://user-images.githubusercontent.com/12187260/33523955-4be3abc4-d84e-11e7-8a33-4821c52b2872.png)

**Comment by EtheriousNatsu** [comment] 2017-12-03 09:22
please tell me how can i do

**Comment by RonnyPfannschmidt** [comment] 2017-12-04 12:23
i recall, that using actual unicode strings is supposed to somewhat work - CC @nicoddemus

**Comment by EtheriousNatsu** [comment] 2017-12-04 12:25
i want testcase name in pytest-html、pytest-xml  display chinese

**Comment by nicoddemus** [comment] 2017-12-12 00:07
Unfortunately keeping unicode in the parametrized values caused all kinds of bugs (#1085) where things would just break apart, so we decided to go with the safer route and [always escape ids using a safe ascii representation](https://github.com/pytest-dev/pytest/blob/master/_pytest/compat.py#L172), even in Python 3.

So @EtheriousNatsu I'm afraid we will have to close this as "working as intended".

**Closed by nicoddemus** 2017-12-12 00:07 UTC
