### ISSUE TITLE
pytest.config.getoption('option', default='yellow submarine") returns default value only if option was not definied by addopts

### ISSUE THREAD

**Issue by gorzynsk** [pytest-dev/pytest#1947] opened 2016-09-19 12:54 UTC
I was trying to get command line option value that was used to run py.test. I've added the option in `pytest_addoption`and assumed that:

`pytest.config.getoption('option', default='yellow submarine")`

will return "yellow submarine" if I don't specify option during py.test invocation in shell.

The py.test code however returns default value **only** if option was not declared with `parser.addoption("--option...`. Not specifying option at command line results in value of `None` being returned from `getoption`.

Of course I can check whether returned value is None and set default value afterwards, but I'm curious if current behavior of py.test is intended as intuitively I feel it shall return default value.

Environment:
python 2.7.12
py.test 3.0.2
windows 8

**Comment by RonnyPfannschmidt** [comment] 2016-09-19 13:04
@gorzynsk the current behaviour intentionally returns the default in case no such option was declared

its indeed a unfortunate api

@hpk42 any idea how it came to be that way? (other than potentially matching declared default values of options)

**Comment by nicoddemus** [comment] 2017-09-29 22:18
Indeed it is kind of strange.

At least the documentation is clear:

```
:arg default: default value if no option of that name exists.
```

I think we can close this as "works as intended, but nobody seems to know why that's the intention". 😜

**Closed by nicoddemus** 2017-09-29 22:18 UTC
Labels: topic: config, type: question
