### ISSUE TITLE
AttributeError on celery_session_app

### ISSUE THREAD

**Issue by gustelle** [pytest-dev/pytest#4641] opened 2019-01-13 13:31 UTC
I got the following error when launching error when lauching a celery task from pytest

Here is the code 

```
@pytest.fixture(scope='session')
def celery_config():
    return {
        'broker_url': 'redis://redis:6379/0',
        'result_backend': 'redis://redis:6379/0',
        'task_always_eager': True,
        'task_eager_propagates': True
    }


@pytest.fixture(scope='session')
def celery_enable_logging():
    return True


@pytest.mark.usefixtures("celery_session_worker")
class TestMyTask(object):

    def test_task_failure(self, celery_session_worker):
        """
        """
        result = mytask.delay('hello')
        assert result.state == 'FAILURE'
```

The versions used 
- pytest 4.1.1
- celery 4.2.0

I have tried downgrading to celery 4.0 and pytest 4.0, but I have the same issue
This is a quite recent issue, I had run this code without trouble since last week about

Is there a bug behind this ?

Thank you

**Comment by asottile** [comment] 2019-01-13 15:12
There isn't enough information to answer / triage:
- post the stacktrace
- post the entire code, what's `celery_session_worker`? what's `celery_session_app`? where does `mytask` come from?

Here's some good topics on how to ask a good question:
- [stackoverflow how-to-ask](https://stackoverflow.com/help/how-to-ask)
- [stackoverflow what is a MCVE](https://stackoverflow.com/help/mcve)

**Comment by gustelle** [comment] 2019-01-13 19:11
Hello Anthony, 

the stack trace I receive is the following:

```
platform linux -- Python 3.6.6, pytest-4.1.1, py-1.7.0, pluggy-0.8.1 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /app, inifile:
plugins: testdox-1.0.1, sanic-0.1.15, mock-1.10.0, celery-4.2.0
collected 1 item                                                               

tests/test_tasks.py::TestMyTask::test_my_task ERROR

==================================== ERRORS ====================================
__________________ ERROR at setup of TestMyTask.test_my_task ___________________

request = <SubRequest 'celery_session_app' for <Function test_my_task>>
celery_config = {'broker_url': 'redis://redis:6379/0', 'result_backend': 'redis://redis:6379/0', 'task_always_eager': True, 'task_eager_propagates': True}
celery_parameters = {}, celery_enable_logging = True
use_celery_app_trap = False

    @pytest.fixture(scope='session')
    def celery_session_app(request,
                           celery_config,
                           celery_parameters,
                           celery_enable_logging,
                           use_celery_app_trap):
        # type: (Any) -> Celery
        """Session Fixture: Return app for session fixtures."""
>       mark = request.node.get_marker('celery')
E       AttributeError: 'Session' object has no attribute 'get_marker'

/usr/local/lib/python3.6/site-packages/celery/contrib/pytest.py:54: AttributeError
=========================== 1 error in 0.33 seconds ============================

```

`celery_session_worker ` and `celery_session_app ` are celery features provided by celery-pytest [celery testing](http://docs.celeryproject.org/en/latest/userguide/testing.html)

mytask is a dummy celery task just to demonstrate the error

here is the celery task details:

```
celery = Celery('tasks')

celery.config_from_object({
    'broker_url': config.ENV.CELERY_BROKER_URL,
    'result_backend': config.ENV.CELERY_RESULT_BACKEND,
})

@celery.task(bind=True)
def mytask(self, param):
    return param
```
Can you help ?

Thanks

**Comment by asottile** [comment] 2019-01-13 19:19
Looks like you're on an older version of `celery` which used the old marker api.  In the latest version they've fixed it to use `get_closest_marker`: https://github.com/celery/celery/pull/5097

looks like you need at least celery version 4.3 -- looks like that might not be released yet?  their issue for this is https://github.com/celery/celery/issues/5271

In the meantime, your workaround until celery is released is to limit the pytest max version, probably to `<4`

**Comment by gustelle** [comment] 2019-01-13 20:06
Thanks Anthony  
I confirm that downgrading to `pytest==3.10.1` fixed the issue, waiting for the release of celery 4.3 to fix the pytest 4 integration

**Comment by asottile** [comment] 2019-01-13 20:09
Sounds good! since this is confirmed an external issue I'll close this
Thanks for the issue 🎉

**Closed by asottile** 2019-01-13 20:09 UTC
Labels: type: question
