### ISSUE TITLE
remove named marker attributes and collect markers in items

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#891] opened 2015-07-26 11:24 UTC
the current model of transferring markers to the objects under test
creates a mess and needs various workarounds

instead we should always collect and merge markers in items

that way the natural path of marker transfer will be much more precisely scoped

**Comment by RonnyPfannschmidt** [comment] 2015-07-26 11:26
#886 is closely related

**Comment by nicoddemus** [comment] 2015-07-30 11:30
Do you think this will be a backward-compatibility issue because there may be people relying on the actual marker decorators being transferred across the various Python functions/classes/modules, instead of relying on the `node.get_marker` public API?

**Comment by RonnyPfannschmidt** [comment] 2015-07-30 11:39
currently markers are attributes on functions, with the change they wouldn't

so its clearly a incompatible api change

however i do think having a object local mark sotorage per object and a merged view on them per node would be most helpfull in future

i suspect we can provide some backward compatibility, but there will be some glitches to handle

**Comment by nicoddemus** [comment] 2015-07-30 11:43
> currently markers are attributes on functions, with the change they wouldn't

But aren't they an internal implementation detail? I'm not sure how much people rely on that...

I imagined that the backward compabitility concern is why you marked it as a `3.0` milestone, that's why I'm curious. :smile:

Btw, was there any talk about a 3.0 release at EuroPython?

**Comment by RonnyPfannschmidt** [comment] 2015-07-30 11:47
i wasn't at EP as well,

while mark attributes are indeed implementation detail, they where exposed as usable attributes and people use them that way (in the past i did so myself, that is pre `node.getmarker`)

**Comment by nicoddemus** [comment] 2015-07-30 12:19
Hmmm I see, thanks!

**Comment by The-Compiler** [comment] 2016-08-05 10:27
Since we really want to get 3.0 out, changing the milestone to 4.0 for this.

**Comment by RonnyPfannschmidt** [comment] 2018-04-10 04:38
deprecated in #3317

**Comment by nicoddemus** [comment] 2018-12-18 23:19
Duplicate of #3379?

**Comment by RonnyPfannschmidt** [comment] 2018-12-19 08:09
@nicoddemus the other way around ^^

**Closed** 2018-12-21 16:32 UTC
Labels: topic: marks, type: backward compatibility, type: enhancement, type: proposal, type: removal
