### ISSUE TITLE
test_something fails

### ISSUE THREAD

**Issue by jlec** [pytest-dev/pytest#1164] opened 2015-11-01 18:59 UTC
```Python
=============================================== FAILURES ================================================
____________________________________________ test_something _____________________________________________

    def test_something():
        # pytest does not import logging
>       assert 'logging' not in sys.modules
E       assert 'logging' not in {'__future__': <module '__future__' from '/usr/lib64/python3.4/__future__.py'>, '__main__': <module '__main__' from '/...e '_ast' (built-in)>, '_bisect': <module '_bisect' from '/usr/lib64/python3.4/lib-dynload/_bisect.cpython-34.so'>, ...}
E        +  where {'__future__': <module '__future__' from '/usr/lib64/python3.4/__future__.py'>, '__main__': <module '__main__' from '/...e '_ast' (built-in)>, '_bisect': <module '_bisect' from '/usr/lib64/python3.4/lib-dynload/_bisect.cpython-34.so'>, ...} = sys.modules

test_logging_initialized_in_test.py:4: AssertionError
======================================= 1 failed in 0.01 seconds ========================================
----------------------------------------- Captured stderr call ------------------------------------------
nomatch: '*hello432*'
    and: 'PLUGIN registered: <_pytest.config.PytestPluginManager object at 0x7f8cfbb02828>'
    and: 'PLUGIN registered: <_pytest.config.Config object at 0x7f8cfb8cbeb8>'
    and: "PLUGIN registered: <module '_pytest.mark' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/mark.py'>"
    and: "PLUGIN registered: <module '_pytest.main' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/main.py'>"
    and: "PLUGIN registered: <module '_pytest.terminal' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/terminal.py'>"
    and: "PLUGIN registered: <module '_pytest.runner' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/runner.py'>"
    and: "PLUGIN registered: <module '_pytest.python' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/python.py'>"
    and: "PLUGIN registered: <module '_pytest.pdb' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/pdb.py'>"
    and: "PLUGIN registered: <module '_pytest.unittest' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/unittest.py'>"
    and: "PLUGIN registered: <module '_pytest.capture' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/capture.py'>"
    and: "PLUGIN registered: <module '_pytest.skipping' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/skipping.py'>"
    and: "PLUGIN registered: <module '_pytest.tmpdir' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/tmpdir.py'>"
    and: "PLUGIN registered: <module '_pytest.monkeypatch' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/monkeypatch.py'>"
    and: "PLUGIN registered: <module '_pytest.recwarn' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/recwarn.py'>"
    and: "PLUGIN registered: <module '_pytest.pastebin' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/pastebin.py'>"
    and: "PLUGIN registered: <module '_pytest.helpconfig' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/helpconfig.py'>"
    and: "PLUGIN registered: <module '_pytest.nose' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/nose.py'>"
    and: "PLUGIN registered: <module '_pytest.assertion' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/assertion/__init__.py'>"
    and: "PLUGIN registered: <module '_pytest.genscript' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/genscript.py'>"
    and: "PLUGIN registered: <module '_pytest.junitxml' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/junitxml.py'>"
    and: "PLUGIN registered: <module '_pytest.resultlog' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/resultlog.py'>"
    and: "PLUGIN registered: <module '_pytest.doctest' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/doctest.py'>"
    and: "PLUGIN registered: <module '_pytest.cacheprovider' from '/var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/cacheprovider.py'>"
    and: "PLUGIN registered: <module 'hypothesis.extra.pytestplugin' from '/usr/lib64/python3.4/site-packages/hypothesis/extra/pytestplugin.py'>"
    and: 'PLUGIN registered: <_pytest.capture.CaptureManager object at 0x7f8cfa893828>'
    and: "PLUGIN registered: <Session 'test_logging_initialized_in_test0'>"
    and: 'PLUGIN registered: <_pytest.cacheprovider.LFPlugin object at 0x7f8cfa875a58>'
    and: 'PLUGIN registered: <_pytest.terminal.TerminalReporter object at 0x7f8cfa84eb00>'
    and: 'PLUGIN registered: <_pytest.python.FixtureManager object at 0x7f8cfa844908>'
    and: '========================================== test session starts =========================================='
    and: 'platform linux -- Python 3.4.3, pytest-2.8.2, py-1.4.30, pluggy-0.3.1'
    and: 'using: pytest-2.8.2 pylib-1.4.30'
    and: 'setuptools registered plugins:'
    and: '  hypothesis-1.12.0 at /usr/lib64/python3.4/site-packages/hypothesis/extra/pytestplugin.py'
    and: 'active plugins:'
    and: '    cacheprovider       : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/cacheprovider.py'
    and: '    capturelog          : None'
    and: '    terminalreporter    : <_pytest.terminal.TerminalReporter object at 0x7f8cfa84eb00>'
    and: '    pytestconfig        : <_pytest.config.Config object at 0x7f8cfb8cbeb8>'
    and: '    monkeypatch         : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/monkeypatch.py'
    and: '    resultlog           : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/resultlog.py'
    and: '    capture             : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/capture.py'
    and: "    session             : <Session 'test_logging_initialized_in_test0'>"
    and: '    mark                : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/mark.py'
    and: '    tmpdir              : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/tmpdir.py'
    and: '    assertion           : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/assertion/__init__.py'
    and: '    junitxml            : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/junitxml.py'
    and: '    unittest            : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/unittest.py'
    and: '    funcmanage          : <_pytest.python.FixtureManager object at 0x7f8cfa844908>'
    and: '    doctest             : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/doctest.py'
    and: '    python              : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/python.py'
    and: '    terminal            : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/terminal.py'
    and: '    helpconfig          : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/helpconfig.py'
    and: '    pdb                 : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/pdb.py'
    and: '    capturemanager      : <_pytest.capture.CaptureManager object at 0x7f8cfa893828>'
    and: '    runner              : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/runner.py'
    and: '    nose                : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/nose.py'
    and: '    pastebin            : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/pastebin.py'
    and: '    skipping            : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/skipping.py'
    and: '    140243494774824     : <_pytest.config.PytestPluginManager object at 0x7f8cfbb02828>'
    and: '    pytest_capturelog   : None'
    and: '    hypothesispytest    : /usr/lib64/python3.4/site-packages/hypothesis/extra/pytestplugin.py'
    and: '    lfplugin            : <_pytest.cacheprovider.LFPlugin object at 0x7f8cfa875a58>'
    and: '    recwarn             : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/recwarn.py'
    and: '    genscript           : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/genscript.py'
    and: '    main                : /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2-python3_4/lib/_pytest/main.py'
    and: 'rootdir: /var/tmp/portage/dev-python/pytest-2.8.2/temp/pytest-of-justin/pytest-15/testdir/test_logging_initialized_in_test0, inifile: '
    and: 'plugins: hypothesis-1.12.0'
    and: 'collected 1 items'
    and: ''
    and: 'test_logging_initialized_in_test.py F'
    and: ''
    and: '=============================================== FAILURES ================================================'
    and: '____________________________________________ test_something _____________________________________________'
    and: ''
    and: '    def test_something():'
    and: '        # pytest does not import logging'
    and: ">       assert 'logging' not in sys.modules"
    and: "E       assert 'logging' not in {'__future__': <module '__future__' from '/usr/lib64/python3.4/__future__.py'>, '__main__': <module '__main__' from '/...e '_ast' (built-in)>, '_bisect': <module '_bisect' from '/usr/lib64/python3.4/lib-dynload/_bisect.cpython-34.so'>, ...}"
    and: "E        +  where {'__future__': <module '__future__' from '/usr/lib64/python3.4/__future__.py'>, '__main__': <module '__main__' from '/...e '_ast' (built-in)>, '_bisect': <module '_bisect' from '/usr/lib64/python3.4/lib-dynload/_bisect.cpython-34.so'>, ...} = sys.modules"
    and: ''
    and: 'test_logging_initialized_in_test.py:4: AssertionError'
    and: '======================================= 1 failed in 0.01 seconds ========================================'
======================================== short test summary info ========================================
XFAIL testing/acceptance_test.py::TestInvocationVariants::()::test_noclass_discovery_if_not_testcase
  decide: feature or bug
XFAIL testing/test_capture.py::TestPerTestCapturing::()::test_capture_scope_cache
  unimplemented feature
SKIP [1] testing/test_assertrewrite.py:557: condition: sys.version_info[0] >= 3
SKIP [1] testing/test_assertrewrite.py:548: condition: sys.version_info[0] >= 3
SKIP [1] testing/test_assertrewrite.py:530: condition: sys.version_info[0] >= 3
SKIP [2] /var/tmp/portage/dev-python/pytest-2.8.2/work/pytest-2.8.2/testing/test_assertinterpret.py:203: could not import '_pytest.assertion.oldinterpret'
SKIP [1] testing/test_assertinterpret.py:337: condition: sys.version_info >= (2,6)
SKIP [1] testing/test_assertion.py:588: This bug does not exist on PY3
SKIP [1] testing/test_assertrewrite.py:539: condition: sys.version_info[0] >= 3
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================== 1 failed, 214 passed, 8 skipped, 2 xfailed in 58.44 seconds =====================
```
pytest-2.8.2 and python3.4.

**Comment by nicoddemus** [comment] 2015-11-18 16:25
Can you provide more information, specially a step-by-step to reproduce? I ask because this test passes on our C.I.

**Comment by nicoddemus** [comment] 2015-11-18 16:26
(Closing this for now, feel free to reopen if you have more information)

**Closed by nicoddemus** 2015-11-18 16:26 UTC

**Comment by The-Compiler** [comment] 2015-11-18 16:27
FWIW I can't reproduce this (or #1163) locally either.
