### ISSUE TITLE
Regression in v3.2.0 - when using null bytes in parameter strings.

### ISSUE THREAD

**Issue by samuelfekete** [pytest-dev/pytest#2669] opened 2017-08-08 14:43 UTC
This error only happens when using the latest version: 3.2.0

When using a parameter string that contains a null character, for example:
```
@pytest.mark.parametrize(
    'display_name',
    ('null-byte-\0.txt', 'forward/slash', r'back\slash')
)
```
The following error is raised:
```
    def __setitem__(self, key, item):
>       putenv(key, item)
E       TypeError: must be string without null bytes, not str

.tox/py27/lib/python2.7/os.py:473: TypeError
```

**Comment by The-Compiler** [comment] 2017-08-08 15:06
Duplicate of #2644, fixed by #2646, which will be part of pytest 3.2.1 soon.

**Closed by The-Compiler** 2017-08-08 15:06 UTC

**Comment by samuelfekete** [comment] 2017-08-08 15:56
Thanks @The-Compiler
