### ISSUE TITLE
UserWarning from pluggy

### ISSUE THREAD

**Issue by Korijn** [pytest-dev/pytest#1687] opened 2016-06-28 14:34 UTC
We're seeing the following warning on our CI output:

```
/home/rof/miniconda/envs/myenv/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py:495: UserWarning: Module argparse was already imported from /home/rof/miniconda/envs/myenv/lib/python2.7/argparse.pyc, but /home/rof/miniconda/envs/myenv/lib/python2.7/site-packages/argparse-1.4.0-py2.7.egg is being added to sys.path
from pkg_resources import iter_entry_points, DistributionNotFound
```

Our configuration:

```
platform linux -- Python 3.5.1, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/rof/src/bitbucket.org/organization/myenv, inifile: 
plugins: mock-0.10.1, xdist-1.14, cov-2.2.1
```

**Comment by RonnyPfannschmidt** [comment] 2016-06-28 15:59
Looks like a Bad egg build, not the fault of pytest

**Comment by nicoddemus** [comment] 2016-07-08 11:45
Hey @Korijn,

It does look like an egg build problem... can you reproduce that in a normal virtual environment?

FWIW we also use py.test 2.9.2 with conda here at work and don't see this problem (although we build the package ourselves). Are you using a standard package, or did you build it youself?

**Comment by Korijn** [comment] 2016-07-08 11:59
We're using one that we built ourselves. I'll try the one from conda-forge to see if that's any better.

We'd like to rely on conda-forge fully but for some reason, the use of their packages breaks PyCharm's compatibility with pytest on Windows, due to the way pydev patches PyQt. Such a rabbit hole...

**Comment by nicoddemus** [comment] 2016-07-08 12:07
pydev? You mean the debugger?

**Comment by Korijn** [comment] 2016-07-08 12:21
Yeah. If we add `conda-forge` to `channels` in `environment.yml`, many packages come in from conda-forge instead of from the default channels, and subsequently we are unable to use the pytest runner in PyCharm (doesn't matter which version) without hitting `ConftestImportFailure` on the very first import that is executed. The stack trace leads through some pyqt monkey-patching code in pydev. We tried switching packages between conda-forge and defaults, and we came to the conclusion that it only happens when the pyqt package originates from conda-forge. It's ridiculous, really. :/

**Comment by nicoddemus** [comment] 2016-07-08 12:32
Bummer, really. 

Back to the topic of this issue, please close it if you don't have the same behavior when using the conda-forge pytest package, in which case take a look at the recipe they use to see what's the difference. Also, here's [ours](https://gist.github.com/nicoddemus/f2aaf8553421ba250f777f16405d35a8) in case it helps.

**Comment by RonnyPfannschmidt** [comment] 2016-07-18 09:21
closing this one due to lack of feedback on something that looks like a issue with conda,
please reopen/notify in case im wrong

**Closed by RonnyPfannschmidt** 2016-07-18 09:21 UTC
