### ISSUE TITLE
Run clean with PEP-597 `PYTHONWARNDEFAULTENCODING=1`, add to selftests

### ISSUE THREAD

**Issue by Zac-HD** [pytest-dev/pytest#10540] opened 2022-11-28 08:49 UTC
I recently [tried checking for encoding issues](https://docs.python.org/3/library/io.html#io-encoding-warning) in a downstream project, but the first thing to fail was in Pytest itself.  I therefore think that we should enable this check for our selftests in CI, and ensure that we're handling encodings correctly per the link above.

**Comment by The-Compiler** [comment] 2022-11-29 08:53
Duplicate of #10326? Also see #10328.

**Closed** 2022-11-29 09:15 UTC
Labels: type: enhancement, status: easy, type: selftests
