### ISSUE TITLE
pytest --doctest-modules freezes computer

### ISSUE THREAD

**Issue by SrMouraSilva** [pytest-dev/pytest#2854] opened 2017-10-19 12:21 UTC
Hello, when I execute `pytest --doctest-modules` in my project [PluginsManager](https://github.com/PedalPi/PluginsManager) the computer freezes and I need reboot!

You can see here the problem: https://travis-ci.org/PedalPi/PluginsManager/jobs/289297278#L1156-L1166

## How to

I tried on my computer on the `virtualenv` and in the `docker` and in both the computer freezes. Also, [`travis` freezes too](https://travis-ci.org/PedalPi/PluginsManager/jobs/289297278#L1156-L1166).

```
# In docker
#sudo docker run -it python:3.6 bash
#cd tmp/
git clone https://github.com/PedalPi/PluginsManager
cd PluginsManager/
python setup.py develop
git checkout 72b2e6e507cfe23c2cf011f6ded08f2f9ffd2b65
pip install pytest
pytest --doctest-modules # WILL FREEZE PC
```

## `pip list` of the virtual environment you are using

```
cffi (1.11.2)
JACK-Client (0.4.2)
PedalPi-PluginsManager (0.5.1, /tmp/PluginsManager)
pip (9.0.1)
py (1.4.34)
PyAudio (0.2.11)
pycparser (2.18)
pytest (3.2.3)
setuptools (36.6.0)
wheel (0.30.0)
```

**Comment by The-Compiler** [comment] 2017-10-19 12:43
This smells like #1217, which is a Python bug. Can you test the same thing with Python 3.6?

**Comment by SrMouraSilva** [comment] 2017-10-19 12:59
Appears to be a python error: https://travis-ci.org/PedalPi/PluginsManager/builds/289297276


* Python: 3.4: Not freeze
```
platform linux -- Python 3.4.6, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /home/travis/build/PedalPi/PluginsManager, inifile:
plugins: cov-2.5.1
collected 125 items / 2 errors 
```
* Python: 3.5: Freezes
```
platform linux -- Python 3.5.3, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /home/travis/build/PedalPi/PluginsManager, inifile:
plugins: cov-2.5.1
collecting 21 items / 2 errors                                                  
/home/travis/.travis/job_stages: line 57:  5604 Killed pytest --doctest-modules
```
* Python: 3.6: Freezes
```
platform linux -- Python 3.6.3, pytest-3.2.2, py-1.4.34, pluggy-0.4.0
rootdir: /home/travis/build/PedalPi/PluginsManager, inifile:
plugins: cov-2.5.1
collecting 21 items / 2 errors
/home/travis/.travis/job_stages: line 57:  5585 Killed  pytest --doctest-modules
```
* Python: 3.7-dev: Not freeze
```
platform linux -- Python 3.7.0a0, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /home/travis/build/PedalPi/PluginsManager, inifile:
plugins: cov-2.5.1
collected 125 items / 4 errors                                                  
```
* Python: nightly: Not freeze
```
platform linux -- Python 3.7.0a0, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /home/travis/build/PedalPi/PluginsManager, inifile:
plugins: cov-2.5.1
collected 125 items / 4 errors
```

**Comment by nicoddemus** [comment] 2018-09-02 12:43
@SrMouraSilva is this still an issue?

**Comment by Zac-HD** [comment] 2018-10-19 05:03
Duplicate of #1217, #3456.  Also related to #2188 - `mock.call` causes a lot of issues!

**Closed by Zac-HD** 2018-10-19 05:03 UTC
Labels: type: question
