### ISSUE TITLE
Possible bug in pytest --doctest comparison

### ISSUE THREAD

**Issue by mirca** [pytest-dev/pytest#2796] opened 2017-09-24 01:16 UTC
In Python:

```
>>> -0.0 == 0.0
True
```

Whereas while running ``pytest --doctest-modules`` (version ``3.0.7``):
```
Expected:
    0.0
Got:
    -0.0
```

**Comment by nicoddemus** [comment] 2017-09-25 23:45
Thanks @mirca.

I can't reproduce the problem though, either on `master` or in version `3.0.7`. Could you please test using the latest version and provide a minimal reproducible example if the error still happens? Thanks!

**Comment by mirca** [comment] 2017-09-26 04:40
I tested with version ``3.2.1`` as well and got the same error:

```
➜ pytest --doctest-modules test.py
================================= test session starts ==================================
platform darwin -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /Users/jvmirca, inifile:
plugins: pep8-1.0.6, cov-2.5.1
collected 1 item

test.py F

======================================= FAILURES =======================================
____________________________________ [doctest] test ____________________________________
001
002 >>> import numpy as np
003 >>> - np.log(1)
Expected:
    0.0
Got:
    -0.0
```

where ``test.py`` is:
```
"""
>>> import numpy as np
>>> - np.log(1)
0.0
"""
```

**Comment by nicoddemus** [comment] 2017-09-26 21:13
Thanks @mirca for the reproducible example.

I can reproduce the same error in pytest and also using the standard library's `doctest`:

```python
"""
>>> import numpy as np
>>> - np.log(1)
0.0
"""

if __name__ == '__main__':
    import doctest
    doctest.testmod()
```

```
$python .tmp\test_doctest.py
**********************************************************************
File ".tmp\test_doctest.py", line 3, in __main__
Failed example:
    - np.log(1)
Expected:
    0.0
Got:
    -0.0
**********************************************************************
1 items had failures:
   1 of   2 in __main__
***Test Failed*** 1 failures.
```

pytest uses the standard `doctest` for test collection and comparison, so it is actually a bug in python's `doctest` module. I suggest to report this problem in Python's issue tracker.

pytest can't really do anything in this case, so I'm closing this.

**Closed by nicoddemus** 2017-09-26 21:13 UTC
Labels: plugin: doctests, status: needs information, type: bug

**Comment by mirca** [comment] 2017-09-26 21:58
@nicoddemus Thanks for following up on this.

**Comment by nicoddemus** [comment] 2017-09-26 22:44
No problem 👍
