### ISSUE TITLE
bad input for traceback

### ISSUE THREAD

**Issue by matasbalcaitis** [pytest-dev/pytest#7779] opened 2020-09-21 07:55 UTC
From pytest 5.4.0, tests fails with `AttributeError: ‘function’ object has no attribute ‘tb_frame’`.  It looks like incorrect object is passed to traceback.

<details>
<summary>versions and `pip list` output</summary>

python 3.7.7
pytest 6.0.1

Package                  Version
------------------------ ---------
attrs              20.2.0   
cached-property    1.5.1    
certifi            2020.6.20
chardet            3.0.4    
distro             1.5.0    
docker             4.3.1    
docker-compose     1.27.2   
dockerpty          0.4.1    
docopt             0.6.2    
idna               2.10     
importlib-metadata 1.7.0    
iniconfig          1.0.1    
jsonschema         3.2.0    
more-itertools     8.5.0    
packaging          20.4     
pip                19.2.3   
pluggy             0.13.1   
py                 1.9.0    
pyparsing          2.4.7    
pyrsistent         0.17.3   
pytest             6.0.1    
python-dotenv      0.14.0   
PyYAML             5.3.1    
requests           2.24.0   
setuptools         41.2.0   
six                1.15.0   
texttable          1.6.3    
toml               0.10.1   
urllib3            1.25.10  
websocket-client   0.57.0   
zipp               3.1.0  
</details>
Error output:

```python-traceback
tests/test_demo.py::TestExample::test_dummy
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/main.py", line 240, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/main.py", line 296, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/main.py", line 321, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/runner.py", line 100, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/runner.py", line 117, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/runner.py", line 209, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)  # type: TestReport
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/skipping.py", line 264, in pytest_runtest_makereport
INTERNALERROR>     rep = outcome.get_result()
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/runner.py", line 320, in pytest_runtest_makereport
INTERNALERROR>     return TestReport.from_item_and_call(item, call)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/reports.py", line 319, in from_item_and_call
INTERNALERROR>     longrepr = item.repr_failure(excinfo)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/python.py", line 1603, in repr_failure
INTERNALERROR>     return self._repr_failure_py(excinfo, style=style)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/nodes.py", line 406, in _repr_failure_py
INTERNALERROR>     truncate_locals=truncate_locals,
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/_code/code.py", line 611, in getrepr
INTERNALERROR>     return fmt.repr_excinfo(self)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/_code/code.py", line 861, in repr_excinfo
INTERNALERROR>     reprtraceback = self.repr_traceback(excinfo_)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/_code/code.py", line 805, in repr_traceback
INTERNALERROR>     reprentry = self.repr_traceback_entry(entry, einfo)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/_code/code.py", line 757, in repr_traceback_entry
INTERNALERROR>     s = self.get_source(source, line_index, excinfo, short=short)
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/_code/code.py", line 699, in get_source
INTERNALERROR>     lines.extend(self.get_exconly(excinfo, indent=indent, markall=True))
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/_code/code.py", line 708, in get_exconly
INTERNALERROR>     exlines = excinfo.exconly(tryshort=True).split("\n")
INTERNALERROR>   File "/mypath/myenv/lib/python3.7/site-packages/_pytest/_code/code.py", line 532, in exconly
INTERNALERROR>     lines = format_exception_only(self.type, self.value)
INTERNALERROR>   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py", line 140, in format_exception_only
INTERNALERROR>     return list(TracebackException(etype, value, None).format_exception_only())
INTERNALERROR>   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py", line 497, in __init__
INTERNALERROR>     _seen=_seen)
INTERNALERROR>   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py", line 508, in __init__
INTERNALERROR>     capture_locals=capture_locals)
INTERNALERROR>   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py", line 344, in extract
INTERNALERROR>     for f, lineno in frame_gen:
INTERNALERROR>   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py", line 309, in walk_tb
INTERNALERROR>     yield tb.tb_frame, tb.tb_lineno
INTERNALERROR> AttributeError: 'function' object has no attribute 'tb_frame'
```

**Comment by Zac-HD** [comment] 2020-09-21 11:04
Can you please post the test code that raises this error?  Reproducing the error is much more helpful than reading a traceback.

**Comment by peteris-zealid** [comment] 2021-01-22 09:39
Had the same error and I traced it back to such a line:
```
r = requests.get(url, json=json_body, headers=headers, timeout=10)
```
With this line there is horrible stacktrace and without it everything works.

Then I made a testcase that calls requests.get with the same parameters and got such an error. 
```
E           requests.exceptions.ConnectionError: HTTPSConnectionPool(host='example.com', port=443): Max retries exceeded with url: /dev/mv/document (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x105f51310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```
I edited out original hostname, but replacing it with example.com gives the same error.


Here is the testcase that sadly works as expected. In the original test nothing was mocked or decorated. Hope this helps.
```
import requests

class TestRequests():
    def test_request_get(self):
        requests.get(
            'https://example.com/dev/mv/document',
            json={'content-type': 'application/json', 'x-api-key': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'},
            headers={'content-type': 'application/json', 'x-api-key': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'},
            timeout=10
        )
        assert True
```

**Comment by peteris-zealid** [comment] 2021-01-22 09:45
Used pytest 6.2.1

**Comment by Zac-HD** [comment] 2021-02-01 08:19
Closing this because I can't reproduce the issue 😢 

If anyone can provide a script which *does* reproduce the issue, I'll be happy to reopen it!

**Closed by Zac-HD** 2021-02-01 08:19 UTC
Labels: status: needs information
