### ISSUE TITLE
Suggestion: collapse report repeated warnings into a single line

### ISSUE THREAD

**Issue by tadeu** [pytest-dev/pytest#6602] opened 2020-01-28 17:02 UTC
Currently, warnings are being output like this (with the 'always' filter):

```
================================================== warnings summary ===================================================
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
source\python\alfasim_core\io\tab_reader\tab_converter.py:15
  K:\alfasim\alfasim_core\source\python\alfasim_core\io\tab_reader\tab_converter.py:15: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
    return np.fromstring(line_clean, sep=' ')
```

the suggestion is to collapse the repeated lines, reporting it like this:

```
================================================== warnings summary ===================================================
  K:\alfasim\alfasim_core\source\python\alfasim_core\io\tab_reader\tab_converter.py:15 (46 times):
    DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
      return np.fromstring(line_clean, sep=' ')
```

**Comment by nicoddemus** [comment] 2020-01-28 17:13
Thanks @tadeu,

It seems there's also a difference on how pytest-xdist reports warnings:

```
λ pytest .tmp\test_warns.py -n2 -q
bringing up nodes...
............................................................... [ 62%]
.....................................                          [100%]
========================= warnings summary ==========================
.tmp\test_warns.py:7
.tmp\test_warns.py:7
  C:\Users\bruno.ESSS.CO\pytest\.tmp\test_warns.py:7: UserWarning: some custom warning
    warnings.warn(UserWarning('some custom warning'))

.tmp\test_warns.py:8
.tmp\test_warns.py:8
  C:\Users\bruno.ESSS.CO\pytest\.tmp\test_warns.py:8: UserWarning: some custom warning
    warnings.warn(UserWarning('some custom warning'))

-- Docs: https://docs.pytest.org/en/latest/warnings.html
100 passed, 4 warnings in 0.71s
``` 

```
 λ pytest .tmp\test_warns.py -q
.............................................................. [ 62%]
......................................                         [100%]
========================= warnings summary ==========================
.tmp\test_warns.py:7
  C:\Users\bruno.ESSS.CO\pytest\.tmp\test_warns.py:7: UserWarning: some custom warning
    warnings.warn(UserWarning('some custom warning'))

.tmp\test_warns.py:8
  C:\Users\bruno.ESSS.CO\pytest\.tmp\test_warns.py:8: UserWarning: some custom warning
    warnings.warn(UserWarning('some custom warning'))

-- Docs: https://docs.pytest.org/en/latest/warnings.html
100 passed, 2 warnings in 0.14s
```

**Comment by blueyed** [comment] 2020-01-28 17:23
Duplicate of https://github.com/pytest-dev/pytest/issues/6591.

**Comment by nicoddemus** [comment] 2020-01-28 17:35
> Duplicate of #6591?

Yes, thanks. 👍

**Closed by nicoddemus** 2020-01-28 17:35 UTC
Labels: plugin: warnings, type: enhancement
