### ISSUE TITLE
PytestUnraisableExceptionWarning: ResourceWarning: unclosed ssl.SSLSocket

### ISSUE THREAD

**Issue by adamjstewart** [pytest-dev/pytest#11461] opened 2023-09-22 16:55 UTC
I'm seeing a weird issue in my new Python 3.11 environment:
<details>
  <summary>Error message</summary>

```python
cls = <class '_pytest.runner.CallInfo'>, func = <function call_runtest_hook.<locals>.<lambda> at 0x123481e40>, when = 'call'
reraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)

    @classmethod
    def from_call(
        cls,
        func: "Callable[[], TResult]",
        when: "Literal['collect', 'setup', 'call', 'teardown']",
        reraise: Optional[
            Union[Type[BaseException], Tuple[Type[BaseException], ...]]
        ] = None,
    ) -> "CallInfo[TResult]":
        """Call func, wrapping the result in a CallInfo.
    
        :param func:
            The function to call. Called without arguments.
        :param when:
            The phase in which the function is called.
        :param reraise:
            Exception or exceptions that shall propagate if raised by the
            function, instead of being wrapped in the CallInfo.
        """
        excinfo = None
        start = timing.time()
        precise_start = timing.perf_counter()
        try:
>           result: Optional[TResult] = func()

../spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/_pytest/runner.py:341: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/_pytest/runner.py:262: in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
../spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/pluggy/_hooks.py:265: in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
../spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/pluggy/_manager.py:80: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
../spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/_pytest/unraisableexception.py:88: in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def unraisable_exception_runtest_hook() -> Generator[None, None, None]:
        with catch_unraisable_exception() as cm:
            yield
            if cm.unraisable:
                if cm.unraisable.err_msg is not None:
                    err_msg = cm.unraisable.err_msg
                else:
                    err_msg = "Exception ignored in"
                msg = f"{err_msg}: {cm.unraisable.object!r}\n\n"
                msg += "".join(
                    traceback.format_exception(
                        cm.unraisable.exc_type,
                        cm.unraisable.exc_value,
                        cm.unraisable.exc_traceback,
                    )
                )
>               warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: <ssl.SSLSocket fd=-1, family=30, type=1, proto=0>
E               
E               Traceback (most recent call last):
E                 File "/Users/Adam/spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/lightly/api/_version_checking.py", line 14, in is_latest_version
E                   latest_version = get_latest_version(current_version)
E                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E               ResourceWarning: unclosed <ssl.SSLSocket fd=14, family=30, type=1, proto=0, laddr=('2003:c5:871c:3401:1c58:c181:796f:7f6e', 56478, 0, 0), raddr=('2a00:1450:4001:827::2013', 443, 0, 0)>

../spack/var/spack/environments/system/.spack-env/view/lib/python3.11/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning
```
</details>

I don't think this issue occurred in my old Python 3.10 environment. It could also be the result of upgrading to a new version of a dependency.

This might be tricky to reproduce unless we can figure out what's causing the issue. Basically, I have some code that is broken, and the unit test fails, as it should. However, instead of printing the normal failing code, it complains about an unclosed SSLSocket.

In my `pyproject.toml`, I'm treating all warnings as errors, so the above ResourceWarning becomes a fatal error. If I remove this, I see the expected failing code.

Do you have any idea why pytest might be behaving this way? Is there some bug in `lightly` relating to SSLSockets or is this just a red herring?

<details>
  <summary>Output of pip list</summary>

```
> pip list
Package                       Version
----------------------------- -----------
absl-py                       1.4.0
aenum                         3.1.12
affine                        2.1.0
aiohttp                       3.8.4
aiosignal                     1.2.0
alabaster                     0.7.13
antlr4-python3-runtime        4.9.3
anyio                         3.6.2
appdirs                       1.4.4
appnope                       0.1.3
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
asttokens                     2.2.1
astunparse                    1.6.3
async-lru                     1.0.3
async-timeout                 4.0.2
attrs                         23.1.0
Babel                         2.12.1
backcall                      0.2.0
backoff                       2.2.1
beautifulsoup4                4.12.2
black                         23.9.1
bleach                        6.0.0
blessed                       1.19.0
Bottleneck                    1.3.7
build                         1.0.3
cachetools                    5.2.0
Cartopy                       0.22.0
certifi                       2023.5.7
cffi                          1.15.1
cftime                        1.0.3.4
charset-normalizer            3.1.0
click                         8.1.3
click-plugins                 1.1.1
cligj                         0.7.2
cmocean                       2.0
colorama                      0.4.6
comm                          0.1.3
contourpy                     1.0.7
coverage                      7.2.6
croniter                      1.3.8
cycler                        0.11.0
Cython                        0.29.36
dateutils                     0.6.12
debugpy                       1.6.7
decorator                     5.1.1
deepdiff                      6.3.0
defusedxml                    0.7.1
docstring-parser              0.15
docutils                      0.18.1
editables                     0.3
efficientnet-pytorch          0.7.1
einops                        0.6.1
et-xmlfile                    1.0.1
executing                     1.2.0
fastapi                       0.98.0
fastjsonschema                2.16.3
filelock                      3.12.0
Fiona                         1.9.4
flake8                        6.1.0
flit_core                     3.9.0
fonttools                     4.39.4
fqdn                          1.5.1
frozenlist                    1.3.1
fsspec                        2023.1.0
GDAL                          3.7.2
geocube                       0.3.2
geopandas                     0.11.1
gevent                        23.7.0
google-auth                   2.20.0
google-auth-oauthlib          0.5.2
greenlet                      2.0.2
grpcio                        1.52.0
h11                           0.13.0
h5py                          3.8.0
hatch-jupyter-builder         0.8.3
hatchling                     1.17.0
huggingface-hub               0.14.1
hydra-core                    1.3.1
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.6.0
importlib-resources           5.12.0
iniconfig                     2.0.0
inquirer                      3.1.3
ipykernel                     6.23.1
ipython                       8.14.0
ipywidgets                    8.0.2
isoduration                   20.11.0
isort                         5.12.0
itsdangerous                  2.1.2
jaraco.classes                3.2.3
jedi                          0.18.2
Jinja2                        3.0.3
joblib                        1.2.0
json5                         0.9.14
jsonargparse                  4.19.0
jsonpointer                   2.0
jsonschema                    4.17.3
jupyter_client                8.2.0
jupyter_core                  5.3.0
jupyter-events                0.6.3
jupyter-lsp                   2.2.0
jupyter_server                2.6.0
jupyter_server_terminals      0.4.4
jupyterlab                    4.0.1
jupyterlab-pygments           0.2.2
jupyterlab_server             2.22.1
jupyterlab-widgets            3.0.3
keyring                       23.13.1
kiwisolver                    1.4.4
kornia                        0.7.0
laspy                         2.2.0
lightly                       1.4.18
lightly-utils                 0.0.2
lightning                     2.0.9
lightning-cloud               0.5.38
lightning-utilities           0.8.0
Markdown                      3.4.1
markdown-it-py                3.0.0
MarkupSafe                    2.1.3
matplotlib                    3.8.0
matplotlib-inline             0.1.6
mccabe                        0.7.0
mdurl                         0.1.2
mistune                       2.0.5
more-itertools                9.1.0
mpmath                        1.2.1
multidict                     6.0.4
munch                         2.5.0
mypy                          1.3.0
mypy-extensions               1.0.0
nbclient                      0.6.7
nbconvert                     7.4.0
nbformat                      5.8.0
nbmake                        1.4.3
nbsphinx                      0.8.8
nest-asyncio                  1.5.6
netCDF4                       1.6.2
networkx                      3.1
notebook_shim                 0.2.3
numexpr                       2.8.4
numpy                         1.25.2
oauthlib                      3.2.1
odc-geo                       0.1.2
omegaconf                     2.3.0
openpyxl                      3.1.2
ordered-set                   4.0.2
overrides                     7.3.1
packaging                     23.1
pandas                        2.0.2
pandocfilters                 1.5.0
parso                         0.8.3
pathspec                      0.11.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.5.0
pip                           23.0
pkginfo                       1.9.6
planetary-computer            0.4.9
platformdirs                  3.5.3
pluggy                        1.0.0
poetry-core                   1.6.1
pretrainedmodels              0.7.4
prometheus-client             0.17.0
prompt-toolkit                3.0.38
protobuf                      3.20.3
psutil                        5.9.5
ptyprocess                    0.7.0
pure-eval                     0.2.2
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pybind11                      2.10.1
pycocotools                   2.0.6
pycodestyle                   2.11.0
pycparser                     2.21
pydantic                      1.10.9
pydocstyle                    6.2.1
pyflakes                      3.1.0
pygeos                        0.10
Pygments                      2.15.1
PyJWT                         2.4.0
pyparsing                     3.0.9
pyproj                        3.6.0
pyproject_hooks               1.0.0
pyrsistent                    0.19.3
pyshp                         2.1.0
pystac                        1.4.0
pystac-client                 0.5.1
pytest                        7.3.2
pytest-cov                    4.0.0
python-dateutil               2.8.2
python-dotenv                 0.19.2
python-editor                 1.0.4
python-json-logger            2.0.7
python-multipart              0.0.5
pytorch-lightning             2.0.0
pytorch-sphinx-theme          0.0.24
pytz                          2023.3
pyupgrade                     3.3.1
PyYAML                        6.0
pyzmq                         25.0.2
radiant-mlhub                 0.5.1
rarfile                       4.1
rasterio                      1.3.8
readchar                      4.0.5
readme-renderer               37.3
requests                      2.31.0
requests-oauthlib             1.3.1
requests-toolbelt             1.0.0
rfc3339-validator             0.1.4
rfc3986                       2.0.0
rfc3986-validator             0.1.1
rich                          13.4.2
rioxarray                     0.4.1.post0
rsa                           4.9
Rtree                         1.0.1
safetensors                   0.3.1
scikit-learn                  1.3.1
scipy                         1.10.1
segmentation-models-pytorch   0.3.3
Send2Trash                    1.8.0
setuptools                    63.4.3
setuptools-scm                7.1.0
Shapely                       1.8.4
six                           1.16.0
sniffio                       1.3.0
snowballstemmer               2.2.0
snuggs                        1.4.1
soupsieve                     2.4.1
Sphinx                        5.3.0
sphinx_design                 0.4.1
sphinx-rtd-theme              1.2.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jquery          4.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-programoutput   0.15
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.9
stack-data                    0.6.2
starlette                     0.27.0
starsessions                  1.3.0
sympy                         1.11.1
tensorboard                   2.13.0
tensorboard-data-server       0.7.0
tensorboard-plugin-wit        1.8.1
terminado                     0.17.1
threadpoolctl                 3.1.0
timm                          0.9.2
tinycss2                      1.1.1
tokenize-rt                   4.2.1
tomli                         2.0.1
torch                         2.0.1
torchmetrics                  1.1.1
torchvision                   0.15.2
tornado                       6.2
tqdm                          4.65.0
traitlets                     5.9.0
trove-classifiers             2023.3.9
twine                         4.0.2
typeshed-client               2.1.0
typing_extensions             4.6.3
tzdata                        2023.3
uri-template                  1.2.0
urllib3                       1.26.12
uvicorn                       0.20.0
vermin                        1.5.2
wcwidth                       0.2.5
webcolors                     1.11.1
webencodings                  0.5.1
websocket-client              1.5.1
websockets                    10.4
Werkzeug                      2.3.4
wheel                         0.37.1
widgetsnbextension            4.0.3
xarray                        2023.7.0
yarl                          1.8.1
zipfile-deflate64             0.2.0
zipp                          3.8.1
zope.event                    4.6
zope.interface                5.4.0
```
</details>

* pytest 7.3.2
* python 3.11.4
* macOS 13.5.2

**Comment by RonnyPfannschmidt** [comment] 2023-09-22 17:17
I recommend to turn the specific pytest warning intro a warning

For better debugging a pytest error mode for warnings may be needed (as the stdlib error variant is debugging hostile), instead of erroring via exception,the erroring ought to be deferred (so one can see all warnings)

**Comment by adamjstewart** [comment] 2023-09-23 18:52
It's possible that the issue is that I'm testing code within jsonargparse CLI which wraps all calls in `sys.exit(...)`.

**Comment by Zac-HD** [comment] 2023-10-01 08:16
See https://docs.python.org/3/library/sys.html#sys.unraisablehook - it's likely that you've finished running some code without closing the socket; then that emits a warning when garbage-collected and your config then turns that warning into an error.

To isolate the cause, I'd be going through the usual process of getting a minimal failing example, with as little in the environment and test code as possible.  If you have reason to think that `lightly` might fail to close a socket, that'd be a good place to start.

**Closed by Zac-HD** 2023-10-01 08:16 UTC
Labels: type: question, plugin: warnings
