### ISSUE TITLE
Experiencing unicode error inside pytester in Hypothesis test suite

### ISSUE THREAD

**Issue by DRMacIver** [pytest-dev/pytest#1131] opened 2015-10-12 11:33 UTC
When running under Python 3 on Windows Hypothesis seems to be triggering an exception inside pytester when I run the following test (I have tried this against 1.11.4). Unfortunately I haven't been able to reproduce a small test case without Hypothesis involved:

``` python
import pytest

pytest_plugins = str('pytester')

UNICODE_EMITTING = """
import pytest
from hypothesis import given, Settings, Verbosity
from hypothesis.strategies import text
import sys

@given(text(), settings=Settings(verbosity=Verbosity.verbose))
def test_should_emit_unicode(t):
    assert all(ord(c) <= 1000 for c in t)
"""


def test_output_emitting_unicode(testdir, monkeypatch):
    script = testdir.makepyfile(UNICODE_EMITTING)
    testdir.runpytest_subprocess(script, "--verbose", "--capture=no")
```

The exception produced is:

```
C:\projects\hypothesis\tests\pytest\test_capture.py:39: in test_output_emitting_unicode 
    script, '--verbose', '--capture=no') 
C:\Python33-x64\lib\site-packages\_pytest\pytester.py:952: in runpytest_subprocess 
    return self.run(*args)
C:\Python33-x64\lib\site-packages\_pytest\pytester.py:873: in run
    return self._run(*cmdargs)
C:\Python33-x64\lib\site-packages\_pytest\pytester.py:894: in _run
    out = f1.read().splitlines()
C:\Python33-x64\lib\codecs.py:691: in read
    return self.reader.read(size) 
C:\Python33-x64\lib\codecs.py:494: in read
    newchars, decodedbytes = self.decode(data, self.errors)
E   UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 37501: invalid start byte 
```

I have run this on pytest 2.8.2, but I was seeing this error before on probably 2.8.0 (which predates the introduction of this test so I haven't tried it on 2.7.x).

I don't know if this is the Hypothesis pytest plugin doing something wrong (it's certainly putting non-ascii string objects in the report section), but if so it would be nice to have this error in a more comprehensible manner as I can't really debug this.

**Comment by lwm** [comment] 2016-11-26 15:26
I've tried to reproduce and I think it is fixed now with:

``` bash
$ wget https://git.io/v1Tbt -O test_foo.py && pytest test_foo.py
```

Where the link is the example in a gist ([source](https://gist.githubusercontent.com/lwm/5223d4a20d65ce107a9aa31443894912/raw/896bcfa8519d7b90515815eec3f7dee3f8887dd4/1131-test.py)).

Looks like this can be closed!

**Comment by nicoddemus** [comment] 2016-11-26 17:01
Thanks @lwm for verifying! I also tested and it works now. 😁

**Closed by nicoddemus** 2016-11-26 17:01 UTC
Labels: bug, unicode
