### ISSUE TITLE
Tests collection is slow on high number of tests

### ISSUE THREAD

**Issue by Nepherhotep** [pytest-dev/pytest#5516] opened 2019-06-28 13:57 UTC
Hi,

We have over 15k tests in the repository, and recently switched from nosetests to pytest. Apparently, tests collection in pytest is way slower than in nosetests - 130s vs 30s. Also, I need to mention that `norecursedirs` and `testpaths` parameters are both set, just to exclude the case of walking in .git or other unrelated directories.
It's also interesting, that the number of collected tests is asymptotic to time:
![image](https://user-images.githubusercontent.com/2122618/60345588-5eb3ff00-9987-11e9-8ef1-59da7c43c9a3.png)

I tried to profile it using pyflame and cProfile, it seems like the slowest part is calling node.py:FixtureManager._matchfactories method call:
![image](https://user-images.githubusercontent.com/2122618/60345970-2cef6800-9988-11e9-9b75-eb99ed216a23.png)

Here is a callgraph:
![image](https://user-images.githubusercontent.com/2122618/60346065-61632400-9988-11e9-86ce-b09eb99c949c.png)

When I tried to log, what's is happening, it seems like, the more tests, the more method is called with polynomial dependency.

Going deeper into `_matchfactories` method, I was able to reduce collection time from 130s to 85s just by caching the results of `_splitnode` method:
```diff
diff --git a/src/_pytest/nodes.py b/src/_pytest/nodes.py
index 491cf9d2c..62eb66086 100644
--- a/src/_pytest/nodes.py
+++ b/src/_pytest/nodes.py
@@ -13,6 +13,9 @@ SEP = "/"
 tracebackcutdir = py.path.local(_pytest.__file__).dirpath()
 
 
+_node_cache = {}
+
+
 def _splitnode(nodeid):
     """Split a nodeid into constituent 'parts'.
 
@@ -31,9 +34,13 @@ def _splitnode(nodeid):
     if nodeid == "":
         # If there is no root node at all, return an empty list so the caller's logic can remain sane
         return []
-    parts = nodeid.split(SEP)
-    # Replace single last element 'test_foo.py::Bar' with multiple elements 'test_foo.py', 'Bar'
-    parts[-1:] = parts[-1].split("::")
+
+    parts = _node_cache.get(nodeid)
+    if not parts:
+        parts = nodeid.split(SEP)
+        # Replace single last element 'test_foo.py::Bar' with multiple elements 'test_foo.py', 'Bar'
+        parts[-1:] = parts[-1].split("::")
+        _node_cache[nodeid] = parts
     return parts
```

It doesn't solve the asymptotic problem, but just making `_splitnode` and thus `_matchfactories` method faster:
![image](https://user-images.githubusercontent.com/2122618/60347343-13035480-998b-11e9-974e-450581a1b5d4.png)

Please let me know if you think there could be a better way to fix the problem.

Thanks!
Alex

**Comment by nicoddemus** [comment] 2019-06-29 19:28
Thanks @Nepherhotep for the report.

I think a cache there wouldn't hurt (might even use `@lru_cache(maxsize=None)` instead), but I think it would be worth to investigate this a little further to see if we can have more gains.

Would it be possible to share the output of `pytest --collect-only` so we can reproduce your test tree with dummy tests? I imagine this would facilitate debugging and improving performance there.

**Comment by Nepherhotep** [comment] 2019-07-01 15:35
Thanks @nicoddemus 
It will take me a while to obfuscate data, but I'll prepare the output soon. 

Thanks!

**Comment by Nepherhotep** [comment] 2019-07-02 20:22
[collected_tests.txt](https://github.com/pytest-dev/pytest/files/3352174/collected_tests.txt)

Hi @nicoddemus,

Please see the file attached. 
As for cache, if I want it to be in 4.6-maintenance branch as well, do I need to submit two different PRs - lru_cache for "master" and dict-based cache to "4.6-maintenance" (as lru_cache is not supported by 2.7 yet)?

**Comment by nicoddemus** [comment] 2019-07-02 21:52
Thanks, I will take a look

> As for cache, if I want it to be in 4.6-maintenance branch as well, do I need to submit two different PRs - lru_cache for "master" and dict-based cache to "4.6-maintenance" (as lru_cache is not supported by 2.7 yet)?

Actually I don't think this qualifies to go to 4.6-maintenance, as this is an improvement and 4.6-maintenance is about critical bug-fixes only for the 4.6 series.

**Comment by Nepherhotep** [comment] 2019-07-06 22:11
Gotcha, that makes sense.

**Comment by bluetech** [comment] 2019-08-01 15:22
I tried to reproduce the issue using `collected_tests.txt` but there is no difference -- just generating the test directory using the following script doesn't call `_splitnodes`. I think fixtures need to be used somewhere. Can you amend the script such that it reproduces the before/after results you got?

Also, since `_splitnodes` is only called from one function, `ischildnode`, it might be more worthwhile to optimize *that*.

---

```py
import os

package, module = None, None
for line in open('collected_tests.txt'):
    if not line.strip():
        continue
    scope, name = line.strip()[1:-1].split(' ')
    if scope == 'Package':
        package = './' + name
        os.makedirs(package)
    elif scope == 'Module':
        module = open(package + '/' + name, 'w')
    elif scope == 'UnitTestCase':
        print(f'class {name}:\n    pass', file=module)
    elif scope == 'TestCaseFunction':
        print(f'    def {name}(self):\n        pass', file=module)

for root, dirs, files in os.walk('dir_0'):
    open(root + '/__init__.py', 'w')
```

**Comment by Nepherhotep** [comment] 2019-08-01 18:07
@bluetech, I'd say, it's required to refactor `getfixturedefs`, which calls `_matchfactories` function polynomial amount of times, which causes a slowdown in performing quite simple calculations like splitting nodes.

**Comment by bluetech** [comment] 2019-08-01 19:36
Sounds like it. If you can arrange a reproduction for this, I think it will be helpful.

Looking narrowly at how `_matchfactories` can be made faster, I am unsure about something. Is the following expected behavior? Are `/` and `::` compatible in this way?

```py
>>> _pytest.nodes.ischildnode(baseid='a/b/c/d', nodeid='a/b::c::d::e')
True
```

**Comment by nicoddemus** [comment] 2019-08-02 01:32
FTR: Some work has been done in #5681 already thanks to @Nepherhotep?

**Comment by Nepherhotep** [comment] 2019-08-02 12:23
@bluetech I'll try to create a fake repo, which is slow to collect.

@nicoddemus great thanks for guidance in that PR!

**Comment by boxed** [comment] 2019-11-04 12:28
I'm looking at some performance issues with pytest at the moment and found this ticket. @Nepherhotep how did the changes that went into pytest already affect your use case?

**Comment by Nepherhotep** [comment] 2019-11-04 15:35
Hi @boxed,

Thanks for getting back. Let me check the performance with the most recent pytest version.

**Comment by Nepherhotep** [comment] 2019-11-05 21:17
@boxed pytest==5.2.2 collects 15k tests for 70 seconds. That's the result of tests collection, when splitnode optimization PR is merged.
However, collection time still seem to asymptotically depend on the number of tests, as the first 5k are collected just for 15 seconds.

**Comment by Zac-HD** [comment] 2019-11-26 03:20
That curve is classic [accidentally quadratic](https://accidentallyquadratic.tumblr.com/) performance, which might help to diagnose it 😄

**Comment by blueyed** [comment] 2019-11-26 20:34
@Nepherhotep 
Have you considered what @bluetech suggested?

> Also, since `_splitnodes` is only called from one function, `ischildnode`, it might be more worthwhile to optimize _that_.

@bluetech 
> Looking narrowly at how `_matchfactories` can be made faster, I am unsure about something. Is the following expected behavior? Are `/` and `::` compatible in this way?
> 
> ```python
> >>> _pytest.nodes.ischildnode(baseid='a/b/c/d', nodeid='a/b::c::d::e')
> True
> ```

That looks wrong to me, but cannot really say for sure.  AFAIK "/" should be used inside of parts (split by "::") for paths.  They should not be mixed.

**Comment by rndusr** [comment] 2020-03-31 13:25
Has this been fixed?

For me, test collection went down from more than a minute to about 6 seconds.

**Comment by blueyed** [comment] 2020-03-31 14:45
@rndusr 
There have been certainly fixes in this regard.  It would be interesting if you could git-bisect it.

**Comment by boxed** [comment] 2020-03-31 15:59
Last I looked it hadn't been fixed at least. Maybe 6 seconds is a lot better than it was but I'd bet it's about 5 seconds too much :)

**Comment by rndusr** [comment] 2020-03-31 17:13
I'd like to bisect, but I'm having trouble installing pytest.

"cd path/to/pytest ; pip install --editable ." fails:

/path/to/venv/bin/python3: can't find '__main__' module in '/path/to/venv/share/python-wheels/pep517-0.7.0-py2.py3-none-any.whl/pep517/_in_process.py'

No idea what's going on here.

"cd path/to/pytest ; python3 ./setup.py develop -e -b ./build" works, but then I
can't reproduce the performance increase. I can checkout master, 5.4.*, 5.3.*
etc, I always get the same bad performance.

When I uninstall pytest and install from pypi, fast test collection is back.

The "Contributing" section in the docs doesn't mention anything about installing
pytest for development.

**Comment by blueyed** [comment] 2020-03-31 17:36
@rndusr 

try:

```
python -m venv .venv
.venv/bin/pip install ".[testing]"
.venv/bin/python -m pytest …
```
Basically step 7 from https://docs.pytest.org/en/latest/contributing.html#long-version

**Comment by Nepherhotep** [comment] 2020-03-31 18:57
@rndusr I tested the most recent version in pypi, and it's still around 2 minutes for 25k tests. What specific version do I need to try?

**Comment by rndusr** [comment] 2020-04-01 10:53
> python -m venv .venv
> .venv/bin/pip install ".[testing]"

That gives me the same "can't find '__main__' module" error.
Doesn't matter if I use Python 3.7 or 3.8.

I've noticed the faster test collection with pytest 5.4.1. It takes between 3
and 7 seconds to collect 13k tests. (But they are mostly parametrized. I don't
know if that matters.)

I've been trying to get the slow test collection back, but I can't!

I've tried old pytest versions with Python 3.7 and 3.8. I *know* some
combination of these had me waiting considerably longer, but now tests are
consistently collected in less than ten seconds.

**Comment by boxed** [comment] 2020-04-01 12:51
@rndusr you might want to check the discussion in https://github.com/pytest-dev/pytest/issues/2206 I believe that pytest is a bit more than 10x slower than it strictly needs to be.

**Comment by blueyed** [comment] 2020-04-04 14:39
@rndusr JFI: https://github.com/pytest-dev/pytest/commit/ce1cc3dddb384d7f73d8409280931342e9c539e2 seems to have quite an impact, but is in 3.10 already (so likely not relevant) - what version have you've been using before this got fixed for you?

**Comment by rndusr** [comment] 2020-04-04 15:20
From looking at the release dates, the fix (for me) was probably introduced in 5.4.0.

**Comment by bluetech** [comment] 2020-04-29 14:30
#7130 fixes at least one instance of quadratic behavior in relation to the number of tests, so might help here.

**Comment by Nepherhotep** [comment] 2020-04-29 15:11
Thanks a lot! I'll compare the performance with the fix and without.

**Comment by Nepherhotep** [comment] 2020-04-29 16:37
Tested our case, without the fix - it's 1m 33 seconds, with the fix - 1m 29
seconds (20k tests).

**Comment by bluetech** [comment] 2020-05-05 20:45
@Nepherhotep To get a better understanding, it will help to get a profile of the collection phase on your test suite. You can do it like this:

```
python -m cProfile --sort=cumtime -m pytest --collect-only your-tests-dirs-here
```

and paste the output here. Notes:

- The command works on Python 3.8, if you use an earlier version, it will need some wrapper script or such.
- The output might contain some references to your source code, you might want to redact it if it's sensitive.

**Comment by Nepherhotep** [comment] 2020-05-06 01:35
Sure, let me generate and obfuscate the report.

**Comment by bluetech** [comment] 2020-09-04 10:50
I'll close this issue for now since it's not actionable for us.

@Nepherhotep if you get around to producing a profile (on the latest available pytest version), please feel free to reopen.

**Closed by bluetech** 2020-09-04 10:50 UTC
Labels: topic: collection, type: performance

**Comment by atzorvas** [comment] 2020-10-01 06:58
Hey @bluetech, what's the command/wrapper that I'd need to run for python-3.6?

> @Nepherhotep To get a better understanding, it will help to get a profile of the collection phase on your test suite. You can do it like this:
> 
> ```
> python -m cProfile --sort=cumtime -m pytest --collect-only your-tests-dirs-here
> ```
> 
> and paste the output here. Notes:
> 
>     * The command works on Python 3.8, if you use an earlier version, it will need some wrapper script or such.
> 
>     * The output might contain some references to your source code, you might want to redact it if it's sensitive.

**Comment by bluetech** [comment] 2020-10-01 07:12
@atzorvas Instead of using `-m pytest`, you can provide the full path to the `pytest` script. For example, on my machine (Linux), in a project which is using a virtualenv called `venv`, pytest is found `venv/bin/pytest`, so the command is:

```
python -m cProfile --sort=cumtime venv/bin/pytest --collect-only your-tests-dirs-here
```

If you are using a unix-like OS, you can find where your pytest by running `which pytest`.

**Comment by ashb** [comment] 2021-02-18 10:33
Running `--collect-only` on apache/airflow is also "slow" (I don't have anything to compare it to) -- it takes 70s to collect 7k tests.

I've attached a cprofile output.

[pytest-collect-cprofile.txt](https://github.com/pytest-dev/pytest/files/6002090/pytest-collect-cprofile.txt)

Anything obvious jump out there?

Additionally you can run this yourself of course. If you won't want to install _all_ the extra deps that Airflow's tests need, then from the checkout of Airflow run `./breeze -p 3.8` and it will dump you in a docker container with most (but not all) deps needed for tests.

**Comment by nicoddemus** [comment] 2021-02-18 11:33
Hi @ashb,

Thanks for posting the results.

Seems like a lot of time is spent in the import mechanism:

```
9813/906    0.043    0.000   60.845    0.067 <frozen importlib._bootstrap>:986(_find_and_load)
9393/725    0.035    0.000   60.822    0.084 <frozen importlib._bootstrap>:956(_find_and_load_unlocked) 
```

What is not clear sometimes is that, in order to import test modules, pytest needs to import the top-level imports in the file, which often import from other modules in the project and its dependencies, which can be costly.

A way to explore that is to remove all top-level imports from all the test files, and run `pytest --collect-only`; this way we can actually measure only pytest's collection overhead.

**Comment by ashb** [comment] 2021-02-18 18:11
I started experimenting on a few files, and yes removing top level imports does seem to help _a lot_.

Sadly changing our test site like this wholesale won't be easy :(

**Comment by nicoddemus** [comment] 2021-02-18 22:29
> Sadly changing our test site like this wholesale won't be easy :(

Indeed. :(

Sadly pytest can't really help here, after all it needs to import the test modules to execute the tests, by definition.

**Comment by neiljp** [comment] 2021-02-18 23:51
Could you clarify the use of "top level imports" here?

**Comment by nicoddemus** [comment] 2021-02-19 02:13
That would be every import which is outside functions/methods:

```python
import foo

def test_bar():
    import bar
```

Above, `foo` is top-level, while `bar` is not.

**Comment by The-Compiler** [comment] 2021-02-19 09:05
Note that on Python 3.7+, you can run `python3 -X importtime -m pytest` to potentially find the worst offenders contributing to this.

https://github.com/kmichel/python-importtime-graph (not hosted anymore, but you can download the `index.html` and use it locally) and https://github.com/asottile/importtime-waterfall (with http://www.softwareishard.com/har/viewer/) can be useful in visualizing the information.

**Comment by boxed** [comment] 2021-02-19 09:28
> > Sadly changing our test site like this wholesale won't be easy :(
> 
> Indeed. :(
> 
> Unfortunately pytest can't really help here, after all it needs to import the test modules to execute the tests, by definition.

To execute yes, but not necessarily to collect. It you just want to execute a single test it could look at the AST of all the test files before to filter down what it needs to import first. This would be a *huge* rewrite though.

**Comment by The-Compiler** [comment] 2021-02-19 09:31
> To execute yes, but not necessarily to collect. It you just want to execute a single test it could look at the AST of all the test files before to filter down what it needs to import first. This would be a _huge_ rewrite though.

Definitely not worth the trouble I'd say - also note that it'd break apart as soon as e.g. parametrization comes into play.

**Comment by ashb** [comment] 2021-02-19 09:49
Airflow makes heavy use of parametrization, both form the parameterize module and pytests own, plus custom marks.

**Comment by nicoddemus** [comment] 2021-02-19 11:46
> Definitely not worth the trouble I'd say - also note that it'd break apart as soon as e.g. parametrization comes into play.

I tend to agree here, unfortunately the AST is not enough to collect all tests: besides perametrization and marks as mentioned by @the-compiler and @ashb, the entire collection mechanism is flexible enough to allow for plugins and normal testing code to generate tests dynamically. It could of course be made to work with the 99% of cases, but as @The-Compiler mentions I'm not sure it is worth the trouble.

**Comment by ashb** [comment] 2021-02-19 11:55
The Airflow CI is perhaps somewhat unique, in that we run pytest multiple times (sequentially) with different custom marks enabled.

Would the option to cache the collection step be an option, so that we wouldn't have to re-collect subsequent times?

**Comment by nicoddemus** [comment] 2021-02-19 11:58
> Would the option to cache the collection step be an option, so that we wouldn't have to re-collect subsequent times?

I don't think so, we need to import to get to the code in the end, and the internals at the moment really need the entire `Item` object and associated test functions to work.
