### ISSUE TITLE
Freeze when comparing byte data with verbose flag

### ISSUE THREAD

**Issue by FeralFox** [pytest-dev/pytest#8404] opened 2021-03-05 13:12 UTC
When comparing a lot of byte data (like two images), pytest will look frozen when using the -v flag. Not sure if this is a bug, but I at least wanted to document this behaviour.

To clarify this, here is the code making problems

```
def test_compare():
    with open('one.png', "rb") as f:
        actual_image = f.read()

    with open('two.png', "rb") as f:
        expected_image = f.read()

    assert actual_image == expected_image
```

Assuming that both images are different, running this code with "pytest -s" will take a view milliseconds, but running it with "pytest -s -v" took 12 minutes on my computer.

A workaround is to put the comparison in an own variable
```
def test_compare():
    with open('one.png', 'rb') as f:
        actual_image = f.read()

    with open('two.png', 'rb') as f:
        expected_image = f.read()

    result = actual_image == expected_image
    assert result
```

Running this will take a view milliseconds only, no matter if the assertion fails or succeeds.

I have attached an example workspace.

By the way you will also run into this issue when executing the tests using the pytest runner of PyCharm.

[freezing_assertion.zip](https://github.com/pytest-dev/pytest/files/6090574/freezing_assertion.zip)

**Comment by asottile** [comment] 2021-03-07 16:21
it's generating a diff between the two sequences, not really sure there is much that can be done here because `-v` is "show me the full diff"

**Comment by RonnyPfannschmidt** [comment] 2021-03-07 16:55
As we don't have a sensible binary diff I'd suggest we show content hashes for big binary items

**Comment by The-Compiler** [comment] 2021-03-08 14:46
Indeed looks like it's mostly difflib to "blame" (via `_pytest.assertion.util._compare_eq_iterable`):

```
         842250151 function calls (842234615 primitive calls) in 2085.428 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
[...]
        1    0.000    0.000    0.001    0.001 difflib.py:1(<module>)
3518/1728    0.008    0.000 1638.433    0.948 difflib.py:1027(_fancy_helper)
       30    0.000    0.000    0.004    0.000 difflib.py:1039(_qformat)
    55597    0.066    0.000    0.066    0.000 difflib.py:1101(IS_CHARACTER_JUNK)
        1    0.000    0.000    0.000    0.000 difflib.py:1343(ndiff)
       10    0.000    0.000    0.011    0.001 difflib.py:152(__init__)
        1    0.000    0.000    0.000    0.000 difflib.py:1706(HtmlDiff)
       16    0.000    0.000    0.013    0.001 difflib.py:216(set_seqs)
  2116727    3.022    0.000    3.022    0.000 difflib.py:228(set_seq1)
     2417    0.009    0.000    1.072    0.000 difflib.py:254(set_seq2)
     2416    0.561    0.000    1.064    0.000 difflib.py:298(__chain_b)
  6131284  758.250    0.000 1423.855    0.000 difflib.py:337(find_longest_match)
  4613922    5.951    0.000    5.951    0.000 difflib.py:39(_calculate_ratio)
        1    0.000    0.000    0.000    0.000 difflib.py:44(SequenceMatcher)
   381492   44.893    0.000 1520.532    0.004 difflib.py:453(get_matching_blocks)
        7    0.000    0.000    0.041    0.006 difflib.py:524(get_opcodes)
   381485    3.618    0.000 1537.782    0.004 difflib.py:629(ratio)
  4703761    5.714    0.000    5.714    0.000 difflib.py:651(<genexpr>)
  2115726  276.136    0.000  522.602    0.000 difflib.py:654(quick_ratio)
  2116711   12.918    0.000   23.404    0.000 difflib.py:683(real_quick_ratio)
       12    0.000    0.000    0.004    0.000 difflib.py:747(_keep_original_ws)
      862    0.002    0.000    0.003    0.000 difflib.py:749(<genexpr>)
        1    0.000    0.000    0.000    0.000 difflib.py:756(Differ)
        1    0.000    0.000    0.000    0.000 difflib.py:850(__init__)
     2429    0.006    0.000 2097.771    0.864 difflib.py:873(compare)
     2415    0.003    0.000    0.003    0.000 difflib.py:914(_dump)
     1685    0.004    0.000    0.006    0.000 difflib.py:919(_plain_replace)
5221/1731    9.823    0.002 2097.742    1.212 difflib.py:933(_fancy_replace)
```

**Comment by nicoddemus** [comment] 2021-03-08 15:57
> As we don't have a sensible binary diff I'd suggest we show content hashes for big binary items

Hashes are one possibility, however I don't think it will help the user much.

Perhaps it would be sensible to just display:

> Two byte strings differ 

After a certain threshold (say 240 bytes)?

**Comment by RonnyPfannschmidt** [comment] 2021-03-08 16:25
I would consider the sums a help for quickly grasping if things broke similar or different

But it's not strictly necessary

**Comment by nicoddemus** [comment] 2021-03-08 16:42
Ahh you mean comparing different runs (subsequential runs or different platforms/versions)? Ahh yes that makes sense.

**Comment by The-Compiler** [comment] 2021-03-08 19:25
240 bytes seems awfully short. Note that there are many useful cases when comparing byte strings, e.g. for data coming from the network in some way (which is often human-readable ASCII, but still stored as bytes).

Either such a limit should be much higher (in this example, the files are 36kB/39kB) - or we should have some kind of heuristic where we consider how many of the characters in the data are printable ASCII characters or something.

Based on the example from @FeralFox (thanks for that amazing reproducer, btw!), when I get the diff based on the 10000 first characters:

```diff
diff --git i/src/_pytest/assertion/util.py w/src/_pytest/assertion/util.py
index da1ffd15e..f6c1fe422 100644
--- i/src/_pytest/assertion/util.py
+++ w/src/_pytest/assertion/util.py
@@ -277,8 +277,8 @@ def _compare_eq_iterable(
     # dynamic import to speedup pytest
     import difflib
 
-    left_formatting = pprint.pformat(left).splitlines()
-    right_formatting = pprint.pformat(right).splitlines()
+    left_formatting = pprint.pformat(left[:10000]).splitlines()
+    right_formatting = pprint.pformat(right[:10000]).splitlines()
 
     # Re-format for different output lengths.
     lines_left = len(left_formatting)

```

it still happens instantly, but if I based it on the 100 last characters:

```diff
diff --git i/src/_pytest/assertion/util.py w/src/_pytest/assertion/util.py
index da1ffd15e..3af815827 100644
--- i/src/_pytest/assertion/util.py
+++ w/src/_pytest/assertion/util.py
@@ -276,9 +276,10 @@ def _compare_eq_iterable(
         return ["Use -v to get the full diff"]
     # dynamic import to speedup pytest
     import difflib
 
-    left_formatting = pprint.pformat(left).splitlines()
-    right_formatting = pprint.pformat(right).splitlines()
+    left_formatting = pprint.pformat(left[-100:]).splitlines()
+    right_formatting = pprint.pformat(right[-100:]).splitlines()
 
     # Re-format for different output lengths.
     lines_left = len(left_formatting)
```

it still takes multiple minutes (I didn't wait for it to finish, might update this comment once that happens).

Thus, clearly there's more than just the amount of characters at play here. There must be something going on with that data which makes difflib perform very poorly. I'm not sure if we can detect/improve that, other than with the heuristic I mentioned above.

**Comment by RonnyPfannschmidt** [comment] 2021-03-08 19:47
true about the network data

i wonder if there is a sensible way to figure this based on the ratio of unprintable data
a custom one for binary seems needed in any case

**Comment by The-Compiler** [comment] 2021-08-15 13:15
Might be a duplicate of #7206?

**Comment by Zac-HD** [comment] 2021-09-27 06:42
Closing as duplicate; per https://github.com/pytest-dev/pytest/issues/8998#issuecomment-900389987 we should try adding a heuristic that skips `difflib.ndiff()` for sequences above a fixed length (tbd based on some benchmarks).

**Closed by Zac-HD** 2021-09-27 06:42 UTC
Labels: type: bug, topic: reporting, type: performance, topic: rewrite
