### ISSUE TITLE
Incorrect AssertionError for Inequations (from AssertionRewrite) 

### ISSUE THREAD

**Issue by marincandenza** [pytest-dev/pytest#8333] opened 2021-02-09 19:36 UTC
**Testcode**
`assert 0.0 <= meas_voltage < 25`

where **meas_voltage** is 0 and pytest report-html displays the assertion error as
> assert meas_voltage > 0 and meas_voltage < 25
> E           assert (0.0 > 0)

Debian buster, Python 3.9.1, pytest 6.2.2

**Comment by The-Compiler** [comment] 2021-02-14 16:20
What is `pytest report-html`? It's not part of pytest's core.

Also I can't reproduce this with pytest itself - the assertion passes. Do you have a runnable example?

**Comment by marincandenza** [comment] 2021-02-15 19:25
I also tried to reproduce on my Windows machine without success. 
Therefore, I suggest to close this issue.

**Comment by The-Compiler** [comment] 2021-02-15 19:30
Alright, closing this then!

**Closed by The-Compiler** 2021-02-15 19:30 UTC
Labels: status: needs information, topic: rewrite, type: bug
