### ISSUE TITLE
parametrized parameters with spaces are not executable individually

### ISSUE THREAD

**Issue by fontealpina** [pytest-dev/pytest#1936] opened 2016-09-15 09:42 UTC
If the parameters of the parametrize are spaces, then the generated tests are not executable individually.
For instance, i just modify the example of the doc, by inserting a space in the `test_input` values:
```python
@pytest.mark.parametrize("test_input,expected", [
    ("3 5", 8),
    ("2 4", 6),
    ("6 9", 42),
])
def test_eval(test_input, expected):
    assert eval(test_input.replace(' ', '+')) == expected

```
Execution:
```
pytest test.py
test.py::test_eval[3 5-8] PASSED
test.py::test_eval[2 4-6] PASSED
test.py::test_eval[6 9-42] FAILED
```
Note that the test ids contain spaces, so if I need to run just one test:
```
pytest test.py::test_eval[3 5-8]
``` 
I get an error cause the test id is interpreted as two tests `test.py::test_eval[3` and `5-8]` that of course are not valid.
How can I solve this? 
I guess a solution could be replace the space with a special character like `\s` into the test nodeid.
Is there a way to modify the `item.nodeid` of a test?
Thanks

**Comment by RonnyPfannschmidt** [comment] 2016-09-15 10:25
please quote the argument, as far as i can tell you pass 2 arguments to pytest due to shell splitting rules

**Comment by The-Compiler** [comment] 2016-09-15 13:25
Works fine here when quoting the argument properly FWIW.

**Comment by RonnyPfannschmidt** [comment] 2016-09-15 13:34
closing as user error then

**Closed by RonnyPfannschmidt** 2016-09-15 13:34 UTC

**Comment by fontealpina** [comment] 2016-09-22 10:56
thanks

**Comment by AlanCoding** [comment] 2020-01-27 20:09
Could you clarify specifically how it is expected to do quotes here?

```
pytest "test.py::test_eval[3 5-8]"
pytest test.py::"test_eval[3 5-8]"
pytest test.py::test_eval["3 5-8"]
pytest test.py::test_eval"[3 5-8]"
```

**Comment by RonnyPfannschmidt** [comment] 2020-01-27 20:14
@AlanCoding the rules of your shell apply, based on rough memory, all of those should be valid in common unix shell, your particular shell should be considered for the rules

**Comment by xliiv** [comment] 2022-04-08 11:46
I can't make it run even with quotes.

The issue is regeg here

```python
            else:
                match = re.match(r"(:?\w|:|\+|-|\.|\[|\]|\\|/)+", input[pos:])
                if match:
```

https://github.com/pytest-dev/pytest/blob/55debfad1f690d11da3b33022d55c49060460e44/src/_pytest/mark/expression.py#L91

When i put it into regex test, it breaks on space, see

![image](https://user-images.githubusercontent.com/298994/162428882-0424868c-6560-4c7a-b73b-e261a7e05671.png)


from https://regex101.com/r/TVYSwg/1

Perhaps making it as below would help

```diff
-match = re.match(r"(:?\w|:|\+|-|\.|\[|\]|\\|/)+", input[pos:])
+match = re.match(r"(:?\w|:|\+|-|\.|\[|\]|\\|/| \w)+", input[pos:])
```

**Comment by hwmq** [comment] 2023-01-31 14:36
I investigated exactly this issue yesterday and found the expression.py identifier regex and came to the same conclusion as @xliiv

Due to there is no other mechanism than this expression to specify individual tests to run, and the expression parser does not accept spaces in identifiers, it is not possible to run an individual test with a parameter that includes spaces.

To get around this, we encode our parameter spaces to non-spaces to pass the test and its parameter to pytest via the `-k` argument, then we decode it back to spaces within the test. Very dissatisfying. Somewhat absurd limitation.

**Comment by spbnick** [comment] 2023-02-08 14:17
Yep, same problem here. When executing this command:
```console
pytest --log-level=DEBUG --tb=native -vv -k 'test_upgrade[mux:sqlite:/tmp/kcidb_cloud.OpkLumCrBr/clean.sqlite3 postgresql:dbname=kcidb_01_clean_test bigquery:kcidb-test2.kcidb_01_clean_test]'
```

I get this error:
```
ERROR: Wrong expression passed to '-k': test_upgrade[mux:sqlite:/tmp/kcidb_cloud.OpkLumCrBr/clean.sqlite3 postgresql:dbname=kcidb_01_clean_test bigquery:kcidb-test2.kcidb_01_clean_test]: at column 67: expected end of input; got identifier
```

Will be replacing spaces with something else to work it around, but would be good to have a solution.

**Comment by spbnick** [comment] 2023-02-08 14:22
Ah, so it's not only spaces, but equals '=' as well. I'm not willing to go into pytest code to figure out which magic incantations are accepted and which are not. If we have this limitation, it would be good to have it documented. Will have to find another way.

**Comment by hwmq** [comment] 2023-02-08 14:24
@spbnick  The regex for "identifier" is documented internally as `(\w|:|\+|-|\.|\[|\]|\\|/)+` , so no whitespaces is allowed, only `\w` (the "Unicode word character class", basically alphanumeric and underscore), and `: + - . [ ] \ /`

**Comment by spbnick** [comment] 2023-02-08 14:27
Thank you, @hwmq, that clears it up. I would say that pytest should refuse to execute tests with "invalid" identifiers, so this problem is curtailed at the start. Although by now it's probably too late, and a ton of projects rely on this behavior, even though they can't actually select those tests.

**Comment by hwmq** [comment] 2023-02-08 14:44
We could potentially improve the situation by determining some additional characters that are safe for "identifier" in the custom expression parser, like in 31c207a0b5171c8a28149189818075f3d4a883c9 and 25c65616f4455ac78be1027c2fb4debef827c4e6. This parser was introduced in a718ad636304ab594eb95c8c64ac28a96354757d to replace passing expressions to Python `eval`. It seems like this change was not fully documented, for instance the help output still says "An expression is a python evaluatable expression". I do not fully understand what capabilities were lost and gained by making this switch. Maybe we can add an additional mechanism to specify individual tests+parameters that does not use this parser, since it clearly lacks some capabilities.

**Comment by RonnyPfannschmidt** [comment] 2023-02-08 14:47
I'm reluctant to add too much magic to it

@bluetech can we use quoted strings for the purpose?

**Comment by spbnick** [comment] 2023-02-08 14:49
Some documented mechanism for quoting, would definitely be welcome from my side.

**Comment by bluetech** [comment] 2023-02-09 12:18
@hwmq

> Due to there is no other mechanism than this expression to specify individual tests to run [...]

I understand what you mean, but it's not accurate as stated of course, because you can specify a directory/file/nodeid directly without using `-k`.

> [...] and the expression parser does not accept spaces in identifiers, it is not possible to run an individual test with a parameter that includes spaces.

So making identifiers allow spaces directly as suggested by @xliiv isn't going to work, because spaces are used for separating the tokens in the expression.

Using `\` is not possible since we allow it verbatim in identifiers since 25c65616f4455ac78be1027c2fb4debef827c4e6.

> It seems like this change was not fully documented, for instance the help output still says "An expression is a python evaluatable expression".

This sentence is a good approximation I feel, do you have any suggestions to improve? We probably can't describe the entire expression language in the help sentence, but it can probably be more informative without making it longer.

> I do not fully understand what capabilities were lost and gained by making this switch

Lost - not much I think.

Gained - ability to extend the language with things that are not valid in Python, like special characters in identifiers, and whatever else we come up with. Also, no eval...

> Maybe we can add an additional mechanism to specify individual tests+parameters that does not use this parser, since it clearly lacks some capabilities.

Adding *another* mechanism would have to clear a very high bar, but if you have ideas I would love to hear them at least. Keep in mind the main use case though: people typing a selector on the command line as quickly and effortlessly as possible, with the 90% case probably being a single word.

@spbnick

> Ah, so it's not only spaces, but equals '=' as well

Since we're no longer using Python eval, allowing `=` in identifiers is possible. It would mean we will not ever be able to use `=` for other purposes in the expression language. Feel free to propose this (and for other special symbols as well), then we can consider it properly.

@RonnyPfannschmidt 

> @bluetech can we use quoted strings for the purpose?

This can work I think, we currently have `"` and `'` reserved.

One downside is that quoted strings are not very ergonomic on the command line -- you need to double-quote e.g. `pytest -k '"my ident with spaces"'`. I also remember Windows cmd having some weird issues with quotes...

Also, using `"` and/or `'` in the language means can't allow them in identifiers, but that's probably fine.

---

BTW, if we ever formalize the structure of nodeids (the `dir/test_foo.py::TestClass::test_it[param1,param2]` string thingies) properly, then we can embed this definition in the expression language, and then say for example that spaces are allowed inside the `[ ... ]` part etc. But that will require some work.

**Comment by hwmq** [comment] 2023-02-09 14:28
If the parser supports arbitrary strings using quotes, and escape character within quotes, I think it resolves my issue.
