### ISSUE TITLE
filterwarnings error::UserWarning causes stack trace that removes the info saying where Always True assertions can be found

### ISSUE THREAD

**Issue by bdfariello** [pytest-dev/pytest#11686] opened 2023-12-07 14:30 UTC
# Environment information
Python version: 3.10.x
Pytest version: 6.2.4

# Issue and sample test
I've noticed we have some test cases being created where "always true" assertions are being written, and people are ignoring these Python warnings.

```
class TestBadAssertions:
    def test_always_true(self):
        assert (False, "oops")
```

# Warning message shows where to fix the problem

```
===================================================================================================== warnings summary =====================================================================================================
.../test_foo.py:512
  .../test_foo.py:512: PytestAssertRewriteWarning: assertion is always true, perhaps remove parentheses?
    assert (False, "oops")
```

# Pytest.ini code to convert it to an error
I tried adding this to my pytest.ini file to force these to become Errors (allowing GitHub PRs to have a gate that would require them to be fixed before merging)

```
filterwarnings =
    error::UserWarning
```

# Error message strips the actual code and the line number
This works to cause a failure, but now I lose the information that the Warning provided, showing me that the bad assertion happened at line 512 (in example above)

```
___________________________________________________________________________________________ ERROR collecting private/test_foo.py ___________________________________________________________________________________________
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:161: in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:355: in _rewrite_test
    rewrite_asserts(tree, source, fn_, config)
venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:418: in rewrite_asserts
    AssertionRewriter(module_path, config, source).run(mod)
venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:741: in run
    new.extend(self.visit(child))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ast.py:410: in visit
    return visitor(node)
venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:852: in visit_Assert
    warnings.warn_explicit(
E   pytest.PytestAssertRewriteWarning: assertion is always true, perhaps remove parentheses?
================================================================================================= short test summary info ==================================================================================================
ERROR .../test_foo.py - pytest.PytestAssertRewriteWarning: assertion is always true, perhaps remove parentheses?
```

# Impact
This makes it so that I can force a failure, but doesn't give the user any information about where to fix it, other than somewhere inside `the `test_foo.py` file

**Comment by The-Compiler** [comment] 2023-12-14 11:21
Duplicate of #4687

**Closed by The-Compiler** 2023-12-14 11:21 UTC
