### ISSUE TITLE
Hang while collecting; no troubleshooting available?

### ISSUE THREAD

**Issue by garthk** [pytest-dev/pytest#6054] opened 2019-10-24 22:45 UTC
G'day! `pytest --doctest-modules` is hanging while `collecting ...` and I can't figure out why. I'm pretty sure it's not #1217 / #2188 because I'm not using `unittest.mock.call`. I'm trying to crank up all the verbosity, but there's no log output after the pre-collection `pytestdebug` output.

```
$ rm -rf .pytest_cache && rm -f pytestdebug.log && PYTEST_DEBUG=true python -m pytest --doctest-modules --log-level=DEBUG --debug --setup-show --collect-only -vv
  pytest_plugin_registered [hook]
      plugin: <_pytest.config.Config object at 0x7f0b283ec110>
      manager: <_pytest.config.PytestPluginManager object at 0x7f0b2911b590>
…
    pytest_cmdline_preparse [hook]
        config: <_pytest.config.Config object at 0x7f0b283ec110>
        args: ['--doctest-modules', '--log-level=DEBUG', '--debug', '--setup-show', '--collect-only', '-vv']
    finish pytest_cmdline_preparse --> [] [hook]
writing pytestdebug information to /workspace/pytestdebug.log
===== test session starts =====
platform linux -- Python 3.7.4, pytest-3.10.1, py-1.8.0, pluggy-0.13.0 -- /opt/conda/bin/python
using: pytest-3.10.1 pylib-1.8.0
setuptools registered plugins:
  pytest-sanic-1.1.2 at /opt/app/app-py3.7/lib/python3.7/site-packages/pytest_sanic/plugin.py
cachedir: .pytest_cache
rootdir: /workspace, inifile:
plugins: sanic-1.1.2
collecting ... 
```

If there's a flag I missed, please let me know and I'll close the issue with all due haste.

If there's no way to figure out why `collecting` is hanging, please take this as a bug or feature issue to add a means to figure this out.

If you suspect it's `pytest-sanic`, that strikes me as totally reasonable... and I still need to get the evidence to prove it, so please advise as above.

**Comment by blueyed** [comment] 2019-10-25 00:14
> pytest-3.10.1

Try the latest release, please.

Otherwise `strace` might help, e.g. `strace -f pytest …` to see where it hangs/loops/stalls.

**Comment by RonnyPfannschmidt** [comment] 2019-10-25 05:09
i believe the [faulthandler support](http://doc.pytest.org/en/latest/usage.html#fault-handler) should be enables via `pytest -o faulthandler_timeout=10` could help as well [

**Comment by asottile** [comment] 2019-10-28 02:15
`--full-trace` + `^C` might also be helpful

**Comment by manoadamro** [comment] 2019-11-07 18:30
I also get this from time to time. Im using github so deleting my local repo and recloning usually fixes it for me. never figured out the problem but I always assumed it was somehting in the chached files that I gitignore

**Comment by blueyed** [comment] 2019-11-07 19:49
Needs more info.

@garthk 
> writing pytestdebug information to /workspace/pytestdebug.log

Have you checked that file?

**Comment by Zac-HD** [comment] 2019-11-20 11:34
Closing this because we don't have an example that reproduces the problem on a supported version of Pytest.

**Closed by Zac-HD** 2019-11-20 11:34 UTC
Labels: status: needs information, topic: collection, type: question

**Comment by xloem** [comment] 2022-06-12 12:20
This problem happens if there is a test_*.py or *_test.py script in the dirtree which does not quickly complete when run.

Example:
```
$ echo 'import time; time.sleep(3600)' > long_delay_quick_test.py; pytest
```

**Comment by asottile** [comment] 2022-06-12 13:37
@xloem yeah that's not a pytest problem that's a you problem

**Comment by xloem** [comment] 2022-06-12 13:56
;P

it would be good if --verbose enumerated the files imported while collecting tests, or threw an error if one timed out. this would change a scenario that needs strace to debug into one that is clear.

but it's not complicated for somebody to submit a PR adding that when they stumble onto this issue googling it in 3 more years.

**Comment by asottile** [comment] 2022-06-12 14:00
scroll up! there are suggestions and options to do what you want

**Comment by xloem** [comment] 2022-06-12 14:05
still hangs
`$ echo 'import time; time.sleep(3600)' > long_delay_quick_test.py; pytest -o faulthandler_timeout=10`

I ended up finding it with strace, as in the first suggestion, although it takes a lot of grepping to find the open calls that identify the hanging module.

**Comment by asottile** [comment] 2022-06-12 14:10
yeah `faulthandler_timeout` isn't for discovery it's for an individual test hanging
