### ISSUE TITLE
pytest 6.0.0 INTERNALERROR with python version 3.8.2

### ISSUE THREAD

**Issue by jitendrs** [pytest-dev/pytest#7570] opened 2020-07-29 11:35 UTC
pytest==6.0.0
python=3.8.2
OS:- centos/Mac/redhat

I am having error while running pytest cases with **@pytest.mark.skip** decorator for my test class.
It's seems this issue appears only for pytest version 6.0.0. I am able to run same test case with pytest version 5.4.3

example code:-
   ```
 @pytest.mark.skip
    def test_get_test_authz_resources(self, apiobj):

        return_value = apiobj.get_client_authz_resources()
        assert return_value != None

```
Error log:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 240, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 296, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 321, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 100, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 111, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 211, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pytest_html/plugin.py", line 602, in pytest_runtest_logreport
INTERNALERROR>     self.append_skipped(report)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pytest_html/plugin.py", line 380, in append_skipped
INTERNALERROR>     self._appendrow("Skipped", report)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pytest_html/plugin.py", line 340, in _appendrow
INTERNALERROR>     result = self.TestResult(outcome, report, self.logfile, self.config)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pytest_html/plugin.py", line 157, in __init__
INTERNALERROR>     self.append_log_html(report, self.additional_html)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pytest_html/plugin.py", line 266, in append_log_html
INTERNALERROR>     for line in report.longreprtext.splitlines():
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/reports.py", line 105, in longreprtext
INTERNALERROR>     self.toterminal(tw)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/reports.py", line 85, in toterminal
INTERNALERROR>     out.line(longrepr)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/_io/terminalwriter.py", line 168, in line
INTERNALERROR>     self.write(s, **markup)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/_io/terminalwriter.py", line 144, in write
INTERNALERROR>     current_line = msg.rsplit("\n", 1)[-1]
INTERNALERROR> AttributeError: 'tuple' object has no attribute 'rsplit'

```
pip list from my machine:-

Package                                           Version   
------------------------------------------------- ----------
boto                                              2.49.0    
boto3                                             1.12.23   
botocore                                          1.15.23   
bs4                                               0.0.1     
decorator                                         4.4.2     
docutils                                          0.15.2    
ecdsa                                             0.15      
entrypoints                                       0.3       
flake8                                            3.7.9     
Flask                                             1.1.1     
grpcio                                            1.27.2    
helpdev                                           0.6.10    
httplib2                                          0.17.1    
idna                                              2.8       
imagesize                                         1.2.0     
importlib-metadata                                1.6.0     
iniconfig                                         1.0.0     
intervaltree                                      3.0.2     
ipaddress                                         1.0.23    
ipykernel                                         5.2.0     
ipython                                           7.13.0    
ipython-genutils                                  0.2.0     
ipywidgets                                        7.5.1     
isort                                             4.3.21    
itsdangerous                                      1.1.0     
jedi                                              0.15.2    
Jinja2                                            2.10.1    
jmespath                                          0.9.5     
json5                                             0.9.4     
jsonschema                                        3.2.0     
jupyter                                           1.0.0     
jupyter-client                                    6.1.2     
jupyter-console                                   6.1.0     
jupyter-core                                      4.6.3     
jupyterlab                                        2.1.1     
jupyterlab-server                                 1.1.1     
keycloak-client-api-packages                      1.0.0     
keyring                                           21.2.0    
kiwisolver                                        1.1.0     
kube-shell                                        0.0.23    
kubernetes                                        2.0.0     
lazy-object-proxy                                 1.4.3     
Markdown                                          3.2.2     
MarkupSafe                                        1.1.1     
matplotlib                                        3.1.2     
mccabe                                            0.6.1     
mistune                                           0.8.4     
more-itertools                                    8.3.0     
nbconvert                                         5.6.1     
nbformat                                          5.0.5     
notebook                                          6.0.3     
numpy                                             1.17.4    
numpydoc                                          0.9.2     
oauth2client                                      4.1.3     
packaging                                         20.3      
pandas                                            0.25.3    
pandocfilters                                     1.4.2     
parso                                             0.5.2     
pathtools                                         0.1.2     
pep517                                            0.8.2     
pep8                                              1.7.1     
pexpect                                           4.8.0     
pickleshare                                       0.7.5     
pip                                               19.2.3    
pluggy                                            0.13.1    
prometheus-client                                 0.7.1     
prompt-toolkit                                    3.0.5     
protobuf                                          3.11.3    
pycodestyle                                       2.5.0     
pycparser                                         2.20      
pydocstyle                                        5.0.2     
pyflakes                                          2.1.1     
Pygments                                          2.6.1     
PyJWT                                             1.7.1     
pylint                                            2.4.4     
pystache                                          0.5.4     
**pytest                                            6.0.0     
pytest-html                                       2.1.1     
pytest-metadata                                   1.10.0**    
requests                                          2.22.0    
rinoh-typeface-dejavuserif                        0.1.1     
rinoh-typeface-texgyrecursor                      0.1.1     
rinoh-typeface-texgyreheros                       0.1.1     
rinoh-typeface-texgyrepagella                     0.1.1     
rinohtype                                         0.4.1     
scipy                                             1.4.1     
setuptools                                        41.2.0    
six                                               1.12.0    
Sphinx                                            2.4.4     
sphinx-rtd-theme                                  0.5.0     
sphinxcontrib-applehelp                           1.0.2     
sphinxcontrib-confluencebuilder                   1.2.0     
sphinxcontrib-devhelp                             1.0.2     
sphinxcontrib-htmlhelp                            1.0.3     
sphinxcontrib-jsmath                              1.0.1     
sphinxcontrib-qthelp                              1.0.3     
sphinxcontrib-serializinghtml                     1.1.4     
typing                                            3.7.4.1   
ujson                                             1.35      
urllib3                                           1.25.8    
wheel                                             0.33.6

**Comment by bluetech** [comment] 2020-07-29 11:37
This is a duplicate of #7559. Should be fixed in 6.0.1 (not released yet).

**Closed by bluetech** 2020-07-29 11:37 UTC
