### ISSUE TITLE
pytest error INTERNALERROR> AttributeError: can't set attribute`

### ISSUE THREAD

**Issue by ke-liang** [pytest-dev/pytest#6970] opened 2020-03-26 03:25 UTC
OS：macOS Catalina Version 10.15.3
Python：3.8.2

I upgrade  pytest from 5.3.2 to 5.4.1(5.4.0 has the same issue)
and then
run pytest

`INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/main.py", line 187, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/config/__init__.py", line 820, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytest_sugar.py", line 176, in pytest_configure
INTERNALERROR>     sugar_reporter = SugarTerminalReporter(standard_reporter)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytest_sugar.py", line 214, in __init__
INTERNALERROR>     self.writer = self._tw
INTERNALERROR> AttributeError: can't set attribute`

So could you please help check this issue?

pip3 list
aiohttp              3.6.2
apipkg               1.5
astroid              2.3.3
async-timeout        3.0.1
asyncio              3.4.3
attrs                19.3.0
beautifulsoup4       4.8.2
bs4                  0.0.1
certifi              2019.11.28
chardet              3.0.4
execnet              1.7.1
gevent               1.4.0
greenlet             0.4.15
idna                 2.9
importlib-metadata   1.5.2
isort                4.3.21
jsonschema           3.2.0
lazy-object-proxy    1.4.3
logger               1.4
mccabe               0.6.1
more-itertools       8.2.0
multidict            4.7.5
packaging            20.3
parameterized        0.7.1
Pillow               7.0.0
pip                  20.0.2
pluggy               0.13.1
py                   1.8.1
pycryptodome         3.9.7
pylint               2.4.4
PyMySQL              0.9.3
pyparsing            2.4.6
pyrsistent           0.16.0
pytest               5.3.5
pytest-asyncio       0.10.0
pytest-forked        1.1.3
pytest-html          2.1.1
pytest-instafail     0.4.1.post0
pytest-metadata      1.8.0
pytest-rerunfailures 9.0
pytest-sugar         0.9.2
pytest-xdist         1.31.0
requests             2.23.0
selenium             3.141.0
setuptools           46.1.3
six                  1.14.0
soupsieve            2.0
SQLAlchemy           1.3.15
tblib                1.6.0
termcolor            1.1.0
urllib3              1.25.8
wcwidth              0.1.9
wrapt                1.12.1
xmltodict            0.12.0
yarl                 1.4.2
zipp                 3.1.0

Now I use pytest 5.3.5, it look good!

**Comment by bluetech** [comment] 2020-03-26 05:22
This is a duplicate of issue #6951, please see the discussion there.

**Closed by bluetech** 2020-03-26 05:22 UTC
