### ISSUE TITLE
Pytest failing silently before or during collection

### ISSUE THREAD

**Issue by y2kbugger** [pytest-dev/pytest#5836] opened 2019-09-10 19:04 UTC
pytest is failing for some projects during or before collection.

Notice that is never makes it to collection.

Works normally when running with the xdist option --looponfail
Fails whether or not xdist is installed
```
zdk@pc ~/devel/MyProject (master)
$ pytest
============================= test session starts =============================
platform win32 -- Python 3.6.9, pytest-5.1.2, py-1.8.0, pluggy-0.12.0
PyQt5 5.9.2 -- Qt runtime 5.9.7 -- Qt compiled 5.9.6
rootdir: C:\Users\zdkohler\devel\MyProject, inifile: pytest.ini, testpaths: tests
plugins: cov-2.7.1, forked-1.0.2, qt-3.2.2, xdist-1.29.0
(base)
zdk@pc ~/devel/MyProject (master)
$
```

Running pytest with --debug

```
$ tail -5 pytestdebug.log
      early skip of rewriting module: urllib2 [assertion]
      early skip of rewriting module: libcooper.http.reports [assertion]
      early skip of rewriting module: libcooper.loghandler [assertion]
      early skip of rewriting module: logging.handlers [assertion]
      early skip of rewriting module: jinja2.ext [assertion]
```

- output of `pip list` from the virtual environment you are using
```
Package                       Version   Location                                           
----------------------------- --------- ---------------------------------------------------
-umpy                         1.16.4    
advbumpversion                1.2.0     
alabaster                     0.7.12    
apipkg                        1.5       
appdirs                       1.4.3     
argh                          0.26.2    
arrow                         0.13.1    
asn1crypto                    0.24.0    
astroid                       2.2.5     
atomicwrites                  1.3.0     
attrs                         19.1.0    
autopep8                      1.4.4     
Babel                         2.7.0     
backcall                      0.1.0     
backports.functools-lru-cache 1.5       
backports.tempfile            1.0       
backports.weakref             1.0.post1 
bcrypt                        3.1.6     
beautifulsoup4                4.8.0     
binaryornot                   0.4.4     
bleach                        3.1.0     
bokeh                         1.3.4     
cached-property               1.5.1     
calmap                        0.0.7     
certifi                       2019.6.16 
cffi                          1.12.3    
chardet                       3.0.4     
Click                         7.0       
cloudpickle                   1.2.1     
colorama                      0.4.1     
comtypes                      1.1.7     
conda                         4.7.11    
conda-build                   3.18.9    
conda-package-handling        1.3.11    
conda-verify                  3.4.2     
constructor                   3.0.0     
cookiecutter                  1.6.0     
coverage                      4.5.3     
cryptography                  2.7       
cycler                        0.10.0    
cytoolz                       0.10.0    
dask                          2.3.0     
decorator                     4.4.0     
defusedxml                    0.6.0     
docutils                      0.15.2    
dogpile.cache                 0.7.1     
entrypoints                   0.3       
et-xmlfile                    1.0.1     
ete3                          3.1.1     
execnet                       1.6.1     
fastcache                     1.1.0     
filelock                      3.0.12    
Flask                         1.1.1     
Flask-WTF                     0.14.2    
future                        0.17.1    
glob2                         0.7       
greenlet                      0.4.15    
idna                          2.8       
imageio                       2.5.0     
imagesize                     1.1.0     
importlib-metadata            0.19      
ipykernel                     5.1.2     
ipython                       7.7.0     
ipython-genutils              0.2.0     
isodate                       0.6.0     
isort                         4.3.21    
itsdangerous                  1.1.0     
jdcal                         1.4.1     
jedi                          0.15.1    
Jinja2                        2.10.1    
jinja2-time                   0.2.0     
joblib                        0.13.2    
json5                         0.8.5     
jsonschema                    3.0.2     
jupyter-client                5.3.1     
jupyter-core                  4.5.0     
jupyterlab                    1.0.2     
jupyterlab-server             1.0.0     
keyboard                      0.13.3    
kiwisolver                    1.1.0     
lazy-object-proxy             1.4.1     
libarchive-c                  2.8       
lxml                          3.7.2     
MarkupSafe                    1.1.1     
matplotlib                    3.1.1     
mccabe                        0.6.1     
menuinst                      1.4.16    
mistune                       0.8.4     
mkl-fft                       1.0.14    
mkl-random                    1.0.2     
mkl-service                   2.0.2     
more-itertools                7.2.0     
mpmath                        1.1.0     
msgpack                       0.6.1     
nbconvert                     5.5.0     
nbformat                      4.4.0     
neovim                        0.3.1     
networkx                      2.3       
notebook                      6.0.0     
ntlm-auth                     1.4.0     
numpy                         1.16.4    
olefile                       0.46      
onnx                          1.5.0     
onnxconverter-common          1.5.3     
openpyxl                      2.6.2     
packaging                     19.1      
pandas                        0.25.0    
pandocfilters                 1.4.2     
paramiko                      2.4.2     
parso                         0.5.1     
pathtools                     0.1.2     
pickleshare                   0.7.5     
Pillow                        6.1.0     
pip                           19.2.2    
pkginfo                       1.5.0.1   
pluggy                        0.12.0    
plumbum                       1.6.7     
poyo                          0.5.0     
prometheus-client             0.7.1     
prompt-toolkit                2.0.9     
protobuf                      3.9.1     
psutil                        5.6.3     
py                            1.8.0     
pyasn1                        0.4.6     
pycodestyle                   2.5.0     
pycosat                       0.6.3     
pycparser                     2.19      
Pygments                      2.4.2     
pylint                        2.3.1     
PyNaCl                        1.3.0     
pynvim                        0.3.2     
pyodbc                        4.0.27    
pyOpenSSL                     19.0.0    
pyparsing                     2.4.2     
pyqtgraph                     0.10.0    
pyrsistent                    0.14.11   
PySocks                       1.7.0     
pytest                        5.1.2     
pytest-cov                    2.7.1     
pytest-forked                 1.0.2     
pytest-qt                     3.2.2     
pytest-xdist                  1.29.0    
python-dateutil               2.8.0     
pythonnet                     2.4.0     
pytz                          2019.2    
PyWavelets                    1.0.3     
pywin32                       223       
pywinpty                      0.5.5     
PyYAML                        5.1.2     
pyzmq                         17.0.0    
requests                      2.22.0    
requests-ntlm                 1.1.0     
requests-toolbelt             0.9.1     
rope                          0.14.0    
ruamel-yaml                   0.15.46   
scikit-image                  0.15.0    
scikit-learn                  0.21.2    
scipy                         1.3.1     
Send2Trash                    1.5.0     
setuptools                    41.0.1    
sip                           4.19.13   
six                           1.12.0    
skl2onnx                      1.5.0     
snakeviz                      2.0.1     
snowballstemmer               1.9.0     
soupsieve                     1.9.2     
Sphinx                        2.1.2     
sphinxcontrib-applehelp       1.0.1     
sphinxcontrib-devhelp         1.0.1     
sphinxcontrib-htmlhelp        1.0.2     
sphinxcontrib-jsmath          1.0.1     
sphinxcontrib-qthelp          1.0.2     
sphinxcontrib-serializinghtml 1.1.3     
SQLAlchemy                    1.3.7     
sympy                         1.4       
terminado                     0.8.2     
testpath                      0.4.2     
toolz                         0.10.0    
tornado                       6.0.3     
tqdm                          4.32.1    
traitlets                     4.3.2     
typed-ast                     1.3.4     
typing                        3.7.4     
typing-extensions             3.7.4     
urllib3                       1.24.2    
watchdog                      0.9.0     
wcwidth                       0.1.7     
webencodings                  0.5.1     
Werkzeug                      0.15.5    
wfastcgi                      3.0.0     
wheel                         0.33.4    
whichcraft                    0.6.0     
win-inet-pton                 1.1.0     
wincertstore                  0.2       
wrapt                         1.11.2    
WTForms                       2.2.1     
xlrd                          1.2.0     
XlsxWriter                    1.1.8     
xlwings                       0.15.8    
zeep                          3.4.0     
zipp                          0.5.2     
```
pytest and operating system versions
Windows 10, Python 3.6, pytest 5.1.2
```
$ pytest --version
pytest will always run as Dev environment/db
This is pytest version 5.1.2, imported from C:\ProgramData\Anaconda3\lib\site-packages\pytest.py
setuptools registered plugins:
  pytest-cov-2.7.1 at C:\ProgramData\Anaconda3\lib\site-packages\pytest_cov\plugin.py
  pytest-forked-1.0.2 at C:\ProgramData\Anaconda3\lib\site-packages\pytest_forked\__init__.py
  pytest-qt-3.2.2 at C:\ProgramData\Anaconda3\lib\site-packages\pytestqt\plugin.py
  pytest-xdist-1.29.0 at C:\ProgramData\Anaconda3\lib\site-packages\xdist\plugin.py
  pytest-xdist-1.29.0 at C:\ProgramData\Anaconda3\lib\site-packages\xdist\looponfail.py
```

**Comment by y2kbugger** [comment] 2019-09-13 17:12
It is a medium sized suite of proprietary code. I have not determine if it is specific test modules causing this. I will work on narrowing down the tests and conftest.py
Other projects's test suites run fine in the same environment so that narrows it down to tests and configuration. Maybe I did something too tricky with sqlalchemy sessions and fixtures, but it has been stable for 2 years.

**Comment by y2kbugger** [comment] 2019-09-13 17:16
The biggest hint I have is that `--looponfail` from xdist masks the problem.

**Comment by y2kbugger** [comment] 2019-09-13 17:42
Ok, so I have narrowed it down to a one-line file:

test_flask_imports.py:
```
 import myproject.http
```

This test is for catching missing dependencies during CI, all it does is import a sub-package that contains the initialization for flask app.

```
from werkzeug.contrib.cache import SimpleCache
from libcustomebusiness.http.core import create_flask_app

from .. import session

MAXSHOWCOUNT = 100
cache = SimpleCache()
# create app from blueprint registered with templates and application url prefix
# also sets up log handlers in a standard way
app = create_flask_app(__name__)
# don't reorder any of this, yes it is cyclic, it is best practice
# import all of you views after creating the app
from . import views, admin, api, home, morepages, history

@app.teardown_appcontext
def shutdown_session(exception=None):
    session.remove()
```

When I run it with `--looponfail`, tests all run correctly and I do get some deprecation warnings.
```
myproject\http\__init__.py:1
  c:\users\zdkohler\devel\myproject\myproject\http\__init__.py:1: DeprecationWarning: 'werkzeug.contrib.cache' is deprecated as of version 0.15 and will be removed in version 1.0. It has moved to https://github.com/pallets/cachelib.
    from werkzeug.contrib.cache import SimpleCache

c:\users\zdkohler\devel\libcustomebusiness\libcustomebusiness\http\__init__.py:2
  c:\users\zdkohler\devel\libcustomebusiness\libcustomebusiness\http\__init__.py:2: DeprecationWarning: 'werkzeug.contrib.profiler' has moved to'werkzeug.middleware.profiler'. This import is deprecated as ofversion 0.15 and will be removed in version 1.0.
    from werkzeug.contrib.profiler import ProfilerMiddleware

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\xml\functions.py:31
  C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\xml\functions.py:31: DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release.
    from defusedxml.lxml import fromstring as _fromstring, tostring

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```


I also tried just adding a fake test to test_flask_imports.py, no change.

Another think to note is that is pauses for a about 9 seconds before return the console. Similar or slightly slower than normal collection. But not as long as running tests.

**Comment by y2kbugger** [comment] 2019-09-13 18:25
Noticed this issue:
#5532 

It states a fix was included in flask 1.0.4, I'm running 1.1.1, but I thought I would mention it here in case they are related.

**Comment by nicoddemus** [comment] 2019-09-13 23:38
@y2kbugger I get we can close this now then?

**Comment by y2kbugger** [comment] 2019-09-14 01:56
@nicoddemus No, the issue is still unknown and there is not a fix. 

To clarify, #5532 is only similar in that they involve pytest>5 and flask, but the trigger and symptoms are different. I thought maybe they could be related, but the fix in flask for #5532 does not fix my issue.

**Comment by asottile** [comment] 2019-09-15 22:15
what is the exit code of the process? is it possible that there's a crash (segfault-like, but I don't know the proper terminology on windows)? given your output it looks like you're on windows and using maybe msys2? -- if you try in cmd.exe instead it might give us a hint since windows error reporting should take over there)

**Comment by y2kbugger** [comment] 2019-09-15 23:26
I'll definitely try it in cmd, I am using msys2.

If I recall it was like 127 (I guess that means it was coded as -1)

**Comment by y2kbugger** [comment] 2019-09-16 15:47
In cmd it makes it very slightly further, printing out this last line:

```
collecting 63 items / 1 errors / 62 selected
```
`collecting 63 items` appears quickly, then ` / 1 errors / 62 selected` is printed after a 9 second pause.

**Comment by asottile** [comment] 2019-09-16 15:53
if you comment put half of the modules would that help pinpoint?

**Comment by y2kbugger** [comment] 2019-09-16 15:57
I go into more detail above, it was pinpointed to importing a flask application that is based on flask blueprint.

**Comment by y2kbugger** [comment] 2019-09-16 16:09
Here is the minimum amount of test code that demonstrates the failure. I'm still working on creating the minimum reproducible flask app that causes this issue.

Start from scratch:
```
~/devel $ mkdir TestApp
~/devel $ cd  TestApp
~/devel/TestApp $ echo import myapp.http > test.py
```
0 Tests run, but no crash on `import sys`
```
~/devel/TestApp $ echo import sys > test.py && pytest test.py
============================= test session starts =============================
platform win32 -- Python 3.6.9, pytest-5.1.2, py-1.8.0, pluggy-0.12.0
PyQt5 5.9.2 -- Qt runtime 5.9.7 -- Qt compiled 5.9.6
rootdir: C:\Users\myuser\devel\TestApp
plugins: cov-2.7.1, forked-1.0.2, qt-3.2.2, xdist-1.29.0
collected 0 items

============================ no tests ran in 0.03s ============================
~/devel/TestApp $
```
Crash occurs when importing flask app:
```
~/devel/TestApp $ ~/devel/TestApp $ echo import myapp.http > test.py && pytest test.py
============================= test session starts =============================
platform win32 -- Python 3.6.9, pytest-5.1.2, py-1.8.0, pluggy-0.12.0
PyQt5 5.9.2 -- Qt runtime 5.9.7 -- Qt compiled 5.9.6
rootdir: C:\Users\myuser\devel\TestApp
plugins: cov-2.7.1, forked-1.0.2, qt-3.2.2, xdist-1.29.0
~/devel/TestApp $
```

**Comment by asottile** [comment] 2019-09-16 16:29
right, I mean to comment out half of my app.http and bisect the imported modules until you have a minimal case

**Comment by Zac-HD** [comment] 2019-10-24 04:43
Closing this issue as there's nothing useful to do without a reproducing test case.

**Closed by Zac-HD** 2019-10-24 04:43 UTC
Labels: status: needs information

**Comment by simsong** [comment] 2021-02-22 22:55
I was dealing with a very similar problem. It turns out that I had an `os.execl()` in my code that was causing the problem. I had to set up `pytest` to set an environment variable and have my code not `exec` if it was running under pytest.
