### ISSUE TITLE
scandir dependency - can it be optional?

### ISSUE THREAD

**Issue by p0las** [pytest-dev/pytest#3790] opened 2018-08-08 01:01 UTC
We are trying to update pytest from 3.5.0  to the latest 3.7.1. The new version seems to require scandir package that in turn needs to be compiled. For our cross platform environment this is a big change as we will have to maintain multiple compiled versions of it. 
Is there a way to make this package optional and skip it during pip install? I'm happy to sacrifice speed for the flexibility in this case.
thank you.

**Comment by asottile** [comment] 2018-08-08 01:45
duplicate of #3750 -- we're looking into ways to make this better 🙏

**Closed by asottile** 2018-08-08 01:45 UTC
