### ISSUE TITLE
Testing an `__init__.py` file tests the entire package 

### ISSUE THREAD

**Issue by spagh-eddie** [pytest-dev/pytest#9263] opened 2021-11-03 01:38 UTC
I found a difference between 6.1.2 and 6.2.0. I would have expected the behavior of only testing `package/__init__.py`, but in 6.2.0 it tests the entire `package`. 

I think it might be due to #8016 but I am not familiar with the internals of this library. 

```console
% tree                     
.
└── package
    ├── __init__.py
    └── dont_test_me.py

% cat package/__init__.py 
"""
>>> round(22/7, 2) == 3.14
True
"""

% cat package/dont_test_me.py 
"""
>>> 2 + 2 == 5
True
"""
```
```console
% pip install pytest==6.1.2  
% pytest -q --tb=no --doctest-modules package/__init__.py
.                                                                                  [100%]
1 passed in 0.02s

% pip install pytest==6.2.0  
% pytest -q --tb=no --doctest-modules package/__init__.py
.F                                                                                 [100%]
================================ short test summary info =================================
FAILED package/dont_test_me.py::package.dont_test_me
1 failed, 1 passed in 0.02s
```

**Comment by bluetech** [comment] 2021-11-03 22:52
I will try to make some time to look at this, but in the meantime it would be helpful for narrowing down the issue if you can check whether this is specific to doctests, or happens in general (with regular test functions).

**Comment by spagh-eddie** [comment] 2021-11-04 05:49
> I will try to make some time to look at this, but in the meantime it would be helpful for narrowing down the issue if you can check whether this is specific to doctests, or happens in general (with regular test functions).

OK, note I changed the name to `test_me_not.py` to be found by test discovery. The previous name of `dont_test_me.py` was not getting picked up. 

They seem to be consistent, but I'm not sure if expected. That is for you, not me. 
```console
% tree                     
.
└── package
    ├── __init__.py
    └── test_dont_test_me.py

% cat package/__init__.py  # empty
% cat package/test_me_not.py 
def test_bad():
	assert 2 + 2 == 5
```
```console
% pip install pytest==6.1.2 
% pytest -q --tb=no package/__init__.py                 
F                                                                               [100%]
=============================== short test summary info ===============================
FAILED package/test_me_not.py::test_bad - assert (2 + 2) == 5
1 failed in 0.01s

% pip install pytest==6.2.0  
% pytest -q --tb=no package/__init__.py                 
F                                                                               [100%]
=============================== short test summary info ===============================
FAILED package/test_me_not.py::test_bad - assert (2 + 2) == 5
1 failed in 0.01s

```

**Comment by The-Compiler** [comment] 2021-11-26 15:14
Is this a duplicate of #8976?

**Comment by spagh-eddie** [comment] 2021-11-26 20:31
> Is this a duplicate of #8976?

Thank you for finding this. It doesn't seem to be exactly the same issue. The MRE in #8976 runs one file, but when adding `--doctest-modules` like in this PR it runs both. 

```console
% tree
.
└── foo_tests
    ├── __init__.py
    ├── test_a.py
    └── test_b.py
```
```console 
% pytest foo_tests/__init__.py
======================== test session starts =========================
platform darwin -- Python 3.9.0, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /Users/Eddie/test
collected 2 items

foo_tests/test_a.py ..                                         [100%]

========================= 2 passed in 0.01s ==========================
```
```console
% pytest --doctest-modules foo_tests/__init__.py
======================== test session starts =========================
platform darwin -- Python 3.9.0, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /Users/Eddie/test
collected 4 items

foo_tests/test_a.py ..                                         [ 50%]
foo_tests/test_b.py ..                                         [100%]

========================= 4 passed in 0.03s ==========================
```

**Comment by mdengler** [comment] 2023-01-31 20:27
Still exists in `7.2.0`:

```
$ tree ./package
./package
├── dont_test_me.py
└── __init__.py

1 directory, 2 files

$ cat package/__init__.py 
"""
>>> round(22/7, 2) == 3.14
True
"""

$ cat package/dont_test_me.py 
"""
>>> 2 + 2 == 5
True
"""

$ poetry run pytest --version
pytest 7.2.0

$ poetry run pytest -q --tb=no --doctest-modules package/__init__.py
.F                                                                                                                                                                                                                                     [100%]
========================================================================================================== short test summary info ===========================================================================================================
FAILED package/dont_test_me.py::package.dont_test_me
1 failed, 1 passed in 0.01s
```

**Closed** 2023-06-23 18:09 UTC
Labels: topic: collection, type: regression
