### ISSUE TITLE
Running individual test files doesn't work without conftest.py

### ISSUE THREAD

**Issue by devonestes** [pytest-dev/pytest#5785] opened 2019-08-26 08:24 UTC
When I try and run an individual test without a `conftest.py` file in the root directory of my project, it appears that it's not loading modules correctly. Here's a screenshot of what I'm doing.

![pytest_bug](https://user-images.githubusercontent.com/8422484/63676577-88ed3600-c7eb-11e9-9984-e705cb28f3da.png)

The imports at the top of that test are:
```python
import pytest
import datetime
import uuid
import kids.database as database
```

I would expect that pytest would have the same functionality without a `conftest.py` file as it would with an empty `conftest.py` file, but that appears not to be the case.

**Comment by The-Compiler** [comment] 2019-08-26 08:45
Duplicate of #2269

**Closed by The-Compiler** 2019-08-26 08:45 UTC

**Comment by pfctdayelise** [comment] 2019-08-26 08:47
Hmm, I think you have run into #2269 and interpreted it as a feature. :)

I would guess that running `python -m pytest tests/database/test_database.py` also works with no conftest.py?

Basically, you need a way for your tests to know where to find the `kids` code to be able to install it. Running `python -m pytest` is one way to do that, because you're in the `kids` directory. The empty conftest.py is having the same effect.

It looks like you don't have the 'kids' package installed in your virtualenv. Perhaps it is not even a package. The [good practices](https://docs.pytest.org/en/latest/goodpractices.html) are to use a virtualenv, make your code a package and install it "editable" in your virtualenv. If that's not feasible, I'd stick with the empty conftest.py or using `python -m pytest`.

**Comment by The-Compiler** [comment] 2019-08-26 08:48
Note that the ModuleNotFoundError is probably the correct behavior here: The current directory isn't necessarily in `sys.path` (where Python looks for modules) - it only happens to work because pytest adds it to load the `conftest.py` file.

IMHO, the proper solution is using a virtualenv where you have a development install of your project, and/or [tox](https://tox.readthedocs.io/en/latest/).

**Comment by pfctdayelise** [comment] 2019-08-26 08:53
Would be another good documentation page, "ModuleNotFoundError: the definitive guide to how pytest can find and import your code"

**Comment by devonestes** [comment] 2019-08-26 09:28
If you want this to throw an error, shouldn't it also throw an error when `conftest.py` is found?

That's what's so confusing to me here. How does an _empty file_ explain a change in behavior? There's no configuration I'm doing there, so I don't see why any behavior would change.

**Comment by The-Compiler** [comment] 2019-08-26 11:04
> If you want this to throw an error, shouldn't it also throw an error when `conftest.py` is found?

It should, which is why #2269 is open :wink:
