### ISSUE TITLE
--pyargs cannot locate namespace packages installed in editable mode

### ISSUE THREAD

**Issue by taschini** [pytest-dev/pytest#1567] opened 2016-05-25 07:43 UTC
The ``--pyargs`` command-line switch cannot locate libraries within a namespace package that are installed in editable mode.

How to reproduce
-----------------------

1. In a fresh virtual environment install the [attached pinned requirements](https://github.com/pytest-dev/pytest/files/281234/pinned_requirements.txt):

   ```
   $ virtualenv env
   $ source env/bin/activate
   $ pip install -r pinned_requirements.txt
   ```

   This will install three libraries ([more.basicauth](https://github.com/morepath/more.basicauth), [more.chameleon](https://github.com/morepath/more.chameleon), [more.forwarded](https://github.com/morepath/more.forwarded)) in editable mode, together with their dependencies.

   These libraries are all defined within the ``more`` namespace package.

2. Run

    ```console
    $ py.test --pyargs more.chamaleon
    ```

This is the output I get:

```console
$ py.test --pyargs more.chamaleon
==================================================================== test session starts =====================================================================
platform darwin -- Python 2.7.11, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir:[…]/pytest_bug, inifile: 
plugins: cov-2.2.1

================================================================ no tests ran in 0.00 seconds ================================================================
ERROR: file or package not found: more.chamaleon
```

Expected output
---------------------

I expect that py.test invocation to produce similar output as
```console
$ py.test env/src/more.chameleon/more
==================================================================== test session starts =====================================================================
platform darwin -- Python 2.7.11, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: […]/pytest_bug/env/src/more.chameleon, inifile: 
plugins: cov-2.2.1
collected 5 items 

env/src/more.chameleon/more/chameleon/tests/test_chameleon.py .....

================================================================== 5 passed in 0.51 seconds ==================================================================
```

**Comment by RonnyPfannschmidt** [comment] 2016-05-25 07:47
i think might be duplicate of #478

do you agree?

**Comment by taschini** [comment] 2016-05-25 07:48
I just realized that this is very likely related to #478.

**Comment by RonnyPfannschmidt** [comment] 2016-05-25 07:48
also note, that this is a bug in setuptools namespaces vs setup.py develop

**Comment by taschini** [comment] 2016-05-25 08:13
I cannot judge whether the difference in behavior between setup tools and ``setup.py develop`` is a bug. Do you happen to have a link to the related issue on the tracker of setuptools?

**Comment by RonnyPfannschmidt** [comment] 2016-05-25 08:18
pypa/pip#3
pypa/setuptools#250

**Comment by taschini** [comment] 2016-05-25 08:37
Thank you, quite an interesting read.  Would you mind if I give a look at ``_tryconvertpyarg`` to see if there is a way to work around these issues?

**Comment by taschini** [comment] 2016-05-25 09:13
> also note, that this is a bug in setuptools namespaces vs setup.py develop 

Actually, the ``--pyargs`` command-line switch cannot locate libraries within a namespace package that have been installed with ``setup.py develop`` either:


```bash
# Create fresh environment:
virtualenv --no-site-packages env
source env/bin/activate

# Get the sources:
mkdir src
git clone https://github.com/morepath/more.chameleon src/more.chameleon
git clone https://github.com/morepath/more.basicauth src/more.basicauth
git clone https://github.com/morepath/more.forwarded src/more.forwarded

# Install the libraries in "develop" mode:
for k in src/*; do (cd $k; python setup.py develop); done

# Install the test requirements:
pip install pytest WebTest pytest-cov

# verify that the libraries are installed
python -c 'import more.chameleon, more.basicauth, more.forwarded'

# Try to run py.test
py.test --pyargs more.chameleon
```

That still fails with 
```
==================================================================== test session starts =====================================================================
platform darwin -- Python 2.7.2, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: […]/pytest_bug2, inifile: 
plugins: cov-2.2.1

================================================================ no tests ran in 0.00 seconds ================================================================
ERROR: file or package not found: more.chameleon
```

**Comment by RonnyPfannschmidt** [comment] 2016-05-25 09:27
i think the problem is finding namespace package path properly - py.test currently does not support that kind of discovery

it needs active support and logic i think

**Comment by taschini** [comment] 2016-06-20 15:52
As far as I'm concerned, #1597 solves this issue, which I think it can now be closed.

**Comment by nicoddemus** [comment] 2016-06-20 21:27
Oh yeah, thanks!

**Closed by nicoddemus** 2016-06-20 21:27 UTC

**Comment by RonnyPfannschmidt** [comment] 2022-12-08 10:03
Pytest is unaware of pep420, nobody fixed that so far

**Comment by dimpase** [comment] 2022-12-08 11:57
> Pytest is unaware of pep420, nobody fixed that so far

If this was documented, it would have saved us unnecessary banging of heads on keyboard.

**Comment by nicoddemus** [comment] 2022-12-08 12:22
@dimpase indeed we should have this documented somewhere, to avoid users wasting time on this.

Perhaps we can improve the error message:

```
ERROR: module or package not found: sage.misc
Possible reasons:
- Missing an __init__.py file
- Namespace package (not supported)
- Not reachable via PYTHONPATH
See <link to docs> for more information.
```

**Comment by dimpase** [comment] 2022-12-08 12:56
should there be an issue on making pytest PEP 420-aware?

**Comment by nicoddemus** [comment] 2022-12-08 13:14
Created https://github.com/pytest-dev/pytest/issues/10569.
