### ISSUE TITLE
Ignore tests not working when invoking Pytest 5.1.1 within Python

### ISSUE THREAD

**Issue by nijian84** [pytest-dev/pytest#5797] opened 2019-08-28 17:41 UTC
Issue:

I wrote my test infrastructure around invoking Pytest from within Python after some setup. I am 
invoking Pytest via Python with the following line:

pytest.main(["-vs", "tests", "--ignore=tests/dir1/"])

But since the update to 5.1.1, seems like this --ignore=dir is being ignored, and it is running all my tests despite some expected to be skipped.

Here my pip list:

ansi2html                1.5.2
appdirs                  1.4.3
astroid                  2.2.5
atomicwrites             1.3.0
attrs                    19.1.0
beautifulsoup4           4.8.0
black                    19.3b0
cachetools               3.1.1
certifi                  2019.6.16
chardet                  3.0.4
Click                    7.0
colorama                 0.4.1
google-api-python-client 1.7.11
google-auth              1.6.3
google-auth-httplib2     0.0.3
google-auth-oauthlib     0.4.0
httplib2                 0.13.1
idna                     2.8
importlib-metadata       0.19
isort                    4.3.21
lazy-object-proxy        1.4.1
mccabe                   0.6.1
more-itertools           7.2.0
oauth2client             4.1.3
oauthlib                 3.1.0
packaging                19.1
paho-mqtt                1.4.0
pip                      19.1.1
pluggy                   0.12.0
py                       1.8.0
pyasn1                   0.4.6
pyasn1-modules           0.2.6
pylint                   2.3.1
pyparsing                2.4.2
pytest                   5.1.1
pytest-metadata          1.8.0
pytest-ordering          0.6
python-dotenv            0.10.3
requests                 2.22.0
requests-oauthlib        1.2.0
rsa                      4.0
setuptools               41.0.1
six                      1.12.0
soupsieve                1.9.2
toml                     0.10.0
typed-ast                1.4.0
uritemplate              3.0.0
urllib3                  1.25.3
wcwidth                  0.1.7
websockets               8.0.2
wheel                    0.33.4
wrapt                    1.11.2
zipp                     0.6.0

OS: Windows 10, Python 3.7.3 32-bit

**Comment by blueyed** [comment] 2019-08-28 20:16
> Confirmed downgrading to 5.0.1 makes --ignore=dir work again, just FYI.

Please consider git-bisecting it then.

**Comment by nijian84** [comment] 2019-08-29 13:00
hello nicoddemus:

I was able to reproduce this in a minimum way. 

`.
│   run.py
│
└───tests
    ├───stuff1
    │       test_1.py
    │
    └───stuff2
            test_2.py`

And this is in run.py:

`import pytest

a = 1

if a == 1:
    pytest.main(["-vs", "tests", "--ignore=tests/stuff1"])
else:
    pytest.main(["-vs", "tests", "--ignore=tests/stuff2"])`

And the output:

`platform win32 -- Python 3.7.3, pytest-5.1.1, py-1.8.0, pluggy-0.12.0 -- 
collected 2 items                                                                                                                                                                                                                

tests/stuff1/test_1.py::test_something1 PASSED
tests/stuff2/test_2.py::test_something2 PASSED`

So I have an IF function around two possible invocations of Pytest, and regardless of which I use, it invokes all the tests. 

Even when I removed the IF function around it, it runs them all.

`import pytest

pytest.main(["-vs", "tests", "--ignore=tests/stuff1"])`

`====================== test session starts ===============================
platform win32 -- Python 3.7.3, pytest-5.1.1, py-1.8.0, pluggy-0.12.0 -- 
collected 2 items                                                                                                                                                                                                                

tests/stuff1/test_1.py::test_something1 PASSED
tests/stuff2/test_2.py::test_something2 PASSED`

**Comment by nijian84** [comment] 2019-08-29 13:06
Downgraded to 5.0.1, and ran the exact same test script:

`================================ test session starts =====================
platform win32 -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0 -- 
collected 1 item                                                                                                                                                                                                                 

tests/stuff2/test_2.py::test_something2 PASSED`

**Comment by nicoddemus** [comment] 2019-08-29 13:25
Sorry, still cannot reproduce it... 😕 

```
λ python run.py
======================== test session starts ========================
platform win32 -- Python 3.7.4, pytest-5.1.1, py-1.8.0, pluggy-0.12.0 -- 
collected 1 item
tests\stuff2\test_2.py::test PASSED

========================= 1 passed in 0.02s =========================
```

But I did not try on Linux (I'm on Windows). What's the output of your `pip list`?

**Comment by nijian84** [comment] 2019-08-29 13:48
Here's my PIP List:

```
Package            Version
------------------ -------
atomicwrites       1.3.0
attrs              19.1.0
colorama           0.4.1
importlib-metadata 0.19
more-itertools     7.2.0
packaging          19.1
pip                19.2.3
pluggy             0.12.0
py                 1.8.0
pyparsing          2.4.2
pytest             5.1.1
setuptools         41.2.0
six                1.12.0
wcwidth            0.1.7
wheel              0.33.6
zipp               0.6.0
```
I'll try reversing the slashes and see if it changes anything.

```
import pytest

pytest.main(["-vs", "tests", "--ignore=tests\stuff1"])
```
and..

```
===================================== test session starts =====================================
platform win32 -- Python 3.7.3, pytest-5.1.1, py-1.8.0, pluggy-0.12.0 -- 
collected 2 items                                                                                                                                                                                                                

tests/stuff1/test_1.py::test_something1 PASSED
tests/stuff2/test_2.py::test_something2 PASSED
```

Maybe it's just because I'm a dirty Windows user this is happening. As a side note, I've always used the linux slashes within Python on Windows and it always worked.

**Comment by nijian84** [comment] 2019-08-29 13:54
I am also using Visual Studio Code, with pipenv in order to isolate environments:

![image](https://user-images.githubusercontent.com/46694646/63946331-f0e98980-ca42-11e9-8a91-19d037ce2d9c.png)

**Comment by nicoddemus** [comment] 2019-08-29 15:35
> Maybe it's just because I'm a dirty Windows user this is happening.

What's a "dirty Windows user"? 😁 

Looking at the dependencies, nothing jumps to me. Can you provide a repo with step by step instructions on how to reproduce this? Bonus points if you can reproduce somewhere neutral, as AppVeyor.

**Comment by nijian84** [comment] 2019-08-29 17:25
Alas, I cannot provide the repo, as it is internally hosted, and contains a fair bit of stuff that needs to be kept internal. 

I will however, try and make some time to re-try this on a new clean system, and see if I can reproduce this.

**Comment by nicoddemus** [comment] 2019-08-29 18:00
Thanks

**Comment by blueyed** [comment] 2019-09-02 13:53
Can you git-bisect it?
Then we should get a clue what the issue is.

**Comment by nijian84** [comment] 2019-09-03 17:59
Here's my git bisect with the minimal infra structure I was able to reproduce it on.

`PS Z:\python-tests> python run.py
====================================================================================================== test session starts ======================================================================================================
platform win32 -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0 -- C:\Users\don.blais\.virtualenvs\python-tests-awHal9fW\Scripts\python.exe
cachedir: .pytest_cache
rootdir: Z:\python-tests
collected 1 item                                                                                                                                                                                                                 

tests/stuff2/test_2.py::test_something2 PASSED

=================================================================================================== 1 passed in 0.09 seconds ====================================================================================================
PS Z:\python-tests> git bisect good
You need to start by "git bisect start"
Do you want me to do it for you [Y/n]? y
PS Z:\python-tests> git bisect good
PS Z:\python-tests> pipenv install --skip-lock pytest==5.1.1
Installing pytest==5.1.1…
[==  ] Installing...
Installation Succeeded

PS Z:\python-tests> python run.py
====================================================================================================== test session starts ======================================================================================================
platform win32 -- Python 3.7.3, pytest-5.1.1, py-1.8.0, pluggy-0.12.0 -- C:\Users\don.blais\.virtualenvs\python-tests-awHal9fW\Scripts\python.exe
cachedir: .pytest_cache
rootdir: \\cifs.cognitivesystems.com\storage\don.blais\python-tests
collected 2 items                                                                                                                                                                                                                

tests/stuff1/test_1.py::test_something1 PASSED
tests/stuff2/test_2.py::test_something2 PASSED

======================================================================================================= 2 passed in 0.22s =======================================================================================================
PS Z:\python-tests> git bisect bad

07c44e41fb6706d37eec49f92f83a0c8aec89659 is the first bad commit
commit 07c44e41fb6706d37eec49f92f83a0c8aec89659
Author: Don Blais
Date:   Tue Sep 3 13:55:00 2019 -0400

    upgraded to pytest 5.1.1

 Pipfile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)`

I literally only changed going from Pytest 5.0.1 to 5.1.1 and then the Ignore stopped working. No actual code changes were required to make this issue start.

**Comment by nicoddemus** [comment] 2019-09-05 10:21
@nijian84, @blueyed meant a `git bisect` on a development version of pytest, not in your code. 😉 

Also, can you provide a clean repository where the problem is reproducible? Otherwise I'm out of ideas on how to help here, as I can't reproduce the issue.

**Comment by nijian84** [comment] 2019-09-05 12:45
yeah, I'm not entirely too sure how to Bi-sect my own installation of Pytest. Sorry, pretty new in general to development stuff.

**Comment by nicoddemus** [comment] 2019-09-05 15:34
Probably better to focus on the reproducible repository first then, I think this is the best way we can help out.

**Comment by aklajnert** [comment] 2019-09-11 06:04
@nijian84 - can you reproduce this issue without the run script? Just directly typing `pytest -vs tests --ignore=tests/stuff2`?

Also, are you able to reproduce this issue with the exact directory structure you mentioned before?
```
└───tests
    ├───stuff1
    │       test_1.py
    │
    └───stuff2
            test_2.py
```
Maybe try to init a new virtual environment, and just install `pytest=5.0.1` via pip, and then install the `5.0.1`:
```
(venv) C:\Windows\Temp\5797>pytest -vs tests --ignore=tests/stuff2
=========================================================================================================== test session starts ============================================================================================================
platform win32 -- Python 3.7.2, pytest-5.0.1, py-1.8.0, pluggy-0.13.0 -- c:\windows\temp\5797\venv\scripts\python.exe
cachedir: .pytest_cache
rootdir: C:\Windows\Temp\5797
collected 1 item

tests/stuff1/test_1.py::test_something1 PASSED

========================================================================================================= 1 passed in 0.11 seconds =========================================================================================================

(venv) C:\Windows\Temp\5797>pip install pytest==5.1.1
Collecting pytest==5.1.1
  Using cached https://files.pythonhosted.org/packages/ef/3b/5652e27e048ae086f79ce9c4ce8a2da6bad1e9590788e5768aafc6f375ef/pytest-5.1.1-py3-none-any.whl
Requirement already satisfied: py>=1.5.0 in c:\windows\temp\5797\venv\lib\site-packages (from pytest==5.1.1) (1.8.0)
Requirement already satisfied: atomicwrites>=1.0 in c:\windows\temp\5797\venv\lib\site-packages (from pytest==5.1.1) (1.3.0)
Requirement already satisfied: more-itertools>=4.0.0 in c:\windows\temp\5797\venv\lib\site-packages (from pytest==5.1.1) (7.2.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in c:\windows\temp\5797\venv\lib\site-packages (from pytest==5.1.1) (0.13.0)
Requirement already satisfied: packaging in c:\windows\temp\5797\venv\lib\site-packages (from pytest==5.1.1) (19.1)
Requirement already satisfied: wcwidth in c:\windows\temp\5797\venv\lib\site-packages (from pytest==5.1.1) (0.1.7)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in c:\windows\temp\5797\venv\lib\site-packages (from pytest==5.1.1) (0.21)
Requirement already satisfied: attrs>=17.4.0 in c:\windows\temp\5797\venv\lib\site-packages (from pytest==5.1.1) (19.1.0)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\windows\temp\5797\venv\lib\site-packages (from pytest==5.1.1) (0.4.1)
Requirement already satisfied: six in c:\windows\temp\5797\venv\lib\site-packages (from packaging->pytest==5.1.1) (1.12.0)
Requirement already satisfied: pyparsing>=2.0.2 in c:\windows\temp\5797\venv\lib\site-packages (from packaging->pytest==5.1.1) (2.4.2)
Requirement already satisfied: zipp>=0.5 in c:\windows\temp\5797\venv\lib\site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest==5.1.1) (0.6.0)
Installing collected packages: pytest
  Found existing installation: pytest 5.0.1
    Uninstalling pytest-5.0.1:
      Successfully uninstalled pytest-5.0.1
Successfully installed pytest-5.1.1
You are using pip version 18.1, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(venv) C:\Windows\Temp\5797>pytest -vs tests --ignore=tests/stuff2
=========================================================================================================== test session starts ============================================================================================================
platform win32 -- Python 3.7.2, pytest-5.1.1, py-1.8.0, pluggy-0.13.0 -- c:\windows\temp\5797\venv\scripts\python.exe
cachedir: .pytest_cache
rootdir: C:\Windows\Temp\5797
collected 1 item

tests/stuff1/test_1.py::test_something1 PASSED
```

**Comment by Zac-HD** [comment] 2019-11-26 03:24
Closing this because we don't have enough information to reproduce it 😞 

Very happy to re-open if we can though!

**Closed by Zac-HD** 2019-11-26 03:24 UTC
Labels: status: needs information
