### ISSUE TITLE
-W not working for warnings emitted from finalizer context

### ISSUE THREAD

**Issue by belm0** [pytest-dev/pytest#8021] opened 2020-11-10 07:40 UTC
I'd like pytest to fail on "coroutine never awaited" RuntimeWarning.  But something about these warnings cause pytest not to behave as expected:  a matching `-W` spec actually causes the warning to be completely ignored.

~I suspect it's because these warnings are issued on shutdown of the interpreter, after the pytest harness has exited.~

```python3
def test_foo():
    async def bar():
        assert False

    bar()
```

```
$ pytest foo.py
====================================== test session starts ======================================
platform darwin -- Python 3.7.7, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
collected 1 item

foo.py .                                                                                  [100%]

======================================= warnings summary ========================================
foo.py::test_foo
foo.py:5: RuntimeWarning: coroutine 'test_foo.<locals>.bar' was never awaited
    bar()

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================= 1 passed, 1 warning in 0.02s ==================================
```

```
$ pytest -Werror foo.py
====================================== test session starts ======================================
platform darwin -- Python 3.7.7, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
collected 1 item

foo.py .                                                                                  [100%]

======================================= 1 passed in 0.04s =======================================
```

**Comment by oremanj** [comment] 2020-11-10 07:45
"coroutine was never awaited", as well as most ResourceWarnings, are raised in finalizer context. That means turning them into errors will just print some stderr, which pytest helpfully suppresses as long as all of your tests pass. If you run with `-s` I bet you'll see it.

I don't know if it's possible to tell if you're in finalizer context, but if so, perhaps pytest could improve this situation by installing a more intelligent warning filter that remembers that warnings occurred in this context and forces the test to fail.

**Comment by belm0** [comment] 2020-11-10 07:57
I see.  Given the lack of options for detecting missing await at lint or test time, it would be great for pytest to improve the warning filter to handle finalizer context.  Otherwise I'm grepping the pytest output...

**Comment by asottile** [comment] 2020-11-11 17:20
duplicate of #5676 -- though I think we didn't quite get far enough to figure out that it's the unraisable context there -- let's follow up there!

**Closed by asottile** 2020-11-11 17:20 UTC
