### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'option' when trying to use  import pytest; pytest.set_trace() from within test

### ISSUE THREAD

**Issue by cjw296** [pytest-dev/pytest#2328] opened 2017-03-23 08:28 UTC
While trying to debug #2327, I inserted `import pytest; pytest.set_trace()` here:

https://github.com/cjw296/sybil/blob/32e7dc509026a2b18ff792e797b7db416c594185/tests/test_functional.py#L54

This resulted in:

```
______________________________________________________________________________________ test_unittest ______________________________________________________________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x1038330b8>

    def test_unittest(capsys):
        main = unittest_main(
            exit=False, module=None,
            argv=['x', 'discover', '-v', join(functional_test_dir, 'unittest')]
        )
        # assert main.result.testsRun == 8
        assert len(main.result.failures) == 1
        assert len(main.result.errors) == 1
    
>       import pytest; pytest.set_trace()

tests/test_functional.py:55: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../virtualenvs/sybil_35/lib/python3.5/site-packages/_pytest/debugging.py:59: in set_trace
    tw = _pytest.config.create_terminal_writer(self._config)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

config = None, args = (), kwargs = {}, tw = <py._io.terminalwriter.TerminalWriter object at 0x103833550>

    def create_terminal_writer(config, *args, **kwargs):
        """Create a TerminalWriter instance configured according to the options
        in the config object. Every code which requires a TerminalWriter object
        and has access to a config object should use this function.
        """
        tw = py.io.TerminalWriter(*args, **kwargs)
>       if config.option.color == 'yes':
E       AttributeError: 'NoneType' object has no attribute 'option'

../../../virtualenvs/sybil_35/lib/python3.5/site-packages/_pytest/config.py:1346: AttributeError
```

This behaviour is the same across Python 2.7 and Python 3.5

**Comment by RonnyPfannschmidt** [comment] 2017-03-23 08:43
i believe this is a duplicate of #1658 

i also believe my pr wrt removing the namespace hook usage should fix it (as i had to add better support for nested sessions) unfortunately i cant give an eta

**Comment by cjw296** [comment] 2017-03-23 08:47
It certainly sounds similar, what's an "inline collect" and how am I likely to have triggered one?

**Comment by RonnyPfannschmidt** [comment] 2017-03-23 08:52
actually, let me check the code again, self._config shouldn't be none in `_pytest/debugging.py`

**Comment by RonnyPfannschmidt** [comment] 2017-03-23 09:08
closing as duplicate of #1658

**Closed by RonnyPfannschmidt** 2017-03-23 09:08 UTC
