### ISSUE TITLE
filterwarnings error not displayed in test summary

### ISSUE THREAD

**Issue by kmantel** [pytest-dev/pytest#7415] opened 2020-06-25 04:28 UTC
pytest correctly fails a test caused by elevating a given warning to an error, but it does not attribute the failed test to the fact that the test threw the warning. This results in misleading/confusing test failure messages.

setup.cfg:

    [tool:pytest]
    filterwarnings =
        error::numpy.VisibleDeprecationWarning

tests/test_numpy.py:

    import numpy as np

    def test_array_equal():
        item = [[0], [0, 0]]
        assert np.array_equal(item, item)

Running `pytest tests/` gives:

    tests/test_numpy.py F                                                                                                              [100%]

    ================================================================ FAILURES ================================================================
    ____________________________________________________________ test_array_equal ____________________________________________________________

        def test_array_equal():
            item = [[0], [0, 0]]
    >       assert np.array_equal(item, item)
    E       assert False
    E        +  where False = <function array_equal at 0x7f578404c320>([[0], [0, 0]], [[0], [0, 0]])
    E        +    where <function array_equal at 0x7f578404c320> = np.array_equal

    tests/test_numpy.py:6: AssertionError
    ======================================================== short test summary info =========================================================
    FAILED tests/test_numpy.py::test_array_equal - assert False
    =========================================================== 1 failed in 0.09s ============================================================

If you trigger the warning directly in the test, it will fail and correctly display the elevated warning as the reason the test failed:

    tests/test_numpy.py F                                                                                                              [100%]

    ================================================================ FAILURES ================================================================
    ____________________________________________________________ test_array_equal ____________________________________________________________

        def test_array_equal():
            item = [[0], [0, 0]]
    >       np.array(item)
    E       numpy.VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray

    tests/test_numpy.py:6: VisibleDeprecationWarning
    ======================================================== short test summary info =========================================================
    FAILED tests/test_numpy.py::test_array_equal - numpy.VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which...
    =========================================================== 1 failed in 0.09s ============================================================

Disabling the warning filter in `setup.cfg` correctly passes the test and displays the warning.

On Ubuntu 18.04, Python 3.7.7, and with pip list

    Package            Version
    ------------------ -------
    attrs              19.3.0
    importlib-metadata 1.6.1
    more-itertools     8.4.0
    numpy              1.19.0
    packaging          20.4
    pip                20.1.1
    pluggy             0.13.1
    py                 1.8.2
    pyparsing          2.4.7
    pytest             5.4.3
    setuptools         41.2.0
    six                1.15.0
    wcwidth            0.2.5
    zipp               3.1.0

**Comment by gdhameeja** [comment] 2020-09-17 07:17
I'd like to work on this.

**Comment by nicoddemus** [comment] 2020-09-18 19:26
Hi @kmantel,

Thanks for the report!

> I'd like to work on this.

Thanks, but I'm not sure that's fixable.

When a filter elevates a warning to an error, merely calling `warnings.warn()` with a warning that matches the filter will not actually issue a warning, but raise a straight up exception. This is not special to pytest, but how the `warnings` module works:

```python
>>> import warnings
>>> warnings.filterwarnings("error")
>>> warnings.warn(UserWarning())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UserWarning
```

Note that's a normal Python exception, not a warning. We get exactly the same traceback by raising the same class:

```python
>>> raise UserWarning()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UserWarning
```

Because this is now a normal exception, I'm not sure how pytest could do anything here in order to improve the message, because there's no way to differentiate between a "normal exception" vs "an exception raised because a warning was elevated to an error". Even some ugly hacks related to inspect the frame would fail, because the warning might be raised at the C level (as your traceback shows).

**Comment by The-Compiler** [comment] 2020-09-21 18:59
Looking at this issue, I think there has been a misunderstanding somewhere (either that, or I'm missing something). I don't understand how @nicoddemus' answer relates to what @kmantel has posted :slightly_smiling_face: 

What seems weird here, and what I think @kmantel meant as well: Why does pytest think the `assert np.array_equal(item, item)` assertion failed (i.e. `np.array_equal(item, item)` is False) when the warning is *not* configured as an error? I can reproduce that:

```
$ python3 -m pytest x.py 
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-5.2.4, py-1.9.0, pluggy-0.13.1
rootdir: /home/florian/proj/pytest, configfile: pyproject.toml
collected 1 item                                                               

x.py F                                                                   [100%]

=================================== FAILURES ===================================
_______________________________ test_array_equal _______________________________

    def test_array_equal():
        item = [[0], [0, 0]]
>       assert np.array_equal(item, item)
E       assert False
E        +  where False = <function array_equal at 0x7f1505fa7ca0>([[0], [0, 0]], [[0], [0, 0]])
E        +    where <function array_equal at 0x7f1505fa7ca0> = np.array_equal

x.py:6: AssertionError
=========================== short test summary info ============================
FAILED x.py::test_array_equal - assert False
============================== 1 failed in 0.15s ===============================
```

yet when I add even just `-Wall` (to show the warning), the test starts to pass!

```
$ python3 -m pytest -Wall x.py 
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-5.2.4, py-1.9.0, pluggy-0.13.1
rootdir: /home/florian/proj/pytest, configfile: pyproject.toml
collected 1 item                                                               

x.py .                                                                   [100%]

=============================== warnings summary ===============================
x.py::test_array_equal
x.py::test_array_equal
  /home/florian/proj/pytest/.venv/lib/python3.8/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
    return array(a, dtype, copy=False, order=order)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 1 passed, 2 warnings in 0.12s =========================
```

**Comment by The-Compiler** [comment] 2020-09-21 19:13
Ah, I have a reproducer outside of pytest now:

```
$ python3 -Werror -c "import numpy as np; item = [[0], [0, 0]]; assert np.array_equal(item, item)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError
```

``` 
$ python3 -c "import numpy as np; item = [[0], [0, 0]]; assert np.array_equal(item, item)"        
.../site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
```

This smells like a bug with how numpy uses the CPython API, it probably doesn't handle errors correctly. I wonder if this is the same as https://github.com/numpy/numpy/issues/11629 - in either case, it's not a pytest issue, so I'm closing this.

**Closed by The-Compiler** 2020-09-21 19:13 UTC
Labels: plugin: warnings, type: bug
