### ISSUE TITLE
AttributeError: 'functools.partial' object has no attribute '__name__'

### ISSUE THREAD

**Issue by Abhilash04** [pytest-dev/pytest#3791] opened 2018-08-08 07:03 UTC
### Basic Info

Platform Linux
Python 3.6.4
pytest-3.7.1
py-1.5.4
pluggy-0.7.1
rootdir: /var/jenkins_home/workspace/{ProjectName}, inifile:
plugins: allure-pytest-2.5.0

### pip list of virtual environment

allure-pytest         2.5.0  
allure-python-commons 2.5.0  
atomicwrites          1.1.5  
attrs                 18.1.0 
et-xmlfile            1.0.1  
jdcal                 1.4    
lml                   0.0.1  
more-itertools        4.3.0  
openpyxl              2.5.5  
pip                   18.0   
pluggy                0.7.1  
py                    1.5.4  
pycmd                 1.2    
pyexcel               0.5.8  
pyexcel-io            0.5.7  
pyexcel-xls           0.5.7  
pyexcel-xlsx          0.5.6  
pytest                3.7.1  
selenium              3.14.0 
setuptools            40.0.0 
six                   1.11.0 
texttable             1.4.0  
urllib3               1.23   
wheel                 0.31.1 
xlrd                  1.1.0  
xlwt                  1.3.0

### requirements.txt contains below packages to install:

pytest
selenium
pycmd
allure-pytest
pyexcel
pyexcel-xls
pyexcel-xlsx

### Bug Details:

collected 4 items
self = <allure_pytest.listener.AllureListener object at 0x7f304d7e4cf8>
fixturedef = 
request = <SubRequest 'method_level_setup' for <TestCaseFunction 'test_verify_login_screen_elements'>>

@pytest.hookimpl(hookwrapper=True)
def pytest_fixture_setup(self, fixturedef, request):
    fixture_name = fixturedef.argname

    container_uuid = self._cache.get(fixturedef)

    if not container_uuid:
        container_uuid = self._cache.set(fixturedef)
        container = TestResultContainer(uuid=container_uuid)
        self.allure_logger.start_group(container_uuid, container)

    self.allure_logger.update_group(container_uuid, start=now())

    before_fixture_uuid = uuid4()
    before_fixture = TestBeforeResult(name=fixture_name, start=now())
    self.allure_logger.start_before_fixture(container_uuid, before_fixture_uuid, before_fixture)

    outcome = yield

    self.allure_logger.stop_before_fixture(before_fixture_uuid,
                                           stop=now(),
                                           status=get_outcome_status(outcome),
                                           statusDetails=get_outcome_status_details(outcome))

    finalizers = getattr(fixturedef, '_finalizers', [])
    for index, finalizer in enumerate(finalizers):
      name = '{fixture}::{finalizer}'.format(fixture=fixturedef.argname, finalizer=finalizer.__name__)

E AttributeError: 'functools.partial' object has no attribute 'name'

**Comment by RonnyPfannschmidt** [comment] 2018-08-08 09:15
duplicate of #3755
upstream bug https://github.com/allure-framework/allure-python/issues/278

**Closed by RonnyPfannschmidt** 2018-08-08 09:15 UTC
