### ISSUE TITLE
some tests just hang outside of tox runs

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2774] opened 2017-09-13 12:34 UTC
as far as i can tell its not possible to correctly test pytest outside of tox since years now
this is starting to impede my testing/re-factoring seriously

common issues happen with terminal/pdb tests

**Comment by RonnyPfannschmidt** [comment] 2018-01-26 10:51
i was typically experiencing hangups when just using my normal testing virtualenv with pexpect availiable, (pexpect using tests would hang, i didnt yet verify against #3116

**Comment by darwinyip** [comment] 2018-09-10 03:47
I just experienced this issue when running tests for https://github.com/vertica/vertica-python on osx.

**Comment by blueyed** [comment] 2019-04-07 22:38
Closing as possible duplicate of #2673 (pexpect related), since this has no additional info, except for the hint to https://github.com/pytest-dev/pytest/pull/3116.

**Closed by blueyed** 2019-04-07 22:38 UTC
Labels: plugin: pytester, status: help wanted, type: infrastructure, type: regression
