### ISSUE TITLE
Pytest 5.4.1 -> 5.4.2 changes

### ISSUE THREAD

**Issue by bertjwregeer** [pytest-dev/pytest#7277] opened 2020-05-28 23:58 UTC
Hey all,

I am a maintainer for Pyramid the web framework and we've got some funky tests doing some funky things... but all was well and I got things running on Pytest 5.4.1, however a change made between 5.4.1 and the now new 5.4.2 has somehow flipped things back to how they were before I switched the project to pytest.

In 5.4.1 I had to make this change to get our tests to pass:

https://github.com/Pylons/pyramid/commit/72eca2f8e82f1af20e433218719d99e7627d5650

Basically it seemed like it was dropping a bunch of information about the module it was actually in, and placing things under the `_pytest` or changing the function to no longer be a a method of a class.

In 5.4.2 that flipped back, and thus I reverted that commit.

However I want to make sure that this doesn't become a game of me reverting a revert to only revert the revert again ;-).

Is there a new test that was introduced that makes sure pytest doesn't regress on this? I couldn't find info in the release notes on what changed to cause this behavior to flip back!

Any help or assuaging of my (probably unfounded) fears of having to play flip the commit would be great!

Thank you all so much!

<3

**Comment by bluetech** [comment] 2020-05-30 11:50
> Is there a new test that was introduced that makes sure pytest doesn't regress on this?

I'm sure we'll be happy to add such a regression test.

It would be helpful if you can provide a reproduction that is independent from the pyramid code. Just glancing at the link you provided, I am not able to quickly figure out what it is testing.

**Comment by bertjwregeer** [comment] 2020-05-30 22:49
What it does is grab the callers module by going up the stack frame, I've put together a simple reproducing example that uses the same code from Pyramid:

https://github.com/theasylum/pytest-issue-7277

```
git clone https://github.com/theasylum/pytest-issue-7277.git
cd pytest-issue-7277
python3 -mvenv .venv
./.venv/bin/pip install -r requirements-good.txt
./.venv/bin/pytest tests
./.venv/bin/pip install -r requirements-bad.txt
./.venv/bin/pytest tests
```

I hope this helps @bluetech

**Comment by RonnyPfannschmidt** [comment] 2020-05-31 07:30
This one is tricky, IMHO pytest should not protect against that kind of regression as it would severely limit the ways in which it can integrate unittest

For future safety, the test should test against a module it owns, not the test framework invoking it

**Comment by bluetech** [comment] 2020-05-31 19:05
Thanks for the reproduction @bertjwregeer.

Intuitively I agree with @RonnyPfannschmidt, I think that for pytest to guarantee particular entries in tests' stack frames is a bit too much.

Is it possible for you to rewrite the tests such that they don't "introspect" the tests themselves, but some other stable code (maybe just some dummy file used for that purpose)?

**Comment by bertjwregeer** [comment] 2020-05-31 19:20
> This one is tricky, IMHO pytest should not protect against that kind of regression as it would severely limit the ways in which it can integrate unittest
> 
> For future safety, the test should test against a module it owns, not the test framework invoking it

It just so happens that going 3 up in the call stack leads to to `unittest` or `_pytest` because that is what the class is derived from.

I may end up rewriting the tests to no longer derive from `unittest.TestCase` and see if I can get more stable results then.

**Comment by Zac-HD** [comment] 2020-06-15 14:03
Closing this because it doesn't seem like something pytest actually wants to test for.

**Closed by Zac-HD** 2020-06-15 14:03 UTC
Labels: type: question, type: regression
