### ISSUE TITLE
Changelog entry not picked up in latest release

### ISSUE THREAD

**Issue by tom-dalton-fanduel** [pytest-dev/pytest#2929] opened 2017-11-15 10:00 UTC
#2836 has been fixed (by #2862), merged and has now been released in 3.2.4 (good times!).

However, the changelog entry https://github.com/pytest-dev/pytest/tree/master/changelog doesn't seem to have been picked up for some reason and so the bugfix isn't mentioned in the final changelog https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst.

Not sure what the solution should be here but at the very least the file in https://github.com/pytest-dev/pytest/tree/master/changelog should probably now be removed.

**Comment by nicoddemus** [comment] 2017-11-15 11:21
Hi @tom-dalton-fanduel, thanks for the heads up! I noticed that yesterday and fixed in #2927, which I will merge shortly.

The problem is that the file is named `2862.bug` and should have been `2862.bugfix`, sorry we didn't realize that during code review.

**Comment by nicoddemus** [comment] 2017-11-15 11:22
Done, thanks again

**Closed by nicoddemus** 2017-11-15 11:22 UTC

**Comment by tom-dalton-fanduel** [comment] 2017-11-15 13:46
I guessed it would be something like that - sorry!

**Comment by nicoddemus** [comment] 2017-11-15 14:10
Not at all, thanks again for the PR!
