### ISSUE TITLE
Testing Distributed Data Parallel with many processes.

### ISSUE THREAD

**Issue by tchaton** [pytest-dev/pytest#7996] opened 2020-11-04 08:58 UTC
Dear people from Pytest,

We are currently investigating testing our Distributed Data Parallel implementation in Pytorch Lightning (possibility with Pytest).

DPP launches one process per gpu and run deep learning training on multi-node multi-gpus.
Here is the line where we launch process using `subprocess.Popen(..)`
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/accelerators/ddp_accelerator.py#L127.

We wondered if Pytest Team would have knowledge about the best way to approach this problem. 

Best regards,
Thomas Chaton
Research Engineer at Pytorch Lightning.

**Comment by The-Compiler** [comment] 2020-11-04 14:11
Duplicate of #7995...

**Closed by The-Compiler** 2020-11-04 14:11 UTC
