### ISSUE TITLE
Fixture inheritance problem

### ISSUE THREAD

**Issue by mjozefcz** [pytest-dev/pytest#2534] opened 2017-06-27 14:01 UTC
I noticed some strange problem with fixtures inheritance - only fixtures from "BaseFirst" class are executed. Fixtures from "BaseSecond" class are not.

Version: pytest==3.1.2

Considering example:

conftest.py:
```
#!/usr/bin/env python
import pytest

@pytest.fixture(scope="class")
def fixture_1(request):
    print('fixture_1')

@pytest.fixture(scope="class")
def fixture_2(request):
    print('fixture_2')

@pytest.fixture(scope="class")
def fixture_3(request):
    print('fixture_3')

```

test.py:
```
#!/usr/bin/env python

import pytest

@pytest.mark.usefixtures(
    "fixture_1",
)
class BaseFirst(object):
    def test_print_fixture_1(self):
        pass

@pytest.mark.usefixtures(
    "fixture_2",
)
class BaseSecond(object):
    def test_print_fixture_2(self):
        pass

@pytest.mark.usefixtures(
    "fixture_3",
)
class TestCase(BaseFirst, BaseSecond):
    def test_print_fixture_3(self):
        pass

```

Result:
```
python -m pytest -svl tests.py::TestCase
================================================ test session starts ================================================
platform linux2 -- Python 2.7.12+, pytest-3.1.2, py-1.4.34, pluggy-0.4.0 -- /usr/bin/python
cachedir: .cache
rootdir: /root/tmp, inifile:
plugins: timeout-1.2.0
collected 3 items 

tests.py::TestCase::test_print_fixture_1 fixture_1
fixture_3
PASSED
tests.py::TestCase::test_print_fixture_2 PASSED
tests.py::TestCase::test_print_fixture_3 PASSED

============================================= 3 passed in 0.01 seconds ==============================================
```

Expected result:
```
python -m pytest -svl tests.py::TestCase
================================================ test session starts ================================================
platform linux2 -- Python 2.7.12+, pytest-3.1.2, py-1.4.34, pluggy-0.4.0 -- /usr/bin/python
cachedir: .cache
rootdir: /root/tmp, inifile:
plugins: timeout-1.2.0
collected 3 items 

tests.py::TestCase::test_print_fixture_1 fixture_1
fixture_2
fixture_3
PASSED
tests.py::TestCase::test_print_fixture_2 PASSED
tests.py::TestCase::test_print_fixture_3 PASSED

============================================= 3 passed in 0.01 seconds ==============================================

```

**Comment by RonnyPfannschmidt** [comment] 2017-06-27 14:18
this is a duplicate of #535 

im working on a fix but it might take until pytest 3.3 to get it

**Closed by RonnyPfannschmidt** 2017-06-27 14:18 UTC
