### ISSUE TITLE
from unittest.mock import call

### ISSUE THREAD

**Issue by dfroger** [pytest-dev/pytest#2769] opened 2017-09-11 13:13 UTC
foo.py:

    from unittest.mock import call

Running:

    pytest foo.py

never finish to collect tests, and consume all CPU and Memory of my computer.

Tested on Debian 8 with 3.1.0 and 3.2.2, Python 3.6.1

**Comment by The-Compiler** [comment] 2017-09-11 13:21
Duplicate of #1217

**Comment by dfroger** [comment] 2017-09-11 13:25
thanks, I did not search enough...

**Closed** 2017-09-11 13:25 UTC
