### ISSUE TITLE
pytest INTERNALERROR when loading a fixture fails when running tests in an executable

### ISSUE THREAD

**Issue by campos-ddc** [pytest-dev/pytest#849] opened 2015-07-16 12:51 UTC
If running tests within an executable (cx_freeze), sometimes this function fails and raises an INTERNALERROR:

```python
class FixtureLookupError(LookupError):

    def formatrepr(self):

        # ... omitted some stuff

        for function in stack:
            fspath, lineno = getfslineno(function)
            lines, _ = inspect.getsourcelines(function)
```

The error happens because source files are not available at this moment.

We override `inspect.getsourcelines` to raise an exception when inside an executable, which makes the traceback look like this:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "<PY>\_pytest\main.py", line 84, in
wrap_session
INTERNALERROR>   File "<PY>\_pytest\main.py", line 122, in _main
INTERNALERROR>   File "<PY>\_pytest\core.py", line 521, in
__call__
INTERNALERROR>   File "<PY>\_pytest\core.py", line 528, in
_docall
INTERNALERROR>   File "<PY>\_pytest\core.py", line 394, in
execute
INTERNALERROR>   File "<remote exec>", line 59, in pytest_runtestloop
INTERNALERROR>   File "<remote exec>", line 72, in run_tests
INTERNALERROR>   File "<PY>\_pytest\core.py", line 521, in
__call__
INTERNALERROR>   File "<PY>\_pytest\core.py", line 528, in
_docall
INTERNALERROR>   File "<PY>\_pytest\core.py", line 393, in
execute
INTERNALERROR>   File "<PY>\_pytest\core.py", line 113, in
wrapped_call
INTERNALERROR>   File "<PY>\_pytest\core.py", line 138, in
get_result
INTERNALERROR>   File "<PY>\_pytest\core.py", line 123, in
__init__
INTERNALERROR>   File "<PY>\_pytest\core.py", line 394, in
execute
INTERNALERROR>   File "<PY>\pytest_timeout.py", line 72, in
pytest_runtest_protocol
INTERNALERROR>   File "<PY>\_pytest\core.py", line 394, in
execute
INTERNALERROR>   File "<PY>\_pytest\runner.py", line 65, in
pytest_runtest_protocol
INTERNALERROR>   File "<PY>\_pytest\runner.py", line 72, in
runtestprotocol
INTERNALERROR>   File "<PY>\_pytest\runner.py", line 121, in
call_and_report
INTERNALERROR>   File "<PY>\_pytest\core.py", line 521, in
__call__
INTERNALERROR>   File "<PY>\_pytest\core.py", line 528, in
_docall
INTERNALERROR>   File "<PY>\_pytest\core.py", line 393, in
execute
INTERNALERROR>   File "<PY>\_pytest\core.py", line 109, in
wrapped_call
INTERNALERROR>   File "<PY>\_pytest\skipping.py", line 157, in
pytest_runtest_makereport
INTERNALERROR>   File "<PY>\_pytest\core.py", line 138, in
get_result
INTERNALERROR>   File "<PY>\_pytest\core.py", line 123, in
__init__
INTERNALERROR>   File "<PY>\_pytest\core.py", line 394, in
execute
INTERNALERROR>   File "<PY>\_pytest\runner.py", line 227, in
pytest_runtest_makereport
INTERNALERROR>   File "<PY>\_pytest\python.py", line 618, in
_repr_failure_py
INTERNALERROR>   File "<PY>\_pytest\main.py", line 392, in
_repr_failure_py
INTERNALERROR>   File "<PY>\_pytest\python.py", line 1540, in
formatrepr
INTERNALERROR>   File "<PY>\lib\inspect.py", line 690, in getsourcelines
INTERNALERROR>   File "<PY>\cx_Freeze\initscripts\ConsoleRedirect.py", line 50, in findsource
INTERNALERROR> IOError: Unable to find source
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "<PY>\_pytest\main.py", line 84, in
wrap_session
INTERNALERROR>   File "<PY>\_pytest\main.py", line 122, in _main
INTERNALERROR>   File "<PY>\_pytest\core.py", line 521, in
__call__
INTERNALERROR>   File "<PY>\_pytest\core.py", line 528, in
_docall
INTERNALERROR>   File "<PY>\_pytest\core.py", line 394, in
execute
INTERNALERROR>   File "<PY>\xdist\dsession.py", line 504, in
pytest_runtestloop
INTERNALERROR>   File "<PY>\xdist\dsession.py", line 522, in
loop_once
INTERNALERROR>   File "<PY>\xdist\dsession.py", line 560, in
slave_slavefinished
INTERNALERROR> AssertionError:
('my_test.py::testSomething', <SlaveController gw1>)
```

**Comment by nicoddemus** [comment] 2015-07-16 23:14
This has been fixed in 2.7.1 already, sorry for not remembering this! :sweat_smile: 

Duplicate of #553.

**Closed by nicoddemus** 2015-07-16 23:14 UTC
Labels: bug
