### ISSUE TITLE
Rewrite assert statements in modules containing fixtures

### ISSUE THREAD

**Issue by anxuae** [pytest-dev/pytest#3454] opened 2018-05-07 16:24 UTC
Hello,

I regularly write tests using BDD syntax, using `pytest` and the plugin [pytest-bdd](https://github.com/pytest-dev/pytest-bdd) at work.
Sometimes, I need to assert on complex data/object. In case of  `AssertionError`, I get generally no introspection information in the output. Here below 2 output examples:

**Test written in pure Python**  => complete introspection information:

```
    def test_disconnection_from_sut_pure_python():
>       assert text1 == text2
E       AssertionError: assert '\nHello worl...Hello world\n' == '\nHello world...nHelo world\n'
E           
E           Hello world
E         + Hello vorld
E         - Hello world
E         ?    -
E         + Helo world
E         - Hello world

test_all.py:17: AssertionError
```

**Test written in BDD using the plugin pytest-bdd** => no introspection information:

```
text1 = 'Hello world\nHello world\nHello world', text2 = 'Hello world\nHello vorld\nHelo world'

    @given('I am connected to SUT')
    def ensure_connection_open(text1, text2):
>       assert text1 == text2
E       AssertionError

steps/simple_steps.py:23: AssertionError
```

After a deep look in the [documentation](https://docs.pytest.org/en/latest/assert.html?highlight=assert#advanced-assertion-introspection) I found the reason (I guess):

> pytest only rewrites test modules directly discovered by its test collection process, so asserts in supporting modules which are not themselves test modules will not be rewritten.

However the plugin  `pytest-bdd` generate tests from a sequence of steps (written in feature files) which are all `fixtures`, in this case, an `AssertionError` in the test step is hard to debug.

**My question is:** there is a way to force rewrite of assert statements also in Python modules that contain fixtures (`conftest.py` and other imported modules)?

**Comment by RonnyPfannschmidt** [comment] 2018-05-07 21:28
https://docs.pytest.org/en/latest/writing_plugins.html?highlight=register_assert#assertion-rewriting has the docs on explicitly requesting it

**Comment by anxuae** [comment] 2018-05-08 08:31
Argh ! My bad, I didn't read all the doc.
Thanks for your quick answer.

**Comment by anxuae** [comment] 2018-05-09 07:47
Hello, 

I have one more question concerning this topic: registering module with `register_assert_rewrite` also concerns the modules dynamically imported using the `imp` and `importlib` libraries?

Thanks

**Comment by nicoddemus** [comment] 2018-05-10 22:47
@anxuae yes, `imp` and `importlib` will trigger the general import hook mechanism, which is ultimately what pytest itself uses for assert rewriting.

I'm closing this but feel free to follow up with further questions!

**Closed by nicoddemus** 2018-05-10 22:47 UTC
Labels: type: question

**Comment by anxuae** [comment] 2018-05-14 19:17
Just for information, I made some tests and also read the doc of `imp` module:

The import hooks are not called when using the `imp.load_module()` function.
I manually called them using the example described in https://www.python.org/dev/peps/pep-0302/#id31

**Comment by tiborsimon** [comment] 2023-01-22 10:26
I had similar experience with `pytest-bdd` that the assertion errors weren't showing any details. **The root cause was that I wanted to be too fancy with the test files structure..**

If you stick to the expected structure without advanced import tricks to be able to have a common step definition library with nicely separated step definitions per given/when/then and per test targets, you will be fine.

However, it is not so easy to figure out what the expected structure is based on the docs, but this tutorial seemed to be working: https://automationpanda.com/2018/10/22/python-testing-101-pytest-bdd/
