### ISSUE TITLE
Expose types used in hooks an core fixtures through pytest

### ISSUE THREAD

**Issue by ReneOschmann** [pytest-dev/pytest#8202] opened 2020-12-29 15:00 UTC
#### What's the problem this feature will solve?

Type hinting with mypy is annoying when using core fixtures or overwriting hooks, because I have to import all necessary types from different modules below `_pytest`. E.g for `pytest_exception_interact` I need to import from three different sub-modules, additionally to pytest:
```Python
import pytest
from _pytest.nodes import Collector, Item
from _pytest.reports import CollectReport, TestReport
from _pytest.runner import CallInfo
from typing import Union

def pytest_exception_interact(
    node: Union[Item, Collector],
    call: CallInfo[Any],
    report: Union[CollectReport, TestReport], 
) -> None:
    #do something useful
```

#### Describe the solution you'd like

All types potentially needed to override hooks or to use core fixtures should be exposed in pytest directly or in a sub-module like pytest.types.

```Python
import pytest
from pytest.types import Callinfo, Collector, CollectReport, Item, TestReport 
from typing import Union

def pytest_exception_interact(
    node: Union[Item, Collector],
    call: CallInfo[Any],
    report: Union[CollectReport, TestReport], 
) -> None:
    #do something useful
```

or

```Python
import pytest
from typing import Union

def pytest_exception_interact(
    node: Union[pytest.Item, pytest.Collector],
    call: pytest.CallInfo[Any],
    report: Union[pytest.CollectReport, pytest.TestReport], 
) -> None:
    #do something useful
```

#### Alternative Solutions

The current way works fine, but it is uglier, and importing from `_pytest` feels just wrong.
A PEP 561 stub solution might work as well

#### Additional context

I personally prefer the solution with a separate types module. This would make the use of mypy more comfortable, especially together with https://github.com/pytest-dev/pytest/issues/8073

**Comment by The-Compiler** [comment] 2020-12-29 15:14
Duplicate of #7469

**Closed by The-Compiler** 2020-12-29 15:14 UTC
