### ISSUE TITLE
Collected tests' `nodeid`s change depending on parser's option values

### ISSUE THREAD

**Issue by mtsokol** [pytest-dev/pytest#11636] opened 2023-11-24 17:53 UTC
Hi!

I recently started working with more advanced `conftest.py` features and I stumbled upon something that looks like an incorrect behavior to me:

❗ Here I share a minimal example to reproduce my issue: https://github.com/mtsokol/pytest-conftest-bug

In a nutshell:
1. I have a pytest option added to a parser `--my-option`
2. I have a custom logic in `pytest_collection_modifyitems` where I traverse collected tests and decide which one should be skipped.
3. When I pass an option value that is an arbitrary string, e.g. `pytest my_module --my-option foobar` the test that is collected has `nodeid` of `'my_module/test_sth.py::test_foo'`
4. But when the option that I pass is an absolute path `pytest my_module --my-option /Users/user/foobar` then the test has `nodeid` of `'test_sth.py::test_foo'`

This breaks my test suite as collected tests can't be properly matched/filtered, because a path for one of the options in `pytest` command changed from relative to absolute.

Would you consider it a bug? Or is it an expected behavior?

I'm using `pytest 7.4.3` and macos 12.7.1.

Thank you for any guidance!

**Comment by RonnyPfannschmidt** [comment] 2023-11-24 18:21
This looks like misguided root dir detection

Is there a pytest.ini or a pyproject.toml

**Comment by mtsokol** [comment] 2023-11-24 18:43
> This looks like misguided root dir detection
> 
> Is there a pytest.ini or a pyproject.toml

There is no `pytest.ini` or `pyproject.toml`. Here's a minimal repo that reproduces my case: https://github.com/mtsokol/pytest-conftest-bug

**Comment by RonnyPfannschmidt** [comment] 2023-11-24 18:48
I reviewed the code in findpaths,this is expected behavior when no python project configuration file is around

Adding a one of them resolves the confusion

else a explicit rootpath has to be passed from the cli

**Comment by mtsokol** [comment] 2023-11-24 18:51
Ah, indeed!

With arbitrary string as an option I get:
```
rootdir: /Users/mateusz/PycharmProjects/pytest-bug
```

And with a path as an option:
```
rootdir: /Users/mateusz/...
configfile: pytest.ini
```

`pytest` basically picked some first `pytest.ini` that it found while traversing paths. Adding an (empty) `pytest.ini` solved my issue.

**Comment by RonnyPfannschmidt** [comment] 2023-11-24 19:07
Thanks for the follow-up, I'm closing this as resolved

**Closed by RonnyPfannschmidt** 2023-11-24 19:07 UTC
Labels: type: question, topic: config

**Comment by mtsokol** [comment] 2023-11-24 19:09
Sure, thank you for your assistance!
