### ISSUE TITLE
Unexpected behaviour catching SyntaxError with pytest.raises

### ISSUE THREAD

**Issue by hotternative** [pytest-dev/pytest#8353] opened 2021-02-18 23:11 UTC
To be honest I am not sure if this is a bug or a feature of `pytest.raises`, but I hope some of you would agree the following behaviour is unexpected.
Running the following minimal code.
```
import pytest
a = 1

def test():
    a = 2
    with pytest.raises(SyntaxError):
        global a   # <-- this still raises a syntax error and not caught by pytest.raises
test()
```
Expected behaviour: `pytest.raises` catches the SyntaxError
Actual behaviour: `pytest.raises` does not catch the SyntaxError

**Comment by RonnyPfannschmidt** [comment] 2021-02-18 23:38
Expected behaviour, the test can never run when python is failing to load the whole file

Nothing pytest can do about that

**Comment by nicoddemus** [comment] 2021-02-19 03:12
Indeed, to add to the answer, there's nothing pytest can do because that code is not even executable.

You can try this yourself:

```python

def x():
    a = 1
    try:
        global a
    except:
        print("some exception")

```

Executing it:

```
  File "foo.py", line 6
    global a
    ^
SyntaxError: name 'a' is assigned to before global declaration
```

IOW, Python cannot load modules with syntex errors on them.

Closing this for now. 👍

**Closed by nicoddemus** 2021-02-19 03:12 UTC
