### ISSUE TITLE
pytest 3.0 on Anaconda

### ISSUE THREAD

**Issue by adler-j** [pytest-dev/pytest#1882] opened 2016-08-29 10:35 UTC
Since pytest 3.0 is officially released, it would be nice if you made it available on anaconda as well!

**Comment by RonnyPfannschmidt** [comment] 2016-08-29 10:39
currentyl we dont maintain a official conda pacakge - from the pov of a python package outhoer, conda is practically a foreign package manager that needs extra packaging effort

we do have a ticket about automating it in #1246
but until we have a proper automation that kills the extra work on top of each release,
its improbable that we will publish an official one

currently the only core dev im aware of using conda is @nicoddemus 

btw, is it fine to close this issue as duplicate of #1246

**Comment by adler-j** [comment] 2016-08-29 10:42
Well since 3.0 contains breaking changes, not upgrading anaconda is a hassle for us since we cannot increment our pytest dependency in our package. Perhaps someone could do a manual upload of 3.0 for now, and then automate it for the minor versions?

**Comment by RonnyPfannschmidt** [comment] 2016-08-29 11:19
as far as i understood its not just uploading, its involving creating and using a conda package specification in some way

as such, at least i will not volunteer unless its a automation
i cant speak for the others tho

**Comment by nicoddemus** [comment] 2016-08-29 12:58
I wasn't even aware that one could contribute to Anaconda's official packages, because AFAIK they're maintained by continuum themselves.

But that reminds me that we can update [conda-forge's pytest though](https://github.com/conda-forge/pytest-feedstock). I will see if I do this tonight.

**Comment by nicoddemus** [comment] 2016-08-29 13:11
Just updated it, took me a minute: https://github.com/conda-forge/pytest-feedstock/pull/3

pytest-3.0.1 should be available in conda-forge in 10 minutes or so.

I'm closing this now because there's nothing that can be done further.

**Closed by nicoddemus** 2016-08-29 13:11 UTC
