### ISSUE TITLE
ImportError ModuleNotFoundError in pytest

### ISSUE THREAD

**Issue by pratapan9** [pytest-dev/pytest#6370] opened 2019-12-26 20:49 UTC
Running python 3.7.3 on mac using pytest

My folder structure/files is 
     src/tests/pn/tests/functional/test_something.py
     src/tests/pn/tests/functional/config.py
     src/tests/pn/lib/util.py

PYTHONPATH is set to ..src/tests/pn which means 'pn' folder is in relative path

In test_something.py I have two import statements

```
from lib.util import *
from tests/functional/config import *
```

I run ```pytest -s tests/functional/test_something.py```

Both paths are relative to 'pn' folder, import of 'lib.util' seems successful..however it fails to import 'tests/functional/config' and gives the error

ImportError while importing test module '..... src/tests/pn/tests/functional/test_something.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/functional/reportgen/test_something.py:23: in <module>
    from tests.functional.config import *
E   ModuleNotFoundError: No module named 'tests.functional'

I am confused how the relative import works for one but fails for the other.. Is it because the source file and import file share the same folder hierarchy 'tests/functional'?

It works when I import with full path like 'from src.tests.pn.tests.functional.config import *

**Comment by nicoddemus** [comment] 2019-12-27 11:10
Hi @pratapan9,

Do you have `__init__.py` files?

**Comment by pratapan9** [comment] 2019-12-27 18:11
Yes, I have empty __init__.py in all folders 'tests' and 'functional'

**Comment by nicoddemus** [comment] 2019-12-27 18:58
I've tried to reproduce the issue, but it's not clear where you are executing the commands from.

What happens if you execute `python tests/functional/test_something.py`? pytest uses the normal Python import mechanism, so I suspect you will see the same traceback if you try to import the module directly.

**Comment by pratapan9** [comment] 2019-12-27 19:31
I am in directory src/tests/pn.  When I run ```python tests/functional/test_something.py``` i dont get any output or error. It doesnt seem to run any tests.  The parent directory of 'src' in 'src/tests/pn/tests/functional' is the repo root folder which should be in the PATH and thats why only after importing whole path seems to work

**Comment by nicoddemus** [comment] 2019-12-27 19:35
What do you get you execute `python -m pytest -s tests/functional/test_something.py`?

**Comment by pratapan9** [comment] 2019-12-27 19:42
same result

**Comment by nicoddemus** [comment] 2019-12-27 20:44
It doesn't give an exception? Hmm I'm surprised then. I will try to reproduce it later and see if I can figure out what's happening.

**Comment by pratapan9** [comment] 2019-12-27 21:22
Thanks.. To clarify with ```python -m pytest -s tests/functional/test_something.py``` I get the exception ModuleNotFoundError... as with just using 'pytest'

**Comment by nicoddemus** [comment] 2019-12-28 15:24
Still unable to reproduce:

```
src
└───tests
    └───pn
        ├───lib
        │       util.py
        │
        └───tests
            └───functional
                │   config.py
                │   test_something.py
```

* cwd: `src/tests/pn`
* `$PYTHONPATH`: `..src/tests/pn`
* command: `pytest tests\functional\test_something.py`

What I get:

```
tests\functional\test_something.py:1: in <module>
    from lib.util import *
E   ModuleNotFoundError: No module named 'lib'
```

My guess is that I'm not reproducing your environment correctly, so please:

* Be *very precise* about all the above variables, otherwise I'm playing a guessing game about the environment instead of trying to find the problem.
* Use correct formatting so there are no misinterpretations.

Correct formatting is very important, for example I'm not sure my `PYTHONPATH` is correct because there's no formatting on the original instructions:

> PYTHONPATH is set to ..src/tests/pn which 

The leading `..` seems weird to me.

**Comment by pratapan9** [comment] 2019-12-30 18:50
Thanks.. Sorry for the lack of clarity. Ive set PYTHONPATH to absolute path of the folder 'src/tests/pn'

**Comment by pratapan9** [comment] 2020-01-03 22:19
@nicoddemus did you get a chance to reproduce, thanks

**Comment by nicoddemus** [comment] 2020-01-09 20:50
Hi @pratapan9,

Sorry for the delay.

Changing `PYTHONPATH` to the absolute path of `src/tests/pn`, my test run succeeds:

```
 λ pytest tests\functional\test_something.py -q
.
1 passed in 0.01s
``` 

Which pytest version are you using?

**Comment by pratapan9** [comment] 2020-01-15 17:44
Sorry for the delayed reply.. I am using 3.7.3.. When I do 'pytest --version' I see

```
pytest --version
This is pytest version 4.0.0, imported from /usr/local/lib/python3.7/site-packages/pytest.py
setuptools registered plugins:
  pytest-testrail-2.3.3 at /usr/local/lib/python3.7/site-packages/pytest_testrail/conftest.py
  pytest-metadata-1.8.0 at /usr/local/lib/python3.7/site-packages/pytest_metadata/plugin.py
  pytest-html-1.20.0 at /usr/local/lib/python3.7/site-packages/pytest_html/plugin.py
```

**Comment by nicoddemus** [comment] 2020-01-15 22:18
Please try to update to the latest version and try agian

**Comment by pratapan9** [comment] 2020-01-17 07:51
Actually I found the cause of the issue! Its not about 'pytest' or 'python -m' in the command line.. 

If you look at the post, my dir hierarchy is ```src/tests/pn/tests/functional```. Here 'src' is the whole project's source directory and there are two directories 'tests' under its sub directory structure. 
In my PYTHONPATH I have absolute path to the ```src/tests/pn``` directory. I think 'src' directory is also in the PYTHONPATH by default ? So when I try to import as ```import tests.functional```, instead of looking for path 'tests.functional' under 'pn', its looking for it under 'src' and since it doesnt exist its throwing the error? 

The issue got resolved when I changed the internal 'tests' directory name to something else like 'ptests'.

**Comment by blueyed** [comment] 2020-01-17 08:28
Thanks for reporting back, closing then.

**Comment by blueyed** [comment] 2020-01-17 08:29
Well, maybe it can be answered/helped with further, also via pytest itself maybe, re-opening.

**Comment by Zac-HD** [comment] 2020-02-06 03:24
Closing this issue because it appears to be a configuration problem with PYTHONPATH rather than a pytest bug, and because it's happening on an old (and unsupported) version of pytest.

**Closed by Zac-HD** 2020-02-06 03:24 UTC
Labels: status: needs information, topic: collection, type: question

**Comment by n3011** [comment] 2021-05-30 09:39
Sometimes when `pytest` is installed outside your development environment, it can cause this issue. So if you are using virtual/conda environment, then deactivate the environment - then uninstall `pytest` from the system; then again activate your environment and run the tests.

**Comment by ToddBradley** [comment] 2021-07-02 01:06
> Sometimes when `pytest` is installed outside your development environment, it can cause this issue. So if you are using virtual/conda environment, then deactivate the environment - then uninstall `pytest` from the system; then again activate your environment and run the tests.

Thank you @n3011  for this comment. I found this page because I was having the same problem, and your advice fixed it.

**Comment by michelgokan** [comment] 2022-02-12 21:08
In my case, I deleted `__init__.py` in the root folder and it resolved an exact same problem.

**Comment by chintherock-git** [comment] 2023-11-18 10:13
Thanks @michelgokan
