### ISSUE TITLE
Failures in nodes.py

### ISSUE THREAD

**Issue by jfinkhaeuser** [pytest-dev/pytest#6520] opened 2020-01-21 10:16 UTC
I'm getting a bunch of failures in nodes.py in this line:
https://github.com/pytest-dev/pytest/blob/6a26ac41255a304eb3eec2da565101caf2112394/src/_pytest/nodes.py#L465

I've tried upgrading to the latest version, but it's still there in 5.3.4 - in master, though, the line is gone. I presume there's a good reason for that.

It would be nice to see a newer release so my builds no longer fail. See jfinkhaeuser/prance#64 for a PR that keeps failing because of this issue.

**Comment by The-Compiler** [comment] 2020-01-21 10:20
Duplicate of #6517 - fixed in #6518, I assume a release will follow as soon someone finds the time to do so.

**Closed by The-Compiler** 2020-01-21 10:20 UTC

**Comment by nicoddemus** [comment] 2020-01-21 10:24
@jfinkhaeuser meanwhile you can pin to `!=5.3.4` to workaround this issue.

**Comment by jfinkhaeuser** [comment] 2020-01-21 10:25
Thanks guys!
