### ISSUE TITLE
AttributeError: 'Function' object has no attribute 'get_marker'

### ISSUE THREAD

**Issue by mbarkhau** [pytest-dev/pytest#4608] opened 2019-01-06 21:07 UTC
```
============= test session starts ===========
platform linux -- Python 3.6.6, pytest-4.0.2, py-1.7.0, pluggy-0.8.0 -- 
plugins: monkeytype-1.0.1, cov-2.6.0
```

Tests work if I pin pytest to this version. Updating to 4.1.0 breaks with this error:

```
platform linux -- Python 3.6.6, pytest-4.1.0, py-1.7.0, pluggy-0.8.0 -- 
plugins: monkeytype-1.0.1, cov-2.6.0

...

self = <pytest_cov.plugin.CovPlugin object at 0x7f13154272b0>, item = <Function test_part_compilation[PP]>

    @compat.hookwrapper
    def pytest_runtest_call(self, item):
>       if (item.get_marker('no_cover')
                or 'no_cover' in getattr(item, 'fixturenames', ())):
E               AttributeError: 'Function' object has no attribute 'get_marker'

/home/mbarkhau/miniconda3/envs/pycalver_py36/lib/python3.6/site-packages/pytest_cov/plugin.py:289: AttributeError
```

I can reproduce the error and provide more information in case it isn't immediately clear what the issue is.

**Comment by blueyed** [comment] 2019-01-06 21:08
Duplicate of https://github.com/pytest-dev/pytest-cov/issues/252.

**Closed by blueyed** 2019-01-06 21:08 UTC

**Comment by mbarkhau** [comment] 2019-01-06 21:09
Hah! Literally the same title. Literally! Sorry about that.

**Comment by blueyed** [comment] 2019-01-06 21:09
At least in another repo.. ;)

**Comment by s2t2** [comment] 2019-03-06 20:58
Hi, I'm running into this issue with pytest version 4.3.0 (Python version 3.7.0). Please advise!

**Comment by s2t2** [comment] 2019-03-06 21:00
Is there a specific version that is considered stable?

**Comment by s2t2** [comment] 2019-03-06 21:11
UPDATE: I was able to bypass the error by reverting to pytest 3.x:

```sh
pip install pytest==3.10.1
```

NOTE: I'm using anaconda.

**Comment by nicoddemus** [comment] 2019-03-06 21:14
@s2t2 that function no longer exists in pytest 4, you can use `.get_closest_marker` instead.

**Comment by s2t2** [comment] 2019-03-06 23:28
Thanks @nicoddemus - I wasn't trying to use that function, nor was I attempting to invoke it, but rather just trying to run a simple test and getting errors.

**Comment by s2t2** [comment] 2019-03-06 23:34
Just a simple invocation of `pytest` using the example function and test provided in the pytest documentation. For some reason I saw the error in question.

**Comment by nicoddemus** [comment] 2019-03-07 01:48
Can you point to the docs you saw? We might have something outdated.

**Comment by blueyed** [comment] 2019-03-07 10:41
@s2t2 
It might also have been some plugin you were using.
Indeed:

> pytest_cov.plugin.CovPlugin

**Comment by blueyed** [comment] 2019-03-07 10:42
cov-2.6.1 should fix this.

**Comment by s2t2** [comment] 2019-03-08 15:50
Was originally following installation instructions here: https://docs.pytest.org/en/latest/getting-started.html

I think it might be an anaconda thing. Here is some more info: https://github.com/s2t2/testing-123-py/issues/2

**Comment by blueyed** [comment] 2019-03-08 16:14
@s2t2 
In https://github.com/s2t2/testing-123-py/issues/2 it is triggered by another plugin..

**Comment by Hawk32604088** [comment] 2019-06-26 07:43
if invoke pytest, the name of func you defined can't be with prefix "test".

**Comment by mirhmousavi** [comment] 2019-11-23 05:28
rename `get_marker` to `get_closest_marker` in
`/usr/local/lib/python3.6/site-packages/pytest_cov/plugin.py`

solved for me

**Comment by RonnyPfannschmidt** [comment] 2019-11-23 06:52
@mirhmousavi that solution is a last stop measure - more recent versions of pytest-cov already have this done correctly - updating is preferred to editing random installed files

**Comment by mirhmousavi** [comment] 2019-11-23 07:14
@RonnyPfannschmidt  I had installed `pytest-cov` from a local repo and it installed v2.6.0
I upgraded and everything's OK
Thanks

**Comment by arvindpdmn** [comment] 2020-05-06 04:41
I'm using `pytest-cov` 2.8.1 and still get the error.

**Comment by nicoddemus** [comment] 2020-05-06 21:43
Thanks @arvindpdmn for coming back to post the solution. 👍
