### ISSUE TITLE
pytest-3.0.3 through 3.0.7 fail test TestGeneralUsage.test_issue109_sibling_conftests_not_loaded with pypy3-5.7.1

### ISSUE THREAD

**Issue by PPed72** [pytest-dev/pytest#2448] opened 2017-05-30 14:25 UTC
testing/acceptance_test.py::TestGeneralUsage::test_issue109_sibling_conftests_not_loaded FAILED

============================================================ FAILURES =============================================================
___________________________________ TestGeneralUsage.test_issue109_sibling_conftests_not_loaded ___________________________________

self = <acceptance_test.TestGeneralUsage object at 0x000055f7bb54d360>
testdir = <Testdir local('/var/tmp/portage/dev-python/pytest-3.0.7/temp/pytest-of-portage/pytest-15/testdir/test_issue109_sibling_conftests_not_loaded0')>

    def test_issue109_sibling_conftests_not_loaded(self, testdir):
        sub1 = testdir.tmpdir.mkdir("sub1")
        sub2 = testdir.tmpdir.mkdir("sub2")
        sub1.join("conftest.py").write("assert 0")
        result = testdir.runpytest(sub2)
        assert result.ret == EXIT_NOTESTSCOLLECTED
        sub2.ensure("__init__.py")
        p = sub2.ensure("test_hello.py")
        result = testdir.runpytest(p)
>       assert result.ret == EXIT_NOTESTSCOLLECTED
E       assert 2 == 5
E        +  where 2 = <_pytest.pytester.RunResult object at 0x000055f7bb520a68>.ret

../../../../../work/pytest-3.0.7/testing/acceptance_test.py:227: AssertionError
------------------------------------------------------ Captured stdout call -------------------------------------------------------
======================================================= test session starts =======================================================
platform linux -- Python 3.5.3[pypy-5.7.1-beta], pytest-3.0.7, py-1.4.30, pluggy-0.4.0
rootdir: /var/tmp/portage/dev-python/pytest-3.0.7/temp/pytest-of-portage/pytest-15/testdir/test_issue109_sibling_conftests_not_loaded0, inifile:
plugins: xdist-1.15.0, hypothesis-3.6.0
collected 0 items

================================================== no tests ran in 0.01 seconds ===================================================
======================================================= test session starts =======================================================
platform linux -- Python 3.5.3[pypy-5.7.1-beta], pytest-3.0.7, py-1.4.30, pluggy-0.4.0
rootdir: /var/tmp/portage/dev-python/pytest-3.0.7/temp/pytest-of-portage/pytest-15/testdir/test_issue109_sibling_conftests_not_loaded0, inifile:
plugins: xdist-1.15.0, hypothesis-3.6.0
collected 0 items / 1 errors

============================================================= ERRORS ==============================================================
_______________________________________________ ERROR collecting sub2/test_hello.py _______________________________________________
ImportError while importing test module '/var/tmp/portage/dev-python/pytest-3.0.7/temp/pytest-of-portage/pytest-15/testdir/test_issue109_sibling_conftests_not_loaded0/sub2/test_hello.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
ImportError: No module named 'sub2.test_hello'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================================== 1 error in 0.83 seconds =====================================================
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================== 1 failed, 24 passed in 22.07 seconds ===============================================

System is Gentoo Linux.
Python interpreters are:
python-2.7.13
python-3.5.3
pypy-5.7.1
pypy3-5.7.1

**Comment by RonnyPfannschmidt** [comment] 2017-05-30 15:11
i did see that issue on nixos as well - as far as i understand this is due to incorrect python interpreter setup - i didn't find the time to deeply investigate, but its certain not to happen on more conservative distros

**Comment by PPed72** [comment] 2017-05-31 07:43
If you tell me which information you need, I can provide that.

**Comment by RonnyPfannschmidt** [comment] 2017-05-31 07:44
@PPed72 the problem is, i don't yet know where to look - this issue is unclear

**Comment by nicoddemus** [comment] 2018-01-18 20:10
Closing for now; we will be happy to re-open this once we get more information.

**Closed by nicoddemus** 2018-01-18 20:10 UTC
Labels: status: help wanted, status: needs information, type: bug, type: infrastructure
