### ISSUE TITLE
Running pytest within pytest fails with pytest==8.0.0rc1

### ISSUE THREAD

**Issue by mwouts** [pytest-dev/pytest#11807] opened 2024-01-12 21:57 UTC
Thanks for maintaining and developing `pytest`. This is such an amazing tool!

I have setup a `--pre` version of the CI on one of the projects that I maintain, and it happens that one test fails with the release candidate `pytest==8.0.0rc1`.

Here are the logs of the action: https://github.com/mwouts/jupytext/actions/runs/7487800603/job/20381150371

The failing test does the following:
- It creates a temporary `.py` file from a Markdown document
- And then it calls `pytest` on that `.py` file, so in the end it's calling `pytest /tmp/notebook_lx_y64ur.py`.

With `pytest==8.0.0rc1`, the test fails with the following error:
```
E   PermissionError: [Errno 13] Permission denied: '/tmp/snap-private-tmp/__init__.py'
```

I am not sure how to extract a simpler minimal example from this, but I can look into this if you think that would help. Thanks!

**Comment by RonnyPfannschmidt** [comment] 2024-01-12 22:22
duplicate of #11781

**Closed by RonnyPfannschmidt** 2024-01-12 22:22 UTC

**Comment by bluetech** [comment] 2024-01-13 09:36
Yes, as written in the other issue, you should avoid running things from `/tmp`; the way pytest works requires looking inside & running things from the directory (like `conftest.py`, `__init__.py`) and since `/tmp` is world-writable you really don't want that. It's better to put the file inside `tmp_path` or even just in a `tempfile.TemporaryDirectory`, but not directly in `/tmp`.

**Comment by mwouts** [comment] 2024-01-13 20:32
> Yes, as written in the other issue, you should avoid running things from `/tmp`; the way pytest works requires looking inside & running things from the directory (like `conftest.py`, `__init__.py`) and since `/tmp` is world-writable you really don't want that. It's better to put the file inside `tmp_path` or even just in a `tempfile.TemporaryDirectory`, but not directly in `/tmp`.

Oh thanks for pointing this out! Sure I should be able to use `tempfile.TemporaryDirectory`, that's a great suggestion!
