### ISSUE TITLE
Autouse=True is inherited by shadowing fixtures

### ISSUE THREAD

**Issue by jgersti** [pytest-dev/pytest#11527] opened 2023-10-20 10:40 UTC
### Issue
Shadowing a fixture with `autouse=True` makes the shadowing fixture being autoused.

### Example
```python
@pytest.fixture(name="a", autouse=True)
def a1():  print("autouse=True")

@pytest.fixture(name="a", autouse=False)
def a2(): print("autouse=False")

def test_autouse(): pass
```
```
=================================== test session starts ===================================
platform win32 -- Python 3.11.2, pytest-7.4.2, pluggy-1.2.0 -- 
cachedir: .pytest_cache
rootdir: xxx
collecting ... 
collected 1 item                                                                                                                                   

test_example.py::test_autouse autouse=False
PASSED

=================================== 1 passed in 0.01s ===================================
```

### Cause
Fixtures are resolved by name

**Comment by The-Compiler** [comment] 2023-10-20 10:44
I'm confused by your example - it doesn't actually run (`b` is not defined), you have a fixture that uses itself, *and* your test uses the `a` fixture which means it really doesn't matter whether `autouse` is set or not.

**Comment by jgersti** [comment] 2023-10-20 10:46
My bad, I forgot to remove them when copying.

**Comment by The-Compiler** [comment] 2023-10-20 10:52
Duplicate of #3225

**Closed by The-Compiler** 2023-10-20 10:52 UTC
Labels: topic: fixtures
