### ISSUE TITLE
Finalizers don't run on SIGTERM

### ISSUE THREAD

**Issue by simonfontana** [pytest-dev/pytest#5243] opened 2019-05-10 19:29 UTC
I caught this issue in a Jenkins environment. This is the series of events:
1. My tests create resources outside the test environment
2. Jenkins kills the pytest process with SIGTERM. Finalizers won't run and resources won't be cleaned up.

That doesn't seem right to me. A cleanup method should always cleanup, no matter what caused the exit. For example KeyboardInterrupt **does** run cleanup, so why shouldn't SIGTERM?

Here is a sample program:

```
import pytest


@pytest.fixture
def myfixture(request):
    print('fixture')

    def finalizer():
        print('finalizer')
    request.addfinalizer(finalizer)


def test_fast_test(myfixture):
    print('run fast test')


def test_slow_test(myfixture):
    print('run slow test')
    import time
    time.sleep(100)
```

Steps to reproduce:
1. Open two terminals.
2. In the first terminal, run the tests withn pytest: `pytest -s finalizer_test.py`
3. In the second terminal, kill the pytest process with SIGTERM. For example using pkill command: `pkill pytest`

This is the output:
```
finalizer_test.py fixture
run fast test
.finalizer
fixture
run slow test
Terminated
```

As you can see the second finalizer didn't run.

Environment:
- Ubuntu 16.04
- Python 3.5.2
- pip packages:
```
$ pip list
Package        Version
-------------- -------
atomicwrites   1.3.0  
attrs          19.1.0 
more-itertools 7.0.0  
pathlib2       2.3.3  
pip            19.1.1 
pkg-resources  0.0.0  
pluggy         0.11.0 
py             1.8.0  
pytest         4.4.2  
setuptools     20.7.0 
six            1.12.0
```

**Comment by blueyed** [comment] 2019-05-10 23:11
I've looked at this in https://github.com/pytest-dev/pytest/pull/5019 - maybe worth re-opening then.
Would you like to pick it up maybe?

**Comment by asottile** [comment] 2019-05-11 03:53
This is standard behaviour in python (and as far as I can tell in most programming languages) -- I think it would be _more suprising_ for pytest to implement this.

If you want something that can make this work for you, you could rewrite the signal to `SIGINT` using a wrapper and then you'd trigger the normal cleanup path for interrupt in python.

One way you could do this is to use [dumb-init](https://github.com/Yelp/dumb-init) to rewrite the signal using `--rewrite`

Here's a simple example where I turn `SIGTERM` into `SIGINT`:

```
$ ./venv/bin/dumb-init --rewrite 15:2 python3 -c 'import time; time.sleep(1000)'

# I pressed enter a few times and then in another terminal tab I did `pkill -TERM dumb-init`

Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyboardInterrupt
```

**Comment by blueyed** [comment] 2019-05-11 09:04
I think it is a bit a definition issue: e.g. Python closes file descriptiors itself (or is that the OS in the end?).
Therefore pytest could also try to close fixtures, i.e. run finalizers.
As for #5019 this should maybe do only this then, but not display summaries etc then.

**Comment by simonfontana** [comment] 2019-05-11 09:32
@asottile I disagree with it not being the standard behaviour for other programs. I think it's the opposite, that's why I opened this ticket. A wrapper doesn't seem like the right way to handle this. Any process should implement signal handling for SIGTERM to do cleanup imo.

SIGTERM is a signal to the process that it should exit. The point of telling the process it should exit instead of just killing it is to let the process do pre-exit execution such as cleanup. If I wanted to kill the process without cleanup I would send SIGKILL.

@blueyed The kernel closes file descriptors on process exit. I think it makes sense to only do cleanup and nothing else on SIGTERM. I could maybe pick up the work in the future but I don't have time at the moment. So if you or anyone else want to do the work I'm all for it.

**Comment by blueyed** [comment] 2019-05-11 11:50
I've re-opened https://github.com/pytest-dev/pytest/pull/5019 - maybe you can test it, or review it?

**Comment by asottile** [comment] 2019-05-11 15:45
> I think it is a bit a definition issue: e.g. Python closes file descriptiors itself (or is that the OS in the end?).
> Therefore pytest could also try to close fixtures, i.e. run finalizers.
> As for #5019 this should maybe do only this then, but not display summaries etc then.

python doesn't register anything other than `SIGINT`, any behaviour that occurs as part of `SIGTERM` today is due to the kernel's default behaviour.  https://github.com/python/cpython/blob/79972f1fad5247ade34ef98ad987162a9a78401d/Modules/signalmodule.c#L1399

The ~usual graceful termination I've seen is SIGINT -> SIGTERM -> SIGKILL

**Comment by asottile** [comment] 2019-05-11 15:54
this also wouldn't be terribly hard to do as a fixture or plugin without adding this to core:

```python
@pytest.fixture(scope='session', autouse=True)
def term_handler():
    orig = signal.signal(signal.SIGTERM, signal.getsignal(signal.SIGINT))
    yield
    signal.signal(signal.SIGTERM, orig)

**Comment by simonfontana** [comment] 2019-05-13 12:43
> python doesn't register anything other than SIGINT, any behaviour that occurs as part of SIGTERM today is due to the kernel's default behaviour.
I'm not sure I understand what you mean. Python can't possibly know what resources I have opened that needs to be cleaned up so it can't have a default behaviour for that.

I appreciate you took the time to write an example of a workaround. Unfortunately it doesn't work with multiple threads (tested with xdist). Maybe this is trickier than I first thought.

I still don't understand why you don't want to add signal handler for pytest. I'm sure there is a good reason for it. Why do you think finalizers should be run for SIGINT and not SIGTERM?

**Comment by asottile** [comment] 2019-05-13 15:39
> I appreciate you took the time to write an example of a workaround. Unfortunately it doesn't work with multiple threads (tested with xdist). Maybe this is trickier than I first thought.

Probably needs a [check for the main thread](https://stackoverflow.com/questions/23206787/check-if-current-thread-is-main-thread-in-python).

> Why do you think finalizers should be run for SIGINT and not SIGTERM?

My fundamental reasoning is that **python does not do this**, we should not deviate from the standard language behaviour as this introduces a difference in the test environment which is not present in the runtime environment.   Additionally, it represents some pretty-complex interaction and cross-platform concerns that we now have to maintain the complexity for.

I have yet to see a programming language which calls finalizers on `SIGTERM`, only on `SIGINT`.  If anything this is something a _language_ should implement (or individual applications which wish to handle `SIGTERM`) and not the concern of a testing framework.

**Comment by blueyed** [comment] 2019-05-13 17:04
> … or individual applications which wish to handle `SIGTERM`

I see pytest more as an application here, making use of the tooling that Python provides to handle the signal.

But I can also see that it gets more involved when tests are using signal handlers themselves etc, they would then see the signal being handled already, while it is not outside of tests.

**Comment by asottile** [comment] 2019-05-13 17:13
> > … or individual applications which wish to handle `SIGTERM`
> 
> I see pytest more as an application here, making use of the tooling that Python provides to handle the signal.

hmmm, ok well I don't see it that way -- pytest is acting as a framework which runs your code but at the end of the day it's really your application's code and the environment your tests choose

**Comment by simonfontana** [comment] 2019-05-13 19:49
> My fundamental reasoning is that python does not do this
My understanding is that Python only does this to raise a specific exception "KeyboardInterrupt". This is to improve user experience. I could wrong though, maybe there are other reasons why Python has a signal handler for that specific signal.

> I have yet to see a programming language which calls finalizers on SIGTERM, only on SIGINT
Again, I don't see any reason why a language would ever do this. It's up to the users of the program language to implement their own signal handlers as they see handy. And as a testing framework I think Pytest should enable users to do so without a hassle. There are other testing frameworks out there that has implemented signal handlers for SIGTERM. Have a look at some examples:

- https://github.com/onsi/ginkgo
- https://maven.apache.org/surefire/maven-failsafe-plugin/
- https://github.com/robotframework/robotframework/issues/2451

And then there are examples that don't:
- https://github.com/mochajs/mocha/issues/516
- https://www.tutorialspoint.com/unittest_framework/unittest_framework_signal_handling.htm

You're definetely not alone in your argument but I'm still trying to understand why SIGINT is so different from SIGTERM in case of cleanup.

**Comment by asottile** [comment] 2019-05-13 20:14
> > My fundamental reasoning is that python does not do this
> 
> My understanding is that Python only does this to raise a specific exception "KeyboardInterrupt". This is to improve user experience. I could be wrong though, maybe there are other reasons why Python has a signal handler for that specific signal.

Python does this specifically so that finalizers are called (because finally blocks are called during exception bubbling)

> You're definetely not alone in your argument but I'm still trying to understand why SIGINT is so different from SIGTERM in case of cleanup.

It's different because the language dictates SIGINT but doesn't dictate SIGTERM, SIGQUIT, SIGHUP or the 20 other signals which by default trigger termination

**Comment by simonfontana** [comment] 2019-05-14 19:30
@asottile I don't agree with you but respect your opinion. Let's leave the issue open for some time so others have a chance the speak their mind as well. If there are no comments in a couple of weeks we can probably close the issue.

**Comment by blueyed** [comment] 2019-05-14 20:00
https://github.com/pytest-dev/pytest/pull/5019 is there since April 1th already.

Calling for @nicoddemus :)

**Comment by ptrivedi2610** [comment] 2020-05-08 07:38
@nicoddemus 
Sorry to jump in between the conversation. I was looking for something similar so thought of sharing my viewpoint on the same.

I agree with @blueyed on handling SIGTERM. There is one specific scenario of multiprocessing that will need pytest to handle SIGTERM. For a background on the same, kindly refer my ticket https://github.com/pytest-dev/pytest/issues/7165

The issue is
1. I have invoked pytest.main() from ProcessS. ProcessS was forked from main process ProcessM (using multiprocessing)
2. Now I want to stop pytest session execution mid run, such a a way that no further test runs, but also all teardown are shut successfully.
3. Ideally ,os.kill() on Linux and MAC machine does the job. However there is bug in windows python regarding os.kill(). Refer https://bugs.python.org/issue23948
4. This means the only option to halt the ProcessS and pytest.main() is using ProcessS.terminate(). However multiprocessing.terminate() uses SIGTERM.

Thus, in my humble opinion it will be good to have SIGTERM handling.

**Comment by gsmethells** [comment] 2021-09-29 22:14
If finalizers are specifically the sticking point, then I suggest that the topic be switched to the essence of the desire: if a fixture is in charge of a resource's lifecycle, then how can resource leaks be avoided? 

Why is this any of pytest's concern? 

Fixtures provide the main mechanism by which all tests that leverage the pytest framework set up their resources. Some of these resources are important to clean up. For example if I create a bucket in object storage and I am being charged for using object storage, then it is essential to know that that resource will be cleaned up if the test is canceled mid-run. If I am using the pytest framework and I use a fixture to create that resource then I expect fixtures to have a mechanism, any mechanism at all, to clean up that resource or suddenly fixtures are no longer useful for resource lifecycles. 

SIGTERM is extremely common for canceling a process gracefully. No one disputes that because it's been that way for a long time. It's very common to have a grace period after the SIGTERM which is then followed by a SIGKILL. For reference check out what [Google does for Kubernetes](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace).

So, since there are certain points that cannot be argued against:

1. SIGTERM is used for graceful termination of a process
2. Resource leaks are bad news
3. [pytest documentation recommends fixtures for the allocation of resources](https://docs.pytest.org/en/latest/how-to/fixtures.html)

That leaves only the final question which is: how should resource leaks be handled by pytest users?

**Comment by RonnyPfannschmidt** [comment] 2021-09-30 11:23
I just reviewed the docs,

I believe pytest should raise a exception and do a graceful shutdown

A correct solution will need a way to sort out blocked teardowns

This may require quite some investigation

**Comment by asottile** [comment] 2021-09-30 12:29
I don't think pytest should do this.  I think at most this should start in a plugin which uses the code I listed above but it's really not pytest's domain to deviate from how python functions

**Comment by RonnyPfannschmidt** [comment] 2021-09-30 12:41
@asottile pytest is a test runner that  does **resource management** - any python service/tool that does resource management is typically expected to handle the term signal and clean up

so i believe pytest should do so as well

**Comment by asottile** [comment] 2021-09-30 12:43
no other test runner that I know of does.  the only software I know of that does are daemons which pytest is not

**Comment by RonnyPfannschmidt** [comment] 2021-09-30 13:03
hmmm, then the best place for this may be a pytest-handle-sigterm plugin

**Comment by gsmethells** [comment] 2021-09-30 19:13
@asottile it was already pointed out that [Ginko for Go and Maven for Java provide a mechanism](https://github.com/pytest-dev/pytest/issues/5243#issuecomment-491960825). I'm not suggesting finalizers are that mechanism at all. I'm suggesting there should be a mechanism of some kind; otherwise, fixtures are not going to be useful for resource lifecycles and that should be called out more clearly in the documentation rather than documenting that fixtures are useful for such purposes.

**Comment by gsmethells** [comment] 2021-09-30 20:07
Keep in mind that the mechanism, to be useful, needs to be able to handle cleaning up `N` resources created by `N` fixtures.

**Comment by asottile** [comment] 2021-09-30 20:09
to be clear, I don't see pytest as a resource manager -- I see it as a test runner

that said, try out the code I posted above, it should work

**Comment by gsmethells** [comment] 2021-09-30 20:30
I understand. The documentation suggests pytest's opinion is otherwise, which is concerning. That says to me it deserves an issue in and of itself to disambiguate:

- pytest fixtures are not intended for handling resource lifecycles (user beware)
- common ways a user can handle resource lifecycles that are known to work smoothly with pytest's framework

A pytest subproject that saves everyone from re-inventing the wheel would be wonderful. I don't desire to write my own solution myself, but it seems I have to. That subject would be a nice issue to have around as well.

**Comment by gsmethells** [comment] 2021-09-30 21:42
Since finalizers are not the answer, I suspect this could now close as long as the above two issues capture all the salient points made over the lifetime of this ticket.

**Comment by nicoddemus** [comment] 2021-10-01 00:36
Closing then, thanks everyone and thanks @gsmethells for opening the follow up issues. 👍

**Closed by nicoddemus** 2021-10-01 00:36 UTC
Labels: type: proposal

**Comment by mortalisk** [comment] 2024-05-06 08:09
We use pytest in a setup together with npm, vite, playwright, etc. When our stuff is killed, everything gets shut down nice a cleanly, except pytest managed resources, which eat up developers computer resources, and sometimes build machines. It's super annoying that pytest doesn't by default run the code we wrote explicitly to do cleanup, and I don't know how to fix it. At least it would be super useful to add an option for pytest to run this code when asked to shut down.
