### ISSUE TITLE
3.6.0 can't find fixtures for cheroot.test.webtest.WebCase based test classes

### ISSUE THREAD

**Issue by lsmithso** [pytest-dev/pytest#3507] opened 2018-05-25 09:18 UTC
A test class derived from cheroot.test.webtest.WebCase can no longer
find fixtures with pytest 3.6.0. It used to work in 3.5.1.

In the following example, both test cases fail in 3.5.1 because both
test class fixtures are foumd. In 3.6.0 only the test case derived
from object fails because the test case derived from
cheroot.test.webtest.WebCase is not found.

import pytest
from cheroot.test import webtest

class Test1(webtest.WebCase):

    @pytest.fixture
    def fixture(self):
        assert 0

    @pytest.mark.usefixtures('fixture')
    def test_cheroot_base(self):
        pass

class Test2(object):

    @pytest.fixture
    def fixture(self):
        assert 0

    @pytest.mark.usefixtures('fixture')
    def test_object_base(self):
        pass

python --version 
Python 2.7.12

	
pip list 
Package                       Version
----------------------------- -------
atomicwrites                  1.1.5  
attrs                         18.1.0 
backports.functools-lru-cache 1.5    
cheroot                       6.3.1  
funcsigs                      1.0.2  
more-itertools                4.2.0  
pip                           10.0.1 
pluggy                        0.6.0  
py                            1.5.3  
pytest                        3.6.0  
setuptools                    39.2.0 
six                           1.11.0 
wheel                         0.31.1

**Comment by RonnyPfannschmidt** [comment] 2018-05-25 09:32
this was fixed in #3500 and is a duplicate of #3498

**Closed by RonnyPfannschmidt** 2018-05-25 09:32 UTC
Labels: type: bug, type: question
