### ISSUE TITLE
Broken link from development docs to stable docs

### ISSUE THREAD

**Issue by michael-k** [pytest-dev/pytest#7403] opened 2020-06-23 08:40 UTC
The link in the header of https://docs.pytest.org/en/latest/ to the documentation of the latest stable release is broken.  It points to https://docs.pytest.org/en/latest/5.4.3/index.html instead of https://docs.pytest.org/en/5.4.3/index.html (the `latest` is wrong).

I'm happy to provide a PR to fix this if it's anywhere in the code base.  But I couldn't find it anywhere in the github org.

![image](https://user-images.githubusercontent.com/152008/85380069-024cd680-b52c-11ea-952f-aab950da720e.png)

**Comment by nicoddemus** [comment] 2020-06-23 15:08
Closing as duplicate of https://github.com/pytest-dev/pytest/issues/7331.

@michael-k it seems this is inherited from the flask template we use, see https://github.com/pytest-dev/pytest/issues/7331. Any hints are welcome.

**Closed by nicoddemus** 2020-06-23 15:08 UTC
Labels: type: docs
