### ISSUE TITLE
Parameter corruption for parameterized tests

### ISSUE THREAD

**Issue by prot0man** [pytest-dev/pytest#1843] opened 2016-08-22 17:34 UTC
It looks like between pytest 2.9.2 and 3.0.0, some change has been introduced that causes incorrect values to be passed to parameterized tests. For instance, given the two tests:

@pytest.mark.parametrize("xid, fromPath, toPath, result", [
                        ("xid1", "/usr/bin/who", "/tmp/who", True),
])
def testFileXferLocal(network, xid, fromPath, toPath, result):
  ...

AND
@pytest.mark.parametrize("xid, fromPath, toPath, result", [
                        ("xid3-1","/tmp/fwd-test-dir-copy", "/tmp/fwd-output-dir-copy", True)
                        ])
def testFolderXferLocal(network, xid, fromPath, toPath, result):
  ...

The value '/usr/bin/who' is being passed to our test 'testFolderXferLocal'  for 'fromPath' instead of the expected '/tmp/fwd-test-dir-copy'. 

The version of pytest that works correctly is 2.9.2, while pytest 3.0.0 causes the erroneus behavior described.
  
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion
- [ ] `pip list` of the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] Minimal example if possible

**Comment by The-Compiler** [comment] 2016-08-22 17:37
Closing as a duplicate of #1832 - we'll hopefully have a fix ready and release a 3.0.1 soon.

As a workaround, you can add an autouse function-scoped fixture to your `conftest.py`, like in https://github.com/The-Compiler/qutebrowser/commit/bd1c63e569599f9546948f82f3a427f5c9cc2ef3

**Comment by prot0man** [comment] 2016-08-22 17:41
That was quick! Thanks

**Closed** 2016-08-22 22:00 UTC
