### ISSUE TITLE
mapping the fixture parameter with the test method parameter

### ISSUE THREAD

**Issue by markshao** [pytest-dev/pytest#1263] opened 2015-12-16 15:18 UTC
I have the test cases  to test some sftp related features under different OS . For example test the file path existence under both windows and Linux.

The test function support two kind of parameters , first parameter is the fixture returns a paramiko ssh connection , the second parameter is a normal string parameter for the file path.

```python
import pytest

@pytest.fixture(scope="module", params=("linux", "windows"))
def ssh_connection(request):
    pass


class TestSftpUtil(object):
    @pytest.mark.parametrize("path", [("c:/windows",), ("/root/path",)])
    def test_is_file(self, ssh_connection, path):
        assert True
```
Now the pytest traverse all the possible parameter groups 
```bash
test/test_sftputil.py::TestSftpUtil::test_is_file[linux-path0] PASSED
test/test_sftputil.py::TestSftpUtil::test_is_file[linux-path1] PASSED
test/test_sftputil.py::TestSftpUtil::test_id_dir[linux] PASSED
test/test_sftputil.py::TestSftpUtil::test_is_file[windows-path0] PASSED
test/test_sftputil.py::TestSftpUtil::test_is_file[windows-path1] PASSED
test/test_sftputil.py::TestSftpUtil::test_id_dir[windows] PASSED
```
But some parameter group is unnecessary, like windows OS + linux file path . Is there a way to define the mapping between the normal parametrize with the fixture params (I don't want to write too much if ... else ... in the test method )

**Comment by RonnyPfannschmidt** [comment] 2015-12-16 16:42
is that a duplicate/variant of #681?

**Comment by markshao** [comment] 2015-12-17 02:07
Yes , I agree with that

**Comment by RonnyPfannschmidt** [comment] 2015-12-17 05:54
Thanks, Closing as duplicate of #681

**Closed** 2015-12-17 05:54 UTC
