### ISSUE TITLE
INTERNALERROR> LookupError: unknown encoding: uft-8 

### ISSUE THREAD

**Issue by Chibbluffy** [pytest-dev/pytest#7674] opened 2020-08-22 20:33 UTC
I've only imported from the libraries: requests, unittest
Created a new project from https://pypi.org/project/PyScaffold/
All I did was `putup test` after I pip installed it
Once I cd into the directory 'test' and run 'pytest' i get this output

```
test ➤ pytest                                                                       git:master
===================================== test session starts =====================================
platform darwin -- Python 3.7.7, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /usr/local/opt/python/bin/python3.7
cachedir: .pytest_cache
rootdir: /Users/tom/Documents/projects/test/test, configfile: setup.cfg, testpaths: tests
plugins: cov-2.10.1
collected 0 items / 1 error
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 397, in find_cookie
INTERNALERROR>     codec = lookup(encoding)
INTERNALERROR> LookupError: unknown encoding: uft-8
INTERNALERROR>
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR>
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/main.py", line 240, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/main.py", line 296, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pytest_cov/plugin.py", line 271, in pytest_runtestloop
INTERNALERROR>     self.cov_controller.finish()
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pytest_cov/engine.py", line 44, in ensure_topdir_wrapper
INTERNALERROR>     return meth(self, *args, **kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pytest_cov/engine.py", line 166, in summary
INTERNALERROR>     total = self.cov.report(**options)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/coverage/control.py", line 888, in report
INTERNALERROR>     return reporter.report(morfs, outfile=file)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/coverage/summary.py", line 45, in report
INTERNALERROR>     for fr, analysis in get_analysis_to_report(self.coverage, morfs):
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/coverage/report.py", line 70, in get_analysis_to_report
INTERNALERROR>     analysis = coverage._analyze(fr)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/coverage/control.py", line 783, in _analyze
INTERNALERROR>     return Analysis(data, it, self._file_mapper)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/coverage/results.py", line 20, in __init__
INTERNALERROR>     self.statements = self.file_reporter.lines()
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/coverage/python.py", line 191, in lines
INTERNALERROR>     return self.parser.statements
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/coverage/python.py", line 184, in parser
INTERNALERROR>     exclude=self.coverage._exclude_regex('exclude'),
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/coverage/parser.py", line 44, in __init__
INTERNALERROR>     self.text = get_python_source(self.filename)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/coverage/python.py", line 65, in get_python_source
INTERNALERROR>     source = source.decode(source_encoding(source), "replace")
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/coverage/phystokens.py", line 261, in _source_encoding_py3
INTERNALERROR>     return tokenize.detect_encoding(readline)[0]
INTERNALERROR>   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 426, in detect_encoding
INTERNALERROR>     encoding = find_cookie(first)
INTERNALERROR>   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 405, in find_cookie
INTERNALERROR>     raise SyntaxError(msg)
INTERNALERROR>   File "<string>", line None
INTERNALERROR> SyntaxError: unknown encoding: uft-8

====================================== 1 error in 1.72s =======================================
```

My pip list:
```
(venv) tom•projects/test/test(master)» pip list                                     [15:23:08]
Package            Version
------------------ -------
attrs              20.1.0
coverage           5.2.1
importlib-metadata 1.7.0
iniconfig          1.0.1
more-itertools     8.4.0
packaging          20.4
pip                20.1.1
pluggy             0.13.1
py                 1.9.0
pyparsing          2.4.7
pytest             6.0.1
pytest-cov         2.10.1
setuptools         47.1.1
six                1.15.0
toml               0.10.1
wheel              0.34.2
zipp               3.1.0
```

I'm running Mac, Catalina 10.15.5 (19F101)
Should be on latest pytest version.
The example files are created with the scaffolding tool. But they look super basic, so I don't think there's a problem with the example files. I can't tell if it's a pytest or pytest-cov issue, but something is going on. Let me know if there's anything else you need to know. Thanks!

I'm really just trying to create a project with pytest setup so I can write unit tests for my project. Thought using a scaffolding tool would make my life easier, but I still can't seem to get pytest working for me. 

- [x] a detailed description of the bug or suggestion
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

**Comment by Chibbluffy** [comment] 2020-08-23 20:08
I had to put it in the try. The Exception didn't hit the breakpoint.
```
try:
    self.text = get_python_source(self.filename)
    breakpoint()
except Exception:
    raise
```

**Comment by graingert** [comment] 2020-08-23 20:11
@Chibbluffy did you discover the value of `self.filename` that triggers the error?

**Comment by Chibbluffy** [comment] 2020-08-23 20:14
So it hits it a few times. Each time it hit the breakpoint I did self.filename. Below are the results of each time it gets hit.

'/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/test/__init__.py'
'/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/test/__main__.py'
'/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/test/_test_multiprocessing.py'
'/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/test/ann_module.py'
'/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/test/ann_module2.py'
'/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/test/ann_module3.py'
'/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/test/audiotests.py'
'/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/test/autotest.py'

**Comment by Chibbluffy** [comment] 2020-08-23 20:15
I have my virtualenv activated, not sure why it's pointing outside of it here. I may have something configured/setup incorrectly?

**Comment by The-Compiler** [comment] 2020-08-23 21:33
I'm guessing it's coming from this test inside Python's own "test" module: https://github.com/python/cpython/blob/master/Lib/test/bad_coding.py

Can you try with a project not called "test"?

**Comment by Chibbluffy** [comment] 2020-08-23 21:57
oh weird, I guess it is. Made a new project with different name and it didnt have the internal error. Thanks!

**Comment by Chibbluffy** [comment] 2020-08-23 21:58
Not sure if it's an edge case you guys want to fix or not, so I'll leave this issue open for you to decide. Thanks for the help!

**Comment by The-Compiler** [comment] 2020-08-23 22:07
Looking at the stacktrace, I doubt this is an issue with pytest. Can you try running `coverage report` in the same folder?

**Comment by Chibbluffy** [comment] 2020-08-24 02:29
Here's the result for coverage report:
```
Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 397, in find_cookie
    codec = lookup(encoding)
LookupError: unknown encoding: uft-8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tom/Documents/projects/test/test/venv/bin/coverage", line 8, in <module>
    sys.exit(main())
  File "/Users/tom/Documents/projects/test/test/venv/lib/python3.7/site-packages/coverage/cmdline.py", line 865, in main
    status = CoverageScript().command_line(argv)
  File "/Users/tom/Documents/projects/test/test/venv/lib/python3.7/site-packages/coverage/cmdline.py", line 615, in command_line
    **report_args
  File "/Users/tom/Documents/projects/test/test/venv/lib/python3.7/site-packages/coverage/control.py", line 888, in report
    return reporter.report(morfs, outfile=file)
  File "/Users/tom/Documents/projects/test/test/venv/lib/python3.7/site-packages/coverage/summary.py", line 45, in report
    for fr, analysis in get_analysis_to_report(self.coverage, morfs):
  File "/Users/tom/Documents/projects/test/test/venv/lib/python3.7/site-packages/coverage/report.py", line 70, in get_analysis_to_report
    analysis = coverage._analyze(fr)
  File "/Users/tom/Documents/projects/test/test/venv/lib/python3.7/site-packages/coverage/control.py", line 783, in _analyze
    return Analysis(data, it, self._file_mapper)
  File "/Users/tom/Documents/projects/test/test/venv/lib/python3.7/site-packages/coverage/results.py", line 20, in __init__
    self.statements = self.file_reporter.lines()
  File "/Users/tom/Documents/projects/test/test/venv/lib/python3.7/site-packages/coverage/python.py", line 191, in lines
    return self.parser.statements
  File "/Users/tom/Documents/projects/test/test/venv/lib/python3.7/site-packages/coverage/python.py", line 184, in parser
    exclude=self.coverage._exclude_regex('exclude'),
  File "/Users/tom/Documents/projects/test/test/venv/lib/python3.7/site-packages/coverage/parser.py", line 44, in __init__
    self.text = get_python_source(self.filename)
  File "/Users/tom/Documents/projects/test/test/venv/lib/python3.7/site-packages/coverage/python.py", line 65, in get_python_source
    source = source.decode(source_encoding(source), "replace")
  File "/Users/tom/Documents/projects/test/test/venv/lib/python3.7/site-packages/coverage/phystokens.py", line 261, in _source_encoding_py3
    return tokenize.detect_encoding(readline)[0]
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 426, in detect_encoding
    encoding = find_cookie(first)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 405, in find_cookie
    raise SyntaxError(msg)
SyntaxError: unknown encoding: uft-8
```

Looks to be the same encoding issue. I think somewhere it's trying to use uft-8, when it should be utf-8 maybe?

**Comment by The-Compiler** [comment] 2020-08-24 07:59
The problem is that coverage.py is trying to somehow give you reports for the `test` module in the Python stdlib. That module contains the `bad_coding.py` I linked above, which *does* say `# -*- coding: uft-8 -*-` (probably to test how Python itself handles a wrong encoding).

Thus, the bug is either with `coverage.py` (which collects the `test` stdlib module instead of the one in your package) or with PyScaffold. Looking at the `.coveragerc` PyScaffold generates:

```ini
[run]
# ...
source = test

[paths]
source =
    src/
    */site-packages/
```

it looks to me like it's asking `coverage.py` to look at a package called `test` in either `src/` or any `site-packages` folder. Not sure why coverage.py is looking at the `test` package in the Python stdlib then...

Either way, closing this now as it's definitely not a pytest bug - you might want to open an issue in the [coverage.py repository](https://github.com/nedbat/coveragepy) to see if they can do anything about it. If you do, please link it here, as I'm curious!

**Closed by The-Compiler** 2020-08-24 07:59 UTC
Labels: status: needs information
