### ISSUE TITLE
pytest version 5.2.4 hanged with param --disable-warnings

### ISSUE THREAD

**Issue by vipkum2** [pytest-dev/pytest#6336] opened 2019-12-12 10:02 UTC
I am Working with OS Linux Re Hat 7.6.

I have found that when I use param --disable-warnings with my pytest script then it is not exit even after generate the execution report. It always remain hang. I have to press CTRL-C to stop the same. Kindly take a look into the same.

These are the last console logs from my execution:

```
---------------------------------------- test25_checkTraps ----------------------------------------
No traps found
PASSED
---------------------------------------- teardown_class ----------------------------------------
/tmp/netconf6500_sim/41-sp2_ea/session.log
Gsim session file from /tmp/netconf6500_sim/ copied successfully to /localdata/gsim_session_pytest.txt
+-------------------------------------------------------------
| 13:02:41: GSIM kill/cleanup tool -- gsim_clean.py -- 3.2652
+-------------------------------------------------------------
| 13:02:42:  Running GSIM kill script: /tmp/netconf6500_sim/shelf.kill
| 13:02:50:   Deleting GSIM workspace: /tmp/netconf6500_sim/
+-------------------------------------------------------------
| 13:02:50: Executed 1 shelf.kill scripts in directory: /tmp/netconf6500_sim
+-------------------------------------------------------------
Cleaned the gsim.


--------------------------------------------------------------------------------- generated xml file: /localdata/testresult3.xml ----------------------------------------------------------------------------------
============================================================================== 22 passed, 5 skipped, 5 warnings in 214.95s (0:03:34) ==============================================================================

^CException ignored in: <module 'threading' from '/opt/tools/swtools/anaconda/pftools/envs/linux-64/openroadm_py3/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/opt/tools/swtools/anaconda/pftools/envs/linux-64/openroadm_py3/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/opt/tools/swtools/anaconda/pftools/envs/linux-64/openroadm_py3/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/opt/tools/swtools/anaconda/pftools/envs/linux-64/openroadm_py3/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

Below is the system configuration:
```
Python version: 3.6.3
List of : hax-vipkumar-1|/localdata$ py3 -m pip list
Package            Version            
------------------ -------------------
asn1crypto         1.2.0              
atomicwrites       1.3.0              
attrs              19.3.0             
autobahn           19.11.1            
Automat            0.8.0              
bcrypt             3.1.7              
certifi            2019.9.11          
cffi               1.13.2             
chardet            3.0.4              
constantly         15.1.0             
cryptography       2.8                
dicttoxml          1.7.4              
hyperlink          19.0.0             
idna               2.8                
importlib-metadata 0.23               
incremental        17.5.0             
ipaddr             2.2.0              
iso8601            0.1.12             
jsonpickle         1.2                
junit-xml          1.8                
ldap3              2.6.1              
lxml               4.4.1              
mkl-fft            1.0.15             
mkl-random         1.1.0              
mkl-service        2.3.0              
mock               3.0.5              
more-itertools     7.2.0              
ncclient           0.6.4              
nose               1.3.7              
numpy              1.17.4             
packaging          19.2               
paramiko           2.6.0              
pathlib2           2.3.5              
pexpect            4.7.0              
pip                19.3.1             
pluggy             0.13.1             
psycopg2           2.7.4              
ptyprocess         0.6.0              
py                 1.8.0              
pyasn1             0.4.8              
pyasn1-modules     0.2.7              
pycparser          2.19               
pycrypto           2.6.1              
PyHamcrest         1.9.0              
PyNaCl             1.3.0              
pyOpenSSL          19.0.0             
pyparsing          2.4.5              
pytest             5.2.4              
requests           2.22.0             
requests-twisted   0.1.2              
robotframework     3.1.2              
service-identity   18.1.0             
setuptools         42.0.1.post20191125
six                1.13.0             
tabulate           0.8.6              
Twisted            19.10.0            
txaio              18.8.1             
urllib3            1.25.7             
wcwidth            0.1.7              
wheel              0.33.6             
xmlrunner          1.7.7              
xmltodict          0.12.0             
zipp               0.6.0              
zope.interface     4.7.1              
```

**Comment by asottile** [comment] 2019-12-12 18:49
can you provide the test code which is failing?

**Comment by vipkum2** [comment] 2019-12-20 11:45
This is a big code , I  will try to reproduce with small code and update here.

**Comment by blueyed** [comment] 2020-01-22 11:25
@vipkum2 any update?
To be clear: you say that `--disable-warnings` triggers the hang, but it works otherwise?
What are the warnings then?
Also it might help you to use `-vv` and only execute parts of the test suite to produce a minimal reproducing example.

**Comment by Zac-HD** [comment] 2020-06-09 02:37
Closing this issue because we have no way to reproduce the problem.

**Closed by Zac-HD** 2020-06-09 02:37 UTC
Labels: status: needs information

**Comment by vipkum2** [comment] 2020-06-10 07:56
Thanks, actually even I was not able to reproduce the same.
