### ISSUE TITLE
Pytest is failing to start up on latest Python 3.11 beta

### ISSUE THREAD

**Issue by DanielNoord** [pytest-dev/pytest#10011] opened 2022-06-01 16:05 UTC
- [x] a detailed description of the bug or problem you are having

I don't have many details (I'm sorry) but `pytest` seems to struggle with the latest beta of `3.11` for our testsuite. We ran `3.11b1` with no issues but the [new image](https://github.com/actions/python-versions/releases/tag/3.11.0-beta.2-2419602742) is creating issues.

The affected workflow can be found here:
https://github.com/PyCQA/astroid/runs/6692787850?check_suite_focus=true
Repository is:
https://github.com/PyCQA/astroid

- [x] output of `pip list` from the virtual environment you are using
Can't really access the runner.

```
Pytest is on 7.x
Runner is Ubuntu
```

The run is broken off so soon that there doesn't seem to be any other information I can extract easily, but I'd be happy to help troubleshoot this locally. I just need some directions 😄 

Perhaps this is another pre-existing issue not directly related to `3.11b2`, but it seems like the update did trigger it.

I looked in the `CPython` repo but couldn't find any issues that seemed related to this but perhaps I missed something!

**Comment by The-Compiler** [comment] 2022-06-01 16:27
Duplicate of #10008

**Comment by DanielNoord** [comment] 2022-06-01 16:28
Thanks! Should have looked better 😓

**Closed as not planned** 2022-06-01 16:27 UTC
