### ISSUE TITLE
unexpected fixture execution order

### ISSUE THREAD

**Issue by jacexh** [pytest-dev/pytest#2547] opened 2017-07-04 10:46 UTC
Hi guys,

I could not understand the execution order between `fixtures` and `setup_*` methods:

**Here is code example:**

```python
# -*- coding: utf-8 -*-

import pytest
import logging

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)


@pytest.yield_fixture(scope="class", autouse=True)
def fixture_class():
    logger.info("fixture_class")
    yield
    logger.info("finish fixture_class")


@pytest.yield_fixture(scope="module", autouse=True)
def fixture_module():
    logger.info("fixture_module")
    yield
    logger.info("finish fixture_module")


@pytest.yield_fixture(scope="session", autouse=True)
def fixture_session():
    logger.info("fixture_session")
    yield
    logger.info("finish fixture_session")


def setup_module():
    logger.info("setup module")


def teardown_module():
    logging.info("teardown module")


class TestSample:

    @classmethod
    def setup_class(cls):
        logger.info("setup class")

    @classmethod
    def teardown_class(cls):
        logger.info("teardown class")

    def setup(self):
        logger.info("setup")

    def teardown(self):
        logger.info("teardown")

    def test_ok(self):
        logger.info("test")

```

**Output:**

```
INFO:cases.test_sample:setup module
INFO:cases.test_sample:setup class
INFO:cases.test_sample:fixture_session
INFO:cases.test_sample:fixture_module
INFO:cases.test_sample:fixture_class
INFO:cases.test_sample:setup
INFO:cases.test_sample:test
INFO:cases.test_sample:teardown
INFO:cases.test_sample:finish fixture_class
INFO:cases.test_sample:teardown class
INFO:cases.test_sample:finish fixture_module
INFO:root:teardown module
INFO:cases.test_sample:finish fixture_session
```

In my opinion, the execution order is: `fixture_session` -> `setup_module` -> `fixture_module` -> `setup_class` ...

I don't undestand why the `fixture_session`/`fixture_module` was invoked after `setup_module`/`setup_class`, is this a bug?

**Comment by jacexh** [comment] 2017-07-04 10:49
pytest (3.1.1)

**Comment by RonnyPfannschmidt** [comment] 2017-07-31 12:43
currently xunit methods are managed by a different system and are not integrated with fixtures

**Comment by rsyring** [comment] 2017-10-23 03:00
I believe this is a duplicate of #517 and could be closed?

**Comment by RonnyPfannschmidt** [comment] 2017-10-23 10:52
correct, thanks for pointing out, closing as duplicate of #517

**Closed by RonnyPfannschmidt** 2017-10-23 10:52 UTC
Labels: plugin: unittest, topic: fixtures
