### ISSUE TITLE
Pytest runs tests not in --rootdir

### ISSUE THREAD

**Issue by dmtucker** [pytest-dev/pytest#7888] opened 2020-10-11 18:40 UTC
- [x] a detailed description of the bug or problem you are having

pytest finds tests not in `--rootdir` and pretends like they _are_ in `--rootdir`.

- [x] output of `pip list` from the virtual environment you are using

```
$ venv/bin/pip list
Package    Version
---------- -------
attrs      20.2.0
iniconfig  1.0.1
packaging  20.4
pip        20.2.3
pluggy     0.13.1
py         1.9.0
pyparsing  2.4.7
pytest     6.1.1
setuptools 49.2.1
six        1.15.0
toml       0.10.1
```

- [x] pytest and operating system versions

```
$ venv/bin/pytest --version
pytest 6.1.1
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 20.04 LTS
Release:	20.04
Codename:	focal
```

- [x] minimal example if possible

```
$ tree -I venv
.
├── test_fails.py
└── tests
    └── test_passes.py

1 directory, 2 files
```
```
$ cat test_fails.py 
def test_fail():
    assert False
```
```
$ cat tests/test_passes.py 
def test_pass():
    pass
```
```
$ venv/bin/pytest --rootdir tests
================================================ test session starts =================================================
platform linux -- Python 3.9.0, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /tmp/tmp.1yLQslb1qy/tests
collected 2 items                                                                                                    

tests/test_fails.py F                                                                                          [ 50%]
tests/test_passes.py .                                                                                         [100%]

====================================================== FAILURES ======================================================
_____________________________________________________ test_fail ______________________________________________________

    def test_fail():
>       assert False
E       assert False

test_fails.py:2: AssertionError
============================================== short test summary info ===============================================
FAILED tests/test_fails.py::test_fail - assert False
============================================ 1 failed, 1 passed in 0.02s =============================================
```
- `tests/test_fails.py` does not exist.
- `test_fails.py` is not in `--rootdir` and should (presumably) be ignored.
- It doesn't seem to matter whether `--rootdir` is relative or absolute.

I'm not entirely sure this is a bug since the desired effect (only ever look in `tests` without requiring explicit pytest args) can be achieved with `testpaths = tests`, but the synthesis of `tests/test_fails.py` seems unexpected.

**Comment by nicoddemus** [comment] 2020-10-17 12:15
Thanks @dmtucker,

Actually the behavior is correct, `rootdir` is not meant to be a directory where to find tests, but merely an anchor to create test node ids from.

However you are right that the terminal output is incorrect, it should probably be:

```
test_fails.py F
tests/test_passes.py .
```

IOW, related to the current directory.

**Comment by nicoddemus** [comment] 2020-10-17 12:27
*Actually* seems like yet another confusion caused by the meaning of `rootdir` today: https://github.com/pytest-dev/pytest/issues/6376.

**Comment by Zac-HD** [comment] 2023-06-20 04:47
Closing as duplicate of #6376.

**Closed by Zac-HD** 2023-06-20 04:47 UTC
Labels: type: bug, topic: reporting
