### ISSUE TITLE
pytest Cannot execute  in command line in window 7 environment

### ISSUE THREAD

**Issue by xiaobai-pan** [pytest-dev/pytest#7182] opened 2020-05-07 14:37 UTC
`pytest` cannot be executed from the command line in the Windows 7 environment，But `pytest.main` can be executed normally

Environmental information：
system：win 7
python version : 3.7.4
pytest version: 5.2.3

 Can you give some advice to deal with this problem in Windows 7?

The error message is as follows:

```
c:\User\test> pytest --version
Traceback (most recent call last):
  File "d:\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\python3\Scripts\pytest.exe\__main__.py", line 9, in <module>
  File "d:\python3\lib\site-packages\_pytest\config\__init__.py", line 71, in main
    config = _prepareconfig(args, plugins)
  File "d:\python3\lib\site-packages\_pytest\config\__init__.py", line 216, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "d:\python3\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "d:\python3\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "d:\python3\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "d:\python3\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "d:\python3\lib\site-packages\_pytest\helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "d:\python3\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "d:\python3\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "d:\python3\lib\site-packages\_pytest\config\__init__.py", line 733, in pytest_cmdline_parse
    self.parse(args)
  File "d:\python3\lib\site-packages\_pytest\config\__init__.py", line 940, in parse
    self._preparse(args, addopts=addopts)
  File "d:\python3\lib\site-packages\_pytest\config\__init__.py", line 897, in _preparse
    early_config=self, args=args, parser=self._parser
  File "d:\python3\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "d:\python3\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "d:\python3\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "d:\python3\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "d:\python3\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "d:\python3\lib\site-packages\pluggy\callers.py", line 182, in _multicall
    next(gen)  # first yield
  File "d:\python3\lib\site-packages\_pytest\capture.py", line 42, in pytest_load_initial_conftests
    _py36_windowsconsoleio_workaround(sys.stdout)
  File "d:\python3\lib\site-packages\_pytest\capture.py", line 823, in _py36_windowsconsoleio_workaround
    sys.stdin = _reopen_stdio(sys.stdin, "rb")
  File "d:\python3\lib\site-packages\_pytest\capture.py", line 816, in _reopen_stdio
    open(os.dup(f.fileno()), mode, buffering),
OSError: [WinError 87] 参数错误。

```

**Comment by asottile** [comment] 2020-05-07 19:53
hello, looks like this is an exact duplicate of #5724 -- I suspect you can fix this similar to what is suggested there, either by upgrading to python 3.7.5 or by downgrading to 3.7.3

**Closed by asottile** 2020-05-07 19:53 UTC
