### ISSUE TITLE
mocker patch string verification

### ISSUE THREAD

**Issue by aIbrar** [pytest-dev/pytest#5700] opened 2019-08-06 08:53 UTC
i often use mocker patch for my services example : 

```python
@pytest.fixture
def mock_client(mocker):
    return mocker.patch("app.actions.filename_a.client_a")


@pytest.mark.unit
def test_abc_success(mock_client):

    # when
    some_method_called("data")

    # then
    event_response = mock_client.trigger_method.call_args[0][0]
    assert event_response == "123"

```
but let's say i change the name of the file from 'filename_a' to 'filename_b', in the fixture, the test does not fail immediately, maybe because its stored in pytest cache for some time. 
Even if it's cache related the test should fail when testing on ci which is not the case.

**Comment by asottile** [comment] 2019-08-08 04:25
it fails for me, sounds like you need to delete your stale pyc files?

**Comment by majorgilles** [comment] 2019-08-08 12:56
also happens for me. note that this happen when we mock an entire imported submodule from within the tested module, not when just mocking a function defined in a single module (in this case, it crashes as expected).

it's as if the magickmock instance is registering unexisting method calls... and doesn't check the original object for the existance of such functions.

**Comment by asottile** [comment] 2019-08-08 14:46
Note that `monkeypatch` doesn't (yet) use unittest.mock (MagicMock)

**Comment by Zac-HD** [comment] 2019-11-26 03:26
Hey @albrar - I haven't been able to reproduce this - can you share an example that we could run to see the problem?

**Comment by Zac-HD** [comment] 2020-06-09 02:42
@aibrar @majorgilles - can either of you supply a self-contained reproducing example?  I haven't been able to trigger this problem, and that makes it very difficult to fix!

**Comment by Zac-HD** [comment] 2021-02-01 06:45
I'm closing this issue because we can't fix it without a reproducing example.  If anyone can provide a short script that we can run to demonstrate this error, we'll be happy to reopen the issue!

**Closed by Zac-HD** 2021-02-01 06:45 UTC
Labels: plugin: cache, plugin: monkeypatch, status: needs information

**Comment by RonnyPfannschmidt** [comment] 2021-02-01 08:29
i beleive this is about pytest-mocker not pytest to begin with
