### ISSUE TITLE
Testing of `pytest` fails with pytest plugins installed

### ISSUE THREAD

**Issue by mtelka** [pytest-dev/pytest#11401] opened 2023-09-06 14:20 UTC
I'm packaging `pytest` for OpenIndiana.  When I run tests for `pytest` I notice that testing fails if there are some `pytest` plugins installed, namely `pytest-black`, `pytest-mypy`, and `pytest-cov`.  The failure is this:
```
__________________ TestConfigFromdictargs.test_basic_behavior __________________
 
self = <test_config.TestConfigFromdictargs object at 0x7fffab105a60>
_sys_snapshot = None 

    def test_basic_behavior(self, _sys_snapshot) -> None:
        option_dict = {"verbose": 444, "foo": "bar", "capture": "no"}
        args = ["a", "b"]
    
        config = Config.fromdictargs(option_dict, args)
        with pytest.raises(AssertionError):
            config.parse(["should refuse to parse again"])
        assert config.option.verbose == 444
        assert config.option.foo == "bar"
        assert config.option.capture == "no"
>       assert config.args == args
E       AssertionError: assert ['a', 'b'] == ['a', 'b', '-...ypy', '--cov']
E         Right contains 3 more items, first extra item: '--black'
E         Full diff:
E         - ['a', 'b', '--black', '--mypy', '--cov']
E         + ['a', 'b']

testing/test_config.py:895: AssertionError
```
When I modify the test using the following patch:
```
--- pytest-7.4.1/testing/test_config.py.orig
+++ pytest-7.4.1/testing/test_config.py
@@ -886,7 +886,7 @@
         option_dict = {"verbose": 444, "foo": "bar", "capture": "no"}
         args = ["a", "b"]
 
-        config = Config.fromdictargs(option_dict, args)
+        config = Config.fromdictargs(option_dict, ["-p", "no:foobar"] + args)
         with pytest.raises(AssertionError):
             config.parse(["should refuse to parse again"])
         assert config.option.verbose == 444
```
then the test pass.

**Comment by nicoddemus** [comment] 2023-09-06 14:31
Hi @mtelka,

The test suite requires a specific testing environment, that's why we have a `tox.ini` which takes care of installing only what we expect.

We cannot realistically support a test suite which runs 100% regardless of which plugins are installed in the environment, given plugins can alter test collection/execution/reporting in many ways (that's why the plugin system is so powerful). For this reason, while  I understand where you are coming from, I'm closing this as "won't fix".

**Closed by nicoddemus** 2023-09-06 14:31 UTC

**Comment by mtelka** [comment] 2023-09-06 14:33
@nicoddemus, do you have any idea why `-p no:foobar` fixes the issue for me?  Thank you.

**Comment by nicoddemus** [comment] 2023-09-06 14:36
Hi @mtelka, at a glance no... it is weird, because `foobar` is not really a plugin... unless this is somehow leaking from a different test.

**Comment by mtelka** [comment] 2023-09-06 14:40
This is exactly my point!  It looks like there is some issue in `pytest`.  I strongly expect that the test _should_ fail with `-p no:foobar` too when it fails without it.

**Comment by nicoddemus** [comment] 2023-09-06 14:42
If you run just that test (as opposed to the full test suite), do you get the same outcome?

**Comment by mtelka** [comment] 2023-09-06 14:56
I forgot to note that `tox` is started using:
```
$ PYTEST_ADDOPTS="--verbose --color=no -p no:asyncio -p no:benchmark -p no:black -p no:checkdocs -p no:cov -p no:flaky  -p no:mypy -p no:randomly -p no:relaxed -p no:reporter -p no:salt-factories -p no:salt-factories-event-listener -p no:salt-factories-factories -p no:salt-factories-loader-mock -p no:salt-factories-log-server -p no:salt-factories-markers -p no:salt-factories-sysinfo -p no:salt-factories-sysstats -p no:tempdir -p no:xprocess " /usr/bin/tox-3.9 --current-env --no-provision --recreate -e py39 -- testing/test_config.py::TestConfigFromdictargs::test_basic_behavior
```

**Comment by The-Compiler** [comment] 2023-09-06 15:05
For what it's worth, I cannot reproduce:

```
$ python3 -m venv .venv
$ .venv/bin/pip install -q pytest-black pytest-mypy pytest-cov
$ .venv/bin/pytest testing/test_config.py::TestConfigFromdictargs::test_basic_behavior
============================= test session starts ==============================
platform linux -- Python 3.11.5, pytest-7.4.1, pluggy-1.3.0
rootdir: /home/florian/proj/pytest
configfile: pyproject.toml
plugins: cov-4.1.0, black-0.3.12, mypy-0.10.3
collected 1 item                                                               

testing/test_config.py .                                                 [100%]

============================== 1 passed in 0.15s ===============================
```

It sounds like you have something else possibly going on in your environment adding those arguments, because I don't see how simply installing those plugins would add command line arguments to the default configuration.

**Comment by mtelka** [comment] 2023-09-06 15:13
@The-Compiler, interesting.  I'm going to find what exactly makes the difference.  Thank you!

**Comment by mtelka** [comment] 2023-09-06 19:12
The problem is caused by the `pytest-enabler` plugin.  Thanks guys for help with root causing this issue.

**Comment by nicoddemus** [comment] 2023-09-06 19:21
Thanks for reporting back @mtelka.

Can you close this issue then?

**Comment by The-Compiler** [comment] 2023-09-06 19:32
@nicoddemus you closed it already 😉

**Comment by nicoddemus** [comment] 2023-09-06 19:38
Duh! 🤦

**Comment by The-Compiler** [comment] 2023-09-06 20:03
I got curious on your mystery why doing `["-p", "no:foobar"] + args` fixed the issue. It's not actually about the `-p` argument, doing `[] + args` works just as well.

The reason why the test failed is that the `Config.fromdictargs(option_dict, args)` call *mutates* the passed in `args` (because that's what `pytest-enabler` does). And then the comparison fails not because `config.args` changed, but because the *expected* value (`args`) did change:

```python
-> assert config.args == args
(Pdb) p config.args
['a', 'b']
(Pdb) p args
['a', 'b', '--black', '--mypy', '--cov']
```

By passing in `[...] + args`, you effectively copy `args`, and thus the expected value doesn't get mutated by `pytest-enabler`, but an independent list (which is not reused) does.

**Comment by mtelka** [comment] 2023-09-06 20:23
> By passing in `[...] + args`, you effectively copy `args`, and thus the expected value doesn't get mutated by `pytest-enabler`, but an independent list (which is not reused) does.

Ah, that's obvious.  But I missed it for some reason :-).  Thank you!
