### ISSUE TITLE
`flaky` is broken with `pytest` 8.1

### ISSUE THREAD

**Issue by qci-amos** [pytest-dev/pytest#12072] opened 2024-03-04 13:04 UTC
```
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/travis/miniconda/envs/env/lib/python3.11/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/home/travis/miniconda/envs/flaqumen/lib/python3.11/site-packages/flaky/flaky_pytest_plugin.py", line 5, in <module>
    from _pytest.runner import call_runtest_hook  # pylint:disable=import-error
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'call_runtest_hook' from '_pytest.runner' (/home/travis/miniconda/envs/env/lib/python3.11/site-packages/_pytest/runner.py)
```

I'm not sure if this is a duplicate of #12069 (please feel free to close if so)

but I will note that `flaky` hasn't had a new release in almost 4 years:
https://github.com/box/flaky

**Comment by RonnyPfannschmidt** [comment] 2024-03-04 13:15
indeed, closing as duplicate of #12069

**Closed by RonnyPfannschmidt** 2024-03-04 13:15 UTC

**Comment by The-Compiler** [comment] 2024-03-04 13:29
#12069 seems unrelated, `flaky` is using private APIs which happen to break. It's a duplicate of #12066, however.

Already reported here: https://github.com/box/flaky/issues/198

But given that `flaky` hasn't had a release since 2020 and hasn't had a commit for the past half year (with [nobody seeming to care](https://github.com/box/flaky/issues/192)), you're probably better off to migrating to something that's actually maintained (e.g. [pytest-rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures)).

**Comment by qci-amos** [comment] 2024-03-04 13:41
Oops, I didn't check for issues that were already closed!

I didn't know that `flaky` was no longer recommended. I'll point out it's still the first on the list that appears here:
https://docs.pytest.org/en/stable/explanation/flaky.html

what do people think about updating that documentation?

**Comment by qci-amos** [comment] 2024-03-04 14:21
I'll also note that I'm discovering that `flaky` and `pytest-rerunfailures` can't co-exist in the same python environment because they define the same mark but with different APIs.
