### ISSUE TITLE
PLEASE can someone do something about the utterly unreadable red font?

### ISSUE THREAD

**Issue by Mrodent** [pytest-dev/pytest#8852] opened 2021-07-04 06:30 UTC
#### What's the problem this feature will solve?

I cannot read the red (non-bright red) font which pytest uses. I've tried changing the background of my CLI (NB OS is W10) but this is not a very satisfactory solution.

#### Describe the solution you'd like

Just allow users to use a font, ANY font, which is actually readable for explaining a fail encountered while testing.

#### Alternative Solutions

I've tried changing the background of my CLI command prompt window. This HORRIBLE dark red font is virtually unreadable against most backgrounds

**Comment by The-Compiler** [comment] 2021-07-04 07:42
Duplicate of #6984. Note that the exact color is coming from your terminal, not from pytest - so you should be able to change it there somehow.

**Closed** 2021-07-04 07:42 UTC

**Comment by Mrodent** [comment] 2021-07-04 17:45
Yes, duplicate... um, with NO solution.

Two points: 
- 1) this is W10, and I don't think opportunities for configuring this sort of thing in the CLI ("Command Prompt", "MS-DOS window" or whatever it is called) exists in the way in does in *nix. 
- 2) somewhere in the pytest code, someone has consciously chosen this particular "colour directive" or whatever it is... Actually if you can tell me what file is involved maybe I can just dig into the thing and change it for something less absurdly illegible.

**Comment by The-Compiler** [comment] 2021-07-04 20:02
> Yes, duplicate... um, with NO solution.

That doesn't change anything about an open duplicate issue not being helpful.

> this is W10, and I don't think opportunities for configuring this sort of thing in the CLI ("Command Prompt", "MS-DOS window" or whatever it is called) exist in the way they do in *nix.

You should be able to set them in the cmd.exe properties:

![image](https://user-images.githubusercontent.com/625793/124397920-45cb4a80-dd13-11eb-827b-37a9b09de231.png)

or consider using the [new Windows terminal](https://docs.microsoft.com/en-us/windows/terminal/)

> somewhere in the pytest code, someone has consciously chosen this particular "colour directive" or whatever it is... Actually if you can tell me what file is involved maybe I can just dig into the thing and change it for something less absurdly illegible, possibly recompiling a file if I really have to...

Search for `red=True` in the code.

**Comment by Mrodent** [comment] 2021-07-05 14:28
Thanks for the heads up about what to look for.
