### ISSUE TITLE
Weird behavior when test fails on teardown on module level after another failed test in teardown.

### ISSUE THREAD

**Issue by KKoukiou** [pytest-dev/pytest#2237] opened 2017-02-06 12:29 UTC
I just stepped into this behavior for the following test:

```python
(ENV) [kkoukiou@katerina pytest]$ cat test.py 
import pytest
 
 
@pytest.fixture(scope='module')
def fix1():
    print('setup 1')
    yield
    print('teardown 1')
    raise Exception('test 1 teardown exception')
 
 
@pytest.fixture(scope='function')
def fix2():
    print('setup 2')
    yield
    print('teardown 2')
    raise Exception('test 2 teardown exception')
 
 
def test1(fix1):
    print('test 1')
 
 
def test2(fix2):
    print('test 2')
```

At the teardown of test1, which follows the teardown of test2, I get an Traceback that implies that sth is not handled correct by pytest.
Instead I would expect something like "ERROR at teardown of test1" under "ERROR" section in pytest results.
Please let me know what you think, and I can look into it more if you agree that might be a bug.
Bellow follows the Traceback I get with this test execution.

ps: I ran against master branch.

```bash
(ENV) [kkoukiou@katerina pytest]$ py.test test.py -s
============================================================================ test session starts ============================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.7.dev0, py-1.4.32, pluggy-0.4.0
rootdir: /home/kkoukiou/repos/pytest, inifile: tox.ini
collected 2 items 

test.py setup 1
test 1
.setup 2
test 2
.teardown 2
Eteardown 1
Traceback (most recent call last):
  File "/home/kkoukiou/repos/pytest/ENV/bin/py.test", line 11, in <module>
    load_entry_point('pytest==3.0.7.dev0', 'console_scripts', 'py.test')()
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/config.py", line 57, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/main.py", line 127, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/main.py", line 122, in wrap_session
    exitstatus=session.exitstatus)
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/terminal.py", line 358, in pytest_sessionfinish
    outcome.get_result()
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 280, in get_result
    _reraise(*ex)  # noqa
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/runner.py", line 56, in pytest_sessionfinish
    session._setupstate.teardown_all()
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/runner.py", line 425, in teardown_all
    self._pop_and_teardown()
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/runner.py", line 398, in _pop_and_teardown
    self._teardown_with_finalization(colitem)
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/runner.py", line 416, in _teardown_with_finalization
    self._callfinalizers(colitem)
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/runner.py", line 413, in _callfinalizers
    py.builtin._reraise(*exc)
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/runner.py", line 406, in _callfinalizers
    fin()
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/fixtures.py", line 755, in finish
    func()
  File "/home/kkoukiou/repos/pytest/ENV/lib/python2.7/site-packages/pytest-3.0.7.dev0-py2.7.egg/_pytest/fixtures.py", line 713, in teardown
    next(it)
  File "/home/kkoukiou/repos/pytest/test.py", line 9, in fix1
    raise Exception('test 1 teardown exception')
Exception: test 1 teardown exception
```

**Comment by nicoddemus** [comment] 2017-02-08 23:37
Hey @KKoukiou thanks for the report.

> Please let me know what you think, and I can look into it more if you agree that might be a bug.

This is definitely a bug. I can reproduce the issue even using `request.addfinalizer`, so it is not related to yield fixtures. If you want to investigate that would be great!

**Comment by kchomski-reef** [comment] 2017-10-26 15:14
Just want to make sure - should desired output from `pytest` look like this:
```bash
======================== test session starts ========================
platform linux2 -- Python 2.7.12, pytest-3.2.4.dev42+g0b540f9.d20171026, py-1.4.34, pluggy-0.4.0 -- /home/kris/.virtualenvs/pytest-dev/bin/python
cachedir: .cache
rootdir: /home/kris/projects/pytest, inifile: tox.ini
collected 2 items                                                    

t.py::test1 setup 1
test 1
PASSEDteardown 1

t.py::test1 ERROR
t.py::test2 setup 2
test 2
PASSEDteardown 2

t.py::test2 ERROR

============================== ERRORS ===============================
____________________ ERROR at teardown of test1 _____________________

    @pytest.fixture(scope='function')
    def fix1():
        print('setup 1')
        yield
        print('teardown 1')
>       raise Exception('test 1 teardown exception')
E       Exception: test 1 teardown exception

t.py:9: Exception
____________________ ERROR at teardown of test2 _____________________

    @pytest.fixture(scope='function')
    def fix2():
        print('setup 2')
        yield
        print('teardown 2')
>       raise Exception('test 2 teardown exception')
E       Exception: test 2 teardown exception

t.py:17: Exception
================= 2 passed, 2 error in 0.02 seconds =================
```
?

**Comment by KKoukiou** [comment] 2017-10-26 15:42
@kchomski-reef almost ;)

You mixed the scope for fix1.
Should be 
``` bash
...
============================== ERRORS ===============================
____________________ ERROR at teardown of test1 _____________________

@pytest.fixture(scope='module')
def fix1():
...
```

Also since fixture fix1 has scope module it should execute its finalizer after all tests in the module finish.
So expected output in the first section would be:

``` bash
test.py::test1 setup 1
 test 1
PASSED
test.py::test2 setup 2
test 2
PASSEDteardown 2
test.py::test2 ERROR
teardown 1
test.py::test1 ERROR
```

Thanks for interest!
JFYI I was not able to solve it easily so I didn't proceed with handling this issue.

**Comment by kchomski-reef** [comment] 2017-10-27 14:35
I've tested various combinations and problem occurs when `fix1` and `fix2` have following scopes:

`fix1` scope |` fix2` scope
----------------|----------------
`module` | `function`
`module` | `class`
`module` | `session`
`session` | `function`
`session` | `class`
`session` | `module`

Notice, that if both scopes are the same (e.g. `module` - `module` or `session` - `session`) then everything works fine.

I've tried to debug this, but I have rather hard time finding where this issue could originate from.

@nicoddemus, @RonnyPfannschmidt and hints where to start looking?

**Comment by tikon93** [comment] 2018-03-16 10:21
Have somebody workarounds to avoid this issue? 
The only idea I got is to catch all of exceptions at fixtures with scope higher than function, but I don't think that it's good enough - I may loose some usefull information.

**Comment by KKoukiou** [comment] 2018-03-16 10:52
@tikon93 unfortunately I don't have WA.

**Comment by bluetech** [comment] 2020-09-12 12:09
This is the output for me:

```
collected 2 items                                                                                                                                                            

test.py::test1 setup 1
test 1
PASSED
test.py::test2 setup 2
test 2
PASSEDteardown 2
teardown 1

test.py::test2 ERROR

=================================================================================== ERRORS ===================================================================================
_________________________________________________________________________ ERROR at teardown of test2 _________________________________________________________________________

    @pytest.fixture(scope='function')
    def fix2():
        print('setup 2')
        yield
        print('teardown 2')
>       raise Exception('test 2 teardown exception')
E       Exception: test 2 teardown exception

test.py:17: Exception
========================================================================== short test summary info ===========================================================================
ERROR test.py::test2 - Exception: test 2 teardown exception
========================================================================= 2 passed, 1 error in 0.07s =========================================================================
```

This seems correct to me. Here `test2` errors due to the teardown exception in `fix2`. If I comment `test2` then `test1` errors due to the teardown exception in `fix1` which is now getting attached to it rather than `test2`.

So closing, please submit a new issue if you see undesirable behavior regarding this.

**Closed by bluetech** 2020-09-12 12:09 UTC
Labels: topic: reporting, type: bug
