### ISSUE TITLE
 pytest version 3.10.1 Fails on python2.7

### ISSUE THREAD

**Issue by henrykironde** [pytest-dev/pytest#4333] opened 2018-11-07 23:21 UTC
python2.7.14/lib/python2.7/site-packages/_pytest/stepwise.py", line 102, in pytest_sessionfinish
    self.config.cache.set("cache/stepwise", [])
AttributeError: 'Config' object has no attribute 'cache'

ref: https://travis-ci.org/weecology/retriever/jobs/451239186

checklist:

- [x] Include a detailed description of the bug or suggestion
- [x] `pip list` of the virtual environment you are using
- [x] pytest and operating system versions
- [x] Minimal example if possible

**Comment by blueyed** [comment] 2018-11-07 23:32
> AttributeError: 'Config' object has no attribute 'cache'

Appears to be a duplicate of https://github.com/pytest-dev/pytest/issues/4304.

**Closed by blueyed** 2018-11-07 23:32 UTC
