### ISSUE TITLE
Way to isolate tests from existing environment variables?

### ISSUE THREAD

**Issue by simonvanderveldt** [pytest-dev/pytest#4226] opened 2018-10-24 16:23 UTC
It could be I've missed something but I've done quiet a bit of searching and it seems there's no out of the box/default way of isolating tests from the environment variables from the calling environment.
Is this something that could be added or was this a conscious design decision?

As a workaround I currently do this in `conftest.py`, which works, though I'm not sure how much I'm abusing the system by doing this :P
```
def pytest_addhooks(pluginmanager):
    os.environ = {}
```

And as an extension of this it would be nice if there would be a way to have this isolation and allow one to globally override/set environment variables before discovery/importing happens, to allow easy testing of modules that make use of environment variables at module level. This sounds similar to https://github.com/pytest-dev/pytest/issues/3597
I'd currently do that using:
```
def pytest_addhooks(pluginmanager):
    os.environ = {"FOO": "bar"}
```
I guess a more specific hook one could add to `conftests.py` that runs before module discovery/import might be one way to enable something like this.

**Comment by blueyed** [comment] 2018-10-24 16:31
JFI: typically CI systems ensure this by design, and tox can also be used for this (where you have to explicitly use `passenv`).

**Comment by nicoddemus** [comment] 2018-10-24 19:17
IMHO environment isolation is done better by an external tool than adding this to pytest itself, because it is hard to do it correctly from within pytest.

**Comment by blueyed** [comment] 2018-10-24 21:30
Agreeing with @nicoddemus, and closing.

**Closed by blueyed** 2018-10-24 21:30 UTC
Labels: type: question

**Comment by RonnyPfannschmidt** [comment] 2018-10-25 09:45
replacing os.environ is pretty much fundamentally broken and you are lucky if things didn't blow up ^^

**Comment by simonvanderveldt** [comment] 2018-10-25 10:03
@RonnyPfannschmidt Do you have any more info on what exactly is fundamentally broken?

**Comment by RonnyPfannschmidt** [comment] 2018-10-25 10:08
@simonvanderveldt `os.environ` is a instance of a private mapping class that maps to the underlying c functions that set/get environment variables

shadowing it with random python data structures just hides away access to the actual data that will still affect subprocesses and c libraries and in addition it breaks expectations for quite a few things out there

**Comment by RonnyPfannschmidt** [comment] 2018-10-29 20:04
@simonvanderveldt i strongly suggest to limit this hack as intensely as possible - its a really good starting point for unexpected failures
