### ISSUE TITLE
warn about tests returning any non-None value

### ISSUE THREAD

**Issue by graingert** [pytest-dev/pytest#5735] opened 2019-08-12 18:31 UTC
Currently there's a warning for coroutine functions (async def) but not for

`twisted.internet.defer.inlineCallbacks`, where the only way to tell is the fact that the test returned a deferred

- [ ] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

**Comment by Zac-HD** [comment] 2020-09-26 12:42
Closing as a duplicate of #7337 - while that issue is considerably newer, it also has the consensus plan to warn (and eventually error) on non-None return values :slightly_smiling_face:

**Closed by Zac-HD** 2020-09-26 12:42 UTC
Labels: topic: reporting, type: enhancement
