### ISSUE TITLE
--durations=0 + pytest-html reports each test twice

### ISSUE THREAD

**Issue by clemente0420** [pytest-dev/pytest#10278] opened 2022-09-07 08:14 UTC
JAVA_HOME | /opt/jdk1.8.0_121
-- | --
Packages | {"pluggy": "1.0.0", "py": "1.11.0", "pytest": "7.1.2"}
Platform | Linux-4.14.0_1-0-0-48-x86_64-with-glibc2.17
Plugins | {"html": "3.1.1", "metadata": "2.0.2", "subprocess": "1.4.1", "timeout": "2.1.0"}
Python | 3.8.13

![image](https://user-images.githubusercontent.com/32806348/188826671-a172aa04-a129-4105-80b4-32efcbf723a3.png)

**Comment by nicoddemus** [comment] 2022-09-07 12:16
Closing as duplicate of https://github.com/pytest-dev/pytest/issues/8042. Reproducible example is welcome.

**Closed by nicoddemus** 2022-09-07 12:16 UTC
