### ISSUE TITLE
Loggers of tests ran in parallel pollute each others, making my logger tests flicker

### ISSUE THREAD

**Issue by guillaume-chevalier** [pytest-dev/pytest#10062] opened 2022-06-21 15:18 UTC
### Problem: 

It appears that the logs of another test pollute the logger of one test. 

### A detailed description of the bug or problem: 
- I run test A at the same time as test B. 
- In test B, I do an assertion on the length of the logs. 
- Test B flickers due to capturing test A's logs. Moreover, the LogRecords (lines of logs) logged by test B appears multiple times, which furthermore confused me while debugging the test. 

### The output of `pip list` from the virtual environment. 

Note that the whole output is not shown. See at least this: 

```
joblib                       1.1.0
coverage                     6.0.2
pytest                       7.1.1
pytest-cov                   3.0.0
pytest-forked                1.3.0
pytest-profiling             1.7.0
pytest-verbose-parametrize   1.7.0
pytest-xdist                 2.4.0
virtualenv                   20.13.3
wheel                        0.37.0
```

### Pytest and operating system versions

- pytest 7.1.1
- Mac OS M1 Monterey 12.4
- Python 3.9.7

### Minimal code example if possible

Here is my code example where I can reproduce the bug, although that depends on how many other tests are logging things to the logs in parallel:
- [Test A](https://github.com/Kimoby/Neuraxle/blob/2faa6770b76f5a50ab00f5e82951d3e5394f662b/testing_neuraxle/test_context_logger.py#L196)
- [Test B](https://github.com/Kimoby/Neuraxle/blob/2faa6770b76f5a50ab00f5e82951d3e5394f662b/testing_neuraxle/test_streaming.py#L433)

Here is a preview of the error in Test B, where the logs of Test A are clearly captured where it should not: 
```
        # Then
        log_history = list(CX().logger)
        n_calls = int(len(GIVEN_INPUTS) / minibatch_size) * 3
        # TODO: fix the fact that sometimes logs are duplicated quite a lot of times in the history.
        # assert len(log_history) == n_calls, log_history
        shortened_log_history = [e[:e.index('#') + 1] for e in set(log_history) if "logging call" in e]
>       assert len(shortened_log_history) == n_calls, log_history
E       AssertionError: ['Testing root.', 'Testing a.', 'Testing b.', '2 - transform call - logging call #0 with UUID=b11547d8-c4bd-4ad8-9001-...5d-43b1-b5fb-1dfc219214a7', '2 - transform call - logging call #0 with UUID=78ef8fed-1518-4118-88ea-21817064fb8d', ...]
E       assert 12 == 6
```

**Comment by Zac-HD** [comment] 2022-06-25 06:36
Can you please provide a https://stackoverflow.com/help/minimal-reproducible-example ?

**Comment by RonnyPfannschmidt** [comment] 2022-06-25 09:39
this looks like a 3rd party logging framework needs to be set up for worker separation, which was not done in the related code

my first impression is that this is a test setup bug, not a pytest bug

**Comment by RonnyPfannschmidt** [comment] 2022-07-11 14:11
closing as likely a downstream issue, based on a quick skim of the downstream logger code there is likely nothing pytest can do about it, the logger needs to get fixed

**Closed by RonnyPfannschmidt** 2022-07-11 14:11 UTC
Labels: status: needs information, plugin: logging
