### ISSUE TITLE
[YANKED] pytest 8.1.0 removes many deprecations, but not mentioned in changelog

### ISSUE THREAD

**Issue by mr-c** [pytest-dev/pytest#12069] opened 2024-03-04 11:18 UTC
https://github.com/pytest-dev/pytest/pull/11757 is not mentioned as a breaking change for the Pytest 8.1.0 Release in https://docs.pytest.org/en/stable/changelog.html ; it breaks plugins who were still supporting the older signature.

I'm opening this issue as a hint to others; is it possible to update the changelog after a release?

**Comment by RonnyPfannschmidt** [comment] 2024-03-04 11:22
this is a duplicate of #12068 

the removal process itself is as intended, the oversight was that warnings of certain hooks where not displayed as expected

leaving this open for now to help people
the fact that it wasn't failing on 8.0 is the actual bug

**Comment by bluetech** [comment] 2024-03-04 14:39
@RonnyPfannschmidt @nicoddemus since we botched the deprecation, perhaps we should revert the removal until we can have at least one release with proper deprecation?

**Comment by RonnyPfannschmidt** [comment] 2024-03-04 14:44
should we yank 8.1 for the deprecation issues?

**Comment by RonnyPfannschmidt** [comment] 2024-03-04 14:45
lets defer the return of code a bit as i'd like to know first how to trigger the errors

**Comment by nicoddemus** [comment] 2024-03-04 14:47
I think it is fair to postpone the removals if we did not issue the proper warnings, as we vouch to do before any removals took place.

Those removals would then have to be postponed to 9.0/9.1 then.

Not sure if you folks would like to yank 8.1? Seems reasonable.

**Comment by bluetech** [comment] 2024-03-04 14:53
Reverting + releasing 8.1.1 should not be a problem, but if @RonnyPfannschmidt wants to avoid a revert, let's yank as it seems to be causing a lot of failures.

**Comment by RonnyPfannschmidt** [comment] 2024-03-04 15:01
lets yank and revert then

**Comment by nicoddemus** [comment] 2024-03-04 15:12
I'm yanking it.

**Comment by nicoddemus** [comment] 2024-03-04 15:13
![image](https://github.com/pytest-dev/pytest/assets/1085180/c83eaeb3-95a5-42df-92fb-96e0868cea2e)

**Comment by bluetech** [comment] 2024-03-04 15:15
Thanks @nicoddemus!

@RonnyPfannschmidt do you want me to revert the removal, or do you want to?

**Comment by nicoddemus** [comment] 2024-03-04 15:16
Opening PR to update the CHANGELOG.

**Comment by mr-c** [comment] 2024-03-04 15:55
Dear maintainers and devs, thank you for all that you do and the quick response! 💖

**Comment by nicoddemus** [comment] 2024-03-05 20:37
> @RonnyPfannschmidt do you want me to revert the removal, or do you want to?

Just to make sure we are all on the same page, is anybody working on the revert?

**Comment by RonnyPfannschmidt** [comment] 2024-03-05 23:04
Apologies, I was hoping to get to it, but I won't be able to Touch it this week

**Comment by jgraichen** [comment] 2024-03-06 09:50
Please note that yanking the release now broke all pipelines, workflows, lock files for everyone else too even for these where v8.1.0 worked fined. It would have been nicer to revert the changes and release a new fixed version (e.g. 8.1.1).

**Comment by bluetech** [comment] 2024-03-06 10:52
@jgraichen how did it break?

**Comment by RonnyPfannschmidt** [comment] 2024-03-06 11:17
As per specification,it ought to be ignored unless it's strictly pinned

I fail to see how this creates failure outside of something deliberately counter acting the tooling

Are you aware of a concrete case?

**Comment by jgraichen** [comment] 2024-03-06 11:21
@RonnyPfannschmidt Every project that bumps constraint ranges e.g. to `=~8.1.0`. See https://github.com/jgraichen/salt-tower/pull/83 as one public example.

**Comment by nicoddemus** [comment] 2024-03-06 13:07
> Please note that yanking the release now broke all pipelines, workflows, lock files for everyone else too even for these where v8.1.0 worked fined. It would have been nicer to revert the changes and release a new fixed version (e.g. 8.1.1).

I was under the impression that yanking was safe, meant exactly to not break those pinning the project... But I understand this would break users if somebody updated their manifests to `>=8.1.0`.

**Comment by edgarrmondragon** [comment] 2024-03-06 14:38
fwiw all my (poetry) packages that dependabot bumped to 8.1.0 in the lock file have no problem installing that version

**Comment by sigma67** [comment] 2024-03-07 09:36
It is common practice in dependency update managers to  bump the lower bound, so yanking is not a good idea imo. 

It's probably better to leave the release up - if it breaks things, people will notice in their pipelines anyway.

**Comment by RonnyPfannschmidt** [comment] 2024-03-07 11:09
It seems the common practice is broken

Opportunistic bump of lower bounds is fatal

Lower bound should bump on feature needs

**Comment by nicoddemus** [comment] 2024-03-07 11:24
I'm a bit surprise by this practice of updating lower bounds automatically too.

Regardless, we will not revert the yank at this point -- it will only cause even more confusion.

We hope to get a new 8.1.1 soon, I will try to reserve some time later today to revert the removal of the deprecated features.

**Comment by nicoddemus** [comment] 2024-03-07 11:28
But in retrospect we probably should not have yanked the release. 

Yanking should be used only in situations where the released package is broken/unusable, when (almost) every installation of the package will break the environment and/or runtime. In this case we only broke some plugins, but users not using those plugins were unaffected.

Live and learn I guess.

**Closed** 2024-03-08 23:06 UTC

**Comment by RonnyPfannschmidt** [comment] 2024-03-09 14:46
I still hold the opinion that yanking a release that enacts breakages whose warning where missing is a correct course of action

However I wasn't aware of wrongly overzealous compatibility pins, so in future I'll ensure a quick fix in the affected line is available for affected Parties

**Comment by sigma67** [comment] 2024-03-09 19:44
The problem isn't just overzealous bumping, there's more to the issue. Another aspect:

Many Python package managers like `poetry`, `pdm` and `pip-compile` have some sort of locking/pinning these days.

If you have set `pytest>=7` in your `pyproject.toml`, the package manager will lock the latest version of that package when you create or update the lockfile.

If you hapepn to have locked & merged a during the timeframe a (later yanked) release was available, all your CI and local project installs will later break when the release is yanked, because it is no longer available.

I guess that's another reason why it should be avoided unless the package is completely broken anyway. Obviously not blaming anyone here -- these kinds of issues are far from obvious.

**Comment by nicoddemus** [comment] 2024-03-09 21:51
@bluetech is correct AIFAK: yanking is not removing, the package is still available if you explicitly ask for it, for example:

```
λ pip install pytest==8.1.0
Collecting pytest==8.1.0
  Using cached pytest-8.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting iniconfig (from pytest==8.1.0)
  Using cached iniconfig-2.0.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: packaging in .\.env310\lib\site-packages (from pytest==8.1.0) (23.2)
Collecting pluggy<2.0,>=1.4 (from pytest==8.1.0)
  Using cached pluggy-1.4.0-py3-none-any.whl.metadata (4.3 kB)
Collecting exceptiongroup>=1.0.0rc8 (from pytest==8.1.0)
  Using cached exceptiongroup-1.2.0-py3-none-any.whl.metadata (6.6 kB)
Collecting tomli>=1 (from pytest==8.1.0)
  Using cached tomli-2.0.1-py3-none-any.whl.metadata (8.9 kB)
Collecting colorama (from pytest==8.1.0)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
WARNING: The candidate selected for download or install is a yanked version: 'pytest' candidate (version 8.1.0 at https://files.pythonhosted.org/packages/5a/4a/3f626e3974bea1e6d471bd86f7965c67cd06d5770d1fec9aae445c44da7b/pytest-8.1.0-py3-none-any.whl (from https://pypi.org/simple/pytest/) (requires-python:>=3.8))
Reason for being yanked: See https://github.com/pytest-dev/pytest/issues/12069
Using cached pytest-8.1.0-py3-none-any.whl (335 kB)
Using cached exceptiongroup-1.2.0-py3-none-any.whl (16 kB)
Using cached pluggy-1.4.0-py3-none-any.whl (20 kB)
Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Installing collected packages: tomli, pluggy, iniconfig, exceptiongroup, colorama, pytest
Successfully installed colorama-0.4.6 exceptiongroup-1.2.0 iniconfig-2.0.0 pluggy-1.4.0 pytest-8.1.0 tomli-2.0.1
```

Even though `8.1.0` was yanked, locked dependencies should be fine then.

**Comment by edgarrmondragon** [comment] 2024-03-09 22:09
Yup, I can confirm that poetry-locked yanked dependencies install just fine and merely emit a warning

**Comment by iurisilvio** [comment] 2024-03-10 11:06
Is it expected to `8.1.1` proper warn about the deprecation?

The [pytest-ruff ](https://github.com/businho/pytest-ruff/blob/41ec4c4cc327aa3c5f86f466025dc53bee29304d/pytest_ruff/__init__.py#L29)don't trigger any deprecation warning. I don't know if it is expected or if I have to test it better.

**Comment by bluetech** [comment] 2024-03-10 11:35
@iurisilvio No, we still need to work on fixing the deprecation.

**Comment by bluetech** [comment] 2024-03-10 11:36
But you can test with the yanked 8.1.0 for now, if it works you're clear :smile:

**Comment by iurisilvio** [comment] 2024-03-10 12:40
Thanks! I'll test with 8.1.0!

**Comment by bwoodsend** [comment] 2024-03-10 14:09
8.1.1 didn't revert all the removals, right? [The `_pytest.runner.call_runtest_hook` removal](https://github.com/box/flaky/issues/198) is still waiving at me insistently using pytest 8.1.1.

**Comment by nicoddemus** [comment] 2024-03-10 14:23
No, we only reverted those two removals:

* [fspath argument for Node constructors replaced with pathlib.Path](https://docs.pytest.org/en/stable/deprecations.html#node-ctor-fspath-deprecation)
* [py.path.local arguments for hooks replaced with pathlib.Path](https://docs.pytest.org/en/stable/deprecations.html#legacy-path-hooks-deprecated).

The rationale being that we were not warning about those deprecations.

`call_runtest_hook` was never deprecated because it was an internal API, which we do not guarantee stability across releases.

>  I guess it gets the well what did you expect? treatment.

Well perhaps not being so harsh, but yes, we reserve the right to break those when we improve the internal code.
