### ISSUE TITLE
py.test interferes the system import behavior

### ISSUE THREAD

**Issue by peter-wangxu** [pytest-dev/pytest#2290] opened 2017-03-06 06:37 UTC
When I setting up my Windows CI, I found a wired behavior introduced by py.test:
https://ci.appveyor.com/project/peter-wangxu/storops/build/1.0.44/job/v8g69v09o5brrkow

After some debugging, I figured out that, py.test mock the system library `Queue` in `c:\python27\Lib\Queue.py`

Here is test run by `unittest`:
```python
(py27) C:\OpenStack\storops>python -m unittest storops_test.lib.test_tasks.TestPQueue
> c:\openstack\storops\.tox\py27\lib\site-packages\persistqueue\queue.py(15)<module>()
-> print(sys.path)
(Pdb) dir(sys.modules['Queue']
*** SyntaxError: unexpected EOF while parsing (<stdin>, line 1)
(Pdb) dir(sys.modules['Queue'])
['Empty', 'Full', 'LifoQueue', 'PriorityQueue', 'Queue', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '_threading', '_time', 'deque', 'heapq']
(Pdb) import Queue
(Pdb) dir(Queue)
['Empty', 'Full', 'LifoQueue', 'PriorityQueue', 'Queue', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '_threading', '_time', 'deque', 'heapq']
```

while stopping in tests triggered by pytest:

```python
(Pdb) sys.modules['Queue']
<module 'Queue' from 'c:\python27\Lib\Queue.py'>
(Pdb) import Queue
(Pdb) dir(Queue)
['@py_builtins', '@pytest_ar', 'Queue', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '_time', 'os', 'pdb', 'pickle', 'sys', 'tempfile', 'threading']
(Pdb) Queue.__file__
'c:\\openstack\\storops\\.tox\\py27\\lib\\site-packages\\persistqueue\\Queue.py'
(Pdb) c
```

You can see, `import Queue` actually imported the `Queue` class from current `Queue.py`, and fininally cause error below:
```python
ImportError while importing test module 'C:\OpenStack\storops\storops_test\lib\test_tasks.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
storops_test\lib\test_tasks.py:23: in <module>
    from persistqueue import Empty
.tox\py27\lib\site-packages\persistqueue\__init__.py:8: in <module>
    from Queue import Empty, Full
.tox\py27\lib\site-packages\persistqueue\Queue.py:16: in <module>
    from Queue import Empty, Full
E   ImportError: cannot import name Empty
```
OS: windows 10
python: python 2.7.13
pytest: 3.0.6

Is this a py.test bug or function as design?

Thanks
Peter

**Comment by nicoddemus** [comment] 2017-03-09 22:54
How are you setting up your environment so pytest can pick your package?

At first glance it doesn't appear to be a pytest problem, but it is hard to say without looking at your configuration (your appveyor link is private btw).

**Comment by peter-wangxu** [comment] 2017-03-10 01:55
sorry, I disabled the windows CI after found this issue. 

Here is my PR which triggered the issue: https://github.com/emc-openstack/storops/pull/98/files

to reproduce, you can clone the ``https://github.com/emc-openstack/storops`` and checkout `add_windows_ci` branch,

run `tox - e py27`,  then you will see the issue.

Please use **python2.7.13** and on **Windows**.

Thanks
Peter

**Comment by nicoddemus** [comment] 2017-03-10 02:32
Thanks,

I'm having trouble reproducing this though. After creating a virtual environment for Python 2.7.13, `pip install tox`, `tox -e py27` produces:

```

Processing x:\storops\.tox\dist\storops-0.4.7.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\bruno\appdata\local\temp\pip-vjyoas-build\setup.py", line 91, in <module>
        install_requires=read_requirements('requirements.txt'),
      File "c:\users\bruno\appdata\local\temp\pip-vjyoas-build\setup.py", line 52, in read_requirements
        with open(filename) as f:
    IOError: [Errno 2] No such file or directory: u'requirements.txt'
```

**Comment by peter-wangxu** [comment] 2017-03-10 03:09
Please include following

```
include *.txt
```
in MANIFEST.in
and then run tox

**Comment by nicoddemus** [comment] 2017-03-10 11:42
The branch seems to [have been deleted](https://github.com/emc-openstack/storops/branches).

**Comment by peter-wangxu** [comment] 2017-03-10 15:55
I just workaround the bug by upgrade the related package [persist-queue](https://github.com/peter-wangxu/persist-queue) to 0.1.6.

Please modify the ``tox.ini`` of storops, and set ``persist-queue==0.1.4``

and run ``tox -e py27`` in storops root to reproduce it.

**Comment by nicoddemus** [comment] 2017-03-10 16:00
I saw the commit which fixes this, using `from .queue import Queue` is the recommended solution because you might get `Queue` from the standard library depending from where you run your code.

I'm closing this for now since you already have a working solution, and IMHO is not a workaround but the proper approach. 👍

**Closed by nicoddemus** 2017-03-10 16:00 UTC
Labels: needs information, question
