### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 298-307: character maps to <undefined>

### ISSUE THREAD

**Issue by dickreuter** [pytest-dev/pytest#5161] opened 2019-04-24 12:49 UTC
When I set log_cli=True I get this error:

```

2019-04-24 13:34:14,8581 (UTC+01:00)] INFO  - >     runtestprotocol(item, nextitem=nextitem)

[2019-04-24 13:34:14,8581 (UTC+01:00)] INFO  - >   File "E:\tc1\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\_pytest\runner.py", line 93, in runtestprotocol

[2019-04-24 13:34:14,8581 (UTC+01:00)] INFO  - >     reports.append(call_and_report(item, "call", log))

[2019-04-24 13:34:14,8581 (UTC+01:00)] INFO  - >   File "E:\tc1\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\_pytest\runner.py", line 177, in call_and_report

[2019-04-24 13:34:14,8591 (UTC+01:00)] INFO  - >     hook.pytest_runtest_logreport(report=report)

[2019-04-24 13:34:14,8591 (UTC+01:00)] INFO  - >   File "E:\tc1\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\pluggy\hooks.py", line 289, in __call__

[2019-04-24 13:34:14,8591 (UTC+01:00)] INFO  - >     return self._hookexec(self, self.get_hookimpls(), kwargs)

[2019-04-24 13:34:14,8591 (UTC+01:00)] INFO  - >   File "E:\tc1\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\pluggy\manager.py", line 68, in _hookexec

[2019-04-24 13:34:14,8601 (UTC+01:00)] INFO  - >     return self._inner_hookexec(hook, methods, kwargs)

[2019-04-24 13:34:14,8601 (UTC+01:00)] INFO  - >   File "E:\tc1\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\pluggy\manager.py", line 62, in <lambda>

[2019-04-24 13:34:14,8611 (UTC+01:00)] INFO  - >     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,

[2019-04-24 13:34:14,8621 (UTC+01:00)] INFO  - >   File "E:\tc1\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\pluggy\callers.py", line 208, in _multicall

[2019-04-24 13:34:14,8621 (UTC+01:00)] INFO  - >     return outcome.get_result()

[2019-04-24 13:34:14,8621 (UTC+01:00)] INFO  - >   File "E:\tc1\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\pluggy\callers.py", line 80, in get_result

[2019-04-24 13:34:14,8621 (UTC+01:00)] INFO  - >     raise ex[1].with_traceback(ex[2])

[2019-04-24 13:34:14,8631 (UTC+01:00)] INFO  - >   File "E:\tc1\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\pluggy\callers.py", line 187, in _multicall

[2019-04-24 13:34:14,8631 (UTC+01:00)] INFO  - >     res = hook_impl.function(*args)

[2019-04-24 13:34:14,8641 (UTC+01:00)] INFO  - >   File "E:\tc1\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\teamcity\pytest_plugin.py", line 205, in pytest_runtest_logreport

[2019-04-24 13:34:14,8641 (UTC+01:00)] INFO  - >     self.report_test_output(report, test_id)

[2019-04-24 13:34:14,8641 (UTC+01:00)] INFO  - >   File "E:\tc1\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\teamcity\pytest_plugin.py", line 156, in report_test_output

[2019-04-24 13:34:14,8651 (UTC+01:00)] INFO  - >     self.teamcity.testStdErr(test_id, out=chunk, flowId=test_id)

[2019-04-24 13:34:14,8651 (UTC+01:00)] INFO  - >   File "E:\tc1\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\teamcity\messages.py", line 134, in testStdErr

[2019-04-24 13:34:14,8651 (UTC+01:00)] INFO  - >     self.message('testStdErr', name=testName, out=out, flowId=flowId)

[2019-04-24 13:34:14,8651 (UTC+01:00)] INFO  - >   File "E:\tc1\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\teamcity\messages.py", line 68, in message

[2019-04-24 13:34:14,8651 (UTC+01:00)] INFO  - >     self.output.write(self.encode(message))

[2019-04-24 13:34:14,8661 (UTC+01:00)] INFO  - >   File "E:\tc1\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\teamcity\messages.py", line 39, in encode

[2019-04-24 13:34:14,8661 (UTC+01:00)] INFO  - >     value = value.encode(self.encoding)

[2019-04-24 13:34:14,8661 (UTC+01:00)] INFO  - >   File "E:\tc1\work\win-na-x64-release\py3\mre_venv3\lib\encodings\cp1252.py", line 12, in encode

[2019-04-24 13:34:14,8661 (UTC+01:00)] INFO  - >     return codecs.charmap_encode(input,errors,encoding_table)

[2019-04-24 13:34:14,8671 (UTC+01:00)] INFO  - > UnicodeEncodeError: 'charmap' codec can't encode characters in position 298-307: character maps to <undefined>
```

**Comment by asottile** [comment] 2019-04-25 23:14
this seems to be coming from the teamcity pytest plugin, I'd suggest reporting there:

```

[2019-04-24 13:34:14,8641 (UTC+01:00)] INFO  - >   File "E:\tc1\work\win-na-x64-release\py3\mre_venv3\lib\site-packages\teamcity\pytest_plugin.py", line 156, in report_test_output

[2019-04-24 13:34:14,8651 (UTC+01:00)] INFO  - >     self.teamcity.testStdErr(test_id, out=chunk, flowId=test_id)
```

**Comment by nicoddemus** [comment] 2019-05-01 14:27
Closing for now, will be happy to reopen if the cause is narrowed down to pytest itself.

**Closed by nicoddemus** 2019-05-01 14:27 UTC
Labels: status: needs information
