### ISSUE TITLE
Test in class, pytest.mark is invalid in subclassed

### ISSUE THREAD

**Issue by landhu** [pytest-dev/pytest#9015] opened 2021-08-18 07:44 UTC
- [ ] Test in class, pytest.mark is invalid in subclassed
- [ ] output of `pip list` from the virtual environment you are using
     none
- [ ] pytest and operating system versions
   Python 3.8.8, pytest-5.4.3, py-1.10.0, pluggy-0.13.1  win10
- [ ] minimal example if possible
    `import pytest

@pytest.mark.slow
class TestA():

    def test_1(self):
        print('xxxx')

    def test_2(self):
        print('uyyyy')

@pytest.mark.demo
class TestB(TestA):

    pass`
- [Result ]
   pytest  -m slow pytest_learn.py --co
     `collected 4 items                                                                                                                                                       
<Module pytest_learn.py>
  <Class TestA>
      <Function test_1>
      <Function test_2>
  <Class TestB>
      <Function test_1>
      <Function test_2>`

**Not Correct!!!**

pytest  -m demo pytest_learn.py --co
 `collected 4 items / 2 deselected / 2 selected                                                                                                                           
<Module pytest_learn.py>
  <Class TestB>
      <Function test_1>
      <Function test_2>`

**It's OK!!**

Why using slow mark collected 4 items??

**Comment by RonnyPfannschmidt** [comment] 2021-08-18 10:02
Marks on classes inherit

 having them pass over is the expected behaviour

**Comment by nicoddemus** [comment] 2021-08-18 11:41
Closing as working as intended. 👍

**Closed by nicoddemus** 2021-08-18 11:41 UTC

**Comment by landhu** [comment] 2021-08-20 01:34
> Marks on classes inherit
> 
> having them pass over is the expected behaviour

Sorry, I dont get it. How can I modify the testcases use by class.

**Comment by nicoddemus** [comment] 2021-08-20 02:29
Not sure I follow, can you please elaborate?
