### ISSUE TITLE
Warning due to PEP660 editable packages

### ISSUE THREAD

**Issue by fschulze** [pytest-dev/pytest#10235] opened 2022-08-22 09:22 UTC
The recently added PEP660 support for editable package installs seems to interfere with assert rewriting. I get the following warning:

``PytestAssertRewriteWarning: Module already imported so cannot be rewritten: __editable__...``

This seems to be caused by the new ``__editable__*`` files in ``site-packages``.

If I install the editable packages with ``--no-use-pep517`` the ``__editable__*`` files aren't generated and the warnings are gone.

**Comment by RonnyPfannschmidt** [comment] 2022-08-22 12:35
closing as dupe of #10230 , which is easy to miss as the same

**Closed by RonnyPfannschmidt** 2022-08-22 12:35 UTC

**Comment by fschulze** [comment] 2022-08-22 18:00
I actually saw that and didn't realize it has the same cause.
