### ISSUE TITLE
AssertionRewritingHook does not obey sys.path order

### ISSUE THREAD

**Issue by Pastafarianist** [pytest-dev/pytest#1220] opened 2015-12-03 17:48 UTC
The same code imports modules from different locations when it runs under `python` and under `py.test`.

`code.py`:

```python
def foo():
   return 1
   
def test_foo():
   assert foo() == 1
   print ("Test OK.")
   
if __name__ == "__main__":
    test_foo()
```

`test_foo.py`:

```python
import code
print("code.py imported from: %s" % code.__file__)

import sys
print("sys.meta_path: %r" % sys.meta_path)
print("sys.path: %r" % sys.path)

from code import foo
   
def test_foo():
   assert foo() == 1
   print ("Test OK.")
   
if __name__ == "__main__":
    test_foo()
```

Output of `python test_foo.py`:

```
$ python test_foo.py 
code.py imported from: /home/pastafarianist/code.py
sys.meta_path: [<class '_frozen_importlib.BuiltinImporter'>, <class '_frozen_importlib.FrozenImporter'>, <class '_frozen_importlib.PathFinder'>]
sys.path: ['/home/pastafarianist', '/usr/lib64/python34.zip', '/usr/lib64/python3.4', '/usr/lib64/python3.4/plat-linux', '/usr/lib64/python3.4/lib-dynload', '/home/pastafarianist/.local/lib64/python3.4/site-packages', '/usr/lib64/python3.4/site-packages']
Test OK.
```

Output of `py.test test_foo.py`:

```
$ py.test test_foo.py 
========================================== test session starts ==========================================
platform linux -- Python 3.4.3, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/pastafarianist, inifile: 
plugins: hypothesis-1.12.0
collected 0 items / 1 errors 

================================================ ERRORS =================================================
_____________________________________ ERROR collecting test_foo.py ______________________________________
test_foo.py:8: in <module>
    from code import foo
E   ImportError: cannot import name 'foo'
-------------------------------------------- Captured stdout --------------------------------------------
code.py imported from: /usr/lib64/python3.4/code.py
sys.meta_path: [<_pytest.assertion.rewrite.AssertionRewritingHook object at 0x7f26b2171fd0>, <class '_frozen_importlib.BuiltinImporter'>, <class '_frozen_importlib.FrozenImporter'>, <class '_frozen_importlib.PathFinder'>]
sys.path: ['/home/pastafarianist', '/usr/lib64/python-exec/python3.4', '/usr/lib64/python34.zip', '/usr/lib64/python3.4', '/usr/lib64/python3.4/plat-linux', '/usr/lib64/python3.4/lib-dynload', '/home/pastafarianist/.local/lib64/python3.4/site-packages', '/usr/lib64/python3.4/site-packages']
======================================== 1 error in 0.02 seconds ========================================

**Comment by nicoddemus** [comment] 2015-12-03 23:23
Thanks for the report!

**Comment by RedBeardCode** [comment] 2016-07-15 04:48
I had a look a the issue and tried to figure out the problem. In my opinion the problem is that pytest itself imports the builtin `code` module in the debugging plugin. So it is a naming problem. The name `code` is already used in the namespace.
The same problem can be created with all module names which are already imported by pytest before the test file is imported. And this are many.
So I think solving this problem would be a really big deal because you should hide the namespace which is created by pytest. I think this doesn't make sense.
May suggestion is to close the issues `as designed`

**Comment by flub** [comment] 2016-07-15 08:13
@RedBeardCode Yeah, your analysis sounds right.  In general it's not a good idea to name modules with the same name as in the stdlib.  This is just standard import behaviour and nothing we can do much about afaik.

**Comment by flub** [comment] 2016-07-15 08:14
@RedBeardCode thanks for digging into this!

**Closed by flub** 2016-07-15 08:13 UTC
Labels: bug
