### ISSUE TITLE
pytest --pdb execute test cases which otherwise are skipped

### ISSUE THREAD

**Issue by gst** [pytest-dev/pytest#2137] opened 2016-12-14 00:00 UTC
Hi,

using pytest 3.0.5 (and xdist (1.15) + cov plugins (2.3.1)), under linux : 

reproduce steps : 

`18:58 $ cat test_pytest_pdb_skip.py `
```
import platform

import unittest2 as unittest


@unittest.skipIf(platform.system() != 'Windows', 'This test need to be run on Windows!')
class MyTestCase(unittest.TestCase):

    def test_one(self):
        self.assertTrue(False)
```

this is ok :
`pytest -xv  test_pytest_pdb_skip.py`

this is not ok : the test is executed and here obviously fail
`pytest --pdb -xv  test_pytest_pdb_skip.py`

**Comment by nicoddemus** [comment] 2016-12-14 00:51
Thanks for the report!

This is a side effect of #1890, because now the skip machinery for `unittest.TestCase` tests is not reached when `--pdb` is given in the command line ([`unittest.py:155`](https://github.com/pytest-dev/pytest/blob/master/_pytest/unittest.py#L155)):

```python
    def runtest(self):
        if self.config.pluginmanager.get_plugin("pdbinvoke") is None:
            self._testcase(result=self)
        else:
            # disables tearDown and cleanups for post mortem debugging (see #1890)
            self._testcase.debug()
```

Have to think about a proper fix for this, we probably need to handle other types of failures as well (such as `unexpectedSuccess`). Perhaps @mbyt can chime in?

**Comment by mbyt** [comment] 2017-01-31 03:55
Thanks for reporting - and yes, that's definitely a regression.

@nicoddemus, sorry for being late. I looked into this and proposed a possible solution in #2225.

**Closed** 2017-02-08 23:23 UTC
Labels: unittest
