### ISSUE TITLE
Annotation based fixtures

### ISSUE THREAD

**Issue by jaryn** [pytest-dev/pytest#7690] opened 2020-08-26 17:35 UTC
There is a possibility to leverage the python annotation system to implement very modular and structured fixtures. I hope the following illustrates the draft of the idea.

```python
from typing import Callable
from dataclasses import dataclass

## Somewhere in the pytest internals would be:

def satisfy_the_annotations(f: Callable):
    sig = inspect.signature(f)
    params = sig.bind(**{n: satisfy_the_annotations(p.annotation)
                         for n, p in sig.parameters.items()})
    return f(*params.args, **params.kwargs)

def run_test(f: Callable):
    retval = satisfy_the_annotations(f)
    return "PASSED"


## In the file with the tests:        
@dataclass
class Name:
    val: int = 0
    def __init__(self):
        self.__class__.val += 1
        self.val = self.__class__.val

@dataclass
class Surname:
    pass

@dataclass
class Fixture:
    name: Name
        
@dataclass
class ExtendedFixture(Fixture):
    surname: Surname
    pass
    
def test_function_with_annotations(somefixture: Fixture,
                                   otherfixture: Fixture,
                                   extended: ExtendedFixture,
                                   aaa="ddd"):
    print(somefixture, otherfixture, extended, aaa)
    assert isinstance(somefixture.name, Name)

    
run_test(test_function_with_annotations)
```

**Comment by graingert** [comment] 2020-08-26 18:11
@jaryn I definitely want FastAPI or similar DI based fixtures!

Closing as duplicate of https://github.com/pytest-dev/pytest/issues/3834#issuecomment-675545958

**Closed by graingert** 2020-08-26 18:11 UTC
