### ISSUE TITLE
Pytest 3.3.0 crashes with ModuleNotFoundError: No module named '_pytest._pluggy' with pytest-metadata installed

### ISSUE THREAD

**Issue by ceridwen** [pytest-dev/pytest#2965] opened 2017-11-28 19:24 UTC
The full traceback, after I call `pytest --version`:

```
Traceback (most recent call last):
  File "/usr/local/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/_pytest/config.py", line 50, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/lib/python3.6/site-packages/_pytest/config.py", line 160, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/usr/local/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 196, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.6/site-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/config.py", line 942, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python3.6/site-packages/_pytest/config.py", line 1107, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/local/lib/python3.6/site-packages/_pytest/config.py", line 1070, in _preparse
    self.pluginmanager.load_setuptools_entrypoints('pytest11')
  File "/usr/local/lib/python3.6/site-packages/pluggy/__init__.py", line 397, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/usr/local/lib/python3.6/site-packages/pytest_metadata/plugin.py", line 8, in <module>
    import _pytest._pluggy as pluggy
ModuleNotFoundError: No module named '_pytest._pluggy'
```

If I uninstall pytest-html and pytest-metadata (the former requires the latter), pytest no longer crashes.

Pytest is running with CPython 3.6.3 inside a Docker container on top of Alpine Linux.  

```
uname -a
Linux f6802de4d8a3 4.9.49-moby #1 SMP Wed Sep 27 23:17:17 UTC 2017 x86_64 Linux
```

```
pip list
attrs (17.3.0)
boltons (17.1.0)
cachetools (2.0.1)
certifi (2017.11.5)
chardet (3.0.4)
ConfigArgParse (0.12.0)
decorator (4.1.2)
dictdiffer (0.7.0)
docker (2.6.1)
docker-pycreds (0.2.1)
dpath (1.4.0)
google-auth (1.2.1)
idna (2.6)
ipaddress (1.0.18)
Jinja2 (2.10)
jsonschema (2.6.0)
kubernetes (3.0.0)
MarkupSafe (1.0)
networkx (2.0)
openshift (0.3.4)
pip (9.0.1)
pluggy (0.6.0)
plumbum (1.6.4)
py (1.5.2)
pyasn1 (0.4.2)
pyasn1-modules (0.2.1)
pytest (3.3.0)
pytest-html (1.16.0)
pytest-metadata (1.5.0)
python-dateutil (2.6.1)
python-string-utils (0.6.0)
PyYAML (3.12)
requests (2.18.4)
rsa (3.4.2)
ruamel.yaml (0.15.34)
setuptools (36.6.0)
six (1.11.0)
swagger-parser (1.0.0)
swagger-spec-validator (2.1.0)
urllib3 (1.22)
websocket-client (0.40.0)
wheel (0.30.0)
```

**Comment by blueyed** [comment] 2017-11-28 19:28
Duplicate of https://github.com/pytest-dev/pytest/issues/2960.

**Closed by blueyed** 2017-11-28 19:28 UTC
