### ISSUE TITLE
UnicodeDecodeError from pytest if object representation contains non-ascii, utf8 encoded, characters

### ISSUE THREAD

**Issue by magopian** [pytest-dev/pytest#877] opened 2015-07-25 07:55 UTC
Given the following test code:
```python
    def test_foobar(self):
        class Foo(object):
            name = u'é'

            def __repr__(self):
                return self.name.encode('utf8')

        foo = Foo()
        assert not foo
```

Running it gives

```
Traceback (most recent call last):
  File "/Users/mathieu/olympia/apps/addons/tests/test_models.py", line 529, in test_foobar
    assert not foo
  File "/Users/mathieu/.virtualenvs/olympia/lib/python2.7/site-packages/_pytest/assertion/util.py", line 33, in format_explanation
    return u('\n').join(result)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
```

`result` is `['assert not \xc3\xa9']`. I believe that python's default encoding used to decode from str to unicode is `ascii`, which fails while decoding the utf-8 encoded object representation.

**Comment by alvinchow86** [comment] 2015-09-13 02:33
i'm seeing this issue too. FYI this is a duplicate of https://github.com/pytest-dev/pytest/issues/678

**Closed** 2015-09-22 09:17 UTC
Labels: unicode

**Comment by alvinchow86** [comment] 2015-09-22 18:50
@RonnyPfannschmidt I did a similar fix here https://github.com/pytest-dev/pytest/compare/master...doordash:unicode-fix?expand=1, but I recall having to also fix some things in `_format_lines()` as well.
