### ISSUE TITLE
IOERROR

### ISSUE THREAD

**Issue by EtheriousNatsu** [pytest-dev/pytest#2937] opened 2017-11-18 10:50 UTC
os: windows10
pytest: 3.2.3

![image](https://user-images.githubusercontent.com/12187260/32979504-535bdcb4-cc91-11e7-9a6d-74c471186399.png)

![image](https://user-images.githubusercontent.com/12187260/32979510-5d437af2-cc91-11e7-83be-22c01c2285ec.png)

![image](https://user-images.githubusercontent.com/12187260/32979514-6435da94-cc91-11e7-94cc-125eca307e34.png)

**Comment by The-Compiler** [comment] 2017-11-18 11:56
Can you please show `pip freeze`? Also, can you reproduce this with a minimal testfile outside of that project? If not, is this project available publicly?

**Comment by EtheriousNatsu** [comment] 2017-11-18 12:31
here is pip freeze:


E:\WorkSpace\test_app_channel>pip freeze
alabaster==0.7.10
Appium-Python-Client==0.25
astroid==1.5.3
autopep8==1.3.3
Babel==2.5.1
backports.functools-lru-cache==1.4
certifi==2017.7.27.1
chardet==3.0.4
colorama==0.3.9
configparser==3.5.0
coverage==4.4.1
decorator==4.1.2
docutils==0.14
enum34==1.1.6
extras==1.0.0
fire==0.1.2
fixtures==3.0.0
flake8==2.5.5
funcsigs==1.0.2
hacking==1.0.0
html==1.16
humanize==0.5.1
idna==2.6
imagesize==0.7.1
isort==4.2.15
Jinja2==2.9.6
jsonpath-rw==1.4.0
jsonpath-rw-ext==1.1.2
lazy-object-proxy==1.3.1
linecache2==1.0.0
MarkupSafe==1.0
mccabe==0.2.1
mock==2.0.0
olefile==0.44
pbr==3.1.1
pep8==1.5.7
pexpect==4.3.0
Pillow==4.3.0
ply==3.10
progress==1.3
ptyprocess==0.5.2
py==1.4.34
pycodestyle==2.3.1
pyflakes==0.8.1
Pygments==2.2.0
pylint==1.7.4
PyMySQL==0.7.11
pytest==3.2.3
pytest-cov==2.5.1
pytest-html==1.16.0
pytest-metadata==1.5.0
python-mimeparse==1.6.0
python-subunit==1.2.0
pytz==2017.3
PyYAML==3.12
requests==2.18.4
retrying==1.3.3
robotframework==3.0.2
robotframework-databaselibrary==1.0.1
robotframework-ride==1.5.2.1
selenium==3.7.0
singledispatch==3.4.0.3
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.6.5
sphinxcontrib-websupport==1.0.1
testrepository==0.0.20
testtools==2.3.0
traceback2==1.4.0
typing==3.6.2
uiautomator==0.3.2
uiautomator2==0.0.1.dev47
unittest2==1.1.0
urllib3==1.22
wd==1.0.0
wrapt==1.10.11
wsgi-intercept==1.5.1
xmlrunner==1.7.7

**Comment by EtheriousNatsu** [comment] 2017-11-18 12:37
here is my code:

[test_app_channel.zip](https://github.com/pytest-dev/pytest/files/1484575/test_app_channel.zip)

**Comment by nicoddemus** [comment] 2017-11-18 12:59
I created a virtual environment and installed the dependencies from your post using pip, but I get this error when I run it:

```
{env27} C:\pytest\.tmp\test_app [console-progress-2657]>python -m pytest
Traceback (most recent call last):
  File "C:\pytest\.tmp\test_app\.env27\lib\site-packages\_pytest\config.py", line 379, in _importconftest
    mod = conftestpath.pyimport()
  File "C:\pytest\.tmp\test_app\.env27\lib\site-packages\py\_path\local.py", line 662, in pyimport
    __import__(modname)
  File "C:\pytest\.tmp\test_app\.env27\lib\site-packages\_pytest\assertion\rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "C:\pytest\.tmp\test_app\.env27\lib\site-packages\py\_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "C:\pytest\.tmp\test_app\conftest.py", line 19, in <module>
    from lib.utils import apk_list
  File "C:\pytest\.tmp\test_app\lib\utils.py", line 27, in <module>
    apk_list = get_apk()
  File "C:\pytest\.tmp\test_app\lib\utils.py", line 22, in get_apk
    raise RuntimeError("{0} has not apk file".format(Config.APK_DIR))
RuntimeError: C:\pytest\.tmp\test_app\build has not apk file
ERROR: could not load C:\pytest\.tmp\test_app\conftest.py
```

**Comment by The-Compiler** [comment] 2017-11-18 13:05
This looks like https://github.com/tartley/colorama/issues/101 - I'm not sure there's something pytest can do about this.

**Comment by nicoddemus** [comment] 2017-11-18 13:06
@The-Compiler nice, thanks for the link.

@EtheriousNatsu you can disable colors by passing `--color=no` to `pytest` as a workaround.

**Comment by EtheriousNatsu** [comment] 2017-11-24 01:21
OK，thank you, I will try

**Comment by nicoddemus** [comment] 2018-01-18 20:17
Closing for now; we will be happy to re-open this if needed.

**Closed by nicoddemus** 2018-01-18 20:17 UTC
Labels: status: needs information
