### ISSUE TITLE
Use automatic CHANGELOG management

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#2390] opened 2017-05-04 12:28 UTC
As suggested by @RonnyPfannschmidt, we want to adopt an automatic CHANGELOG file management to remove/reduce merge conflicts due to changes in the CHANGELOG file (which are quite common).

[towncrier](https://github.com/hawkowl/towncrier) has been suggested as a good tool for this.

Here's what's needed:

* Configure `towncrier` according to the instructions in its README;
* Update instructions in `CONTRIBUTING.rst` related to the CHANGELOG;
* Update instructions in `.github/PULL_REQUEST_TEMPLATE.md`;

Ideally we should tackle this right after the upcoming `3.1` release.

@RonnyPfannschmidt, you mentioned you wanted to do this?

**Comment by RonnyPfannschmidt** [comment] 2017-05-04 13:49
@nicoddemus correct

**Comment by nicoddemus** [comment] 2017-05-04 13:50
Nice. I suggest we also adopt `invoke` to have well named tasks in place. You could introduce `invoke` and the first new task, `generate_news` or so (similar to what pip does in https://github.com/pypa/pip/blob/master/tasks/generate.py).

**Comment by RonnyPfannschmidt** [comment] 2017-05-04 13:53
@nicoddemus we first have to agree on some formatting tho - if we keep doing changelogs as is towncrier as is will be a pain

**Comment by nicoddemus** [comment] 2017-05-04 13:59
Looking at pip's changelog, the only difference I see is the fact that it doesn't generate links to the issues; that could be suggested upstream or even contributed by us.

If that's the only reason, I'm not against just using towncrier as is; I think switching to towncrier will be a huge maintenance improvement for us, so it out weights this small drawback.

**Comment by fschulze** [comment] 2017-05-04 14:08
We looked into towncrier for devpi and it was too opinionated for us. Your milage may vary. I'm currently throwing together an alternative after I didn't find anything else that matches what we would like.

**Comment by RonnyPfannschmidt** [comment] 2017-05-04 14:09
@nicoddemus hence wanting to agree on formatting, not open up big cans of worm

**Comment by RonnyPfannschmidt** [comment] 2017-05-04 14:10
@fschulze, can you show me where it was too opinionated?

**Comment by nicoddemus** [comment] 2017-05-04 14:19
I looked at pip's [`NEWS.rst`](https://github.com/pypa/pip/blob/master/NEWS.rst) file and it looks good to me. I would like to contribute linking the issues automatically though, but I'm fine with starting using it now and enjoying the links later.

**Comment by nicoddemus** [comment] 2017-05-04 14:19
> can you show me where it was too opinionated?

I'm curious as well. 😁

**Comment by fschulze** [comment] 2017-05-04 15:41
Turns out, it was just lacking documentation. After I looked again into how pip uses towncrier, I found the ``title_format`` and ``template`` options, which allow me to remove the opinionated stuff. Now there is only a small bug preventing towncrier to work with the ``template`` option on Python 3.x. Reporting it ...

**Comment by fschulze** [comment] 2017-05-04 15:50
And the issue is already fixed in 17.4.0 https://github.com/hawkowl/towncrier/commit/c48a58f5da8ad88bb6c2768a1f0faf0c34f0f892

**Comment by nicoddemus** [comment] 2017-05-22 22:44
@RonnyPfannschmidt with `3.1.0` being out, now it would be a good time to tackle this! 👍

**Closed** 2017-05-30 15:41 UTC
