### ISSUE TITLE
No way to create FixtureRequest without deprecation warning.

### ISSUE THREAD

**Issue by cjw296** [pytest-dev/pytest#8832] opened 2021-06-30 06:24 UTC
As of pytest 6.2.0, pytest now emits numerous warnings when you have a plugin that needs to requests fixtures: https://github.com/cjw296/sybil/issues/29

How should a plugin such as Sybil be requesting fixtures now?

Here's the current code: 
https://github.com/cjw296/sybil/blob/master/sybil/integration/pytest.py#L58

**Comment by The-Compiler** [comment] 2021-06-30 06:32
Using fixtures in any custom way is (unfortunately) one big area of pytest which isn't really exposed publicly to plugins at all. As evident by `self.session._fixturemanager` you're accessing private pytest API there, so those warnings are indeed correct.

I wish we had a better story to make fixtures on a low level accessible to plugins (it's certainly something a project at work would need to, and many others), but from what I've seen so far, there's a lot of internal cleanup to be done until that's possible.

**Comment by cjw296** [comment] 2021-06-30 06:52
So, have I got this right? pytest has introduced a bunch of noisy deprecation warnings without any possibility for people experiencing them to do anything about them?

Would it perhaps make sense to remove those deprecation warnings until such time as an alternative has been provided?

**Comment by The-Compiler** [comment] 2021-06-30 07:02
That entirely depends on the project. Not using pytest fixtures that way might be a viable solution for some.

Personally I'm -0.5 on removing the deprecation warnings - if you're using pytest internals, you will need to keep up even with patch releases of pytest, so having to silence a deprecation warning is probably the least of your problems.

**Comment by bluetech** [comment] 2021-06-30 07:03
The idea is to let you know the API you are using is private, which in practice means that pytest doesn't document it, and it is liable to break on a feature release.

However, you can shut up the deprecation warning by using `FixtureRequest(item, _ispytest=True)`. By this you are explicitly opting in and acknowledging that you understand that the API is not public.

I fully expected some plugins would set this. The idea is not to prevent plugins from doing creative things with pytest internals, just to make pytest itself have some chance of being improved internally.

When using `_ispytest=True`, I'd recommend testing against pytest `main` occasionally if possible -- this way if something breaks, you'll be notified ahead of time and have a chance to fix it before it affects your users.

**Comment by bluetech** [comment] 2021-06-30 07:05
Note: for `FixtureRequest` in particular, `_ispytest` was added in pytest 6.2, so you'll want to pass it only since that version if you support older pytests.

**Comment by cjw296** [comment] 2021-06-30 07:10
The lack of consideration for plugin developers is really quite frustrating.
Requesting fixtures doesn't feel like the most unusual thing for a plugin to need to do and the constantly shifting sands aren't at all helpful.

> The idea is to let you know the API you are using is private, which in practice means that pytest doesn't document it, and it is liable to break on a feature release.

I already know this API is private, I only use it because there is no other option. All this has done is add a bunch of noise for end users of pytest and sybil, which I now have to work around with [yet more fragile and unnecessary code](https://github.com/cjw296/sybil/blob/94a878e5d53c7eba218bf01cf8c328ec9f7cb7b8/sybil/integration/pytest.py#L43-L58).

How about avoiding this noise unless a public and supported alternative is being provided in its place?

**Comment by bluetech** [comment] 2021-06-30 07:29
>  I mean, I would be much more sympathetic if this was a step along the way to a public api, but I'm struggling to see any upside of these changes in 6.2; what am I missing?

We are working on demarcating public API and private API, even for plugins. I hope you can see why it is hard maintaining a library and adding new features and APIs without such a distinction.

**Comment by The-Compiler** [comment] 2021-06-30 07:31
The reason it was introduced as part of #7469 is because we started exposing the class as `pytest.FixtureRequest`, to use in type annotations for the `request` fixture.

However, the class now being reachable via `pytest.FixtureRequest` rather than the internal `_pytest.fixtures.FixtureRequest` could give the impression that it's part of pytest's public API - however, that's not the case, hence the warning to make that clear.

Like said above, I fully agree that it'd be beneficial to officially expose fixture mechanics to plugins in a supported way - I'm not sure how's that "lack of consideration for plugin developers". I'd expect an issue about that being open already even, but it's a rather hard thing to search for.

However, the reality we live in is that pytest's fixture mechanics are one of the most entangled (and probably oldest?) parts of pytest's internal code, and very few people feel like they understand what's going on there. It'd be great if it could be cleaned up and exposed as a plugin API (being the probably biggest part of pytest's internals not exposed yet), but I don't expect that to happen before we can get together in a physical [development sprint](https://blog.pytest.org/2016/pytest-development-sprint/) once again and clean internals up first.

You decided to do things which aren't officially supported. When accessing private API, changes in it are something to be expected. Dishing out your frustration about doing something unsupported at other open source maintainers is neither helpful in any way, nor productive.

**Comment by cjw296** [comment] 2021-06-30 07:31
Perhaps you could do that in such a way as to not cause unnecessary work for plugin maintainers?
Maybe comments, or an internal decorator, or some kind of audit mode?

**Comment by RonnyPfannschmidt** [comment] 2021-06-30 08:49
@cjw296 thats certainly thinkable, but currently its only in part doable due to lack of manpower and time on the core team

also plugins that actively use internal private apis have to accept some extra churn - its hard enough to keep the external api reasonably working - adding those to the internals is simply overstretch it as we are primarily volunteer driven atm

there are some considerations for doing something else in near future to create more dedicated engineering time for pytest,
but its yet to be discussed among the core devs

**Comment by The-Compiler** [comment] 2021-06-30 09:09
Even with more development resources we shouldn't aim to keep pytest internals backwards compatible - this is why they are internals in the first place. Making everything public and stable means very little wiggle room for changing things, which means less development no matter how many resources there are.

IMHO, the problem here clearly isn't "pytest isn't considering plugin developers who access pytest internals" (that's on them, they're internals for a reason), the problem is "there's no plugin API for low-level fixture access/customization".

**Comment by bluetech** [comment] 2023-07-14 08:04
I'll close this as there are no actionable items (for better plugin API for fixtures it will be better to open a different issue).

**Closed by bluetech** 2023-07-14 08:04 UTC
Labels: type: proposal, topic: fixtures
