### ISSUE TITLE
py.test reports IndexError/KeyError as an Failure instead of Error

### ISSUE THREAD

**Issue by ycui** [pytest-dev/pytest#2156] opened 2016-12-21 22:14 UTC
- [ ] Include a detailed description of the bug or suggestion
py.test reports IndexError/KeyError as an Failure instead of Error, same file run by nosetest and unittest runner report as Error

- [ ] `pip list` of the virtual environment you are using
$ python2.7 -m pip list
cffi (1.9.1)
cryptography (1.7.1)
enum34 (1.1.6)
idna (2.1)
ipaddress (1.0.17)
paramiko (2.1.1)
pip (8.1.2)
py (1.4.29)
pyasn1 (0.1.9)
pycparser (2.17)
pytest (2.7.2)
setuptools (25.0.1)
six (1.9.0)
wheel (0.29.0)

- [ ] pytest and operating system versions
This is pytest version 2.7.2

- [ ] Minimal example if possible
http://stackoverflow.com/questions/41272327/py-test-reporting-indexerror-keyerror-as-a-failure-instead-of-error

Not sure if this is my user error, or an issue, or a design difference, pls help to clarify, thanks for your help.

**Comment by nicoddemus** [comment] 2016-12-22 02:30
Posted [an answer in the stackoverflow thread](http://stackoverflow.com/questions/41272327/py-test-reporting-indexerror-keyerror-as-a-failure-instead-of-error/41274925#41274925), but in short the current behavior is by design and not a bug.

Worth mentioning again [pytest-finer-verdicts](https://github.com/rvprasad/pytest-finer-verdicts) written by @rvprasad. 😁 

Closing this for now, feel free to post other questions though.

**Closed by nicoddemus** 2016-12-22 02:30 UTC
