### ISSUE TITLE
Type Error using patch decorator for 7.0.0rc1

### ISSUE THREAD

**Issue by rohitsheth** [pytest-dev/pytest#9414] opened 2021-12-15 19:41 UTC
```
    @patch("packge.class.method")
    def setup(self, mock_method):
```
The mentioned method is with decorated @staticmethod

Error 

```
    @wraps(func)
    def patched(*args, **keywargs):
        with self.decoration_helper(patched,
                                    args,
                                    keywargs) as (newargs, newkeywargs):
>           return func(*newargs, **newkeywargs)
E           TypeError: setup() takes 2 positional arguments but 3 were given

.eggs/mock-4.0.3-py3.6.egg/mock/mock.py:1346: TypeError

```

When I use pytest 6.2.5 I do not see this error. This error happens when using pytest 7.+

**Package   Version**     
coverage 5.6b1
pytest 7.0.0rc1     
pytest-cov 2.11.1
PyHamcrest 2.0.2
mock 4.0.3  
tomli 1.2.3

OS: Linux 14.04.6 LTS, Trusty Tahr
Python: Python 3.6.8

Note: Truncated details due to limitations on what I can share about the code and packages.
I can answer further questions if this information is unsufficient.

Quick check-list while reporting bugs:

- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

**Comment by The-Compiler** [comment] 2021-12-16 14:39
It'd be good to have a minimal, complete reproducer demonstrating the issue - I was able to cook one up though:

issue9414.py:

```python
class Cls:

    @staticmethod
    def meth():
        pass
```

`test_9414.py`:

```python
from unittest.mock import patch

class TestNothing:

    @patch("issue9414.Cls.meth")
    def setup(self, mock_method):
        pass

    def test_x(self):
        pass
```

---

Bisected to 89f0b5b5a2f485f77999d15cb9437ad9234003a1 from #9273 ("nose: fix class- and module-level fixture behavior"), cc @bluetech

**Comment by bluetech** [comment] 2021-12-16 15:20
@rohitsheth Thanks for testing the rc!

The method name `setup` has a special meaning in test classes - see https://docs.pytest.org/en/latest/how-to/nose.html. Pytest 7.0 has some fixes in this area which make the patching fail, but technically the conflict also exists in previous versions.

You can fix the problem either by using a different name, or by disabling the nose compatibility by passing `-p no:nose` to pytest (can also be added to `addopts` config).

**Comment by The-Compiler** [comment] 2021-12-16 16:17
I think that was the intention here though: Having some kind of special `setup` method which does some patching, no?

**Comment by rohitsheth** [comment] 2021-12-16 20:50
Yes, the intention was to have a special `setup` method. 
I do have a workaround by changing the name, thank you for the link. 
Additionally, thank you adding complete reproducible code, I couldn't share mine due to work limitations.

**Comment by bluetech** [comment] 2021-12-16 21:35
I'm closing for #9391 because it's the same underlying issue.

**Closed by bluetech** 2021-12-16 21:35 UTC
Labels: type: regression, plugin: nose
