### ISSUE TITLE
pytest 5.0.0 complains about pytest -ra

### ISSUE THREAD

**Issue by mgedmin** [pytest-dev/pytest#5558] opened 2019-07-05 07:34 UTC
I have a `pytest.ini` with

```ini
[pytest]
addopts = -ra
```

This stopped working when I upgraded pytest to version 5.0.0.  Now any invocation, inluding `pytest --help` fails with

```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -ra
  inifile: /home/mg/src/check-python-versions/pytest.ini
  rootdir: /home/mg/src/check-python-versions
```

Changing the option to `-r a` makes pytest happy again.

Is this an intentional change?  If so, it would be nice to update https://docs.pytest.org/en/latest/changelog.html to mention it.  (It's probably related to the ~~parting~~ parsing changes not to accept shortened versions of long options, but `-r` is not a long option.)

**Comment by nicoddemus** [comment] 2019-07-05 11:11
Hi @mgedmin,

This is a duplicate of https://github.com/pytest-dev/pytest/issues/5523, which has been fixed already and will be available in `5.0.1`, which I'm about to release. 👍

**Closed by nicoddemus** 2019-07-05 11:11 UTC
