### ISSUE TITLE
[Docs] Broken Warning URL to the latest stable version

### ISSUE THREAD

**Issue by kchomski** [pytest-dev/pytest#7444] opened 2020-07-03 10:42 UTC
Hi guys!

URL in the online documentation warning is broken:
<kbd>![warning](https://user-images.githubusercontent.com/5850999/86460991-9fc4b900-bd29-11ea-98e7-a079b459cb87.png)</kbd>

After clicking:
<kbd>![page_not_found](https://user-images.githubusercontent.com/5850999/86461015-aa7f4e00-bd29-11ea-99ed-6c7df669a37b.png)</kbd>

It points to `https://docs.pytest.org/en/latest/5.4.3/xunit_setup.html` instead of `https://docs.pytest.org/en/5.4.3/xunit_setup.html` - the `latest` part is not needed.

<kbd>![working](https://user-images.githubusercontent.com/5850999/86461408-414c0a80-bd2a-11ea-8fbc-cc9f640c1ca1.png)</kbd>

**Comment by nicoddemus** [comment] 2020-07-06 23:21
Thanks @kchomski!

Closing as duplicate of https://github.com/pytest-dev/pytest/issues/7331. 👍

**Closed by nicoddemus** 2020-07-06 23:21 UTC
