### ISSUE TITLE
AttributeError: 'str' object has no attribute 'iter_parents'

### ISSUE THREAD

**Issue by orestk-adorama** [pytest-dev/pytest#12067] opened 2024-03-04 11:01 UTC
pytest-allure fails with pytest version 8.1.0

Error traceback:
```self = <allure_pytest.listener.AllureListener object at 0x000001E0979AE360>
item = <Function test_shipping_charged[CreditCard]>

    @pytest.hookimpl(hookwrapper=True)
    def pytest_runtest_setup(self, item):
        if not self._cache.get(item.nodeid):
            uuid = self._cache.push(item.nodeid)
            test_result = TestResult(name=item.name, uuid=uuid, start=now(), stop=now())
            self.allure_logger.schedule_test(uuid, test_result)
        yield
>       self._update_fixtures_children(item)

venv\Lib\site-packages\allure_pytest\listener.py:88:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
venv\Lib\site-packages\allure_pytest\listener.py:63: in _update_fixtures_children
    for fixturedef in _test_fixtures(item):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

item = <Function test_shipping_charged[CreditCard]>

    def _test_fixtures(item):
        fixturemanager = item.session._fixturemanager
        fixturedefs = []

        if hasattr(item, "_request") and hasattr(item._request, "fixturenames"):
            for name in item._request.fixturenames:
>               fixturedefs_pytest = fixturemanager.getfixturedefs(name, item.nodeid)
E               AttributeError: 'str' object has no attribute 'iter_parents'

venv\Lib\site-packages\allure_pytest\listener.py:303: AttributeError
```
Pip list:
```
> pip list
Package                  Version
------------------------ -----------
allure-pytest            2.12.0
allure-python-commons    2.12.0
appdirs                  1.4.4
attrs                    23.2.0
Authlib                  1.3.0
Avalara                  23.11.0
beautifulsoup4           4.12.3
bs4                      0.0.2
cachetools               5.3.2
certifi                  2023.11.17
cffi                     1.16.0
charset-normalizer       3.3.2
colorama                 0.4.6
cryptography             42.0.1
cssselect                1.2.0
deepdiff                 6.3.1
deepmerge                1.1.1
ecdsa                    0.18.0
execnet                  2.0.2
fake-useragent           1.4.0
google-api-core          2.16.0
google-auth              2.27.0
google-cloud-core        2.4.1
google-cloud-firestore   2.14.0
google-cloud-pubsub      2.19.0
googleapis-common-protos 1.62.0
grpc-google-iam-v1       0.13.0
grpcio                   1.60.0
grpcio-status            1.60.0
h11                      0.14.0
idna                     3.6
importlib-metadata       7.0.1
iniconfig                2.0.0
isodate                  0.6.1
lxml                     5.1.0
ordered-set              4.1.0
outcome                  1.3.0.post0
packaging                23.2
parse                    1.20.1
Pillow                   9.5.0
pip                      24.0
pixelmatch               0.3.0
platformdirs             4.1.0
pluggy                   1.4.0
proto-plus               1.23.0
protobuf                 4.25.2
pyasn1                   0.5.1
pyasn1-modules           0.3.0
pycparser                2.21
pyee                     8.2.2
pyodbc                   5.0.1
pypdf                    4.0.1
pyppeteer                1.0.2
pyquery                  2.0.0
PySocks                  1.7.1
pyspnego                 0.10.2
pytest                   8.1.0
pytest-rerunfailures     13.0
pytest-xdist             3.5.0
python-dateutil          2.8.2
python-jose              3.3.0
pytz                     2023.4
PyYAML                   6.0.1
requests                 2.31.0
requests-file            2.0.0
requests-html            0.10.0
requests-toolbelt        1.0.0
rsa                      4.9
selenium                 4.16.0
simple-salesforce        1.11.6
six                      1.16.0
smbprotocol              1.12.0
sniffio                  1.3.0
sortedcontainers         2.4.0
soupsieve                2.5
sspilib                  0.1.0
tqdm                     4.66.1
trio                     0.24.0
trio-websocket           0.11.1
urllib3                  1.26.18
w3lib                    2.1.2
websockets               10.4
wsproto                  1.2.0
xmltodict                0.13.0
zeep                     4.2.1
zipp                     3.17.0
```

**Comment by bluetech** [comment] 2024-03-04 11:05
Duplicate of #12063.

**Closed by bluetech** 2024-03-04 11:05 UTC
