### ISSUE TITLE
monkeypatch don't patch functions which only raising exceptions

### ISSUE THREAD

**Issue by PerchunPak** [pytest-dev/pytest#9705] opened 2022-02-22 10:58 UTC
Code for reproduce:
```py
def something(arg1: bool = True):
    if arg1:
        return arg1
    else:
        raise ValueError

def main():
    try:
        return something()
    except ValueError:
        return False

def fake_something(*args, **kwargs):
    raise ValueError

def test_main(monkeypatch):
    monkeypatch.setattr("test_main.something", fake_something)
    assert main()
```
My packages:
```bash
> pip list
Package      Version
------------ -------
atomicwrites 1.4.0
attrs        21.4.0
colorama     0.4.4
iniconfig    1.1.1
packaging    21.3
pip          22.0.3
pluggy       1.0.0
py           1.11.0
pyparsing    3.0.7
pytest       7.0.1
setuptools   60.5.0
tomli        2.0.1
wheel        0.37.1
```
Using windows 11, pytest 7.0.1, installed with poetry env based on Python 3.10.2.

**Comment by PerchunPak** [comment] 2022-02-22 20:57
Strange, but after some atemps, example code start work for me. Some later will try to create code for another reproduce.

**Comment by PerchunPak** [comment] 2022-02-23 08:18
Okay, so I tried to create example code, but again, nothing worked.
I pushed my unfinished tests to [2c1569e](https://github.com/PerchunPak/PingerBot/commit/2c1569ec188e55df9d9e0c815c4206f9c0cd2344).

---
Steps to reproduce:
```bash
git clone https://github.com/PerchunPak/PingerBot.git
cd PingerBot
git checkout 2c1569ec188e55df9d9e0c815c4206f9c0cd2344
```
Then we install dependencies: 
```bash
(create venv)
pip install -Ur requirements.txt -r tests_requirements.txt
```
And finaly run tests:
```bash
pytest .
```
We will get something like:
```bash
(venv) C:\Users\perch\Desktop\programming\PingerBot>pytest . --no-cov
================================================= test session starts =================================================
platform win32 -- Python 3.9.7, pytest-7.0.1, pluggy-1.0.0
rootdir: C:\Users\perch\Desktop\programming\PingerBot, configfile: pytest.ini
plugins: asyncio-0.18.1, cov-3.0.0
asyncio: mode=auto
collected 96 items

tests\test_cmd_add.py .......                                                                                    [  7%]
tests\test_cmd_alias.py ........                                                                                 [ 15%]
tests\test_cmd_motd.py ......                                                                                    [ 21%]
tests\test_cmd_other.py ...............EEE...                                                                    [ 43%]
tests\test_cmd_ping.py .........                                                                                 [ 53%]
tests\test_cmd_stat.py ..............                                                                            [ 67%]
tests\test_database.py .................                                                                         [ 85%]
tests\test_metods_for_commands.py ..............                                                                 [100%]

======================================================= ERRORS ========================================================
_________________________ ERROR at setup of TestOtherCommands.test_get_bot_version_fail_color _________________________
tests\test_cmd_other.py:150: in get_bot_version_fail
    monkeypatch_session.setattr(OtherCommands, "get_commit", fake_get_commit)
E   AttributeError: <class 'src.commands.other.OtherCommands'> has no attribute 'get_commit'
______________________ ERROR at setup of TestOtherCommands.test_get_bot_version_fail_git_in_name ______________________
tests\test_cmd_other.py:150: in get_bot_version_fail
    monkeypatch_session.setattr(OtherCommands, "get_commit", fake_get_commit)
E   AttributeError: <class 'src.commands.other.OtherCommands'> has no attribute 'get_commit'
_____________________ ERROR at setup of TestOtherCommands.test_get_bot_version_fail_git_in_value ______________________
tests\test_cmd_other.py:150: in get_bot_version_fail
    monkeypatch_session.setattr(OtherCommands, "get_commit", fake_get_commit)
E   AttributeError: <class 'src.commands.other.OtherCommands'> has no attribute 'get_commit'
============================================ 93 passed, 3 errors in 25.52s ============================================
```

**Comment by nicoddemus** [comment] 2022-02-23 15:51
Doesn't seem related to monkeypatch, when the setup of those tests is happening, `OtherCommands` doesn't have a `get_commit` method/attribute.

You can test this hypothesis by adding a `assert hasattr(OtherCommands, "get_commit")` just before calling `monkeypatch_session.setattr`.

Glancing at the code at https://github.com/PerchunPak/PingerBot/blob/pr/rewrite/fail-tests-git/src/commands/other.py, I don't see any attribute or method named `get_commit`, is that something that's being added dynamically?

**Comment by PerchunPak** [comment] 2022-02-23 16:35
Oops, I missed up. Fixed in [e9439a5](https://github.com/PerchunPak/PingerBot/commit/e9439a53f251f2e2c2b2fc889680b8e932089c13). Here real output:
```bash
C:\Users\perch\Desktop\programming\PingerBot> pytest . --no-cov
========================================================================================================== test session starts ===========================================================================================================
platform win32 -- Python 3.9.7, pytest-7.0.1, pluggy-1.0.0
rootdir: C:\Users\perch\Desktop\programming\PingerBot, configfile: pytest.ini
plugins: asyncio-0.18.1, cov-3.0.0
asyncio: mode=auto
collected 96 items                                                                                                                                                                                                                        

tests\test_cmd_add.py .......                                                                                                                                                                                                       [  7%]
tests\test_cmd_alias.py ........                                                                                                                                                                                                    [ 15%]
tests\test_cmd_motd.py ......                                                                                                                                                                                                       [ 21%]
tests\test_cmd_other.py ...............FFF...                                                                                                                                                                                       [ 43%]
tests\test_cmd_ping.py .........                                                                                                                                                                                                    [ 53%]
tests\test_cmd_stat.py ..............                                                                                                                                                                                               [ 67%]
tests\test_database.py .................                                                                                                                                                                                            [ 85%]
tests\test_metods_for_commands.py ..............                                                                                                                                                                                    [100%]

================================================================================================================ FAILURES ================================================================================================================ 
___________________________________________________________________________________________ TestOtherCommands.test_get_bot_version_fail_color ____________________________________________________________________________________________ 
tests\test_cmd_other.py:346: in test_get_bot_version_fail_color
    assert str(get_bot_version_fail.color) == str(Color.red())
E   AssertionError: assert '#2ecc71' == '#e74c3c'
E     - #e74c3c
E     + #2ecc71
________________________________________________________________________________________ TestOtherCommands.test_get_bot_version_fail_git_in_name _________________________________________________________________________________________ 
tests\test_cmd_other.py:354: in test_get_bot_version_fail_git_in_name
    assert "GIT" in get_bot_version_fail.fields[0].name
E   AssertionError: assert 'GIT' in 'Хэш коммита'
E    +  where 'Хэш коммита' = EmbedProxy(inline=True, name='Хэш коммита', value='2c1569e').name
________________________________________________________________________________________ TestOtherCommands.test_get_bot_version_fail_git_in_value ________________________________________________________________________________________ 
tests\test_cmd_other.py:362: in test_get_bot_version_fail_git_in_value
    assert "GIT" in get_bot_version_fail.fields[0].value
E   AssertionError: assert 'GIT' in '2c1569e'
E    +  where '2c1569e' = EmbedProxy(inline=True, name='Хэш коммита', value='2c1569e').value
===================================================================================================== 3 failed, 93 passed in 26.27s ====================================================================================================== 
```

**Comment by nicoddemus** [comment] 2022-02-23 17:58
Nothing jumps to the eyes, but I would debug this like so:

1. Put a breakpoint right before the `monkeypatch.setattr` call, to ensure it is replacing what I think it is replacing, and also *when* it is doing that is matching what I expect.
2. Put a breakpoint right before the failed assertion, and then jump in that point, to see what is being called (instead of the replacement in 1).

Good luck!

**Comment by PerchunPak** [comment] 2022-02-25 17:58
It is didn't patching function.
![image](https://user-images.githubusercontent.com/68118654/155763587-756847ce-a0ab-4185-ab28-4b36dcc599d3.png)
Result, if I change `raise ...` to `return`:
![image](https://user-images.githubusercontent.com/68118654/155764093-2eb5554e-ee62-47b2-98a0-5ab70cc84cf0.png)

**Comment by nicoddemus** [comment] 2022-02-25 18:17
Ahh I see. 

The problem is how you are importing the function: `monkeypatch.setattr` sets an attribute (`fake_get_commit`) into an object `subprocess` module), it does not the the *actual function* object.

In short, if you patch in your test with:

```python
monkeypatch.setattr("subprocess.check_output", fake_get_commit)
```

Then in order for the module you are interested in patching to see the patched function, it needs to access the object via `subprocess.check_output`. In other words, instead of this:

```python
# mymodule_under_test.py
from subprocess import check_output


def foo():
    check_output(...)  # This will always be the original function.
```

You need to write this instead:

```python
import subprocess

def foo():
    subprocess.check_output(...)  # Here you will see `fake_get_commit`.
```

See [docs.python.org/3/library/unittest.mock.html#where-to-patch](https://docs.python.org/3/library/unittest.mock.html#where-to-patch) for more information.

Closing this then.

**Closed by nicoddemus** 2022-02-25 18:17 UTC
Labels: status: needs information
