### ISSUE TITLE
pytest.importorskip not working

### ISSUE THREAD

**Issue by syrusakbary** [pytest-dev/pytest#1839] opened 2016-08-22 07:03 UTC
`pytest.importorskip` seems to be not working.

This code that was working with pytest `2.9.2` is not working anymore in `3.0`

```python
import pytest
asyncio = pytest.importorskip("asyncio")
```
Receiving the following error:
```
____________________________________________________________________ ERROR collecting graphql/execution/tests/test_executor_asyncio.py ____________________________________________________________________
Using @pytest.skip outside a test (e.g. as a test function decorator) is not allowed. Use @pytest.mark.skip or @pytest.mark.skipif instead.
```

Envlist:
```
pytest (3.0.0)
pytest-benchmark (3.0.0)
pytest-cov (2.2.0)
pytest-django (2.9.1)
pytest-mock (0.11.0)
pytest-profiling (1.1.1)
pytest-xdist (1.13.1)
```

**Comment by RonnyPfannschmidt** [comment] 2016-08-22 09:45
this is a duplicate of #1822 which was fixed in #1823 

it will be released with the next bugfix release

**Closed by RonnyPfannschmidt** 2016-08-22 09:45 UTC
