### ISSUE TITLE
Assert errors to the bottom

### ISSUE THREAD

**Issue by ganwell** [pytest-dev/pytest#1455] opened 2016-03-16 09:52 UTC
When I run a single test either with -x or -k I want the assert at the bottom of the screen. We have many projects that log a lot. So I usually have to scroll up 100s or 1000s of lines to get to the error. Here my ideas to improve this situation:

* A short command-line argument that tells pytest only to run one test, stop then and present captured output (including plugins) first and then the error. Can be combine with -k and if you specify a expression that include multiple tests only the first is executed.

* A short command-line argument that disables logs (including plugins) like --no-print-logs but shorter

* Generally change the order (probably too many regressions)

* Other ideas. In the end the scrolling takes too long, so I am happy with other solutions.

**Comment by The-Compiler** [comment] 2016-03-16 09:58
Closing as a duplicate of #1456 :wink:

**Closed by The-Compiler** 2016-03-16 09:58 UTC
