### ISSUE TITLE
[BUG] filterwarnings don't support colon escaping in `pytest.ini`

### ISSUE THREAD

**Issue by webknjaz** [pytest-dev/pytest#5765] opened 2019-08-19 11:30 UTC
It looks like pytest just splits config entries by colon unconditionally but I think it should ignore escaped colons.

When want to match a URL in the warning I have to fall back to using a dot (matches any character) while what I want is `\:` there.

```console
$ cat pytest.ini         
[pytest]
filterwarnings =
    error
    ignore:Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working:DeprecationWarning
    ignore:trio.hazmat.notify_socket_close is deprecated since Trio 0.12.0; use trio.hazmat.notify_closing instead \(https\://github.com/python-trio/trio/issues/878\):trio.TrioDeprecationWarning
    ignore:trio.hazmat.wait_socket_writable is deprecated since Trio 0.12.0; use trio.hazmat.wait_writable instead \(https.//github.com/python-trio/trio/issues/878\):trio.TrioDeprecationWarning
    ignore:trio.hazmat.wait_socket_readable is deprecated since Trio 0.12.0; use trio.hazmat.wait_readable instead \(https.//github.com/python-trio/trio/issues/878\):trio.TrioDeprecationWarning
$ tox -- -k test_github_app_webhook_client_works
python installed: You are using pip version 10.0.1, however version 19.2.2 is available.,You should consider upgrading via the 'pip install --upgrade pip' command.,aiofiles==0.4.0,anyio==1.0.0,asks==2.3.5,asn1crypto==0.24.0,async-generator==1.10,atomicwrites==1.3.0,attrs==19.1.0,blinker==1.4,boltons==19.1.0,cachetools==3.1.1,certifi==2019.6.16,cffi==1.12.3,Click==7.0,coverage==4.5.4,cryptography==2.7,face==19.1.2,gidgethub==3.1.0,glom==19.2.0,h11==0.9.0,h2==3.1.1,hpack==3.0.0,Hypercorn==0.7.2,hyperframe==5.2.0,idna==2.8,importlib-metadata==0.19,itsdangerous==1.1.0,Jinja2==2.10.1,MarkupSafe==1.1.1,more-itertools==7.2.0,multidict==4.5.2,outcome==1.0.0,packaging==19.1,pendulum==2.0.5,pluggy==0.12.0,psycopg2-binary==2.8.3,py==1.8.0,pycparser==2.19,PyJWT==1.7.1,pyparsing==2.4.2,pytest==5.1.0,pytest-cov==2.7.1,pytest-trio==0.5.2,python-dateutil==2.8.0,pytzdata==2019.2,Quart==0.9.1,Quart-Trio==0.3.0,sentry-sdk==0.11.0,six==1.12.0,sniffio==1.1.0,sortedcontainers==2.1.0,toml==0.10.0,trio==0.12.1,typing-extensions==3.7.4,uritemplate==3.0.0,urllib3==1.25.3,wcwidth==0.1.7,wsproto==0.15.0,zipp==0.5.2
python run-test-pre: PYTHONHASHSEED='1389958408'
python run-test: commands[0] | ~/src/github/python-trio/snekomatic/.tox/python/bin/python -m pytest -k test_github_app_webhook_client_works
========================================================= test session starts ==========================================================
platform linux -- Python 3.7.1, pytest-5.1.0, py-1.8.0, pluggy-0.12.0
cachedir: .tox/python/.pytest_cache
rootdir: ~/src/github/python-trio/snekomatic, inifile: pytest.ini
plugins: anyio-1.0.0, cov-2.7.1, trio-0.5.2
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "~/src/github/python-trio/snekomatic/.tox/python/lib/python3.7/site-packages/_pytest/main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "~/src/github/python-trio/snekomatic/.tox/python/lib/python3.7/site-packages/_pytest/main.py", line 234, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "~/src/github/python-trio/snekomatic/.tox/python/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "~/src/github/python-trio/snekomatic/.tox/python/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "~/src/github/python-trio/snekomatic/.tox/python/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "~/src/github/python-trio/snekomatic/.tox/python/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "~/src/github/python-trio/snekomatic/.tox/python/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "~/src/github/python-trio/snekomatic/.tox/python/lib/python3.7/site-packages/pluggy/callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File "~/src/github/python-trio/snekomatic/.tox/python/lib/python3.7/site-packages/_pytest/warnings.py", line 121, in pytest_collection
INTERNALERROR>     config=config, ihook=config.hook, when="collect", item=None
INTERNALERROR>   File "~/.pyenv/versions/3.7.1/lib/python3.7/contextlib.py", line 112, in __enter__
INTERNALERROR>     return next(self.gen)
INTERNALERROR>   File "~/src/github/python-trio/snekomatic/.tox/python/lib/python3.7/site-packages/_pytest/warnings.py", line 78, in catch_warnings_for_item
INTERNALERROR>     _setoption(warnings, arg)
INTERNALERROR>   File "~/src/github/python-trio/snekomatic/.tox/python/lib/python3.7/site-packages/_pytest/warnings.py", line 19, in _setoption
INTERNALERROR>     category = wmod._getcategory(category)
INTERNALERROR>   File "~/.pyenv/versions/3.7.1/lib/python3.7/warnings.py", line 255, in _getcategory
INTERNALERROR>     raise _OptionError("invalid module name: %r" % (module,)) from None
INTERNALERROR> warnings._OptionError: invalid module name: '//github'

======================================================== no tests ran in 0.01s =========================================================
ERROR: InvocationError for command ~/src/github/python-trio/snekomatic/.tox/python/bin/python -m pytest -k test_github_app_webhook_client_works (exited with code 3)
_______________________________________________________________ summary ________________________________________________________________
ERROR:   python: commands failed
```

**Comment by blueyed** [comment] 2019-08-19 16:45
How does it work with `python -W`?  Does it handle escaped colons there?

**Comment by webknjaz** [comment] 2019-08-19 18:24
No idea...

**Comment by RonnyPfannschmidt** [comment] 2019-08-20 10:13
pytest is completely in line with cpython here

**Comment by RonnyPfannschmidt** [comment] 2019-08-20 10:16
https://github.com/pytest-dev/pytest/blob/0e569faca2802be124cd1a6b6690a35a464fb0a8/src/_pytest/warnings.py#L77-L86 is the logic for adding it

https://github.com/pytest-dev/pytest/blob/0e569faca2802be124cd1a6b6690a35a464fb0a8/src/_pytest/warnings.py#L8-L29 is the logic we copied form cpython

so as far as im concerned this is in line and works as intended

**Comment by nicoddemus** [comment] 2019-08-20 22:26
Hi @webknjaz,

As @RonnyPfannschmidt mention, this difference is intentional to reproduce what CPython does, albeit I agree it is weird. This is reported in this CPython issue: https://bugs.python.org/issue34624.

Closing this as "won't fix" for now, feel free to follow with further questions. 👍

**Closed by nicoddemus** 2019-08-20 22:26 UTC
Labels: plugin: warnings, type: enhancement
