### ISSUE TITLE
pytest-6.0.1 does not find custom fixtures, test filename incorrect (just ..\..\)

### ISSUE THREAD

**Issue by naugustin** [pytest-dev/pytest#7628] opened 2020-08-07 16:26 UTC
```
============================= test session starts =============================
platform win32 -- Python 3.7.0, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- c:\prog
ram files (x86)\python37-32\python.exe
cachedir: .pytest_cache
metadata: {'Python': '3.7.0', 'Platform': 'Windows-2008ServerR2-6.1.7601-SP1', '
Packages': {'pytest': '6.0.1', 'py': '1.9.0', 'pluggy': '0.13.1'}, 'Plugins': {'
html': '2.1.1', 'metadata': '1.10.0'}}
rootdir: C:\
plugins: html-2.1.1, metadata-1.10.0
collected 2 items

..\..\::test_install[uninstall_S0_0] ERROR (0 secs)

..\..\::test_install[ver_1.6.1_S0_1] ERROR (0 secs)


=================================== ERRORS ====================================
________________ ERROR at setup of test_install[uninstall_S0_0] _________________
file C:\install\tests\install_test.py, line 77
  @pytest.mark.parametrize("rel_info", release_dirs, ids=test_ids)
  def test_install(install_fixture, rel_info):
file C:\install\tests\install_test.py, line 26
  @pytest.fixture(scope='session')
  def module_init_fixture(session_fixture):
E       fixture 'session_fixture' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbin
ary, doctest_namespace, extra, install_fixture, metadata, module_init_fixture, m
onkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml
_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

- [ ] output of `pip list` from the virtual environment you are using
```
Package            Version
------------------ -------
atomicwrites       1.4.0
attrs              19.3.0
bcrypt             3.1.7
cffi               1.14.1
colorama           0.4.3
cryptography       3.0
importlib-metadata 1.7.0
iniconfig          1.0.1
json-flatten       0.1
more-itertools     8.4.0
packaging          20.4
paramiko           2.7.1
pip                10.0.1
pluggy             0.13.1
py                 1.9.0
pycparser          2.20
PyNaCl             1.4.0
pyparsing          2.4.7
pytest             6.0.1
pytest-html        2.1.1
pytest-metadata    1.10.0
scp                0.13.2
selenium           3.141.0
setuptools         39.0.1
six                1.15.0
toml               0.10.1
urllib3            1.25.10
zipp               3.1.0
```

 Python 3.7.0, pytest-6.0.1
OS Name:                   Microsoft Windows Server 2008 R2 Enterprise
OS Version:                6.1.7601 Service Pack 1 Build 7601

The same test work with pytest-5.3.2

**Comment by Zac-HD** [comment] 2020-08-09 05:54
Hi @naugustin - can you share a reproducing example that we can run?  The test output helps, but being able to replay your problem locally is a lot better :slightly_smiling_face:

**Comment by naugustin** [comment] 2020-08-10 19:59
Thank you.

I mimicked my fixture order with simple script. I am able to reproduce it. please find attached the script. Simply unzip under c:\ and run below command.
[test.zip](https://github.com/pytest-dev/pytest/files/5053060/test.zip)


pytest -s -v --show-capture=no \test\test\tests\dummy_test.py
============================= test session starts =============================
platform win32 -- Python 3.7.0, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- c:\prog
ram files (x86)\python37-32\python.exe
cachedir: .pytest_cache
metadata: {'Python': '3.7.0', 'Platform': 'Windows-2008ServerR2-6.1.7601-SP1', '
Packages': {'pytest': '6.0.1', 'py': '1.9.0', 'pluggy': '0.13.1'}, 'Plugins': {'
html': '2.1.1', 'metadata': '1.10.0'}}
rootdir: C:\
plugins: html-2.1.1, metadata-1.10.0
collected 1 item

..\..\::test_dummy ERROR

=================================== ERRORS ====================================
________________________ ERROR at setup of test_dummy _________________________
file C:\test\test\tests\dummy_test.py, line 9
  def test_dummy(session_fixture2):
E       fixture 'session_fixture2' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbin
ary, doctest_namespace, extra, metadata, module_fixture, monkeypatch, pytestconf
ig, record_property, record_testsuite_property, record_xml_attribute, recwarn, t
mp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

C:\test\test\tests\dummy_test.py:9
=========================== short test summary info ===========================
ERROR ..\..\::test_dummy
============================== 1 error in 0.03s ===============================

**Comment by RonnyPfannschmidt** [comment] 2020-08-11 06:20
can you try with pytest master, i recall that @bluetech just recently landed some enhancements for path handling that might help that (i don't have a windows box)

**Comment by nicoddemus** [comment] 2020-08-11 13:05
I can reproduce the problem even with current `master`. The key to make this fail is to use an absolute path but without the drive letter:

```
d:\projects\pytest (HEAD detached at 92af2e2 -> origin)
(.env37) λ pytest \projects\pytest\.tmp\drive\tests\dummy_test.py
==fails==
```

Including the drive letter the test passes:

```
d:\projects\pytest (master -> origin)
(.env37) λ pytest d:\projects\pytest\.tmp\drive\tests\dummy_test.py
==passes==
```

I can investigate this later. 👍

**Comment by nicoddemus** [comment] 2020-08-11 13:06
Quick hunch in case somebody wants to investigate this before me:

```
>>> from pathlib import Path
>>> Path(r'd:\projects\pytest\.tmp\drive\tests\dummy_test.py') == Path(r'\projects\pytest\.tmp\drive\tests\dummy_test.py')
False
>>> Path(r'd:\projects\pytest\.tmp\drive\tests\dummy_test.py') == Path(r'\projects\pytest\.tmp\drive\tests\dummy_test.py').absolute()
True
```

**Comment by nicoddemus** [comment] 2020-08-11 13:48
@naugustin meanwhile a workaround is to pass the full path including the drive letter.

**Comment by naugustin** [comment] 2020-08-11 17:16
Thank you.

Yes. it works if i specify the test file starting with C:\

**Comment by mcsitter** [comment] 2020-08-11 20:29
I ran the code from above in Python 3.8.5 and could not reproduce the results. Both comparisons result in False. I ran this in the context of my C: drive.
```
>>> from pathlib import Path
>>> Path(r'd:\projects\pytest\.tmp\drive\tests\dummy_test.py') == Path(r'\projects\pytest\.tmp\drive\tests\dummy_test.py')
False
>>> Path(r'd:\projects\pytest\.tmp\drive\tests\dummy_test.py') == Path(r'\projects\pytest\.tmp\drive\tests\dummy_test.py').absolute()
False
>>> Path(r'd:\projects\pytest\.tmp\drive\tests\dummy_test.py')
WindowsPath('d:/projects/pytest/.tmp/drive/tests/dummy_test.py')
>>>Path(r'\projects\pytest\.tmp\drive\tests\dummy_test.py')
WindowsPath('/projects/pytest/.tmp/drive/tests/dummy_test.py')
>>> Path(r'\projects\pytest\.tmp\drive\tests\dummy_test.py').absolute()
WindowsPath('C:/projects/pytest/.tmp/drive/tests/dummy_test.py')
```
Also running `pytest` in the directory of the extracted `test.zip` provided above discovers a test in `tests\dummy_test.py` which passes.

**Comment by nicoddemus** [comment] 2020-08-12 22:34
> . Both comparisons result in False. I ran this in the context of my C: drive.

You need to be in the same drive as the drives of the paths being used. If you are on the C: drive, you should use `C:` paths, because `absolute()` will use the current directory to construct the full path. In the examples above, just replace `d:` by `c:` and you will see the same results.

> Also running pytest in the directory of the extracted test.zip provided above discovers a test in tests\dummy_test.py which passes.

It is important to pass the *full path without a drive letter* to pytest, so if you extracted that zip to `C:\temp`, you need to execute pytest from the C: drive and pass `\temp\tests`.

**Closed** 2020-08-17 19:58 UTC
Labels: platform: windows, status: needs information, topic: fixtures, type: regression
