### ISSUE TITLE
3.7.0: Fixture misses attribute

### ISSUE THREAD

**Issue by JohanLorenzo** [pytest-dev/pytest#3747] opened 2018-07-31 12:19 UTC
From https://github.com/pytest-dev/pytest/issues/3742#issuecomment-409170661: 

Hello! Thank you for this great library! The Mozilla release engineering team relies on it for several projects :smiley: 

I just found a similar regression:
``` py
AttributeError: 'async_generator' object has no attribute 'put'
```
This async generator is a regular `aiohttp.ClientSession()` and is [initialized here](https://github.com/mozilla-releng/scriptworker/blob/cbd8ba44aa8ed1d3eeaf40d7d2a987f887074171/scriptworker/test/__init__.py#L180). This might be an integration issue with the `pytest-asyncio` plugin. 

I rolled pytest back to 3.6.4 and things are back working. You can see both the failure and the workaround in

* https://github.com/mozilla-releng/beetmoverscript/pull/176
* https://travis-ci.org/mozilla-releng/beetmoverscript/jobs/410250756#L598

## Example

I put up a minimal example over here: https://github.com/JohanLorenzo/pytest-fixture-bug-3747

**Comment by RonnyPfannschmidt** [comment] 2018-07-31 13:11
@JohanLorenzo the perceived issue can be fixed by reordering the marker and the fixture declaration

due to the introduction of the deprecaationwarning the structure changed a bit and the markers dont pass on

since pytest core doesn't support markers on fixtures to begin with this is a bit of a grey area,
basically this issue is with pytest-asyncio

upon quick skimming i beleive it should have declared an own asyncio_fixture decorator as a starting pointpoint

**Comment by JohanLorenzo** [comment] 2018-07-31 13:31
Got it. Thanks for the context!

To make I get this right, do you mean I should write:
```py
@pytest.fixture(scope='function')
@pytest.mark.asyncio
async def fake_session():
```
?

**Comment by RonnyPfannschmidt** [comment] 2018-07-31 13:40
correct - i believe that should work, please report back with the details

**Comment by JohanLorenzo** [comment] 2018-07-31 13:42
Crap, I get the same error locally :/

**Comment by RonnyPfannschmidt** [comment] 2018-07-31 13:45
in that case its a unintended interaction with pytest-asyncio that we aren't aware of, please report against pytest-asyncio as well so we can collaborate on the root cause analysis

**Comment by JohanLorenzo** [comment] 2018-07-31 13:48
Looks like https://github.com/pytest-dev/pytest-asyncio/issues/89 was already filed. I commented there.

**Comment by daniloaf** [comment] 2018-07-31 13:50
I'm having the same issue when using asyncio inside a fixture, but I'm not using the `@pytest.mark.asyncio`

**Closed** 2018-08-02 05:17 UTC
Labels: status: needs information
