### ISSUE TITLE
Unrecognized arguments using pytest with python3.8-dev

### ISSUE THREAD

**Issue by rllola** [pytest-dev/pytest#5545] opened 2019-07-03 13:28 UTC
Recently the pytest call using travis CI broke with python 3.8 dev 

See : https://travis-ci.org/HelloZeroNet/ZeroNet/jobs/553544808

Log says : 
```
pytest.py: error: unrecognized arguments: -rsxX
  inifile: /home/travis/build/HelloZeroNet/ZeroNet/plugins/CryptMessage/Test/pytest.ini
  rootdir: /home/travis/build/HelloZeroNet/ZeroNet/plugins/CryptMessage/Test
```

pytest.ini 
```
[pytest]
python_files = Test*.py
addopts = -rsxX -v --durations=6
markers =
    webtest: mark a test as a webtest.
```

It only breaks with python 3.8

Something seems to have changed but cant really tell what....

**Comment by nicoddemus** [comment] 2019-07-03 14:12
Duplicate of https://github.com/pytest-dev/pytest/issues/5523, will be fixed in `5.0.1`; meanwhile a workaround is to use `-r sxX` instead.

(I'm pinning https://github.com/pytest-dev/pytest/issues/5523 so it is more visible)

**Closed** 2019-07-03 14:12 UTC
