### ISSUE TITLE
PDF Documentation lind redirects on 404 page

### ISSUE THREAD

**Issue by rojaster** [pytest-dev/pytest#1494] opened 2016-03-30 13:22 UTC
Good time of day, The PDF documentation link is broken, it redirects to the page 404.

http://pytest.org/latest/pytest.pdf

**Comment by nicoddemus** [comment] 2016-03-30 13:52
We are aware of that, thanks! Meanwhile please find the PDF docs generated by readthedocs [here](http://readthedocs.org/projects/pytest/downloads/pdf/2.9.1/).

Duplicate of #1436

**Closed by nicoddemus** 2016-03-30 13:52 UTC

**Comment by rojaster** [comment] 2016-03-30 13:54
Ok, thank you

**Comment by The-Compiler** [comment] 2016-04-13 21:15
I did a build of the 2.9 docs and uploaded them. Sorry for the delay!
