### ISSUE TITLE
[BUG] `testdir` fixture usage seems to cause `PytestDeprecationWarning: The TerminalReporter.writer attribute is deprecated, use TerminalReporter._tw instead at your own risk.`

### ISSUE THREAD

**Issue by webknjaz** [pytest-dev/pytest#7328] opened 2020-06-05 22:15 UTC
While implementing https://github.com/pytest-dev/pytest-forked/pull/34, I've faced this, when writing tests for the plugin:
```python-traceback
  $PYTHON_PREFIX/lib/python3.8/site-packages/_pytest/compat.py:333: PytestDeprecationWarning: The TerminalReporter.writer attribute is deprecated, use TerminalReporter._tw instead at your own risk.
  See https://docs.pytest.org/en/latest/deprecations.html#terminalreporter-writer for more information.
    return getattr(object, name, default)
```

It's funny that the docs even showcase this exact warning in the test report snippet in this section:  https://docs.pytest.org/en/stable/writing_plugins.html#testing-plugins.

N.B. I'm currently unable to determine what exactly triggers this because of the dynamic `getattr()`.

**Comment by asottile** [comment] 2020-06-06 03:35
dupe of #6936

**Closed by asottile** 2020-06-06 03:35 UTC
