### ISSUE TITLE
AttributeError: '_HookCaller' object has no attribute 'spec_opts'

### ISSUE THREAD

**Issue by ionelmc** [pytest-dev/pytest#1310] opened 2016-01-06 00:16 UTC
I get this error with 2.8.5, but [only on python2.6 it seems](https://travis-ci.org/ionelmc/pytest-benchmark/jobs/100465771):
```
INTERNALERROR> Traceback (most recent call last):

INTERNALERROR>   File "/home/travis/build/ionelmc/pytest-benchmark/.tox/2.6-pytest28-xdist-nocov/lib/python2.6/site-packages/_pytest/main.py", line 86, in wrap_session

INTERNALERROR>     config._do_configure()

INTERNALERROR>   File "/home/travis/build/ionelmc/pytest-benchmark/.tox/2.6-pytest28-xdist-nocov/lib/python2.6/site-packages/_pytest/config.py", line 830, in _do_configure

INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))

INTERNALERROR>   File "/home/travis/build/ionelmc/pytest-benchmark/.tox/2.6-pytest28-xdist-nocov/lib/python2.6/site-packages/_pytest/vendored_packages/pluggy.py", line 729, in call_historic

INTERNALERROR>     self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)

INTERNALERROR>   File "/home/travis/build/ionelmc/pytest-benchmark/.tox/2.6-pytest28-xdist-nocov/lib/python2.6/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec

INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)

INTERNALERROR>   File "/home/travis/build/ionelmc/pytest-benchmark/.tox/2.6-pytest28-xdist-nocov/lib/python2.6/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>

INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()

INTERNALERROR>   File "/home/travis/build/ionelmc/pytest-benchmark/.tox/2.6-pytest28-xdist-nocov/lib/python2.6/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute

INTERNALERROR>     res = hook_impl.function(*args)

INTERNALERROR>   File "/home/travis/build/ionelmc/pytest-benchmark/.tox/2.6-pytest28-xdist-nocov/lib/python2.6/site-packages/pytest_benchmark/plugin.py", line 373, in pytest_configure

INTERNALERROR>     config._benchmarksession = BenchmarkSession(config)

INTERNALERROR>   File "/home/travis/build/ionelmc/pytest-benchmark/.tox/2.6-pytest28-xdist-nocov/lib/python2.6/site-packages/pytest_benchmark/session.py", line 36, in __init__

INTERNALERROR>     self.machine_info = config.hook.pytest_benchmark_generate_machine_info(config=self.config)

INTERNALERROR>   File "/home/travis/build/ionelmc/pytest-benchmark/.tox/2.6-pytest28-xdist-nocov/lib/python2.6/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__

INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)

INTERNALERROR>   File "/home/travis/build/ionelmc/pytest-benchmark/.tox/2.6-pytest28-xdist-nocov/lib/python2.6/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec

INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)

INTERNALERROR>   File "/home/travis/build/ionelmc/pytest-benchmark/.tox/2.6-pytest28-xdist-nocov/lib/python2.6/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>

INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()

INTERNALERROR> AttributeError: '_HookCaller' object has no attribute 'spec_opts'
```

Any clues? Should I try to make a smaller repro?

**Comment by ionelmc** [comment] 2016-01-06 00:17
Ah yes, it only happens with xdist. Could it be that I call the hook "too early"?

**Comment by nicoddemus** [comment] 2016-01-06 01:32
Thanks @ionelmc!

Closing this as a duplicate of #1062

**Closed by nicoddemus** 2016-01-06 01:32 UTC
