### ISSUE TITLE
Plugins are not  recognized

### ISSUE THREAD

**Issue by alenickwork** [pytest-dev/pytest#1497] opened 2016-03-30 20:09 UTC
Hi!
Strange situation I met:
1. install pytest 2.9.1 with pip
2. install pytest-allure-adaptor or pytest-html plugins
3. try to use any - pytest does not recognizethem installed

Could you pelase assist what can be wrong?
Platform Windows 2008.

```
>py.test
============================= test session starts =============================
platform win32 -- Python 2.7.8, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: ..., inifile:
collected 0 items / 1 errors

C:\Users\e>pip install pytest-allure-adaptor
Requirement already satisfied (use --upgrade to upgrade): pytest-allure-adaptor
in c:\python27\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in c:\pytho
n27\lib\site-packages (from pytest-allure-adaptor)
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.2.0 in c:\pyth
on27\lib\site-packages (from pytest-allure-adaptor)
Requirement already satisfied (use --upgrade to upgrade): pytest>=2.7.3 in c:\py
thon27\lib\site-packages (from pytest-allure-adaptor)
Requirement already satisfied (use --upgrade to upgrade): enum34 in c:\python27\
lib\site-packages (from pytest-allure-adaptor)
Requirement already satisfied (use --upgrade to upgrade): namedlist in c:\python
27\lib\site-packages (from pytest-allure-adaptor)
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.29 in c:\pytho
n27\lib\site-packages (from pytest>=2.7.3->pytest-allure-adaptor)
Requirement already satisfied (use --upgrade to upgrade): colorama in c:\python2
7\lib\site-packages (from pytest>=2.7.3->pytest-allure-adaptor)
c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py
:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Na
me Indication) extension to TLS is not available on this platform. This may caus
e the server to present an incorrect TLS certificate, which can cause validation
 failures. For more information, see https://urllib3.readthedocs.org/en/latest/s
ecurity.html#snimissingwarning.
  SNIMissingWarning
c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py
:120: InsecurePlatformWarning: A true SSLContext object is not available. This p
revents urllib3 from configuring SSL appropriately and may cause certain SSL con
nections to fail. For more information, see https://urllib3.readthedocs.org/en/l
atest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

C:\Users\el>py.test --traceconfig
PLUGIN registered: <_pytest.config.PytestPluginManager object at 0x0201C8F0>
PLUGIN registered: <_pytest.config.Config object at 0x021CCA70>
PLUGIN registered: <module '_pytest.mark' from 'c:\python27\lib\site-packages\_p
ytest\mark.pyc'>
PLUGIN registered: <module '_pytest.main' from 'c:\python27\lib\site-packages\_p
ytest\main.pyc'>
PLUGIN registered: <module '_pytest.terminal' from 'c:\python27\lib\site-package
s\_pytest\terminal.pyc'>
PLUGIN registered: <module '_pytest.runner' from 'c:\python27\lib\site-packages\
_pytest\runner.pyc'>
PLUGIN registered: <module '_pytest.python' from 'c:\python27\lib\site-packages\
_pytest\python.pyc'>
PLUGIN registered: <module '_pytest.pdb' from 'c:\python27\lib\site-packages\_py
test\pdb.pyc'>
PLUGIN registered: <module '_pytest.unittest' from 'c:\python27\lib\site-package
s\_pytest\unittest.pyc'>
PLUGIN registered: <module '_pytest.capture' from 'c:\python27\lib\site-packages
\_pytest\capture.pyc'>
PLUGIN registered: <module '_pytest.skipping' from 'c:\python27\lib\site-package
s\_pytest\skipping.pyc'>
PLUGIN registered: <module '_pytest.tmpdir' from 'c:\python27\lib\site-packages\
_pytest\tmpdir.pyc'>
PLUGIN registered: <module '_pytest.monkeypatch' from 'c:\python27\lib\site-pack
ages\_pytest\monkeypatch.pyc'>
PLUGIN registered: <module '_pytest.recwarn' from 'c:\python27\lib\site-packages
\_pytest\recwarn.pyc'>
PLUGIN registered: <module '_pytest.pastebin' from 'c:\python27\lib\site-package
s\_pytest\pastebin.pyc'>
PLUGIN registered: <module '_pytest.helpconfig' from 'c:\python27\lib\site-packa
ges\_pytest\helpconfig.pyc'>
PLUGIN registered: <module '_pytest.nose' from 'c:\python27\lib\site-packages\_p
ytest\nose.pyc'>
PLUGIN registered: <module '_pytest.assertion' from 'c:\python27\lib\site-packag
es\_pytest\assertion\__init__.pyc'>
PLUGIN registered: <module '_pytest.genscript' from 'c:\python27\lib\site-packag
es\_pytest\genscript.pyc'>
PLUGIN registered: <module '_pytest.junitxml' from 'c:\python27\lib\site-package
s\_pytest\junitxml.pyc'>
PLUGIN registered: <module '_pytest.resultlog' from 'c:\python27\lib\site-packag
es\_pytest\resultlog.pyc'>
PLUGIN registered: <module '_pytest.doctest' from 'c:\python27\lib\site-packages
\_pytest\doctest.pyc'>
PLUGIN registered: <module '_pytest.cacheprovider' from 'c:\python27\lib\site-pa
ckages\_pytest\cacheprovider.pyc'>
PLUGIN registered: <_pytest.capture.CaptureManager instance at 0x02CBE940>
PLUGIN registered: <Session 'emikhail'>
PLUGIN registered: <_pytest.cacheprovider.LFPlugin instance at 0x02C73FD0>
PLUGIN registered: <_pytest.terminal.TerminalReporter instance at 0x02CD5760>
PLUGIN registered: <_pytest.python.FixtureManager instance at 0x02CE6760>
============================= test session starts =============================
platform win32 -- Python 2.7.8, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
using: pytest-2.9.1 pylib-1.4.31
active plugins:
    cacheprovider       : c:\python27\lib\site-packages\_pytest\cacheprovider.py
c
    helpconfig          : c:\python27\lib\site-packages\_pytest\helpconfig.pyc
    pytestconfig        : <_pytest.config.Config object at 0x021CCA70>
    runner              : c:\python27\lib\site-packages\_pytest\runner.pyc
    unittest            : c:\python27\lib\site-packages\_pytest\unittest.pyc
    pastebin            : c:\python27\lib\site-packages\_pytest\pastebin.pyc
    skipping            : c:\python27\lib\site-packages\_pytest\skipping.pyc
    genscript           : c:\python27\lib\site-packages\_pytest\genscript.pyc
    session             : <Session 'emikhail'>
    lfplugin            : <_pytest.cacheprovider.LFPlugin instance at 0x02C73FD0
>
    tmpdir              : c:\python27\lib\site-packages\_pytest\tmpdir.pyc
    capture             : c:\python27\lib\site-packages\_pytest\capture.pyc
    terminalreporter    : <_pytest.terminal.TerminalReporter instance at 0x02CD5
760>
    assertion           : c:\python27\lib\site-packages\_pytest\assertion\__init
__.pyc
    mark                : c:\python27\lib\site-packages\_pytest\mark.pyc
    terminal            : c:\python27\lib\site-packages\_pytest\terminal.pyc
    main                : c:\python27\lib\site-packages\_pytest\main.pyc
    nose                : c:\python27\lib\site-packages\_pytest\nose.pyc
    python              : c:\python27\lib\site-packages\_pytest\python.pyc
    recwarn             : c:\python27\lib\site-packages\_pytest\recwarn.pyc
    funcmanage          : <_pytest.python.FixtureManager instance at 0x02CE6760>

    monkeypatch         : c:\python27\lib\site-packages\_pytest\monkeypatch.pyc
    resultlog           : c:\python27\lib\site-packages\_pytest\resultlog.pyc
    33671408            : <_pytest.config.PytestPluginManager object at 0x0201C8
F0>
    capturemanager      : <_pytest.capture.CaptureManager instance at 0x02CBE940
>
    junitxml            : c:\python27\lib\site-packages\_pytest\junitxml.pyc
    doctest             : c:\python27\lib\site-packages\_pytest\doctest.pyc
    pdb                 : c:\python27\lib\site-packages\_pytest\pdb.pyc
rootdir: C:\Users\el, inifile:
collected 0 items / 1 errors
```

**Comment by The-Compiler** [comment] 2016-03-30 20:15
Hmm, it seems the locations are correct, I wonder if you're just running into #1479 here.

(by the way - I edited your post to add ``` around your output so it's interpreted as a literal code block)

**Comment by The-Compiler** [comment] 2016-03-31 10:59
Since this seems to be caused by https://github.com/allure-framework/allure-python/issues/92 in your case, closing this as a duplicate of #1479.

**Closed by The-Compiler** 2016-03-31 10:59 UTC
