### ISSUE TITLE
using yield in a test causes -k EXPRESSION not to work properly.

### ISSUE THREAD

**Issue by dnozay** [pytest-dev/pytest#2066] opened 2016-11-16 23:46 UTC
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [x] Include a detailed description of the bug or suggestion
When I use `yield` in a testcase, that confuses the test runner and it executes the testcase, even though I provided `-k EXPRESSION` on the command line.

- [x] `pip list` of the virtual environment you are using
```
(foobar)/tmp/dummy > (4) pip list
pip (7.1.2)
py (1.4.31)
pytest (3.0.4)
setuptools (18.2)
wheel (0.24.0)
```

- [x] pytest and operating system versions
```
(foobar)/tmp/dummy > (4) uname -v
Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64
```

- [x] Minimal example if possible
```python
# tests.py
def test_do_not_execute():
    1/0
    yield 1/0

def test_to_execute():
    pass
```

```
(foobar)/tmp/dummy > (4) py.test -v tests.py  -k test_to_execute 
========================================================= test session starts =========================================================
platform darwin -- Python 2.7.10, pytest-3.0.4, py-1.4.31, pluggy-0.4.0 -- /private/tmp/dummy/foobar/bin/python
cachedir: .cache
rootdir: /private/tmp/dummy, inifile: 
collected 1 items / 1 errors 

=============================================================== ERRORS ================================================================
______________________________________________________ ERROR collecting tests.py ______________________________________________________

    def test_do_not_execute():
>       1/0
E       ZeroDivisionError: integer division or modulo by zero

tests.py:3: ZeroDivisionError
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================= 1 error in 0.10 seconds =======================================================
```

**Comment by The-Compiler** [comment] 2016-11-17 05:49
pytest used to have yield-tests (deprecated in 3.0) which means you could yield multiple testcases from one test function, causing them to be collected as individual tests.

This means pytest needs to run those yield-tests (not the *actual* tests, but the test function) during collection, which is what you see happening here.

In other words, I think this is intended behavior - why are you using `yield` in a test? Is it for yield-tests?

**Comment by dnozay** [comment] 2016-11-17 17:28
Thanks for the clarification.

If `yield`-tests are run during collection, then they are effectively not filtered by the `-k EXPRESSION` option; we could argue that those tests should not be generated if the test function didn't match the filter.

Why am I using `yield` in a test? I have inherited some code that was ported from `nose` which does use test generators. http://nose.readthedocs.io/en/latest/writing_tests.html#test-generators

If the behavior w.r.t collection is documented, then please close.

**Comment by RonnyPfannschmidt** [comment] 2016-11-18 06:42
its documented, deprecated and warned about, we actually want to remove yield tests in 4.0

**Comment by nicoddemus** [comment] 2016-11-27 16:58
@dnozay if probably want to convert those tests to use `pytest.mark.parametrize` instead. We would be happy to help if you post the actual test code.

Closing this then.

**Closed by nicoddemus** 2016-11-27 16:58 UTC
