### ISSUE TITLE
Pytest 4.2.0 seems to break django's @override_settings

### ISSUE THREAD

**Issue by diox** [pytest-dev/pytest#4704] opened 2019-02-01 10:12 UTC
Upgrading to Pytest 4.2.0 broke our tests: https://github.com/mozilla/addons-server/pull/10556

The issue looked strange - it seemed like django's [`@override_settings` ](https://docs.djangoproject.com/en/2.1/topics/testing/tools/#django.test.override_settings)persisted from one class to the next instead of being reset, triggering those weird failures. I've bisected it down to https://github.com/pytest-dev/pytest/commit/0f918b1a9dd14a2d046d19be6ec239e8e2df4cb2 - before that commit, everything works fine.

Our pip list is huge, I'm working on a reduced testcase (**edit:** see https://github.com/pytest-dev/pytest/issues/4704#issuecomment-459692279), but this is with:
```
pytest                         4.2.0
Django                         1.11.18 
pytest-django                  3.4.5

Python 2.7.15 and 3.6.8
Debian stretch
```

I don't think the version of pytest-django matters here, and since I've bisected it down to a pytest commit I'm filing it here.

**Comment by diox** [comment] 2019-02-01 10:14
Note: I've seen https://github.com/pytest-dev/pytest/issues/4700 but we don't have skipped classes. I've tried applying https://github.com/pytest-dev/pytest/pull/4703 but it didn't have any impact, the issue persisted.

**Comment by nicoddemus** [comment] 2019-02-01 10:47
Hi @diox,

Thanks for the detailed report, we really appreciate it.

I'm happy to investigate this later, meanwhile could you please post a minimal reproducible example if you can? 

I've zero experience with pytest-django, so would appreciate if @pytest-dev/pytest-django-developers and @pytest-dev/pytest-django-admin could take a look as well.

**Comment by blueyed** [comment] 2019-02-01 11:20
@diox 
Are you using `@override_settings` (from Django), or the `settings` wrapper from pytest-django?  (https://github.com/pytest-dev/pytest-django/blob/fe6ddb8c7086accdb9d82746908538a7f805ad70/pytest_django/fixtures.py#L322-L329)

**Comment by blueyed** [comment] 2019-02-01 11:37
Maybe pytest-django's method for handling Django unittests needs to be adjusted for the new behavior/code in pytest?
It was introduced initially in https://github.com/pytest-dev/pytest-django/commit/96f5fb1817285fbf9ef9b0de89c5190d134f845a.  I have no time to investigate currently though.

**Comment by diox** [comment] 2019-02-01 11:46
Interesting, it seems to be working without `pytest-django`. With the following patch applied to my testcase repo (need to `pip uninstall pytest-django` first if installed already), tests are passing:
```diff
diff --git a/conftest.py b/conftest.py
new file mode 100644
index 0000000..075048d
--- /dev/null
+++ b/conftest.py
@@ -0,0 +1,6 @@
+import pytest
+
+@pytest.mark.trylast
+def pytest_configure():
+    import django
+    django.setup()
diff --git a/requirements.txt b/requirements.txt
index efa3723..b2adbb8 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -8,7 +8,6 @@ pkg-resources==0.0.0
 pluggy==0.8.1
 py==1.7.0
 pytest==4.2.0
-pytest-django==3.4.5
 pytz==2018.9
 scandir==1.9.0
 six==1.12.0
```

**Comment by blueyed** [comment] 2019-02-01 12:10
Good to know.. so likely a bug/issue caused by pytest-django then.

I am releasing pytest-django 3.4.6, which disallows pytest 4.2.0 (I've hoped this could be fixed in pytest 4.2.1, which is still the case maybe, but it might have been better to use `<4.2` instead).

**Comment by nicoddemus** [comment] 2019-02-01 12:51
Let's close this then; if further debugging reveals we need to change pytest, we can re-open or create a new issue. 👍

**Closed by nicoddemus** 2019-02-01 12:51 UTC
Labels: topic: fixtures, type: regression

**Comment by blueyed** [comment] 2019-02-01 20:11
It turns out that pytest and pytest-django do a similar thing here, ending in the methods being called twice.
Skipping the processing in pytest-django for `pytest.__version__ <= '4.2'` fixes it there (https://github.com/pytest-dev/pytest-django/pull/700).

1. Is the version check sane? (i.e. comparing it to a string; IIRC there was something in this regard lately)
2. I do not fully grasp currently what pytest-django is doing, but maybe pytest's method could be made compatible to it?  (likely not though)

**Comment by nicoddemus** [comment] 2019-02-01 20:21
Cool finding @blueyed.

1. Comparing versions with strings is not a good idea, I suggest using `from pkg_resources import parse_version` instead:

   ```python
   parse_version(pytest.__version__) < parse_version('4.2')
   ``` 

2. Probably not; if it is trying to "fix" the same problem pytest fixes, then just skipping it on based on pytest version seems better, because you can rip that code out when dropping support for pytest < 4.2 in a few years.
