### ISSUE TITLE
Injecting class into a package using monkeypatch.setattr requires raising=False

### ISSUE THREAD

**Issue by Dowwie** [pytest-dev/pytest#904] opened 2015-07-30 10:34 UTC
When attempting to monkeypatch.setattr a class into a package, unless I explicitly set raising=False, I cannot temporarily add the class to the package.  I've set up an example repo to illustrate. See the /test directory, line 8 in test.py:

https://github.com/Dowwie/pytestclsinjectionissue

**Comment by The-Compiler** [comment] 2015-07-30 11:03
That sounds like the intended behaviour of `raising` (which is `True` by default) to me. Why is that unexpected?

**Comment by RonnyPfannschmidt** [comment] 2015-07-30 11:16
the problem is with `monkeypatch.setattr('module.Foo', replacement, raising=False)` when `Foo` doesn't exist

**Comment by The-Compiler** [comment] 2015-07-30 11:22
@RonnyPfannschmidt The reporter says "unless I explicitly set raising=False", so that doesn't seem to be the issue. The issue you're describing (#746) was fixed by me in ff8d787cd51efa1ab6afccc882877cd686abe0cf already.

**Comment by RonnyPfannschmidt** [comment] 2015-07-30 11:25
oh, then its miss-understanding on my side testing based on the last release,
then indeed, the issue #746 is the correct solution

the communication with @Dowwie wasn't clear on irc due to my time constraint so i asked him to open a issue so a correct clarification can be done later

Thanks for pointing out the implementation

**Closed by RonnyPfannschmidt** 2015-07-30 11:25 UTC
Labels: easy
