### ISSUE TITLE
Outdated PDF documentation

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#1253] opened 2015-12-11 08:45 UTC
http://pytest.org/latest/pytest.pdf is still on 2.7.1.

**Comment by nicoddemus** [comment] 2015-12-11 09:13
Thanks for noticing Florian. HOWTORELEASE is written like PDF generation is
an optional step though, we should update that.

I'm curious though, do people even use that nowadays?

Em sex, 11 de dez de 2015 06:45, Florian Bruhin <notifications@github.com>
escreveu:

**Comment by The-Compiler** [comment] 2015-12-11 09:31
I do sometimes - I find the online documentation quite hard to navigate (and didn't get to improving that yet), so I think the PDF is a nice way to get an overview of everything.

(As an example: "Customize" is not listed in "Contents", "Usages and Examples" has a lot of important basic documentation at the top which is not apparent inside "Contents" at all, etc.)

**Comment by nicoddemus** [comment] 2015-12-11 10:54
Yeah, I agree our documentation would benefit from a restructuring (as you mention in #1112).

**Comment by The-Compiler** [comment] 2015-12-11 11:47
Oh, I entirely forgot about that issue :laughing:

**Comment by nicoddemus** [comment] 2016-04-13 20:46
Closing as duplicate of #1436

**Closed by nicoddemus** 2016-04-13 20:46 UTC
