### ISSUE TITLE
Giving `file_or_dir` twice collects tests twice

### ISSUE THREAD

**Issue by htgoebel** [pytest-dev/pytest#1187] opened 2015-11-22 20:41 UTC
When passing the same directory twice to py.test, all tests are run twice. The same is true if passing a sub-directory and a parent-directory:

`$ python3 -m py.test --collect-only tests/              | grep collected`
collecting ... collected **338 items**
`$ python3 -m py.test --collect-only tests/ tests/      | grep collected`
collecting ... collected **676 items**
`$ python3 -m py.test --collect-only tests/unit/ tests/ | grep collected`
collecting ... collected **418 items**

platform linux -- Python 3.4.3, pytest-2.8.3, py-1.4.30, pluggy-0.3.1 -- /usr/bin/python3

Rationale: I want to run the unit-test (which are in a certain directory) prior to he other ones. Thus I put the `tests/unit` directory in front, but this gave me duplicate tests.

**Comment by nicoddemus** [comment] 2015-11-23 17:41
Thanks for the report @htgoebel!

I had used this behavior of collecting tests more than once from the command-line in order to run the same test multiple times to track down some flaky behavior, but I think my use-case is a little contrived and yours makes more sense IMO.

Any more thoughts, @hpk42 @RonnyPfannschmidt @The-Compiler?

**Comment by The-Compiler** [comment] 2015-11-23 18:15
I usually do something like `while (($? == 0)); do py.test -k 'test_foo'; done` in that case... I guess I should write a `pytest-repeat` plugin :laughing: 

I don't really have an opinion on this, I can find arguments for and against both behaviours, and I'd be fine with both.

**Comment by hpk42** [comment] 2015-11-24 08:05
don't have a strong opinion either but if in doubt i'd rather not change the default and better introduce a ``--drop-duplicate`` option or so.  Maybe it's even better to write a ``pytest-drop-duplicates`` plugin which, when installed, will drop duplicates?  It's easy to implement through the ``pytest_collect_modifyitems`` hook, basically a plugin with 20 lines of code or so.

**Comment by RonnyPfannschmidt** [comment] 2015-11-24 08:37
I'm for the plugin solution

**Comment by htgoebel** [comment] 2015-11-24 11:56
Plugin sounds complicated. So I'm for a plugin `keep-duplicates`.

**Comment by RonnyPfannschmidt** [comment] 2015-11-24 12:03
a propperly separate `keep-duplicates` plugin would be impossible to do cleanly since the duplicates would be gone by the time it gets to the plugin

**Comment by nicoddemus** [comment] 2015-11-24 17:41
Making a plugin is actually really easy using the [cookiecutter-pytest-plugin](https://github.com/pytest-dev/cookiecutter-pytest-plugin), in fact just made one myself to quickly see it in action.

@htgoebel, could you try it out? If all is well I can publish it to PyPI, it still needs more tests and README. To install it use:

```
pip install git+https://github.com/nicoddemus/pytest-drop-dup-tests.git
```

No other configuration is necessary.

**Comment by RonnyPfannschmidt** [comment] 2015-11-24 19:45
i'm closing this as working as intended given that @nicoddemus already finished a plugin

**Closed by RonnyPfannschmidt** 2015-11-24 19:45 UTC
Labels: collection

**Comment by nicoddemus** [comment] 2015-11-24 20:14
Btw kudos to @hackebrot, it took me 10 minutes to have that plugin working, well done! Makes it really simple to create new plugins, covering a lot of the boiler plate of setting up a new repository, setup.py, etc etc, highly recommended.

**Comment by htgoebel** [comment] 2015-11-24 20:20
@nicoddemus The plugin does not show any effect here. I still get duplicates.

**Comment by nicoddemus** [comment] 2015-11-24 20:24
Can you show me the output of a sample session?

**Comment by htgoebel** [comment] 2015-11-24 20:43
It is the same as in my very fist comment here. I used `--traceconfig` to verified the plugin is loaded:
```
$ rm -rf /tmp/pytest-* ; python3 -m py.test --collect-only --traceconfig tests/unit/ tests/ | grep -P 'collected|-dup-'
  pytest-drop-dup-tests-0.1.0 at /home/xxx/.local/lib/python3.4/site-packages/pytest_drop_dup_tests.py
    drop-dup-tests      : /home/xxx/.local/lib/python3.4/site-packages/pytest_drop_dup_tests.py
plugins: drop-dup-tests-0.1.0
collected 418 items
```

**Comment by hackebrot** [comment] 2015-11-24 20:56
Thank you @nicoddemus! :bow: Happy to hear that :smile_cat:

**Comment by nicoddemus** [comment] 2015-11-24 21:05
@htgoebel hmm that's strange. I will investigate this later (most probably tomorrow). I moved over this discussion over to nicoddemus/pytest-drop-dup-tests#2

**Comment by foxx** [comment] 2016-01-05 22:44
Just came up against this problem, I'm confused why this functionality has to be placed into a separate plugin, why can't it be submitted as a `pytest` patch? Surely collecting tests twice, when given a directory to look for tests, would be considered a bug?

**Comment by nicoddemus** [comment] 2016-01-06 01:24
Mostly because it is a behavior change and no one seemed to have a strong opinion for it... the change is trivial, as the plugin demonstrates. If more people are in favor of changing the behavior, I would gladly merge it into the core. :smile:

**Comment by foxx** [comment] 2016-01-06 10:21
Ah okay. I'm struggling to think of a scenario where allowing duplicates would be considered an advantage. Can someone give me an example of where this behaviour might be desired? If not, I'd vote for re-opening this for merge into the core. 

PS) It turns out my duplication issue was caused by different bug, which I've raised in another issue.

**Comment by The-Compiler** [comment] 2016-01-06 10:29
@foxx Check the history of this discussion - e.g. to run the same test multiple times to track down some flaky behaviour.

**Comment by foxx** [comment] 2016-01-06 10:56
> I had used this behavior of collecting tests more than once from the command-line in order to run the same test multiple times to track down some flaky behavior, but I think my use-case is a little contrived and yours makes more sense IMO.

I might have misinterpreted the use case, but I'd argue that if a test suite is producing different results on each run, with no actual change to any of the code, then the tests are broken. 

That being said, most of the GNU core utils do not have any sort of de-duplication, for example if you run `cat /etc/issue /etc/issue` the file will be outputted twice. The same goes for `find tests/ tests/`, and `ls /etc/passwd /etc/passwd`.

In fact it could be argued that changing the behaviour to be different than the standard of most other utilities, would be the wrong thing to do. 

In my situation, the problem was caused by a bug with `setup.cfg` handling (see #1311), and de-duplication would actually have hidden the problem, rather than fix it.

On that basis, I'm changing my vote to -1

**Comment by The-Compiler** [comment] 2016-01-07 17:24
@nicoddemus FYI, for your usecase: I just wanted to write a `pytest-repeat` and then noticed [it already exists](https://github.com/bobsilverberg/pytest-repeat) :laughing:

**Comment by nicoddemus** [comment] 2016-01-07 17:51
:laughing: thanks

**Comment by LewisGaul** [comment] 2020-05-23 13:53
FWIW I'd like to see this implemented in core pytest, so just giving my +1 here.

See https://github.com/nicoddemus/pytest-drop-dup-tests/issues/5 for my use-case and issue with the plugin approach (although thanks to niccodemus for making the plugin usable for my case!).
