### ISSUE TITLE
UsageError in package that contains pytest_plugins module

### ISSUE THREAD

**Issue by kohr-h** [pytest-dev/pytest#3899] opened 2018-08-28 09:30 UTC
When running `pytest --doctest-modules` on a package that contains a pytest plugin, `pytest` errors out and produces a pretty long stacktrace. The code that triggers the error is the `_get_plugin_specs_as_list` function that receives a module object instead of a list or a string.

The behavior is OS-independent as far as I can tell, but affects only pytest 3.7+ ; pytest 3.6.4 works fine. Also note that the error is *only* triggered when doc-testing the specific subpackage that contains the plugin.

For proper context, we have the following directory structure:
```
odl
 |
 |- util --
 |        |- pytest_plugins.py
 |        |- ...
 | - ...
```
The error is triggered by `pytest --doctest-modules odl/util`.

The full backtrace is [here](https://gist.github.com/kohr-h/0899f6e87262de1f16e409e46f46c1e2).
Link to the subpackage: https://github.com/odlgroup/odl/tree/master/odl/util

Edit: Updated pytest versions affected

**Comment by kohr-h** [comment] 2018-09-15 14:40
Update: all 3.7 versions and 3.8.0 show this behavior.

**Comment by blueyed** [comment] 2019-01-17 21:17
From the traceback (please consider putting those in the issues themselves for searchability etc):
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_pytest.config.PytestPluginManager object at 0x0000000002B84240>
mod = <module 'odl.util' from '[...]\\odl\\util\\__init__.py'>

    def consider_module(self, mod):
>       self._import_plugin_specs(getattr(mod, "pytest_plugins", []))

[...]\_pytest\config\__init__.py:462:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_pytest.config.PytestPluginManager object at 0x0000000002B84240>
spec = <module 'odl.util.pytest_plugins' from '[...]\\odl\\util\\pytest_plugins.py'>

    def _import_plugin_specs(self, spec):
>       plugins = _get_plugin_specs_as_list(spec)

[...]\_pytest\config\__init__.py:465:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

specs = <module 'odl.util.pytest_plugins' from '[...]\\odl\\util\\pytest_plugins.py'>

    def _get_plugin_specs_as_list(specs):
        """
        Parses a list of "plugin specs" and returns a list of plugin names.

        Plugin specs can be given as a list of strings separated by "," or already as a list/tuple in
        which case it is returned as a list. Specs can also be `None` in which case an
        empty list is returned.
        """
        if specs is not None:
            if isinstance(specs, str):
                specs = specs.split(",") if specs else []
            if not isinstance(specs, (list, tuple)):
                raise UsageError(
                    "Plugin specs must be a ','-separated string or a "
>                   "list/tuple of strings for plugin names. Given: %r" % specs
                )
E               _pytest.config.exceptions.UsageError: Plugin specs must be a ','-separated string or a list/tuple of strings for plugin names. Given: <module 'odl.util.pytest_plugins' from '[...]\\odl\\util\\pytest_plugins.py'>

[...]\_pytest\config\__init__.py:518: UsageError
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[...]\_pytest\_code\source.py:341: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --fulltrace)
========================== 12 error in 5.32 seconds ===========================
```

It looks like `odl.util.pytest_plugins` is expected to be a list, but is a
module:

```

self = <_pytest.config.PytestPluginManager object at 0x0000000002B84240>
mod = <module 'odl.util' from '[...]\\odl\\util\\__init__.py'>

    def consider_module(self, mod):
>       self._import_plugin_specs(getattr(mod, "pytest_plugins", []))

[...]\_pytest\config\__init__.py:462:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_pytest.config.PytestPluginManager object at 0x0000000002B84240>
spec = <module 'odl.util.pytest_plugins' from '[...]\\odl\\util\\pytest_plugins.py'>

    def _import_plugin_specs(self, spec):
>       plugins = _get_plugin_specs_as_list(spec)
```

I don't know the internals really, but it looks like pytest should skip / not consider this?!

**Comment by blueyed** [comment] 2019-01-17 21:18
While it seems to be clear what the issue is, it might still be useful to git-bisect it.

> only pytest 3.7+ ; pytest 3.6.4 works fine

**Comment by nicoddemus** [comment] 2019-01-17 21:21
We should probably issue a warning instead, instead of ignoring it.

**Comment by kohr-h** [comment] 2019-01-29 12:51
I'm not sure if ignoring and/or warning is desirable here since the `pytest_plugins` module contains some package-global fixtures that should be used, in particular the one to amend the doctest namespace.

What do you think is the root cause of the error? Are we using plugins in an unintended or unsupported way?

**Comment by blueyed** [comment] 2019-01-29 21:02
@kohr-h 
You could git-bisect it to see where/why it was changed.

**Comment by nicoddemus** [comment] 2019-01-29 21:13
> What do you think is the root cause of the error? Are we using plugins in an unintended or unsupported way?

The cause seems to be that you have a module named `pytest_plugins` [in `odl/util`](https://github.com/odlgroup/odl/tree/master/odl/util). Since pytest 3.8 we now collect `__init__.py` files.

This part of the traceback:

```
self = <_pytest.config.PytestPluginManager object at 0x0000000002B84240>
mod = <module 'odl.util' from '[...]\\odl\\util\\__init__.py'>

    def consider_module(self, mod):
>       self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
``` 

Indicates that `odl.util` is importing the `pytest_plugins.py` module into its namespace, which is triggering the error, because `pytest_plugins` is a [special variable](https://docs.pytest.org/en/latest/reference.html#pytest-plugins).

I don't see `pytest_plugins.py` being imported into `odl.util` though...

**Comment by RonnyPfannschmidt** [comment] 2019-01-30 05:36
@nicoddemus the testutils sibling module imports it, so the python import system adds the name to the module

**Comment by nicoddemus** [comment] 2019-01-30 11:42
You mean this import?

https://github.com/odlgroup/odl/blob/ef8193ed5a51c410ed6d4eff6280d362fbf22421/odl/util/testutils.py#L658

Weird, didn't know just by importing a module it would become an attribute of the parent package object, even though the parent package never imports the sibling module in its `__init__.py`... 🤔

**Comment by RonnyPfannschmidt** [comment] 2019-01-30 12:09
@nicoddemus its what makes `import foo.bar.baz` work as well as how namespace packages are filled with objects

**Comment by nicoddemus** [comment] 2019-01-30 13:22
Indeed, cool, didn't know about that fact. Thanks!

**Comment by kohr-h** [comment] 2019-02-04 20:47
@nicoddemus @RonnyPfannschmidt @blueyed Thanks for looking into this. I thinks the issue sits deep and one has to be somewhat unlucky to hit it. So I think we'll just change the name of the module. I can confirm that giving it some other name solves the problem.

The [documentation](https://docs.pytest.org/en/latest/plugins.html#installing-and-using-plugins) on plugins doesn't mention the case discussed here. If you think it's worth giving it a brief mention, I can add a sentence to the docs.

**Comment by nicoddemus** [comment] 2019-02-06 01:47
Meanwhile I'm closing this issue. 👍

**Comment by nicoddemus** [comment] 2019-02-06 01:55
Actually we should not raise that error if `pytest_plugins` is a module...

**Closed** 2019-02-06 14:22 UTC
