### ISSUE TITLE
Test collection in directories when files from them also specified

### ISSUE THREAD

**Issue by Alexander-Shukaev** [pytest-dev/pytest#12550] opened 2024-07-01 13:32 UTC
If on the command line Pytest is given directories from where to collect tests and also some individual files from some of these directories, then it appears that such directories are skipped and only those individual files are collected.  I would expect a file specification to be just a duplicate in this case that should be filtered out and instead all files from its directory to be collected instead since the directory was specified in the first place.

**Comment by bluetech** [comment] 2024-07-09 17:57
This is a duplicate of #12083.

**Closed by bluetech** 2024-07-09 17:57 UTC
Labels: topic: collection
