### ISSUE TITLE
"usage of Generator.Function is deprecated" error coming from PyTest code, not ours

### ISSUE THREAD

**Issue by nickwilliams-eventbrite** [pytest-dev/pytest#4400] opened 2018-11-15 17:26 UTC
We upgraded one of our projects to PyTest 4.0.0, and our builds started failing with this deprecation error. We're filtering out the warning for now to get our build running, because there's nothing we can do about it. The warning isn't coming from our code. As you can see from the stacktrace below, the warning is coming from PyTest code.

```
self = <CallInfo when='collect' exception: usage of Generator.Function is deprecated, please use pytest.Function instead>
func = <function <lambda> at 0x7fa771266d70>, when = 'collect'
treat_keyboard_interrupt_as_exception = False

    def __init__(self, func, when, treat_keyboard_interrupt_as_exception=False):
        #: context of invocation: one of "setup", "call",
        #: "teardown", "memocollect"
        self.when = when
        self.start = time()
        try:
>           self.result = func()

../venv/lib/python2.7/site-packages/_pytest/runner.py:211: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../venv/lib/python2.7/site-packages/_pytest/runner.py:272: in <lambda>
    call = CallInfo(lambda: list(collector.collect()), "collect")
../venv/lib/python2.7/site-packages/_pytest/python.py:769: in collect
    function_class = self.Function
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = _CompatProperty(name='Function')
obj = <Generator 'test_parse_valid_tokens'>
owner = <class '_pytest.python.Generator'>

    def __get__(self, obj, owner):
        if obj is None:
            return self
    
        from _pytest.deprecated import COMPAT_PROPERTY
    
        warnings.warn(
>           COMPAT_PROPERTY.format(name=self.name, owner=owner.__name__), stacklevel=2
        )
E       RemovedInPytest4Warning: usage of Generator.Function is deprecated, please use pytest.Function instead

../venv/lib/python2.7/site-packages/_pytest/nodes.py:70: RemovedInPytest4Warning
```

Information from the test startup:

```
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-4.0.0, py-1.7.0, pluggy-0.8.0
django settings: xxxxxxxxxxxx (from ini file)
rootdir: xxxxxxxxxxxxxxx, inifile: setup.cfg
plugins: django-2.9.1, forked-0.2, pysoa-0.55.0, mock-1.10.0, cov-2.6.0, xdist-1.24.1
```

Here's a quick checklist in what to include:

- [x] Include a detailed description of the bug or suggestion
- [x] `pip list` of the virtual environment you are using (I've shared what I can without divulging confidential information)
- [x] pytest and operating system versions
- [ ] Minimal example if possible (Not possible because I don't know what exactly causes this to replicate and I can't share the project)

**Comment by nicoddemus** [comment] 2018-11-15 18:16
The error happens inside pytest because when you turn errors into warnings the exception is raised by the calling code, but the cause of the exception is still because there are `yield` tests in your testing code. Look for the `yield` keyword in your tests directory and I'm sure you will find those. 👍 

Closing this for now, but feel free to follow up with further questions.

**Comment by nickwilliams-eventbrite** [comment] 2018-11-15 18:30
I'm both confused and not sure I agree with your assessment. I get that the error is due to the flag turning warnings into errors. That's fine. My concern is sussing out the source of the warning in the first place. I'm confused because the warning says nothing about `yield` statements. The warning says that something is using `Generator.Function`, which is deprecated and has been replaced with `pytest.Function`. I'm in disagreement because the stack trace says that `_pytest/python.py` is the code using `Generator.Function` in violation of the deprecation.

**Comment by nicoddemus** [comment] 2018-11-15 18:35
Oh I'm sorry, I read your post on the run and assumed it was related to `yield` tests.

I'm still on the run so I will have to look into this with more detail later, but meanwhile perhaps other maintainers can help out.

**Comment by nicoddemus** [comment] 2018-11-15 18:35
Can you also post the entire traceback please?

**Comment by nickwilliams-eventbrite** [comment] 2018-11-15 18:36
Yes, the entire traceback is posted above in the issue body. That's all there was. There was no other traceback above or below that.

**Comment by RonnyPfannschmidt** [comment] 2018-11-15 18:48
the broken test is called `test_parse_valid_tokens`

**Comment by RonnyPfannschmidt** [comment] 2018-11-15 18:51
we also ought to take a look why its not blowing up while collecting the generator itself

**Comment by nickwilliams-eventbrite** [comment] 2018-11-15 18:52
What about the test `test_parse_valid_tokens` is broken?

**Comment by RonnyPfannschmidt** [comment] 2018-11-15 18:53
@nickwilliams-eventbrite can you please show the output if you set up -rw - i suspect there is a incorrectly categorized deprecation which is why the real warning rror is missing

test_parse_valid_tokens is a yield based test - its a feature that has been deprecated since ages

is it possible your codebase has a warning filter that hides the deprecation about generators?

**Comment by RonnyPfannschmidt** [comment] 2018-11-15 18:55
https://github.com/pytest-dev/pytest/blob/master/src/_pytest/python.py#L767 that one strikes me as a strange mistake on our  part

**Comment by RonnyPfannschmidt** [comment] 2018-11-15 18:58
so we have 2 bugs there

- [ ] warning is triggered after error prone collect
- [ ] `Function` is not obtained using `self._getcustomclass`

i feel its necessary to put this into a bugfix release even tho we completely remove it in 4.1

**Comment by nickwilliams-eventbrite** [comment] 2018-11-15 18:59
We have the following filters:

```
    # FIXME: Ignored warnings, until we can use `pytest-django` >= 3.0.0
    ignore:MarkInfo objects are deprecated.*:DeprecationWarning
    ignore:getfuncargvalue is deprecated, use getfixturevalue.*:DeprecationWarning
    # FIXME: Ignored warnings, until we fix it in soa repository
    ignore:encoding is deprecated, Use raw=False instead:PendingDeprecationWarning
```

I don't think any of those would filter out a generator warning.

You were indeed right. That test was a generator test:

```
def test_parse_valid_tokens():
    for token in VALID_TOKENS:
        yield check_parse, token
```

Full disclosure: I've never seen that test before, so I'm admittedly playing catch-up here. What was the expected behavior of that test back when it _was_ supported (I've never seen a test do that before)?

**Comment by RonnyPfannschmidt** [comment] 2018-11-15 19:04
@nickwilliams-eventbrite that particular test looks like its a really simple transform to a parameterized test

```
@pytest.mark.parametrize('token', VALID_TOKENS)
def test_parse_valid_token(token):
    check_parse(token)
```

**Comment by nickwilliams-eventbrite** [comment] 2018-11-15 19:13
Okay. So the test as-is is a generator of tests, and the existing behavior (which is being removed in 4.1) was that it would iterate over the generator and run each test with the supplied arguments. Hence why replacing it with parameterization is the best course of action. Do I understand that correctly?

**Comment by RonnyPfannschmidt** [comment] 2018-11-15 19:15
correct - you are really lucky the test was stateless ^^

**Closed** 2018-11-17 23:57 UTC
Labels: type: question
