### ISSUE TITLE
Unable to debug plays when pytest numprocesses specified 

### ISSUE THREAD

**Issue by Sergii22** [pytest-dev/pytest#4672] opened 2019-01-23 21:06 UTC
**Unable to debug plays when pytest numprocesses specified** 
Hi all!
I have pytest framework which is using ansible==2.7.5 to operate with win/nix machines
When running code below with `--capture=no /test` getting ansible output and I'm able to run script with debug break points - screenshot is attached.
But when test is executed with `--capture=no numprocesses=1  /test` - there is no ansible output but all tasks are completed. Also, in case of debug it will get stuck on  tqm.run(play) forever.

**STR:**
Run code below with --capture=no numprocesses=1  /test 

```
class Test:
 def test(self):
        self.group = "win1"
        self.role = "node"
        self.operating_system = "Windows"
        self.ansible_host = "IP"
        self.ansible_user = "admin"
        self.ansible_password = "pass"

        self.loader = DataLoader()
        # initialization empty inventory to avoid using physical files as hosts.ini
        # console warn 'No inventory was parsed, only implicit localhost is available' is expected
        self.inventory_manager = InventoryManager(loader=self.loader, sources=[])

        # update inventory to use parsed values from env and vars from stub
        self.inventory_manager.add_group(self.group)
        self.inventory_manager.add_host(self.ansible_host, group=self.group)
        self.inventory_manager.groups[self.group].vars = self.var_stubs()

        self.variable_manager = VariableManager(loader=self.loader, inventory=self.inventory_manager)
        self.options_config = namedtuple('Options',
                                         ['connection', 'module_path', 'forks', 'become', 'become_method',
                                          'become_user',
                                          'check',
                                          'diff', 'listhosts'])
        self.options = self.options_config(connection=None, module_path=None, forks=10, become=None, become_method=None,
                                           become_user=None,
                                           check=False, diff=False, listhosts=None)
        self.stab = self.var_stubs()
        self.play_tasks(self.create_dir_a())
        self.play_tasks(self.create_dir_b())

    def var_stubs(self):
        """
        Method to gather all common variables required for playbooks
        :return: stub dictionary
        """
        return {
            "ansible_user": self.ansible_user,
            "ansible_password": self.ansible_password,
            "ansible_connection": "winrm" if self.operating_system == "Windows" else "ssh",
            "ansible_winrm_server_cert_validation": "ignore",
            "path_to_java_exe": "C:\\Program Files\\Java\\jdk1.8.0_191\\bin\\java.exe",
           }

    def create_dir_a(self):
        """
        This method to form playbook to create working directory for ansible
        :return: playbook dictionary
        """
        log.debug("Create working directory for ansible")

        playbook = dict(
            name="Create workidir for ansible",
            hosts=self.group,
            gather_facts='no',
            tasks=[
                dict(name="Create workdir", action=dict(module="win_file", path="aaa",
                                                        state="directory"))])

        return playbook

    def play_tasks(self, playbook):
        """
        Method to run playbooks
        :param playbook: dictionary with tasks
        """
        play = Play().load(playbook, variable_manager=self.variable_manager, loader=self.loader)
        tqm = TaskQueueManager(
            inventory=self.inventory_manager,
            variable_manager=self.variable_manager,
            loader=self.loader,
            options=self.options,
            passwords=None,
            stdout_callback='default'
        )

        tqm.run(play)

```
ACTUAL RESULT: 
There is no ansible output but all tasks are completed. 
NOTE: Also, in case of debug it will get stuck on  tqm.run(play) forever. 

EXPECTED RESULT:
Ansible output should be displayed and user should be able to use debug

PIP LIST:
```
Package              Version  
-------------------- ---------
ansible              2.7.5    
ansible-generator    1.1.0    
apipkg               1.5      
Appium-Python-Client 0.34     
asn1crypto           0.24.0   
astroid              2.0.4    
atomicwrites         1.2.1    
attrs                18.2.0   
autopep8             1.4.3    
bcrypt               3.1.4    
boto                 2.49.0   
cached-property      1.3.1    
certifi              2018.4.16
cffi                 1.11.2   
chardet              3.0.4    
colorama             0.3.7    
colorlog             2.7.0    
configparser         3.5.0    
cryptography         2.1.4    
ddt                  1.1.1    
decorator            4.1.2    
dill                 0.2.8.2  
EasyProcess          0.2.3    
execnet              1.5.0    
fabric               2.1.3    
Faker                1.0.1    
idna                 2.6      
invoke               1.1.0    
ipython-genutils     0.2.0    
isort                4.3.4    
Jinja2               2.8      
jsonschema           2.6.0    
jupyter-core         4.4.0    
lazy-object-proxy    1.3.1    
MarkupSafe           0.23     
mccabe               0.6.1    
more-itertools       4.3.0    
nbformat             4.4.0    
ndg-httpsclient      0.4.3    
ntlm-auth            1.2.0    
packaging            18.0     
paramiko             2.4.1    
pathlib2             2.3.3    
pip                  18.0     
plotly               2.1.0    
pluggy               0.8.0    
psutil               5.4.8    
py                   1.5.2    
pyasn1               0.4.2    
pycodestyle          2.4.0    
pycparser            2.18     
pylint               2.2.2    
pymongo              3.3.0    
PyNaCl               1.2.1    
pyOpenSSL            17.5.0   
pyparsing            2.2.0    
pytest               4.1.1    
pytest-forked        0.2      
pytest-instafail     0.4.0    
pytest-reportportal  1.0.4    
pytest-rerunfailures 4.1      
pytest-xdist         1.26.0   
python-dateutil      2.6.1    
python-dotenv        0.10.1   
pytz                 2016.6.1 
PyVirtualDisplay     0.2.1    
pywinrm              0.3.0    
PyYAML               3.13     
raven                6.9.0    
requests             2.21.0   
requests-ntlm        1.1.0    
retrying             1.3.3    
selenium             3.141.0  
setuptools           40.0.0   
six                  1.11.0   
SQLAlchemy           1.2.14   
text-unidecode       1.2      
tox                  2.5.0    
traitlets            4.3.2    
typed-ast            1.1.0    
urllib3              1.23     
virtualenv           16.0.0   
wheel                0.31.1   
wrapt                1.10.11  
xmltodict            0.11.0   
```
- pytest==4.1.1, pytest-xdist==1.26.0

SCREENSHOTS:
output with -n1:
<img width="585" alt="fail" src="https://user-images.githubusercontent.com/11478933/51636722-99da7e00-1f62-11e9-8254-fb24510c0b77.png">
output without n:
<img width="601" alt="pass" src="https://user-images.githubusercontent.com/11478933/51636735-a363e600-1f62-11e9-9498-d68e23e13355.png">

Please, let me know if any other info needed. Thanks in advance!

**Comment by nicoddemus** [comment] 2019-01-24 22:53
Hi @Sergii22,

This is a known issue: pytest-xdist uses `execnet` for orchestrating master/workers, and it uses stdout/stderr for communication. For this reason we can't transfer output from workers to the master node for reporting, unfortunately.

Closing as duplicate of: https://github.com/pytest-dev/pytest-xdist/issues/82

**Closed by nicoddemus** 2019-01-24 22:53 UTC
Labels: plugin: xdist, topic: reporting

**Comment by Sergii22** [comment] 2019-01-24 23:04
@nicoddemus, thanks for feedback!
