### ISSUE TITLE
pexpect using tests regulary hang/die

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2673] opened 2017-08-09 16:56 UTC
we pretty much have broken tests there,
whenever i have pexpect installed, py.test hangs testing terminal or pdb

**Comment by RonnyPfannschmidt** [comment] 2017-10-06 08:33
i keep hitting this one, i'm tempted to just remove pexpect since its all broken atm

**Comment by nicoddemus** [comment] 2017-10-06 10:22
That doesn't happen on CI though does it?

**Comment by RonnyPfannschmidt** [comment] 2017-10-06 12:01
yes, which makes it even more of a pain, since ithappens in tox/local usage and its typically due to badly set timeouts/interactions in each test

**Comment by nicoddemus** [comment] 2017-10-06 12:07
In this case I would think twice about removing it, specially if we can't pin point the actual cause *and* it currently passes on CI.

**Comment by RonnyPfannschmidt** [comment] 2017-10-06 12:37
what value does a test have, where we dont know why it works when it works

**Comment by nicoddemus** [comment] 2017-10-06 13:12
I thought the `pexpect` tests ensured that user interaction work as expected in situations like `--pdb`. I never took a deeper look at them though.

**Comment by RonnyPfannschmidt** [comment] 2017-12-17 14:13
@nicoddemus all i know that they regularly fall apart for me - and its starting to be really irritating

**Comment by srinivasreddy** [comment] 2017-12-18 17:22
I can confirm this on my local. 
![image](https://user-images.githubusercontent.com/198396/34118829-067fe530-e446-11e7-9e5c-181df6a6e5bb.png)

**Comment by stanislavlevin** [comment] 2018-03-22 14:32
ping

**Comment by RonnyPfannschmidt** [comment] 2018-03-22 14:39
it wont pong, its hanging

**Comment by blueyed** [comment] 2019-04-07 22:35
Is this still happening for you?

I've noticed "hacks" / code for Mac OS, but are you all using MacOS for when it happens/hangs?
(never seen it myself on Linux)

**Comment by blueyed** [comment] 2019-04-07 22:39
So if you're seeing this, please use `-vv` to see the test that hangs.. see https://github.com/pytest-dev/pytest/pull/3116 for a possible fix in this regard.

**Comment by nicoddemus** [comment] 2019-05-01 14:24
Closing as no more information has been provided. We can reopen once the suggestion by @blueyed has been tried. 👍

**Closed by nicoddemus** 2019-05-01 14:24 UTC
Labels: status: critical, status: needs information, type: bug, type: infrastructure

**Comment by blueyed** [comment] 2019-05-27 02:24
Turns out you have to `read()` with pending output before `wait()` - likely related to different behavior with regard to output buffering then maybe, but https://github.com/pytest-dev/pytest/pull/5313 should fix it.
