### ISSUE TITLE
marks should propogate through fixtures

### ISSUE THREAD

**Issue by majuscule** [pytest-dev/pytest#2399] opened 2017-05-10 06:42 UTC
Example code below. Expected output: passing tests. Actual output, AssertionError.

```python
import pytest

@pytest.fixture(scope='function', autouse=True)
def db_rollback(request):
    assert request.node.get_marker('db_rollback_exempt')

@pytest.fixture(scope='function')
@pytest.mark.db_rollback_exempt
def context():
    return True

def test_foo(context):
    assert True
```

**Comment by RonnyPfannschmidt** [comment] 2017-05-10 07:24
in #977 we already documented that this doesn't work

there are 2 problems keeping it that way
a) in any more complex fixture setup its completely unclear in what way to propagate marks, nobody sat down and made a reasonably complete proposal (that includes parametrisation)
b) the current implementation of marks and mark propagation is completely misfit for such a feature and would need a relatively large restructuring/rewrite

**Comment by nicoddemus** [comment] 2017-05-10 12:21
Should we close this then, or keep it open for reference?

**Comment by RonnyPfannschmidt** [comment] 2017-05-10 13:33
@nicoddemus i'd like to decide after feedback from @majuscule

**Comment by majuscule** [comment] 2017-05-10 19:46
Hi @RonnyPfannschmidt, @nicoddemus, thanks for the quick response. I'd like to keep this open as a feature request. Can you give an example of a complex fixture design (possibly with parametrization) that makes this difficult? I'm thinking that a mark should simply be inherited by any function that the marked fixture is provided to.

**Comment by RonnyPfannschmidt** [comment] 2017-05-14 10:00
oh, also im closing thos one as a duplicate of #1368

**Closed by RonnyPfannschmidt** 2017-05-14 10:00 UTC
Labels: feature-branch, mark-issue, proposal
