### ISSUE TITLE
Running tests with xdist can cause zombie processes

### ISSUE THREAD

**Issue by nShade** [pytest-dev/pytest#2498] opened 2017-06-13 11:08 UTC
I am running a script inside a Docker container, which periodically executes tests with pytest and xdist. It turns out that xdist is never terminates subprocesses that it creates and they remain running even after all tests are finished. These processes then become zombies inside the Docker container.

Here is the example script which can show the problem
```python 
import pytest

if __name__ == "__main__":
    pytest_exit_status = pytest.main('-n 10')

    import psutil

    current_process = psutil.Process()
    children = current_process.children(recursive=True)

    for child in children:
        print('Child pid is {}'.format(child.pid))
```

The output of it:
```
============================= test session starts ==============================
platform darwin -- Python 3.6.1, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /Users/nShade/PycharmProjects/untitled, inifile:
plugins: xdist-1.17.1, capturelog-0.7
gw0 I / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I / gw8 I / gw9 I
gw0 [0] / gw1 [0] / gw2 [0] / gw3 [0] / gw4 [0] / gw5 [0] / gw6 [0] / gw7 [0] / gw8 [0] / gw9 [0]

scheduling tests via LoadScheduling

Child pid is 5930
Child pid is 5931
Child pid is 5932
Child pid is 5933
Child pid is 5934
Child pid is 5935
Child pid is 5936
Child pid is 5937
Child pid is 5938
Child pid is 5939

Process finished with exit code 0
```
I thought it is because `ensure_teardown` method of `SlaveController` is never actually called, but calling it does't make any difference. The only solution (pretty ugly) I found so far is killing those subprocesses in pytest_sessionfinish hook:

```python
@pytest.mark.tryfirst
def pytest_sessionfinish(session):
    plugin = session.config.pluginmanager.getplugin("dsession")
    if plugin:
        for gw in plugin.nodemanager.group._gateways:
            # only this sequence works:
            gw._io.kill()
            gw._io.wait()
```

**Comment by The-Compiler** [comment] 2017-06-13 11:28
Errr... @RonnyPfannschmidt @nicoddemus I wanted to point @nShade to the [pytest-xdist issue tracker](https://github.com/pytest-dev/pytest-xdist/issues), but then I noticed its readme says ["Please use the pytest issue tracker for reporting bugs in this plugin."](https://github.com/pytest-dev/pytest-xdist#issue-and-bug-tracker) - is that just oudated?

**Comment by RonnyPfannschmidt** [comment] 2017-06-13 12:05
@The-Compiler nice find, that readme bit was totally forgotten

**Comment by nShade** [comment] 2017-06-13 16:02
I found the origin of the issue. It is in the execnet code, not the xdist.
Here is the description https://bitbucket.org/hpk42/execnet/issues/56/misusing-lambdas-in-multygroupterminate

**Comment by RonnyPfannschmidt** [comment] 2017-06-13 20:40
@nShade thanks for investigation, so this is due for sometime after moving execnet to github

**Comment by Zac-HD** [comment] 2020-09-26 11:28
Closing as duplicate of https://github.com/pytest-dev/execnet/issues/56, closed in https://github.com/pytest-dev/execnet/commit/e8eda7924dc441844b8e1756065d5657ad146649.

**Closed by Zac-HD** 2020-09-26 11:28 UTC
Labels: plugin: xdist, type: bug
