### ISSUE TITLE
docs about TestClassDemoInstance is wrong

### ISSUE THREAD

**Issue by haihit** [pytest-dev/pytest#8745] opened 2021-06-09 06:57 UTC
Something to be aware of when grouping tests inside classes is that each test has a unique instance of the class.
but the example TestClassDemoInstance show the same object ID
self = <test_class_demo.TestClassDemoInstance object at 0xdeadbeef>
self = <test_class_demo.TestClassDemoInstance object at 0xdeadbeef>
it should be different

**Comment by RonnyPfannschmidt** [comment] 2021-06-09 07:18
indeed, thats a known issue from regendoc (trying to make the addresses in docs stable)

**Comment by nicoddemus** [comment] 2021-06-09 11:10
Thanks @haihit, 

Duplicate of https://github.com/pytest-dev/pytest/issues/7646.

**Closed by nicoddemus** 2021-06-09 11:10 UTC
