### ISSUE TITLE
Fixture scope mixing?

### ISSUE THREAD

**Issue by richardasaurus** [pytest-dev/pytest#2732] opened 2017-08-30 10:12 UTC
I'm sure this must have come up before, but is there any plan to solve this issue?

```
ScopeMismatch: You tried to access the 'function' scoped fixture 'my_fixture' with a 'module' scoped request object, involved factories
```

Surely one fixture is per session or module, fixtures with a shorter lifespan (function scoped) with them should be permitted? 
As a user i'd expect the`function` scoped fixtures within a`module` scoped parent fixture to have their scope altered automatically `module`.

---

Currently to get around this i'm having to create many duplicate fixtures, with slightly different names and scopes, which makes a mess of the test code.

**Comment by RonnyPfannschmidt** [comment] 2017-08-30 10:59
well, the error could be more clear indeed

a function scoped fixture can use a session scoped one just fine, however the other way around is not permit table

we tried to introduce multi scoped fixtures before in pytest 3.0, but discovered a serious structural issue that wont allow this sanely without restructuring some internals

back then @nicoddemus was working on it and may remember more details on the hardships in the area

**Comment by nicoddemus** [comment] 2017-08-31 00:09
@richardasaurus (heh cool nick), unfortunately as @RonnyPfannschmidt said it was tried once, but I did not manage to overcome the problems with the approach.

For reference, #1681 #1811.

I'm closing this as duplicate of #1681 for now, but please feel free to follow up with further questions.

**Closed by nicoddemus** 2017-08-31 00:09 UTC
