### ISSUE TITLE
When multiple fixtures raise during tear down, only one exception is seen

### ISSUE THREAD

**Issue by podusowski** [pytest-dev/pytest#8355] opened 2021-02-19 21:32 UTC
My test looks like this.

```python
import pytest

@pytest.fixture
def foo():
    yield
    print("foo")
    raise ValueError("foo")

@pytest.fixture
def bar():
    yield
    print("bar")
    raise ValueError("foo")


def test_foo(foo, bar):
    pass
```

And it gives me this output:

```
======================= test session starts =======================
platform linux -- Python 3.6.9[pypy-7.3.1-final], pytest-6.0.1, py-1.9.0, pluggy-0.13.0
rootdir: /home/ppodusowski/Playground/pytest-fixtures
plugins: asyncio-0.14.0, flakefinder-1.0.0, timeout-1.4.2
collected 1 item                                                  


test_foo.py .E                                              [100%]

============================= ERRORS ==============================
__________________ ERROR at teardown of test_foo __________________

    @pytest.fixture
    def bar():
        yield
        print("bar")
>       raise ValueError("foo")
E       ValueError: foo

test_foo.py:13: ValueError
-------------------- Captured stdout teardown ---------------------
bar
foo
===================== short test summary info =====================
ERROR test_foo.py::test_foo - ValueError: foo
=================== 1 passed, 1 error in 0.26s ====================
```

So despite both finalizers being called, exception from only one of them is reported. Apparently the issue [is known](https://github.com/sangongs/pytest/blob/04b65cfba00624fa217fb2f8647cf79e4cf57a52/src/_pytest/runner.py#L502).

**Comment by bluetech** [comment] 2021-02-20 08:04
You are correct. This issue is a duplicate of #8217, so I'll close this one.

**Closed by bluetech** 2021-02-20 08:04 UTC
