### ISSUE TITLE
One Line Status Summaries for Each Test

### ISSUE THREAD

**Issue by tdrobbin** [pytest-dev/pytest#3726] opened 2018-07-28 06:00 UTC
Hello! I'm wondering if it's possible to just show the "short test summary info". Or something similar to the following
```
4 failed, 2 passed, 2 warnings in 68.00 seconds

PASSED test_main.py::test_a
PASSED test_main.py::test_b
FAIL test_main.py::test_c
FAIL test_main.py::test_d
FAIL test_main.py::test_e
FAIL test_main.py::test_f
```

I've tried running it with the ```-q``` and ```-r pf``` options but I still get the entire traceback output for the failed tests. 

Ideally I would like an output format to get the basic summary of all tests at a quick glance.

Thanks!

**Comment by RonnyPfannschmidt** [comment] 2018-07-28 07:18
a stopgap to get that more easily could be using `pytest -v --tb=no` making the test names/status more verbose, but foregoing the output of tracebacks

**Comment by nicoddemus** [comment] 2018-07-28 13:11
I think `--tb=no -ra` might be what you want:

```
$ pytest --tb=no -ra
======================== test session starts ========================
platform win32 -- Python 3.6.3, pytest-3.6.4.dev53+g7f27512a.d20180728, py-1.5.3, pluggy-0.6.0
rootdir: c:\pytest, inifile: tox.ini
plugins: xdist-1.22.2, forked-0.2, hypothesis-3.66.5
collected 10 items

foo.py F.F.F.F.F.                                              [100%]
====================== short test summary info ======================
FAIL foo.py::test[0]
FAIL foo.py::test[2]
FAIL foo.py::test[4]
FAIL foo.py::test[6]
FAIL foo.py::test[8]

================ 5 failed, 5 passed in 0.07 seconds =================
```

**Comment by tdrobbin** [comment] 2018-08-01 04:33
Both of these actually work very well. Thank you!

**Comment by RonnyPfannschmidt** [comment] 2018-08-01 05:12
closing as it seems to me that the issue is resolved for you,
please correct me if there is more

**Closed by RonnyPfannschmidt** 2018-08-01 05:12 UTC
Labels: type: question
