### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by Barry4679** [pytest-dev/pytest#8300] opened 2021-01-30 07:05 UTC
The example shown here seems to be incorrect:  https://docs.pytest.org/en/stable/fixture.html#yield-fixtures-recommended

> def test_email_received(receiving_user, email):

should be 
> def test_email_received(receiving_user, **sending_user**):

**Comment by RonnyPfannschmidt** [comment] 2021-01-30 10:07
thanks for tho note, those indeed have been missed as that particular example is not covered in the regendoc verification process, its a detail thats soon going to be fixed thanks to a issue i recewntly noted but cant find right now

**Comment by matthewhughes934** [comment] 2021-02-04 21:36
@RonnyPfannschmidt I think the issue is #8213, and with #8312 it might be possible to close this issue.

**Comment by nicoddemus** [comment] 2021-02-05 02:15
Indeed, thanks @matthewhughes934!

(Btw, I've invited you to pytest-dev, so you can close this yourself in the future 😉)

**Closed by nicoddemus** 2021-02-05 02:15 UTC
Labels: type: bug, type: docs
