### ISSUE TITLE
pytest triggering deprecation warnings in 3.0.5

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#2118] opened 2016-12-05 16:03 UTC
As commented by @nedbat in https://bitbucket.org/ned/coveragepy/pull-requests/94, it seems pytest itself is making use of the deprecated `compatproperty` names:

```
/Users/ned/coverage/trunk/.tox/py27/lib/python2.7/site-packages/_pytest/fixtures.py:1071: PendingDeprecationWarning: This usage is deprecated, please use pytest.Class instead
  obj = getattr(holderobj, name, None)
/Users/ned/coverage/trunk/.tox/py27/lib/python2.7/site-packages/_pytest/fixtures.py:1071: PendingDeprecationWarning: This usage is deprecated, please use pytest.File instead
  obj = getattr(holderobj, name, None)
/Users/ned/coverage/trunk/.tox/py27/lib/python2.7/site-packages/_pytest/fixtures.py:1071: PendingDeprecationWarning: This usage is deprecated, please use pytest.Function instead
  obj = getattr(holderobj, name, None)
/Users/ned/coverage/trunk/.tox/py27/lib/python2.7/site-packages/_pytest/fixtures.py:1071: PendingDeprecationWarning: This usage is deprecated, please use pytest.Instance instead
  obj = getattr(holderobj, name, None)
/Users/ned/coverage/trunk/.tox/py27/lib/python2.7/site-packages/_pytest/fixtures.py:1071: PendingDeprecationWarning: This usage is deprecated, please use pytest.Item instead
  obj = getattr(holderobj, name, None)
/Users/ned/coverage/trunk/.tox/py27/lib/python2.7/site-packages/_pytest/fixtures.py:1071: PendingDeprecationWarning: This usage is deprecated, please use pytest.Module instead
  obj = getattr(holderobj, name, None)
```

cc @nmundar

**Comment by RonnyPfannschmidt** [comment] 2016-12-05 16:05
this may prove tricky, it happens in parse_factories

**Comment by nedbat** [comment] 2016-12-05 16:24
Couldn't you put a "with warnings.catch_warnings():" around line 1071?  https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings

**Comment by RonnyPfannschmidt** [comment] 2016-12-05 16:29
i'd rather investigate why we run into those objects, and whether we can avoid the situation to begin with (as we could be hiding other deprecations as well)

**Comment by nedbat** [comment] 2016-12-05 16:33
A quick test in my tox virtualenv seems to show that the context manager doesn't prevent the warnings..?

BTW, I run my test suite with:
```
# We want to see all warnings while we are running tests.  But we also need to
# disable warnings for some of the more complex setting up of tests.
warnings.simplefilter("default")

# Silence specific warnings that are not our fault.
warnings.filterwarnings("ignore", module="xdist", message="type argument to addoption")
```
So I try to see warnings, but that last line is to suppress a warning that pytest-xdist causes.

**Comment by nedbat** [comment] 2016-12-05 17:06
Oops, I hadn't tried catch_warnings correctly.  This works, and should only silence this specific warning:
```
            with warnings.catch_warnings():
                warnings.filterwarnings("ignore", message="This usage is deprecated, please use pytest.* instead")
                obj = getattr(holderobj, name, None)
```

**Comment by RonnyPfannschmidt** [comment] 2016-12-05 17:33
@nedbat the real bug is, that it tries to operate on a Node object as test object

**Comment by RonnyPfannschmidt** [comment] 2016-12-05 17:51
@nicoddemus @nedbat the problem lies in `_pytest/python.py:360` - getcustomclass triggers this

i will fix this one

**Comment by The-Compiler** [comment] 2016-12-05 21:35
I can confirm this, breaks my testsuite since I use `-Werror` :wink:

Bisected to b38fad4b82123b392409fe78be01db2f39c7985b - cc @nmundar

**Comment by nicoddemus** [comment] 2016-12-05 21:40
After @RonnyPfannschmidt fixes it, should we do a  `3.0.6` release or it can wait a few weeks?

**Comment by RonnyPfannschmidt** [comment] 2016-12-05 22:26
@The-Compiler you should never error on pending ones tho ^^

**Comment by The-Compiler** [comment] 2016-12-06 06:44
I just blacklisted 3.0.5, so no hurry from my side.

@RonnyPfannschmidt I'll have to disagree - if pytest failed on PendingDeprecationWarnings in its testsuite, I'm pretty we'd have noticed that it's issuing them during normal operation. And in my own testsuite, IMHO it's good to know about deprecated stuff as early as possible :wink:

**Comment by RonnyPfannschmidt** [comment] 2016-12-06 08:16
@The-Compiler pendingdeprecations are really silent by default

also while investigating we added pending deprecation in a really bad way
i put a real deprecation there because it should fail hard on this one since a while (namely 2.x)

**Comment by The-Compiler** [comment] 2016-12-06 08:19
`DeprecationWarning`s are also silent by default :wink:

Your PR still does `PendingDeprecationWarning` though, right? FWIW I don't think we should change that to a `DeprecationWarning` with a patch release.

**Comment by RonnyPfannschmidt** [comment] 2016-12-06 08:25
i still do the pending ones for the old usage site, i changed the other usage side that uses a old api to log the deprecation

**Comment by rgant** [comment] 2016-12-20 15:49
Wish I'd known about this error before I upgraded pytest to 3.0.5. I don't think that 3.0.5 should be available without this issue resolved. I guess I'm going to figure out how to downgrade my pytest install.

**Comment by The-Compiler** [comment] 2017-01-20 09:11
I haven't really had time for much pytest work recently, and just happened to rediscover today that I blacklisted pytest 3.0.5 for qutebrowser 😆 

Judging from the commits referencing this issues, others did the same - so I think this should really be fixed for a 3.0.6.

**Comment by RonnyPfannschmidt** [comment] 2017-01-20 09:16
i have a related pr in the work, it will be fixed by `3.0.6`

**Comment by The-Compiler** [comment] 2017-01-20 09:21
I agree with @nicoddemus ([this comment](https://github.com/pytest-dev/pytest/pull/2120#issuecomment-265413822) and the following ones) that we should rather revert patch-level deprecations and deprecate things properly for the next feature release.

**Comment by RonnyPfannschmidt** [comment] 2017-01-20 09:30
@The-Compiler the triggering deprecation will be removed, there is an original deprecation that simply doesnt cause warnings that i want to ressurrect at the same time

**Comment by nicoddemus** [comment] 2017-01-20 10:15
IMHO just moving the deprecation that was introduced to the `features` branch is enough, no need to ressurect the other deprecation because I suspect users don't see it anyway.

**Comment by RonnyPfannschmidt** [comment] 2017-01-20 10:27
@nicoddemus both need to be resurrected as they trigger in different usage cases (one happens if attributes on the class dont match the compat property, one triggers when using a compat property in a class declaration)

**Comment by RonnyPfannschmidt** [comment] 2017-01-20 10:31
@nicoddemus oh, and im reasonably sure both will happen in the pypy codebase

**Comment by nicoddemus** [comment] 2017-01-20 10:36
Oh OK, thanks.

I guess after this is in place we can make a `3.0.6` release.

**Closed** 2017-01-20 16:38 UTC
Labels: bug
