### ISSUE TITLE
caplog always empty in Python 3.10.4

### ISSUE THREAD

**Issue by DVAlexHiggs** [pytest-dev/pytest#9948] opened 2022-05-12 09:30 UTC
### Description

In Python 3.10.4, `caplog` is always empty. I've tried a multitude of different approaches and resorted to just testing with a minimal example using the root logger to see if it still did not capture any logs. This proved that it's related to `caplog` itself, rather than any of my own code. The below test fails in Python 3.10.4. I changed my Python version to 3.9.6 without changing any code at all: the test passed and `caplog` was no longer empty, so I know it's related to Python 3.10.

```python
def test_my_logger(caplog):
    caplog.set_level(logging.INFO)
    with caplog.at_level(logging.INFO):
        logging.getLogger().info("test")

    assert caplog.text
```

PyCharm Debugger output, showing an empty `caplog`:
![image](https://user-images.githubusercontent.com/25080503/168040420-60992fd0-4665-4392-b146-135c6299ace1.png)

### versions
- pytest: 7.1.2
- Python: 3.10.4
- OS: Ubuntu 21.04

### pip list
```bash
Package                    Version
-------------------------- ---------
agate                      1.6.3
art                        5.6
asn1crypto                 1.5.1
attrs                      21.4.0
Babel                      2.10.1
certifi                    2021.10.8
cffi                       1.15.0
charset-normalizer         2.0.12
click                      8.1.3
colorama                   0.4.4
contextlib2                21.6.0
cryptography               3.4.8
dataclasses-json           0.5.7
dbt-core                   1.1.0
dbt-extractor              0.4.1
dbt-snowflake              1.1.0
future                     0.18.2
graphviz                   0.20
hologram                   0.0.14
htmlmin                    0.1.12
idna                       3.3
importlib-metadata         4.11.3
iniconfig                  1.1.1
isodate                    0.6.1
jeepney                    0.8.0
Jinja2                     2.11.3
json-schema-for-humans     0.34.4
jsonschema                 3.1.1
keyring                    23.5.0
leather                    0.3.4
Logbook                    1.5.3
markdown2                  2.4.3
MarkupSafe                 2.0.1
marshmallow                3.15.0
marshmallow-enum           1.5.1
mashumaro                  2.9
mdutils                    1.3.1
minimal-snowplow-tracker   0.0.2
msgpack                    1.0.3
mypy-extensions            0.4.3
networkx                   2.8
oscrypto                   1.3.0
packaging                  21.3
parsedatetime              2.4
pip                        22.0.4
pluggy                     1.0.0
py                         1.11.0
pycparser                  2.21
pycryptodomex              3.14.1
pydantic                   1.9.0
Pygments                   2.12.0
PyJWT                      2.3.0
pyOpenSSL                  21.0.0
pyparsing                  3.0.9
pyrsistent                 0.18.1
pytest                     7.1.2
python-dateutil            2.8.2
python-slugify             6.1.2
pytimeparse                1.1.8
pytz                       2022.1
PyYAML                     6.0
requests                   2.27.1
ruamel.yaml                0.17.21
ruamel.yaml.clib           0.2.6
schema                     0.7.5
SecretStorage              3.3.2
setuptools                 62.2.0
six                        1.16.0
snowflake-connector-python 2.7.7
sqlparse                   0.4.2
text-unidecode             1.3
tomli                      2.0.1
typing_extensions          4.2.0
typing-inspect             0.7.1
urllib3                    1.26.9
Werkzeug                   2.1.2
wheel                      0.37.1
zipp                       3.8.0
```

**Comment by asottile** [comment] 2022-05-12 11:51
I can't reproduce -- I suspect some code you're not showing is interfering? or a rogue dependency?

**Comment by DVAlexHiggs** [comment] 2022-05-12 12:34
> I can't reproduce -- I suspect some code you're not showing is interfering? or a rogue dependency?

Thanks for your reply. I cannot think of anything that would be causing it, and I'm not sure that explains why switching from 3.10.4 to 3.9.6 would have an affect. 

Will continue to investigate. Thanks

**Comment by DVAlexHiggs** [comment] 2022-05-12 14:40
Created a fresh environment with Python 3.10.4 and a very basic test and function which logs. The test passes, so I cannot reproduce it myself. Very strange! Will keep the thread updated as I discover more

**Comment by nicoddemus** [comment] 2022-05-12 15:44
I will close the issue for now, we can reopen later as things progress. 👍

**Closed by nicoddemus** 2022-05-12 15:44 UTC
Labels: status: needs information
