### ISSUE TITLE
Imperative xfail does not reports a test as XPASS when the test passes

### ISSUE THREAD

**Issue by sandeep-test** [pytest-dev/pytest#2157] opened 2016-12-23 14:53 UTC
- [ ] detailed description of the bug
When marking a test as xfail imperatively (i.e from within the test using pytest.xfail() ), its not reported as XPASS on passing.
Its rather reported as PASSED.

(At this point of time it may be a feature as well.
But as a tester if I'm marking a test as xfail either at time of test collection or at the time of test execution, it makes more sense to report it as unexpected passed than just passed.
)

- [ ] `pip list` 
I'm using python 2.7.6:
ansi2html (1.1.1)
arrow (0.10.0)
binaryornot (0.4.0)
cffi (1.9.1)
chardet (2.3.0)
click (6.6)
colorama (0.3.7)
cookiecutter (1.4.0)
cryptography (1.5.3)
enum34 (1.1.6)
future (0.16.0)
idna (2.1)
ipaddress (1.0.17)
Jinja2 (2.8)
jinja2-time (0.2.0)
MarkupSafe (0.23)
numpy (1.11.2)
paramiko (2.0.2)
pip (9.0.1)
poyo (0.4.0)
py (1.4.31)
pyasn1 (0.1.9)
pycparser (2.17)
pytest (3.0.4)
pytest-html (1.12.0)
pytest-repeat (0.4.1)
PytestHTMLDashboardReport (1.0.0)
python-dateutil (2.6.0)
selenium (3.0.2)
setuptools (28.8.0)
six (1.10.0)
wheel (0.29.0)
whichcraft (0.4.0)

- [ ] pytest and operating system versions
pytest (3.0.4)
Windows 7 Professional

- [ ] Minimal example if possible

def test_foo(self):
    if True:
        pytest.xfail('marking test xfail every time')
    print "running test"
    assert 1==1

now execute test using option --runxfail (as without this option tests marked as xfail imperatively, are not executed and rightly marked as xfail)

**Comment by sandeep-test** [comment] 2016-12-23 14:57
resubmitting the example as formatting is lost during submission:

```

def test_foo(self):
    if True:
        pytest.xfail('marking test xfail every time')
    print "running test"
    assert 1==1
```

now execute test using option --runxfail (as without this option tests marked as xfail imperatively, are not executed and rightly marked as xfail)

**Comment by nicoddemus** [comment] 2016-12-23 17:10
This is expected by design; if you are imperatively executing `xfail`, it will always fail as `XFAIL`. in fact,`pytest.xfail` is even implemented internally by raising an exception.

Do you have a specific example where this would be useful?

**Comment by sandeep-test** [comment] 2016-12-25 07:06
As i said, there are cases where we know at the time of test collection whether a test is expected to fail or not. Whereas at certain time we know this at the time of test execution that because of certain test failing, the other test is also expected to fail.

As a quality analyst if I'm marking my tests as xfail (whether at test collection or at execution) it makes sense to report it as XPASS because then it tells me that my application under test is inconsistent, as the test i expected to fail has somehow passed.

If it is reported as PASSED, it doesn't even draws my attention that something unexpected has happened.

**Comment by RonnyPfannschmidt** [comment] 2016-12-25 08:10
Imperative xfail is not a mark, it would need a imperative xpass to set up symmetry

**Comment by nicoddemus** [comment] 2016-12-27 00:25
> As a quality analyst if I'm marking my tests as xfail (irrespective of whether its done at test collection or at execution) it makes sense to report it as XPASS (incase it passes) because then it tells me that my application under test is inconsistent, as the test i expected to fail has somehow passed.

I understand, thanks. Unfortunately the current implementation can't be changed easily, imperative `pytest.fail`, `pytest.xfail` and `pytest.skip` are all implemented as exceptions, so they immediately stop the normal flow of the test. `pytest.mark.xfail` on the other hand, being a mark, can wait for the test to end in order to decide if it was a `XFAIL`/`XPASS` or even prevent the test from running at all with `run=False`. 

If we change `pytest.xfail` to instead somehow mark the current test as `xfail` (like the mark does), then we need to continue the flow of execution, which would break backward compatibility.

The xpass/xfail distinction is a little confusing, because most users expect for it to fail the test suite if the test passes (xfail = "expected to fail"), but at some point it was changed to be a "soft" mode where it doesn't fail the test suite, but marks the test as `XPASS` if it passes. That's the reason why the `strict` flag was introduced, to restore the original behavior.

In the end, I don't think there's an easy way out at this point; adding an imperative `xpass` doesn't seem to solve the problem as well, because the user doesn't know if the test will pass or not at the point that `pytest.xpass` gets called.

**Comment by sandeep-test** [comment] 2016-12-28 05:42
Thanks for your clarifications RonnyPfannschmidt and nicoddemus.
I can live with it by moving the test steps as prerequisite steps to be executed at the time of test collection (by moving these steps outside of test and setup function). That ways i can execute a few steps at the time of test collection and decide on which tests to mark XFAIL etc...

**Comment by nicoddemus** [comment] 2016-12-28 09:13
No problem, anytime. Closing this for now, feel free to follow with further questions.

**Closed by nicoddemus** 2016-12-28 09:13 UTC

**Comment by karolzlot** [comment] 2022-04-05 17:27
I think this is still an issue nowadays.

In some cases it would be convenient to be able to mark test as `xfail` during execution. So in addition to `pytest.xfail()`, we would also have something like `pytest.mark_as_xfail()`

**Comment by karolzlot** [comment] 2022-04-05 17:32
But this package solves it, I think.
https://pypi.org/project/pytest-runtime-xfail/
