### ISSUE TITLE
Internal Error: AttributeError: 'ReprFailDoctest' object has no attribute 'reprcrash'

### ISSUE THREAD

**Issue by inducer** [pytest-dev/pytest#785] opened 2015-06-17 20:06 UTC
I got this traceback from one of my doctests:

```
============================= test session starts ==============================
platform linux -- Python 3.4.1 -- py-1.4.28 -- pytest-2.7.1
rootdir: /home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy, inifile: 
collected 114 items

test_dg.py .
test_fortran.py ..........x..
test_isl.py .
test_linalg.py ..............
test_loopy.py .........................................................................
test_nbody.py .
test_sem_reagan.py .
test_statistics.py ....F.
../doc/index.rst .
../doc/misc.rst .
../doc/reference.rst .
../doc/tutorial.rst F
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/main.py", line 84, in wrap_session
INTERNALERROR>     doit(config, session)
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/main.py", line 122, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/core.py", line 521, in __call__
INTERNALERROR>     return self._docall(self.methods, kwargs)
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/core.py", line 528, in _docall
INTERNALERROR>     firstresult=self.firstresult).execute()
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/core.py", line 394, in execute
INTERNALERROR>     res = method(*args)
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/main.py", line 142, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/core.py", line 521, in __call__
INTERNALERROR>     return self._docall(self.methods, kwargs)
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/core.py", line 528, in _docall
INTERNALERROR>     firstresult=self.firstresult).execute()
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/core.py", line 393, in execute
INTERNALERROR>     return wrapped_call(method(*args), self.execute)
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/core.py", line 113, in wrapped_call
INTERNALERROR>     return call_outcome.get_result()
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/core.py", line 137, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/core.py", line 123, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/core.py", line 394, in execute
INTERNALERROR>     res = method(*args)
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/runner.py", line 65, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/runner.py", line 75, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/runner.py", line 123, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/core.py", line 521, in __call__
INTERNALERROR>     return self._docall(self.methods, kwargs)
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/core.py", line 528, in _docall
INTERNALERROR>     firstresult=self.firstresult).execute()
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/core.py", line 394, in execute
INTERNALERROR>     res = method(*args)
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/junitxml.py", line 180, in pytest_runtest_logreport
INTERNALERROR>     self.append_failure(report)
INTERNALERROR>   File "/home/gitlab_ci_multi_runner/tmp/builds/runner-5b708ae5-project-14-concurrent-0/gitlab.tiker.net/inducer/loopy/.env/lib/python3.4/site-packages/_pytest/junitxml.py", line 129, in append_failure
INTERNALERROR>     message = report.longrepr.reprcrash.message
INTERNALERROR> AttributeError: 'ReprFailDoctest' object has no attribute 'reprcrash'

============== 2 failed, 111 passed, 1 xfailed in 344.00 seconds ===============
```

**Comment by nicoddemus** [comment] 2015-06-17 20:31
Duplicate of #713, which has been solved (but not released yet). Thanks for the report!

**Closed by nicoddemus** 2015-06-17 20:31 UTC
