### ISSUE TITLE
Unexpected or undocumented behavior of pytest.mark.parametrize?

### ISSUE THREAD

**Issue by Thomasillo** [pytest-dev/pytest#9889] opened 2022-04-25 14:43 UTC
Consider the following file `test_stuff.py`

```python
import pytest

@pytest.fixture(scope="function")
def fixt_1():
    return 7

@pytest.fixture(scope="function")
def fixt_2(fixt_1):
    return fixt_1 * 2

@pytest.mark.parametrize("fixt_1", [4, 5])
def test_stuff(fixt_2):
    assert fixt_2 < 10
```
The second case fails, the first does not.
If this is intended behavior, I couldn't find documentation about this.

pytest version: 6.2.5

**Comment by Thomasillo** [comment] 2022-04-27 16:44
> 8 is less than 10 but 10 is not less than 10 -- seems expected?

Absolutely, no PhD in math necessary for that. 

What is not expected resp. undocumented is the possibility to use `pytest.mark.parametrize` to parametrize the return value of a fixture that is only indirectly used by the parametrized test.

**Comment by asottile** [comment] 2022-04-27 16:47
oh true, it is overwriting a fixture that does seem wrong

**Comment by nicoddemus** [comment] 2022-04-27 16:50
Yes, this is an "undocumented" feature (I'm putting that in quotes because seems mostly like an accident in implementation). I think we discussed this in the past, either to change the behavior, document it, or leave it undocumented, don't have the time to dig and find the issue right now unfortunately.

**Comment by asottile** [comment] 2022-04-27 16:52
looks like this is a dupe of #5712

**Comment by The-Compiler** [comment] 2022-05-16 08:13
Should we close this then?

**Comment by nicoddemus** [comment] 2022-05-17 12:13
Yes, thanks @The-Compiler!

**Closed by nicoddemus** 2022-05-17 12:13 UTC
Labels: type: question, type: docs, topic: parametrize, topic: fixtures
