### ISSUE TITLE
`unittest` TestCase collection fails silently when there are unclear circular dependencies

### ISSUE THREAD

**Issue by jrybinski** [pytest-dev/pytest#8348] opened 2021-02-17 07:56 UTC
Hey!
I have problem with collecting unittest/asynctest based test.

I'm trying to run tests TestCase from unittest/asynctest and have problem when I provide for example exact dir
`pytest directory_name`
then collecting works fine, it will collect correct test and run it but when I will run pytest without directory
`pytest`
it's collecting same tests but in this case it skipps all of them becasue it has _init_ method defined from testcase.
```
PytestCollectionWarning: cannot collect test class 'TestCase' because it has a __init__ constructor 
````
but If I run it directly, by passing 
`pytest test_name.py` or `pytest dir_name`
it will run single test or in second case, it will collect correctly test from dir and run it

In every case the same test are collected but in one is skipped and in another it run normally.

also 
https://docs.pytest.org/en/stable/unittest.html
it says that 
`pytest tests` should run unittest style test but it will work only if there are in `test` dir, right? 

Is it bug or missing configuration?

- pytest                   6.2.2
- asynctest                0.13.0
- python 3.9.1
- osx Big Sur on m1

**Comment by RonnyPfannschmidt** [comment] 2021-02-17 09:53
unittest based tests should work,
its a bit of a surprise that they are not detected as unittest based when the folder is not added

do you have a minimal example?

**Comment by jrybinski** [comment] 2021-02-18 11:41
@RonnyPfannschmidt thanks for the answer

I think I fixed the problem. While I was trying to reproduce with minimal example in the clean repo I was reproducing the same steps in the old repository where the problem exists. 

When I add a new empty test with proper name, alphabetically in the right order it was passing but when I put in like in the middle of the collection, alphabetically later in the collection process,  it was skipped so I start thinking that some test have some problems which affect collection and error messages are choke somewhere.

I was removing test by test until it started passing and collecting correctly.

For now, I found in one test there had a circular dependency problem that was causing that whole collection test was falling without any particular reason displayed on the console. 
Now I found all test which was causing problems, I removed them by renaming, running one by one and founding why it's not collected/ran properly, restoring name with `test_` and checking if collection works.

Don't know if we can improve some warning/errors message in a case like this? If I will found time after work I will try to reproduce it in the new repo to have the possibility to handle it in a better way if that even possible?

**Comment by RonnyPfannschmidt** [comment] 2021-02-18 12:12
Yes please, if a circular dependency in code somehow breaks collection, there should be a error at least

I wonder why pytest lacks it

**Comment by Zac-HD** [comment] 2021-11-29 00:24
@jrybinski - can you share a reproducing case?  It's very hard to fix this kind of bug without one 🙂

(and better to share a large or messy reproducer than wait another nine months!)

**Comment by Zac-HD** [comment] 2022-09-27 05:59
Closing because we don't have the needed information to resolve this, happy to reopen if that changes 😕

**Closed by Zac-HD** 2022-09-27 05:59 UTC
Labels: type: bug, topic: collection, plugin: unittest, status: needs information
