### ISSUE TITLE
Feature request - add new scope for fixture to support running once on a parameterized test

### ISSUE THREAD

**Issue by amitwer** [pytest-dev/pytest#7313] opened 2020-06-03 14:46 UTC
Hi, 
Currently, the supported scopes of a fixture are  - function, class, module, package or session. 
I encountered the need to run a fixture once per unique function - or, in pytest terms: once per request.node.originalname

I ended up storing a global dictionary with this as key and  caching the value in it. Having a fixture with scope "original_function_name" would have been nice. 

Example: 
```
@pytest.mark.parametrize("x" [ * a few dozens of values *] )
def test_me(x,client):
    client.send_request(value=x) 


@pytest.fixture(scope="function",scope="original_function_name")
def client(request):
    client= Client()
    client.register()  # this takes a lot of time
    yield client
    client.unregister()
```

**Comment by RonnyPfannschmidt** [comment] 2020-06-03 15:12
The functiondefinition scope is intended for that, it will require the functiondefinition nodes be integrated into the collection tree

**Comment by asottile** [comment] 2020-06-04 14:01
another workaround for now is to use a class with class scope

**Comment by Zac-HD** [comment] 2020-06-06 03:41
Might be duplicate of #3432?

**Comment by RonnyPfannschmidt** [comment] 2020-06-06 05:31
Indeed, closing as duplicate of #3432

**Closed by RonnyPfannschmidt** 2020-06-06 05:31 UTC
Labels: topic: fixtures, topic: parametrize, type: proposal
