### ISSUE TITLE
NameError in all() condition with nested lists

### ISSUE THREAD

**Issue by st-pasha** [pytest-dev/pytest#5381] opened 2019-06-03 19:34 UTC
MRE:
```
$ python -m pytest tests/models/test_kfold.py::test_pytest --cache-clear --showlocals
===================================================== test session starts =====================================================
platform darwin -- Python 3.6.6, pytest-4.6.2, py-1.7.0, pluggy-0.12.0
benchmark: 3.2.2 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Users/pasha/github/datatable, inifile: setup.cfg
plugins: cov-2.6.1, benchmark-3.2.2
collected 1 item                                                                                                              

tests/models/test_kfold.py F                                                                                            [100%]

========================================================== FAILURES ===========================================================
_________________________________________________________ test_pytest _________________________________________________________

    def test_pytest():
        items = [(1,1), (2,2)]
>       assert all(thing
                   for item in items
                   for thing in item)
E       NameError: name 'thing' is not defined

item       = (1, 1)
items      = [(1, 1), (2, 2)]

tests/models/test_kfold.py:180: NameError
================================================== 1 failed in 0.08 seconds ===================================================

$ python -c "from tests.models.test_kfold import *; test_pytest(); print('ok')"
ok

```

**Comment by nicoddemus** [comment] 2019-06-03 19:46
Hi @st-pasha,

I see from your header you are using  `4.6.2`, but I can't reproduce the issue (using a fresh virtual environment):

```
 λ pytest foo.py
======================== test session starts ========================
platform win32 -- Python 3.6.8, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
rootdir: C:\Users\bruno.ESSS.CO\temp, inifile: pytest.ini
collected 1 item

foo.py .                                                       [100%]

===================== 1 passed in 0.01 seconds ======================
``` 

File:

```python
 def test_pytest():
    items = [(1,1), (2,2)]
    assert all(thing
               for item in items
               for thing in item)
```

I do get the same error however if I use `pytest-4.6.1` and remove the `*.pyc` files. 

Please remove your `*.pyc` files and try again.

**Comment by st-pasha** [comment] 2019-06-03 19:54
Ah, indeed, you're correct. I thought that `--cache-clear` option would be removing all caches, but `*.pyc` files still remain cached... 
So, after removing the `*.pyc` files the error disappears in 4.6.2 and reappears in 4.6.1, same as you.

**Comment by nicoddemus** [comment] 2019-06-03 20:06
Thanks for the follow up.

`--cache-clear` is about the internal cache plugin, not about `*.pyc` files.

I'm closing this now then, feel free to follow with further questions. 👍

**Closed by nicoddemus** 2019-06-03 20:06 UTC
Labels: status: needs information
