### ISSUE TITLE
ValueError on testcase with bytes parameter containing Null character

### ISSUE THREAD

**Issue by florianbehrens** [pytest-dev/pytest#2986] opened 2017-11-30 16:47 UTC
The following testcase fails in v3.3.0 with a `ValueError` exception, but not in v3.2.5:

```
  import pytest


  @pytest.mark.parametrize('param', [b'x', b'\0'])
  def test_parametrized_with_bytes(param):
      assert True

```

This is the PyTest output:

```
____________________________________________________________________________ ERROR at setup of test_parametrized_with_bytes[] _____________________________________________________________________________

self = environ({...})
key = b'PYTEST_CURRENT_TEST', value = b'test_1.py::test_parametrized_with_bytes[\x00] (setup)'

    def __setitem__(self, key, value):
        key = self.encodekey(key)
        value = self.encodevalue(value)
>       self.putenv(key, value)
E       ValueError: embedded null byte

/usr/lib/python3.5/os.py:731: ValueError
___________________________________________________________________________ ERROR at teardown of test_parametrized_with_bytes[] ___________________________________________________________________________

self = environ({...})
key = b'PYTEST_CURRENT_TEST', value = b'test_1.py::test_parametrized_with_bytes[\x00] (teardown)'

    def __setitem__(self, key, value):
        key = self.encodekey(key)
        value = self.encodevalue(value)
>       self.putenv(key, value)
E       ValueError: embedded null byte

/usr/lib/python3.5/os.py:731: ValueError
```

**Comment by The-Compiler** [comment] 2017-11-30 17:03
Duplicate of #2957

**Closed by The-Compiler** 2017-11-30 17:03 UTC
