### ISSUE TITLE
use travis and appvoyer caching feature to keep pip cache around

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1000] opened 2015-09-14 14:20 UTC
this helps speed up the builds

**Comment by nicoddemus** [comment] 2015-09-14 14:26
I'm not sure this would improve build speeds much, as all pytest dependencies are small `wheel` packages... 

On the other hand, I think we could easily drop `x64` builds, because pytest is pure python and I would be really surprised if a regression difference happened in 64 versus 32-bits build.

**Comment by nicoddemus** [comment] 2015-09-14 14:30
Hmm now that I think about it, I don't think `tox` is using the `64` bits interpreters to run the tests. The `64` bits interpreters are being used only to install tox itself, which is not very useful to pytest.

@bubenkoff, if I remember correctly you added the appveyor scripts, to you know if the `64` bits interpreters are being used?

**Comment by bubenkoff** [comment] 2015-09-14 14:33
It runs for both 32 and 64
and for 64 it sets env variables:

```
IF "%PYTHON_ARCH%"=="64" (
    ECHO Configuring Windows SDK %WINDOWS_SDK_VERSION% for Python %MAJOR_PYTHON_VERSION% on a 64 bit architecture
    SET DISTUTILS_USE_SDK=1
    SET MSSdk=1
    "%WIN_SDK_ROOT%\%WINDOWS_SDK_VERSION%\Setup\WindowsSdkVer.exe" -q -version:%WINDOWS_SDK_VERSION%
    "%WIN_SDK_ROOT%\%WINDOWS_SDK_VERSION%\Bin\SetEnv.cmd" /x64 /release
    ECHO Executing: %COMMAND_TO_RUN%
    call %COMMAND_TO_RUN% || EXIT 1
```

so it should pick up the correct ones

**Comment by nicoddemus** [comment] 2015-09-14 14:40
I mean if `tox` itself is using the `64` bits interpreters. For example, take this output from a `x64` build:

```
Executing: tox -e py33
GLOB sdist-make: C:\projects\pytest\setup.py 
py33 create: C:\projects\pytest\.tox\py33 
py33 installdeps: nose, mock 
py33 inst: C:\projects\pytest\.tox\dist\pytest-2.7.3.dev420+ng4b01472.zip 
py33 installed: colorama==0.3.3,mock==1.3.0,nose==1.3.7,pbr==1.7.0,pluggy==0.3.0,py==1.4.30,pytest==2.7.3.dev420+ng4b01472,six==1.9.0 
py33 runtests: PYTHONHASHSEED='548' 
py33 runtests: commands[0] | py.test --lsof -rfsxX testing 
============================= test session starts ============================= 
platform win32 -- Python 3.3.5, pytest-2.7.3.dev420+ng4b01472, py-1.4.30, pluggy-0.3.0
rootdir: C:\projects\pytest, inifile: tox.ini 
collected 1247 items
```

I might be wrong, but I think tox is using the python installed at `C:\Python33` instead of `C:\Python33-x64`. This is what `tox`'s documentation say about it:

> On Windows a ``pythonX.Y`` named executable will be searched in typical default locations using the ``C:\PythonX.Y\python.exe`` pattern.

**Comment by nicoddemus** [comment] 2015-09-14 14:45
Hmm looking at the code, I think you're right, it will find the first `python` available in the `PATH`:

```python
if sys.platform != "win32":
    @hookimpl
    def tox_get_python_executable(envconfig):
        return py.path.local.sysfind(envconfig.basepython)

else:
    @hookimpl
    def tox_get_python_executable(envconfig):
        name = envconfig.basepython
        p = py.path.local.sysfind(name)
        if p:
            return p
        actual = None
        # Is this a standard PythonX.Y name?
        m = re.match(r"python(\d)\.(\d)", name)
        if m:
            # The standard names are in predictable places.
            actual = r"c:\python%s%s\python.exe" % m.groups()
        if not actual:
            actual = win32map.get(name, None)
        if actual:
            actual = py.path.local(actual)
            if actual.check():
                return actual
        # The standard executables can be found as a last resort via the
        # Python launcher py.exe
        if m:
            return locate_via_py(*m.groups())
```

Sorry for the noise! :sweat_smile:

**Comment by RonnyPfannschmidt** [comment] 2015-09-14 16:39
for my testing of even a small project using tox + pytest + things, keeping the caches around resulted in a nie speedup,

it might be less noticable on py.test tho

**Comment by blueyed** [comment] 2016-06-22 09:03
I've tested it for Travis on my fork, it seems to save a few minutes, but also removes the `--recreate` for tox - probably not a good idea?!

Base branch: https://travis-ci.org/blueyed/pytest/builds/139329262: Total time 34 min 1 sec (Elapsed time 8 min 26 sec)
PR for that branch: https://travis-ci.org/blueyed/pytest/builds/139426852: Total time 30 min 3 sec (Elapsed time 7 min)

I've pushed a new commit/build with some `before_cache` cleanup: https://travis-ci.org/blueyed/pytest/builds/139430521

**Comment by bubenkoff** [comment] 2016-06-22 10:22
without --recreate and will all the caches, where is the guarantee that it all builds without any cache available?

**Comment by The-Compiler** [comment] 2016-06-22 18:27
So personally I'd rather spend 10% more time and be sure the builds are fresh and sane myself.

**Comment by RonnyPfannschmidt** [comment] 2016-06-23 05:58
We should ensure recent pip versions and only cache wheels/pypi downloads

**Comment by blueyed** [comment] 2016-06-24 07:52
Tried that.
Base build: https://travis-ci.org/blueyed/pytest/builds/139859285 (Elapsed time 7 min 49 sec, Total time 31 min 52 sec)
Following: https://travis-ci.org/blueyed/pytest/builds/139859386 (Elapsed time 9 min 25 sec
Total time 32 min 23 sec).
Given that Travis itself has http caching already, this does not appear to be worth it.

@RonnyPfannschmidt I suggest closing this issue and my PR.

**Comment by nicoddemus** [comment] 2016-06-24 11:52
Agreed, thanks @blueyed for the report

**Closed** 2016-06-24 14:48 UTC
