### ISSUE TITLE
Updated test collection breaks on adjacent restricted directories

### ISSUE THREAD

**Issue by ntjohnson1** [pytest-dev/pytest#11902] opened 2024-01-31 21:10 UTC
# Problem
In pytest 8.0.0 the test collection breaks (at least on python 3.10 and 3.11) if there is an adjacent unrelated directory with restricted access in the current working directory.

## Minimum reproducer
```bash
$ mkdir example/test -p
$ touch example/test/test_example.py
$ mkdir other
$ chown root:root other
$ chmod 700 other
$ pytest --collect-only test/
<--snip-->
... Permission denied: '<home>/other/__init__.py'
```

I confirmed that the `--ignore` option properly filters out the problematic directory. But this could be resolved by first checking access to the directory [here](https://github.com/pytest-dev/pytest/blob/4546d5445aaefe6a03957db028c263521dfb5c4b/src/_pytest/python.py#L206) prior to testing the directory contains an `__init__`.

**Comment by bluetech** [comment] 2024-02-08 11:11
Closing as duplicate of #11904.

**Closed by bluetech** 2024-02-08 11:11 UTC
