### ISSUE TITLE
Proposal: display skip reason inline with test result

### ISSUE THREAD

**Issue by DariusL** [pytest-dev/pytest#2484] opened 2017-06-09 06:55 UTC
Currently the skip reason with `-rs` is displayed after the tests.

```
(venv) Dariuss-MacBook-Pro:e2e dlapunas$ pytest proposal.py -rs -v
====================================================================================================================================================================== test session starts ======================================================================================================================================================================

proposal.py::test_skipped SKIPPED
proposal.py::test_not_skipped PASSED

==================================================================================================================================================================== short test summary info ====================================================================================================================================================================
SKIP [1] proposal.py:3: some reason
============================================================================================================================================================== 1 passed, 1 skipped in 0.01 seconds ==============================================================================================================================================================
```
With `-v` often there's enough space to display the skip reason next to the test result. Should improve readability. Possibly something like.
```
(venv) Dariuss-MacBook-Pro:e2e dlapunas$ pytest proposal.py -rs -v
====================================================================================================================================================================== test session starts ======================================================================================================================================================================

proposal.py::test_skipped SKIPPED: some reason
proposal.py::test_not_skipped PASSED

============================================================================================================================================================== 1 passed, 1 skipped in 0.01 seconds ==============================================================================================================================================================
```

**Comment by RonnyPfannschmidt** [comment] 2017-06-09 07:50
just a note - this kind of display would solve a different use-case (as the current -rs does aggregate, so if you have 100 tests skipping with the same skip, you still get 1 message not 100

**Comment by nicoddemus** [comment] 2017-06-09 11:40
Closing as duplicate of #2044

**Closed by nicoddemus** 2017-06-09 11:40 UTC
