### ISSUE TITLE
Setuptools integration example does not work anymore

### ISSUE THREAD

**Issue by danijar** [pytest-dev/pytest#1201] opened 2015-11-29 12:50 UTC
The [Good Integration Practices](https://pytest.org/latest/goodpractises.html#integration-with-setuptools-test-commands) guide includes an example of how to integrate with setuptools. It doesn't work anymore since `test_args` is now read-only. The problem was also [discovered by users](https://github.com/marshmallow-code/marshmallow/issues/300) of the Marshmallow library, however their fix was to not use setuptools anymore.

```python
import sys

from setuptools.command.test import test as TestCommand


class PyTest(TestCommand):
    user_options = [('pytest-args=', 'a', "Arguments to pass to py.test")]

    def initialize_options(self):
        TestCommand.initialize_options(self)
        self.pytest_args = []

    def finalize_options(self):
        TestCommand.finalize_options(self)
        self.test_args = []
        self.test_suite = True

    def run_tests(self):
        #import here, cause outside the eggs aren't loaded
        import pytest
        errno = pytest.main(self.pytest_args)
        sys.exit(errno)


setup(
    #...,
    tests_require=['pytest'],
    cmdclass = {'test': PyTest},
    )
```

```
Traceback (most recent call last):
  File "setup.py", line 72, in <module>
    cmdclass={'test': TestCommand, 'build_ext': BuildExtCommand},
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 973, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 15, in finalize_options
    self.test_args = []
AttributeError: can't set attribute
```

**Comment by jiffyclub** [comment] 2015-11-30 23:49
Duplicate of #1134

**Comment by nicoddemus** [comment] 2015-12-01 00:06
Thanks @jiffyclub

**Closed by nicoddemus** 2015-12-01 00:06 UTC
