### ISSUE TITLE
search results links have bad url

### ISSUE THREAD

**Issue by dsisson-twist** [pytest-dev/pytest#2351] opened 2017-04-06 20:21 UTC
1. go to docs.pytest.org and do a search; you end up on a page like this:
https://docs.pytest.org/en/latest/search.html?q=conftest&check_keywords=yes&area=default

2. the urls in the results item links have urls like this:
https://docs.pytest.org/en/latest/plugins.rst.html?highlight=conftest

because of that .rst string, the link returns a 404

**Comment by The-Compiler** [comment] 2017-04-06 20:25
Duplicate of #2302.

**Closed by The-Compiler** 2017-04-06 20:25 UTC
