### ISSUE TITLE
py shim module breaks module resolution in venvs with --system-site-packages enabled

### ISSUE THREAD

**Issue by crazyfermions** [pytest-dev/pytest#10603] opened 2022-12-21 19:09 UTC
If pytest is installed in a venv which has system-site-packages enabled and py is installed in the system-site-packages, the shim module provided by pytest is preferred over the one from the system (contrary of what is stated in the shim module's comment). This leads to code breaking the venv which otherwise would run fine.

Possibly related to #10428 (comment further down in thread).

**Comment by nicoddemus** [comment] 2022-12-21 19:36
Thanks @crazyfermions, but closing as duplicate of #10520. 👍

**Closed by nicoddemus** 2022-12-21 19:36 UTC
