### ISSUE TITLE
Confusing error message around tmpdir fixture

### ISSUE THREAD

**Issue by asottile** [pytest-dev/pytest#1098] opened 2015-10-01 00:42 UTC
Simplest reproduction:

```python
import pytest

@pytest.yield_fixture
def tmpdir_factory(tmpdir):
    yield

def test_1(tmpdir):
    pass
```

```
$ py.test test.py
============================= test session starts ==============================
platform linux2 -- Python 2.7.6, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: /tmp, inifile: 
collected 1 items 

test.py E

==================================== ERRORS ====================================
___________________________ ERROR at setup of test_1 ___________________________
file /tmp/test.py, line 7
  def test_1(tmpdir):
file /tmp/venv/local/lib/python2.7/site-packages/_pytest/tmpdir.py, line 109
  @pytest.fixture
  def tmpdir(request, tmpdir_factory):
file /tmp/test.py, line 3
  @pytest.yield_fixture
  def tmpdir_factory(tmpdir):
        fixture 'tmpdir' not found
        available fixtures: tmpdir_factory, pytestconfig, cache, recwarn, monkeypatch, record_xml_property, capfd, capsys, tmpdir
        use 'py.test --fixtures [testpath]' for help on them.

/tmp/test.py:3
=========================== 1 error in 0.01 seconds ============================
```

pytest version: 2.8.1

fwiw this breaks my build here: https://travis-ci.org/pre-commit/pre-commit/jobs/83034637

**Comment by nicoddemus** [comment] 2015-10-01 03:14
Thanks the report!

The problem is that `tmpdir_factory` is now a builtin fixture, and you're overriding it here with a fixture which also receives `tmpdir`. Problem is that the builtin fixture `tmpdir` requires `tmpdir_factory`, and since your fixture overwrote the builtin, there's a recursion.

The workaround is to rename your `tmpdir_factory` fixture. 

Not sure how simple it is to fix this in `pytest` to at least produce a better message, though.

**Comment by nicoddemus** [comment] 2015-10-02 15:54
I see you renamed your fixture to `tmpdir_factory` in pre-commit/pre-commit#270, so I'm closing this for now. :smile:

**Closed by nicoddemus** 2015-10-02 15:54 UTC
Labels: reporting
