### ISSUE TITLE
Memory error with Python 3.6

### ISSUE THREAD

**Issue by thmo** [pytest-dev/pytest#2154] opened 2016-12-21 13:06 UTC
We got this [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1406707) in Fedora:
```
=================================== FAILURES ===================================
_________________________ test_fromfile[wrapnl-args12] _________________________

self = <CallInfo when='call' exception: >
func = <function call_runtest_hook.<locals>.<lambda> at 0x7f597c4377b8>
when = 'call'

    def __init__(self, func, when):
        #: context of invocation: one of "setup", "call",
        #: "teardown", "memocollect"
        self.when = when
        self.start = time()
        try:
>           self.result = func()

/usr/lib/python3.6/site-packages/_pytest/runner.py:163: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.6/site-packages/_pytest/runner.py:151: in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py:745: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py:339: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py:334: in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py:613: in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py:245: in _wrapped_call
    next(wrap_controller)   # first yield
/usr/lib/python3.6/site-packages/_pytest/capture.py:131: in pytest_runtest_call
    self.activate_funcargs(item)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_pytest.capture.CaptureManager object at 0x7f597a472080>
pyfuncitem = <Function 'test_fromfile[wrapnl-args12]'>

    def activate_funcargs(self, pyfuncitem):
        capfuncarg = pyfuncitem.__dict__.pop("_capfuncarg", None)
        if capfuncarg is not None:
            capfuncarg._start()
>           self._capfuncarg = capfuncarg
E           MemoryError

/usr/lib/python3.6/site-packages/_pytest/capture.py:101: MemoryError
--------------------------- Captured stdout teardown ---------------------------
```
This happens in the test suite for https://github.com/ignatenkobrain/python-smartcols, when using Python 3.6.

**Comment by ignatenkobrain** [comment] 2016-12-21 13:13
P.S. it didn't happen with 3.5

**Comment by swt2c** [comment] 2016-12-27 04:19
I think this has something to do with `capfd`.  If I remove that argument from all of the tests, the memory explosion goes away.  In addition, I'm seeing a similar problem with python-suds in Fedora where the tests use `capsys`.

**Comment by lwm** [comment] 2016-12-27 12:44
@thmo Can we get a traceback of the value of the `MemoryError`?

[According to the docs][1], we might get some more information there.

[1]: https://docs.python.org/3/library/exceptions.html#MemoryError

**Comment by ignatenkobrain** [comment] 2016-12-27 13:46
@lwm how exactly? (I'm original bugreporter of this)

**Comment by lwm** [comment] 2016-12-27 18:39
@ignatenkobrain No idea, some debugging magic?

**Comment by nicoddemus** [comment] 2016-12-28 00:07
Did you guys tried to reduce this to a minimal example? It would help to pinpoint the problem.

Alternatively, try installing [pytest-faulthandler](https://github.com/pytest-dev/pytest-faulthandler) to see if we get some extra information.

**Comment by swt2c** [comment] 2016-12-28 01:25
It looks like this was actually a bug in the Python interpreter itself:
http://bugs.python.org/issue28147

After upgrading to the official 3.6 release, I can no longer reproduce the problem.

**Comment by nicoddemus** [comment] 2016-12-28 01:28
@swt2c thanks for following up!

I'm closing this then. @thmo feel free to reply here if you can reproduce the issue in the 3.6.0 release.

**Closed by nicoddemus** 2016-12-28 01:28 UTC
Labels: bug
