### ISSUE TITLE
Minor documentation issue 

### ISSUE THREAD

**Issue by unchaoss** [pytest-dev/pytest#8849] opened 2021-07-03 01:02 UTC
The output for the test program **test_class_demo.py** for in [https://docs.pytest.org/en/6.2.x/getting-started.html#run-multiple-tests](url) shows both pointer values as 'deadbeef'. They cannot both be the same value

**Comment by The-Compiler** [comment] 2021-07-03 08:33
Duplicate of #2201

**Closed** 2021-07-03 08:33 UTC
