### ISSUE TITLE
pytest assumes __repr__ is safe on an object with unsuccessful constructor - causing Segmentation Fault

### ISSUE THREAD

**Issue by pelson** [pytest-dev/pytest#4659] opened 2019-01-21 13:50 UTC
When presenting a failed stack trace, pytest assumes that it is safe to ``repr`` an object even if the failure occurred in that object's constructor. Take the following case:

```
import ctypes
import pytest

class SegRepr:
    """The most horrific class... raises a SegFault if you try to repr."""
    def __init__(self):
        raise ValueError("You really don't want me.")

    def __repr__(self):
        print("You can't get here, which is lucky because I'm "
              "about to SegFault.")
        import ctypes
        ctypes.string_at(0)


def test_bad():
    # The test case (it fails because of a ValueError being raised).
    assert SegRepr()
```

In everyday python, if you try to ``print(SegRepr())`` you will get a ``ValueError`` because you can't construct the object (though if you really try, you could do ``print(SegRepr.__new__(SegRepr))``).

However with pytest, we end up calling through to the repr:

```
pytest seg.py -sv
======================================================================== test session starts ========================================================================
platform darwin -- Python 3.7.2, pytest-4.1.1, py-1.7.0, pluggy-0.8.1 -- /Users/pelson/dev/scitools/cf-units/seg_env/bin/python
cachedir: .pytest_cache
rootdir: /Users/pelson/dev/scitools/cf-units, inifile:
collected 1 item                                                                                                                                                    

seg.py::test_bad You can't get here, which is lucky because I'm about to SegFault.
Segmentation fault: 11
```

This might sound like an esoteric case, but this is a boiled down version of a case that was genuinely seen in https://github.com/SciTools/cf-units/issues/133#issuecomment-456051865. In my comment on that issue I do state that I think it could be a challenge to address this issue without losing some of the functionality that pytest already provides (like giving a really helpful stack trace with information about the objects at each level). I therefore think this issue should be addressed in one of two ways:

 * Recognise that it was the constructor that failed, and only do a repr if the exception was caused elsewhere (potentially hard)
 * Document the pytest feature that it will call ``__repr__`` on potentially incomplete classes, and that objects that make use of state to call out to external interfaces run the real risk of Segmentation Faulting.

To be honest, I consider this issue as the beginning of addressing bullet-point 2 - hopefully others will see this and be able to recognise why their own libraries are failing with such ugly seg faults. 

For my own next course of action, I intend to make my ``__repr__`` more tolerant of incomplete initialisation within the library that this turned up for.

Apologies if this *is* a duplicate, however I went through each of the issues relating to Seg Faulting and could not find such a simple case that reproduced the issue. 

<details>
 <summary>Full environment definition</summary>
<br><br>

Using a basic conda environment on OSX Mojave, created with:

```
$ conda install pip python
$ pip install pytest
```

Spec:
```
# Name                    Version                   Build  Channel
atomicwrites              1.2.1                     <pip>
attrs                     18.2.0                    <pip>
ca-certificates           2018.12.5                     0    defaults
certifi                   2018.11.29               py37_0    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.2.1                h475c297_4    defaults
more-itertools            5.0.0                     <pip>
ncurses                   6.1                  h0a44026_1    defaults
openssl                   1.1.1a               h1de35cc_0    defaults
pip                       18.1                     py37_0    defaults
pluggy                    0.8.1                     <pip>
py                        1.7.0                     <pip>
pytest                    4.1.1                     <pip>
python                    3.7.2                haf84260_0    defaults
readline                  7.0                  h1de35cc_5    defaults
setuptools                40.6.3                   py37_0    defaults
six                       1.12.0                    <pip>
sqlite                    3.26.0               ha441bb4_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
wheel                     0.32.3                   py37_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
zlib                      1.2.11               h1de35cc_3    defaults
```
</details>

**Comment by RonnyPfannschmidt** [comment] 2019-01-21 16:36
at the python level, unless you interact with a ffi and miss-configure it, nothing should ever segfault, so that's a sane base assumption

**Comment by asottile** [comment] 2019-01-21 16:37
The bug here is that your `__repr__` is segfaulting imo.  pytest protects against `Exception` throwing `__repr__`s in this case:

```
=================================== FAILURES ===================================
___________________________________ test_bad ___________________________________

    def test_bad():
        # The test case (it fails because of a ValueError being raised).
>       assert SegRepr()

t.py:18: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <[TypeError("__repr__ returned non-string (type NoneType)") raised in repr()] SegRepr object at 0x7f346004b320>

    def __init__(self):
>       raise ValueError("You really don't want me.")
E       ValueError: You really don't want me.

t.py:7: ValueError
=========================== 1 failed in 0.05 seconds ===========================
```

Emphasis on

```
self = <[TypeError("__repr__ returned non-string (type NoneType)") raised in repr()] SegRepr object at 0x7f346004b320>
```

**Comment by asottile** [comment] 2019-01-21 16:51
Note also you'd cause a segfault if you put `breakpoint()` inside your `__init__` and then typed `self` -- it's not just pytest that could cause this

**Comment by pelson** [comment] 2019-01-21 17:41
> at the python level, unless you interact with a ffi and miss-configure it, nothing should ever segfault

>  it's not just pytest that could cause this

These are both completely accurate and reasonable statements, but searching SegFault on the issue tracker indicates that this *does* come up on a number of occasions (under several guises, but I suspect a number of them are the same case, just hidden by a ton of complexity).

Because tools like unittest and nose don't have the great feature of showing the extra traceback context that pytest does, I believe documenting that any object being used within pytest *MUST* be fault tolerant upon ``__repr__`` is a reasonable suggestion. I'm proposing at most 2 sentences at the point where the traceback context is described.

As I said, one of my goals was to provide a simple, searchable case that others can find/reference in the future, so this issue has already addressed that.

Do you agree that this should be documented in pytest? (I'm OK with the answer being *"no"* FWIW)

**Comment by asottile** [comment] 2019-01-21 17:49
I highly doubt _most_ segfaults are caused by invalid `__repr__` implementations -- the last few I've triaged here have been due to refcounting bugs or bugs in cpython itself

pytest already makes sure that exception-throwing code does not bring down the interpreter -- in my mind there's really nothing we should document here.  "Don't write code that segfaults" is already the default 😆

**Comment by nicoddemus** [comment] 2019-01-21 18:31
> Do you agree that this should be documented in pytest?

I think @pelson's suggestion is reasonable, in the sense that we might warn that pytest on failure will call `repr()` on the object, and depending on the library this might cause a segfault. This might seem "obvious", but at least will appear on a search on the docs and might save someone some time.

**Comment by horta** [comment] 2019-10-22 14:55
Shouldn't we never call member of an object that has failed to be constructed? I ended up having the same problem as @pelson had. In my opinion, we should assume that is dangerous to call a function of such an object.

**Comment by asottile** [comment] 2019-10-22 15:02
the object is constructed (that is, it has been created through `__new__`, it's just potentially not initialized.  

it's pretty easy to repr such an object through debugger or (in this case) traceback.  the fix should be in the faulty `__repr__`  implementation

**Comment by asottile** [comment] 2019-10-22 15:03
and afaik it's not possible to discern the difference between an initialized and uninitialized object

**Comment by horta** [comment] 2019-10-22 16:51
Failing at `__init__` is another way to say "this object is broken" and therefore it should not be used. AFAIK, there is nothing special about the `__repr__` method.

**Comment by asottile** [comment] 2019-10-22 16:55
`__del__`, a member function, is still called even when `__init__` fails.

**Comment by horta** [comment] 2019-10-22 17:31
Then `__del__` is special in that sense. I've tried to find in the python documentation anything that would indicate that `__repr__` should work even if the object initialization fails but I found nothing. That requirement seems to be a pytest one.

**Comment by asottile** [comment] 2019-10-22 17:50
Here's a very simple non-pytest case:
1. put a breakpoint in `__init__`
2. type `self` in the debugger

**Comment by asottile** [comment] 2019-10-22 17:52
at the end of the day, you're defending a **segfault** in pure code, I'm not sure how that's defensible :(

**Comment by The-Compiler** [comment] 2019-10-22 19:17
> Here's a very simple non-pytest case: [...]

A perhaps more realistic one: `print(self)` (or formatting `self` into an exception) inside `__init__` with an object without a `__str__` - I can see why you'd do that while e.g. debugging, and if your code segfaults when doing that, the problem probably is with your code.

**Comment by horta** [comment] 2019-10-23 10:54
segfault is an instance of the problem: `__repr__` might create a file lock and not release it with an object in an inconsistent state.

I think the question is: is `__repr__` supposed to work (by common sense, official Python documentation, historical reason, etc.) if `__init__` did not succeed? If not, it is a pytest requirement that few people will ever know about it.

Maybe another relevant question would be: how important is for pytest to call `__repr__` on objects that have failed to initialize?

**Comment by asottile** [comment] 2019-10-23 13:52
yes, __repr__ should not crash independent of initialization

it's not important I would think for pytest to call `__repr__` in such situations, however it is impossible to determine such situations

**Comment by nicoddemus** [comment] 2019-10-24 21:18
> it's not important I would think for pytest to call __repr__ in such situations, however it is impossible to determine such situations

Indeed, I can't see how.

@horta do you have some sample code that can show that the `__init__` of an object did not succeed? If so I wouldn't mind adding something to pytest (if it is not overly complicated) that won't call `__repr__` in such an object, but I believe @RonnyPfannschmidt, @The-Compiler, and @asottile is that *this is not possible* in general.

**Comment by RonnyPfannschmidt** [comment] 2019-10-24 22:10
imho `safe_repr` already handles all we need to handle, exceptions in repr are fine, segfauting in repr is a bug in the user code

**Comment by horta** [comment] 2019-10-24 23:28
@nicoddemus An exception thrown by `__init__` can be used to mean it has failed to initialize the object.

I still can't see why it is ok to call `__repr__` of an object that has failed to initialize. It would be fine if it was a method like `__del__`, as pointed by @asottile. If `__repr__` is not special in that sense (safe to call when `__init__` fails), I should be able to have a class like follows:

```python
from ._clib import ffi, lib

class Car:
    def __init__(self, name: str):
        self._car = lib.NULL
        self._car = ffi.create_car(name.encode())
        if self._car == lib.NULL:
            raise RuntimeError("Could not create a car.")

    @property
    def name(self) -> str:
        return ffi.get_car_name(self._car).decode()

    def __del__(self):
        if self._car != lib.NULL:
            ffi.destroy_car(self._car)

    def __repr__(self) -> str:
        return self.name
```

Would you say that the above code is faulty? If if fails to initialize (for example, by passing an array of bytes as car's name or by internal failure of the clib), it will thrown an exception so the user knows that it has failed to be initialized. The user wouldnt even be able to call any of its methods (without black magic), which is indeed the intention.

Using python, I need to adjust the above code to something like

```python
from ._clib import ffi, lib

class Car:
    def __init__(self, name: str):
        self._car = lib.NULL
        self._car = ffi.create_car(name.encode())
        if self._car == lib.NULL:
            raise RuntimeError("Could not create a car.")

    @property
    def name(self) -> str:
        return ffi.get_car_name(self._car).decode()

    def __del__(self):
        if self._car != lib.NULL:
            ffi.destroy_car(self._car)

    def __repr__(self) -> str:
        if self._car == lib.NULL:
            raise RuntimeError("Please, don't call me.")
        return self.name
```

And again, segfault is just an instance of the problem. `__repr__` might be doing some network stuff and getting stuck because who knows in what inconsistent state the object is.

**Comment by asottile** [comment] 2019-10-24 23:33
> Would you say that the above code is faulty?

yes, there should be a null check in the `__repr__` before assuming that `self._car` is not `None` (in the same way that you've checked in `__del__`!)

**Comment by horta** [comment] 2019-10-24 23:43
What about

```python
from ._clib import ffi, lib

class Car:
    def __init__(self, name: str):
        self._car = lib.NULL
        self._car = ffi.create_car(name.encode())
        if self._car == lib.NULL:
            raise RuntimeError("Could not create a car.")

    @property
    def name(self) -> str:
        return ffi.get_car_name(self._car).decode()

    def __del__(self):
        if self._car != lib.NULL:
            ffi.destroy_car(self._car)
```
code? Is it also faulty?

**Comment by asottile** [comment] 2019-10-24 23:44
is this a trick question?

**Comment by horta** [comment] 2019-10-24 23:46
I want you to realize that calling `__repr__` is essentially calling `name`.

**Comment by asottile** [comment] 2019-10-24 23:48
then yes?

though `print(...)` / the debugger / `pytest` would be fine with the second implementation because `__repr__` is not implemented

**Comment by nicoddemus** [comment] 2019-10-25 00:05
@horta I still don't understand how it could be possible to detect that an arbirtrary object `o` has failed during its initialization.

In other words, can you provide the implementation to this function?

```python
def was_properly_initialized(o) -> bool:
    """Returns True if `o` has been properly initialized"""
    ...
```

**Comment by horta** [comment] 2019-10-25 00:22
I can't. I don't even know how pytest manage to catch those objects.

**Comment by nicoddemus** [comment] 2019-10-25 00:56
> I can't. I don't even know how pytest manage to catch those objects.

Sorry, I don't think I made my point across, let me try a different explanation.

To try to simplify things, imagine you have a dict of unknown objects (which is how we analyse a stack frame essentially):

```python
variables = {
    "x": <some object 1>,
    "y": <some object 2>,
}
```

When we try to to display information about those objects to the user, what we usually do is use `repr`:

```python
for name, obj in variables.items():
    r = repr(obj)
    print(f"{name} = {r}")
```

One problem is that `repr` might raise an exception, so here's what pytest does now (simplified for illustration):


```python
for name, obj in variables.items():
    try:
        r = repr(obj)
    except Exception:
        r = "<error on repr>"
    print(f"{name} = {r}")
```

What you are asking is for pytest to do this:

```python
for name, obj in variables.items():
    if was_initialized_correctly(obj):
        try:
            r = repr(obj)
        except Exception:
            r = "<error on repr>"
    else:
        r = "<not initialized>"
    print(f"{name} = {r}")
```

But my point is that *there is no way to implement* the `was_initialized_correctly` function, as far as I know.

I hope I made my point clearer now. 👍

**Comment by blueyed** [comment] 2019-10-25 01:03
> An exception thrown by __init__ can be used to mean it has failed to initialize the object.

Doesn't that result in the object not being created at all?

Maybe the problem is with pytest then using `repr` on things in the `__init__` frame?  (including self etc)
(that might be an indicator for object-has-not-been-initialized somehow: if the `__init__` frame is the last one, for example)

But in general I agree that you should have a `__repr__` that never segfaults in the first place.

@horta 
It's not clear if you're also affected by a segfault after all, so a minimal example (test for pytest) might help to clarify things.

**Comment by nicoddemus** [comment] 2019-10-25 01:05
> Doesn't that result in the object not being created at all?

Good point, in general yes, but depending on the framework things might being done in two steps, with `__new__` being called manually, followed by an `__init__`.

> It's not clear if you're also affected by a segfault after all, so a minimal example (test for pytest) might help to clarify things.

Good idea, I agree.

**Comment by asottile** [comment] 2019-10-25 02:24
in the python object model, something which has gone through `__new__` is considered "constructed" (that is, it has a memory address and eventually the runtime will call `__del__` eventually (when depends on implementation, for example in cpython this is usually when the refcount hits 0)

after construction is initialization (via `__init__`)

`__init__` is purely side effects (mutations of the `self` parameter and no return value)

**Comment by RonnyPfannschmidt** [comment] 2019-10-25 04:49
the moment anyone assigns a c level object they aren't handling properly to the instance, its a bug

using cffi as in the example is basically punching holes into the memory model of python
if you do that, the faulthandler module should sort it out, pytest shouldn`t

**Comment by RonnyPfannschmidt** [comment] 2019-10-25 09:09
i believe we can do something more general for the python level (by saying "mid initialization instead of the repr of self" simply to be generally nicer about ctors breaking mid flight (which in good practice they shouldn't, but its certainly a concern of a lot of commonly implemented code)

my personal opinion is that the constructor itself should never do work that can fail,
but that is not always something that makes sense to implement in teams/projects/organizations

i believe having a user focus there and simply avoiding repr in `__init__` methods should be sufficient to let the objects that are broken wrt the memeory model work out

**Comment by horta** [comment] 2019-10-25 11:51
@nicoddemus Answering your first question, I believe an object that has failed to initialized itself should __not__ be in the following list:

```python
variables = {
    "x": <some object 1>,
    "y": <some object 2>,
}
```

My understanding of object-oriented programming and Python is that `__init__` is called to create and to leave an object in a __ready-to-use__ state:

What constructors are for?
> They [constructors] have the task of initializing the object's data members and of establishing the __invariant of the class__, __failing if the invariant is invalid__. A properly written constructor leaves the resulting object in a __valid state__.
https://en.wikipedia.org/wiki/Constructor_(object-oriented_programming)

What is an invariant?
> [...] __an invariant__ is a property, held by a class of mathematical objects, which remains unchanged when transformations of a certain type are applied to the objects
https://en.wikipedia.org/wiki/Invariant_(mathematics)

A `__init__` might fail to establish an invariant and that is signaled by raising an exception and, therefore, preventing the user to use that object in an invalid state.  The invariant we are talking about in this thread is the following: this object won't segfault. The `class Car` example I gave first guarantee, after succesfully constructing the object, that invariant throughout the object's lifetime. Therefore, the class implementation is not faulty. 

> Class invariants are established during construction and constantly maintained between calls to public methods. __Code within functions may break invariants as long as the invariants are restored before a public function ends__.
>
> An object invariant, or representation invariant, is a computer programming construct consisting of a set of invariant properties that remain uncompromised regardless of the state of the object. This ensures that the object will always meet predefined conditions, and that methods may, therefore, always reference the object without the risk of making inaccurate presumptions. Defining class invariants can help programmers and testers to catch more bugs during software testing.
https://en.wikipedia.org/wiki/Class_invariant

The `print(self)` inside `__init__` while debbuging a code is an example of a code within a public function that irrevocably breaks an invariant for classes that promisses to not `segfault` after their objects being constructed. Therefore, using the `print(self)` in that situation is faulty.

**Comment by horta** [comment] 2019-10-25 13:56
@RonnyPfannschmidt 
I would like to comment the statement you've made:

> ctors breaking mid flight (which in good practice they shouldn't, but its certainly a concern of a lot of commonly implemented code)

It is common to raise exception from a constructor as a way to enforce parameter constraints.

```python
class FileReader:
    def __init__(self, filepath : Path):
        if not filepath.exists():
            raise ValueError(f"{filepath} does not exist.")
```

It is also good pratice to create test cases that violate those contraints.

**Comment by blueyed** [comment] 2019-10-25 14:15
> What about just not printing the `self` argument inside `__init__` on exceptions there?

That's what I suggested also, but I am not sure that's the problem with @horta's code still.

Also it does not work for e.g. the following still (with `pytest -l`):
```python
import ctypes


class SegRepr:
    def __init__(self):
        # raise ValueError("You really don't want me.")
        pass

    def __repr__(self):
        ctypes.string_at(0)

    def __str__(self):
        return "str"


def test_bad():
    foo = SegRepr()
    assert 0
```

**Comment by RonnyPfannschmidt** [comment] 2019-10-25 17:41
@horta that common practice is even a good idea in languages that have RAII, for everything else i beg to differ

python is not a language with raii, and additionally even if the exception is raised, all that happens is that repr would raise one as well

**Comment by RonnyPfannschmidt** [comment] 2021-02-19 10:58
@nicoddemus @asottile  i'd like to close this as with faulthandler in pytest we get a traceback showing the actual code where it happens and imho thats a sensible way to handle code that punches holes in the memory model

```
$ pytest segfault.py -vl
========================================================================================================== test session starts ===========================================================================================================
platform linux -- Python 3.9.1, pytest-6.3.0.dev181+g6393893aa.d20210209, py-1.10.0, pluggy-0.13.1 -- ~/Projects/pytest-dev/pytest/.env/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('~/Projects/pytest-dev/pytest/.hypothesis/examples')
rootdir: ~/Projects/pytest-dev/pytest, configfile: pyproject.toml
plugins: hypothesis-5.43.4, forked-1.3.0, xdist-2.2.1.dev6+ge4bcbbe
collected 1 item                                                                                                                                                                                                                         

segfault.py::test_bad Fatal Python error: Segmentation fault

Current thread 0x00007fcf50ae3740 (most recent call first):
  File "/usr/lib64/python3.9/ctypes/__init__.py", line 517 in string_at
  File "~/Projects/pytest-dev/pytest/segfault.py", line 10 in __repr__
```

**Comment by nicoddemus** [comment] 2021-02-19 11:40
Agreed. 👍

**Comment by RonnyPfannschmidt** [comment] 2021-02-19 12:21
closing as sorted by faulthandler then

**Closed by RonnyPfannschmidt** 2021-02-19 12:21 UTC
Labels: invalid
