### ISSUE TITLE
--failed-first no longer sort correctly since v6.0 ?

### ISSUE THREAD

**Issue by jedie** [pytest-dev/pytest#8105] opened 2020-12-06 12:48 UTC
I use these settings:
```
    --failed-first
    --last-failed-no-failures all
    --new-first
```
Since pytest v6.0.x the "--failed-first" seems not to work anymore.
"--new-first" works fine. So a work-a-round is to "update" the last failed test to change the test order, to run the last failed test first ;)

Tested with pytest v6.1.2 and v6.0.2 with Python 3.8...
I tried to downgrade to v5.4.3 but then my django project will not work because of wrong import order. Don't know if that's related...

**Comment by asottile** [comment] 2020-12-06 18:19
could you describe what you mean by "seems not to work anymore"?  -- it doesn't work is not a bug report, show us what you intend to see and what is actually happening

**Comment by jedie** [comment] 2020-12-07 08:08
Sorry. The failed test doesn't start first ;)

I will take a look on this and add more information if i get one.

**Comment by nicoddemus** [comment] 2020-12-07 12:00
Thanks @jedie,

Try to add a reproducible example if possible; we have several tests for that feature, so if it is failing for you it must be some edge case we are currently missing. 👍

**Comment by Zac-HD** [comment] 2021-02-01 06:58
I'm closing this issue because we can't fix it without a reproducing example.  If anyone can provide a short script that we can run to demonstrate this error, we'll be happy to reopen the issue!

**Closed by Zac-HD** 2021-02-01 06:58 UTC
Labels: status: needs information
