### ISSUE TITLE
4.2.1 regression: "assert path.isfile()" hit in python.py:602

### ISSUE THREAD

**Issue by rouault** [pytest-dev/pytest#4788] opened 2019-02-13 17:44 UTC
My software uses pytest in Travis-CI and it has just caught up with the 4.2.1 release. On a target running under Wine, I now get (extract from https://travis-ci.com/OSGeo/gdal/jobs/177514628 )
```
=================================== ERRORS ====================================
___________________ ERROR collecting pyscripts/__init__.py ____________________
C:\Python27\lib\site-packages\_pytest\runner.py:226: in from_call
    result = func()
C:\Python27\lib\site-packages\_pytest\runner.py:289: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
C:\Python27\lib\site-packages\_pytest\python.py:650: in collect
    for x in self._collectfile(path):
C:\Python27\lib\site-packages\_pytest\python.py:602: in _collectfile
    assert path.isfile()
E   AssertionError
```

**Comment by rouault** [comment] 2019-02-13 17:49
Actually this is also true for a pure Windows run on AppVeyor: https://ci.appveyor.com/project/OSGeo/gdal/builds/22342341/job/0vumo9br4uus7jpb

**Comment by nicoddemus** [comment] 2019-02-13 17:57
Thanks for the report @rouault!

**Comment by nicoddemus** [comment] 2019-02-13 18:00
Hmmm that assert was added in https://github.com/pytest-dev/pytest/commit/913a2da6e52b6f2395b19c3163200726070b449d, cc @blueyed 

On a side note, we probably should ban plain `assert` messages in favor of more descriptive error messages

**Comment by blueyed** [comment] 2019-02-13 18:08
Duplicate of https://github.com/pytest-dev/pytest/issues/4782.

#4784 fixes it.

**Closed by blueyed** 2019-02-13 18:08 UTC
Labels: type: bug, type: regression

**Comment by blueyed** [comment] 2019-02-13 18:10
@rouault 
Can you debug why that assertion fails for you?
I was currently assuming it would be a dangling symlink.

**Comment by blueyed** [comment] 2019-02-13 18:10
Also please test if #4784 fixes it for you.

**Comment by rouault** [comment] 2019-02-13 18:18
Thanks for the quick response. Unfortunately testing your fix will be impractical while it has not reached pip.
The issue is for some reason Windows specific, as Linux tests pass.
The content of the directory that causes the assertion is
https://github.com/OSGeo/gdal/tree/master/autotest/pyscripts
So it has a "__init__.py" file of size zero. There is no symlink.

**Comment by nicoddemus** [comment] 2019-02-13 18:23
Thanks @blueyed!

> Unfortunately testing your fix will be impractical while it has not reached pip.

@rouault It seems you install pytest with `exec { pip install -Ur requirements.txt }`, in that case you just need to change the line in `requirements.txt` from `pytest>=3.6.0,<=4.2.0` to `git+https://github.com/blueyed/pytest@fix-4782`.

**Comment by rouault** [comment] 2019-02-13 19:32
Thanks for the hint ! OK, so I can confirm that fix-4782 solves my issues on Windows.

**Comment by blueyed** [comment] 2019-02-13 19:34
@rouault 
Thanks for the feedback.

I would still be interested in what triggers it though.
Note that `path` is not the `__init__.py` (from the error message) likely: https://github.com/pytest-dev/pytest/blob/8726be27a652733ada44e443e4196c322f22bc71/src/_pytest/python.py#L626-L633

**Comment by blueyed** [comment] 2019-02-13 19:35
@rouault 
How did you test it?  If you cannot reproduce it locally, maybe we could use a branch without the fix, but display the actual path?

**Comment by blueyed** [comment] 2019-02-13 19:44
@rouault 
You could try the assert branch: https://github.com/pytest-dev/pytest/pull/4790

**Comment by rouault** [comment] 2019-02-13 19:51
> How did you test it?

I updated my requirements.txt to `git+https://github.com/blueyed/pytest@fix-4782` and pushed that to get a new AppVeyor run

> You could try the assert branch: #4790

Will do
