### ISSUE TITLE
Warn when an async function is executed without an appropriate plugin

### ISSUE THREAD

**Issue by crusaderky** [pytest-dev/pytest#4814] opened 2019-02-22 15:21 UTC
In the following code:

```
async def test1():
    assert Fail

@pytest.mark.asyncio
async def test2():
    assert Fail
```

- test1 is silently skipped and marked as successful.
- test2 follows the same fate if pytest-asyncio is not installed.

Both use cases can be very easily triggered by distraction in real life; the sensible behaviour should be that both tests fail no matter what:

- Using the @pytest.mark.asyncio decorator without pytest-asyncio installed should cause an error
- An error should be raised if a test function returns a coroutine

**Comment by nicoddemus** [comment] 2019-02-22 15:34
I agree that we should do something when a function returns a coroutine, but I believe a warning would be better. The warning might even suggest one of the existing `async` plugins, for example: `pytest-asyncio`, `pytest-trio` or `pytest-tornasync`.

**Comment by Zac-HD** [comment] 2019-02-24 22:47
> * Using the `@pytest.mark.asyncio` decorator without pytest-asyncio installed should cause an error

You can [opt-in to errors on unknown marks](https://docs.pytest.org/en/latest/mark.html#raising-errors-on-unknown-marks-strict) with the `--strict` argument.

**Comment by nicoddemus** [comment] 2019-02-25 23:04
Closing as duplicate of #2224

**Closed by nicoddemus** 2019-02-25 23:04 UTC
Labels: topic: reporting, type: enhancement
