### ISSUE TITLE
Ordering of fixtures with mixed scoping

### ISSUE THREAD

**Issue by wcooley** [pytest-dev/pytest#2888] opened 2017-11-01 19:15 UTC
- [x] Include a detailed description of the bug or suggestion
  Given:
    * A session-scoped fixture.
    * A function-scoped fixture that requires the session-scoped fixture and modifies it.
    * Tests which use these fixtures in the order of session, function, session.
    * The last test expects the fixture to be in the same state that the first test expects.

  Then:
    * The last test fails because the function-scoped fixture has changed the fixture.

  Expectation:
    * All tests should succeed because the tests are re-ordered so that tests which depend only on the session-scoped fixture run first.
      * What should happen if there are other tests which use the function-scoped fixture; should they receive the resource as-is or should the session-scoped fixture be re-run as if it were also a function-scoped fixture? (I would expect the latter.)
      * I presume this occurs with any mixing of valid scopes.

- [x] Minimal example if possible

I've used a shared file as an example, although it is clearly not a realistic use-case and would be easy enough to avoid.
A more realistic example might be a database, where a function-scoped fixture might load bad data to test error handling.
It would be non-trivial to make completely separate instances of the database service to fully isolate a chain of function-scoped fixtures.
Currently, the only way to handle this is to carefully and explicitly order the tests, so that the tests using the session-scoped fixture are never able to run before the function-scoped (but that could fail with the use of `--failed-first`).

Even though I've used `pytester` to be able to run it all in one file, I started out with 4 separate files, so I am certain this is not a weird side-effect of running in an artificial environment.

```python
# test_fixture_scope.py
from textwrap import dedent as dd
import pytest

pytest_plugins = 'pytester'

def test_fixture_scope(testdir):
    testdir.makeconftest(dd("""
        import pytest

        @pytest.fixture(scope='session')
        def sample_file_name():
            return '/tmp/testfile.txt'

        @pytest.fixture(scope='session')
        def sample_file(sample_file_name):
            with open(sample_file_name, 'w') as f:
                f.writelines(['session fixture\\n'])
        """))

    test_01_and_03 = dd("""
        import pytest

        @pytest.mark.usefixtures('sample_file')
        def test_session_fixture(sample_file_name):
            with open(sample_file_name) as f:
                lines = [l.strip() for l in f.readlines()]
                assert len(lines) == 1
                assert lines == ['session fixture']
        """)
    testdir.makepyfile(test_01=test_01_and_03)
    testdir.makepyfile(test_03=test_01_and_03)

    testdir.makepyfile(test_02=dd("""
        import pytest

        @pytest.fixture(scope='function')
        def _sample_file(sample_file_name, sample_file):
            with open(sample_file_name, 'a') as f:
                f.writelines(['function fixture\\n'])

        @pytest.mark.usefixtures('_sample_file')
        def test_function_fixture(sample_file_name):
            with open(sample_file_name) as f:
                lines = [l.strip() for l in f.readlines()]
                assert len(lines) == 2
                assert lines == ['session fixture', 'function fixture']
        """))
            
    result = testdir.runpytest_subprocess()
    result.assert_outcomes(passed=3)
```

Partial output:
```
------ Captured stdout call -------
============================= test session starts ==============================
platform darwin -- Python 3.6.1, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /private/tmp/pytest-of-wcooley/pytest-11/testdir/test_fixture_scope0, inifile:
collected 3 items

test_01.py .
test_02.py .
test_03.py F

=================================== FAILURES ===================================
_____________________________ test_session_fixture _____________________________

sample_file_name = '/tmp/testfile.txt'

    @pytest.mark.usefixtures('sample_file')
    def test_session_fixture(sample_file_name):
        with open(sample_file_name) as f:
            lines = [l.strip() for l in f.readlines()]
>           assert len(lines) == 1
E           AssertionError: assert 2 == 1
E            +  where 2 = len(['session fixture', 'function fixture'])

test_03.py:7: AssertionError
====================== 1 failed, 2 passed in 0.05 seconds ======================
```

- [x] `pip list` of the virtual environment you are using
```
pip==9.0.1
py==1.4.34
pytest==3.2.3
setuptools==36.6.0
wheel==0.30.0
```
- [x] pytest and operating system versions
Python 3.6.1
pytest 3.2.3
OS X 10.11.6

**Comment by RonnyPfannschmidt** [comment] 2017-11-02 09:30
this is expected behaviour for modifiation of session scoped things
the scope controlls how long things stay around, so the file and file contents aren't going to be remade in between multiple tests using the fixture

**Comment by nicoddemus** [comment] 2018-03-20 23:25
Closing this for now since it's been awhile since there's been activity.

**Closed by nicoddemus** 2018-03-20 23:25 UTC
Labels: type: question
