### ISSUE TITLE
NameError in `exec()` when `from`-imported objects referenced in class scope

### ISSUE THREAD

**Issue by Zac-HD** [pytest-dev/pytest#7523] opened 2020-07-21 02:59 UTC
This is a bizzare issue, best explained by example:

```python
def test_exec_nameerror():
    exec("""
from re import match
class A:
    match("", "")
""")
```

```python-traceback
================================== FAILURES ===================================
_______________________________ test_nameerror ________________________________
Traceback (most recent call last):
  File "bugreport.py", line 6, in test_nameerror
    """
  File "<string>", line 3, in <module>
  File "<string>", line 4, in A
NameError: name 'match' is not defined
```

- Running the test function directly works
- Placing the same `exec` call at module level, so it is executed at import-time when the test is collected, also works
- *Only* running the test via `pytest` fails
- I've already checked that the `exec` function is not being replaced - `id(exec)` is the same at module level and inside the test function, despite the difference in behaviour

(also there really is a good reason to do this, I'm testing an introspection and templating tool outputs valid code)

**Comment by The-Compiler** [comment] 2020-07-21 07:13
I can reproduce this outside of pytest by just calling the function:

```python
def test_exec_nameerror():
    exec("""
from re import match
class A:
    match("", "")
""")

test_exec_nameerror()
```

```
$ python3 match.py 
Traceback (most recent call last):
  File "match.py", line 8, in <module>
    test_exec_nameerror()
  File "match.py", line 2, in test_exec_nameerror
    exec("""
  File "<string>", line 3, in <module>
  File "<string>", line 4, in A
NameError: name 'match' is not defined
```

**Comment by The-Compiler** [comment] 2020-07-21 07:20
From what I understand, what's happening is that the import is just an assignment. Because `exec` runs the code in your current scope, you end up with a `match` name in the `test_exec_nameerror` function scope, but the `match` inside your `class` expects to find one at global scope.

Running `exec` with `{}` or `globals()` as second argument will work, and so will adding a `global match` before the `import`.

Also see e.g. https://stackoverflow.com/questions/12505047/why-doesnt-an-import-in-an-exec-in-a-function-work which explains this behavior. I doubt there's anything pytest-specific there, so I'm closing this - happy to reopen if I'm wrong, though!

**Closed by The-Compiler** 2020-07-21 07:20 UTC
Labels: status: help wanted, type: bug

**Comment by Zac-HD** [comment] 2020-07-22 08:11
Huh, this is bizzare: it works *if and only if* I pass the same dict for globals and locals!  The two-dict form of `exec` fails :shrug: 

Anyway, I have it working now - thanks for the help.

**Comment by The-Compiler** [comment] 2020-07-22 08:28
The [docs for `exec()` say](https://docs.python.org/3/library/functions.html#exec):

> If exec gets two separate objects as *globals* and *locals*, the code will be executed as if it were embedded in a class definition.

Which might be what's influencing this?

**Comment by Zac-HD** [comment] 2020-07-22 08:31
Woah, yep:

```python
class A:
    from re import match

    class B:
        match("foo", "bar")
```

gets a `NameError` without any `exec` involvement at all :grimacing:
