### ISSUE TITLE
BUG: Keyboard is non-responsive  with Windows py.test 2.9.2 with --pdb

### ISSUE THREAD

**Issue by thequackdaddy** [pytest-dev/pytest#1825] opened 2016-08-20 00:23 UTC
Hello,

I had anaconda 4.1.1 installed on Windows. By default, that uses pytest 2.9.2. I'm working on debugging something and when I typed...

    (C:\Anaconda3) C:\git\glmtools>py.test glmtools --pdb

It started up the py.test and upon a fail, it it would got into `pdb` mode. However, The keyboard is totally non-responsive. Pressing Ctrl-C a couple times will eventually exit the pdb mode, and all the keys I had been trying to press will show up and the subsequent prompt. 

Any ideas how to fix this? 

My workaround was to downgrade to py.test 2.8.5, which works fine. pdb enters interactive mode and I can enter and change commands. 

Happy to provide more information, but here's some version information. 

    (C:\Anaconda3) C:\git\glmtools>python --version
    Python 3.5.2 :: Anaconda custom (64-bit)
    (C:\Anaconda3) C:\Users\pquackenbush\git\glmtools>py.test --version
    This is pytest version 2.9.2, imported from C:\Anaconda3\lib\site-packages\pytes
    t.py

The package glmtools is something I'm working on myself. Its not a complex script. With that said, I've tried this on multiple packages (and both a Windows 7 laptop and a Windows Server 2013 virtual machine) and had the same outcome. 

Thoughts?

**Comment by nicoddemus** [comment] 2016-08-20 18:58
Thanks for the report, I'm closing this as a duplicate of #1388.

**Closed by nicoddemus** 2016-08-20 18:58 UTC
