### ISSUE TITLE
Pytest suddenly cannot find module

### ISSUE THREAD

**Issue by adamhrosenberg** [pytest-dev/pytest#3789] opened 2018-08-07 19:38 UTC
Hello. I use pytest on a CI server to test our software. We have been using pytest for years but with the latest update we have an error importing a module during pytest. My logic behind isolating this issue to pytest is: on the CI server, nothing has changed (same python, same code, same OS image) the updated version of pytest is the only thing that has changed.

original versions of what pytest passed with
platform linux2 -- Python 2.7.12, pytest-3.6.3, py-1.5.4, pluggy-0.6.0

current versions where I get failures:
platform linux2 -- Python 2.7.12, pytest-3.7.1, py-1.5.4, pluggy-0.7.1

Let's say the module that cannot import is called X. When within the directory of X, (where the _UnitTest directory is) running pytest allows all of the tests to pass. Changing directory back one layer (or anywhere outside of the X directory), now those tests from module X fail because the import statement failed. 

Also on macOS I had all of the tests passing with pytest 3.6.3. Upgraded pytest, and now the tests related to module X fail. Many other modules import and work however module X does not. I have debugged a lot of it, and all of the paths look good, but it still fails to import. I'm not exactly sure what sets module X apart from the other dozens of module we use successfully. 

I hope this makes sense and I can elaborate more if needed. I am not working in a virtualenv but I can put full pip lists in the comments if more is needed other then the versions I gave above. 

Thank you

Adam

**Comment by Agi-dev** [comment] 2018-08-09 08:08
Same issue for me, if I downgrade to version <7.1 it's working.

**Comment by adamhrosenberg** [comment] 2018-08-09 15:13
@Agi-dev thank you for the feedback! glad to know i'm not alone

**Comment by nicoddemus** [comment] 2018-08-09 23:29
Hi guys, sorry for the delay.

Does `3.7.0` work for you? It might help pin point the problem. Also if any of you can produce a reproducible use case it would be great.

**Comment by Agi-dev** [comment] 2018-08-10 08:57
Sorry, I've tried to reproduce it with simple example with no success despite the fact I've found a way to make my tests work again.
I've fixed the pb (for me) by deleting a '__init__.py' in the first sub directory of my tests directory. I'm not sure it's the way to go, I'm relatively new in Python programming.

**Comment by nicoddemus** [comment] 2018-08-10 15:15
We should release `3.7.2` soon (probably next week) with a few fixes in place regarding package collection (#3768, #3526), let's see if they end up solving this issue as well.

**Comment by adamhrosenberg** [comment] 2018-08-10 17:37
Sounds great

**Comment by highvelcty** [comment] 2018-08-10 17:38
Here is a way to reproduce the problem:

Make a directory structure such as

```
/tmp/dir1/
/tmp/dir1/__init__.py
/tmp/dir1/dir1_1/
/tmp/dir1/dir1_1/__init__.py
/tmp/dir1/dir1_1/test_1_1.py
/tmp/dir1/dir1_1/test_1_1.py::test_1_1_case
/tmp/dir1/dir1_2/
/tmp/dir1/dir1_2/test_1_2.py
/tmp/dir1/dir1_2/test_1_2.py::test_1_2_case
```

then `run pytest /tmp --collect-only`

the output is
```
================================================ test session starts =================================================
platform linux -- Python 3.5.2, pytest-3.7.1, py-1.5.4, pluggy-0.7.1
rootdir: /, inifile:
collected 2 items                                                                                                    
<Package '/tmp/dir1'>
  <Package '/tmp/dir1/dir1_1'>
    <Module 'test_1_1.py'>
      <Function 'test_1_1_case'>
  <Module 'test_1_2.py'>
    <Function 'test_1_2_case'>
```

It seems there is a problem when mixing directories of tests with packages of tests. Note that there is no mention of dir1_2 in the output. I saw this starting with 3.7.0. I do not see the issue with 3.6.4.

Eric

**Comment by adamhrosenberg** [comment] 2018-08-10 17:44
Thank you! That's great

**Comment by adamhrosenberg** [comment] 2018-08-10 17:49
@nicoddemus I still haven't found a way to reproduce it outside of my software package. We are open source so if you really want to test, you can get our code from here:

[source](https://bitbucket.org/avslab/basilisk/src
)
Here is some documentation on compiling:
[documents](http://hanspeterschaub.info/bskHtml/pages.html)

**Comment by jonozzz** [comment] 2018-08-10 20:41
Seems like a duplicate of #3768 . Can you try my pull request and see if that fixes your issue?

**Comment by adamhrosenberg** [comment] 2018-08-13 15:40
yea i can do that today

**Comment by adamhrosenberg** [comment] 2018-08-13 20:04
@jonozzz assuming i've followed your PR trail correctly, I should be cloning your fork of pytest-dev with this branch?
https://github.com/jonozzz/pytest/tree/fix-3768

**Comment by jonozzz** [comment] 2018-08-13 20:58
I would install it in a virtualenv like this:
`pip install git+git://github.com/jonozzz/pytest.git@fix-3768`

**Comment by adamhrosenberg** [comment] 2018-08-14 15:58
yea that's pretty much what I did. no luck though, same error

**Comment by jonozzz** [comment] 2018-08-14 21:16
@adamhrosenberg might be a different issue then. Can you work on a minimal set of repro steps that you could share? Or at least paste the command you're running and the complete traceback and maybe I can figure out what's going on.

**Closed** 2018-08-16 00:43 UTC
Labels: status: needs information

**Comment by adamhrosenberg** [comment] 2018-08-18 17:37
Not sure why this was closed, the PR still doesn't fix my problem. Sorry I wasn't able to get back to you right away it was a busy week. I'll post the traceback below

**Comment by nicoddemus** [comment] 2018-08-18 17:41
Hi @adamhrosenberg, if this is still is an issue we can re-open this, no problem! Did you try out with the recently released `3.7.2`?

**Comment by jonozzz** [comment] 2018-08-18 18:15
I think this has more to do with PR #3797 because `__init__.py` is hardcoded in python_files. It will error out when there's a bad `__init__.py` somewhere, whereas in 3.6.x it'd just ignore it.

**Comment by jonozzz** [comment] 2018-08-21 04:39
@adamhrosenberg can you post that traceback, hopefully that'll give me some clues on what's going on.

**Comment by burg** [comment] 2018-08-22 16:37
I am also encountering a similar sounding issue on 3.7.2. I'll try to figure out a reduced test case.

**Comment by CrimsonGlory** [comment] 2018-08-23 19:30
3.7.2 has fixed the issue for me.

**Comment by GiriManas** [comment] 2019-08-24 02:40
Need a help...( I am very new to python)
I am not getting pytest.assume
I have imported 
import pytest
and trying to use pytest.assume as mentioned in the doc, unable to use it

**Comment by CrimsonGlory** [comment] 2019-08-24 05:05
@GiriManas pytest-assume works as expected. 

```
$ cat test-assume.py                                                                                                      
import pytest

@pytest.mark.parametrize(('x', 'y'), [(1, 1), (1, 0), (0, 1)])
def test_simple_assume(x, y): 
    pytest.assume(x == y)
    pytest.assume(True)
    pytest.assume(False)

$ sudo docker run -ti --rm -v "$(pwd)/test-assume.py:/root/test-assume.py" python:3 bash -c "pip install pytest-assume > /
dev/null 2>&1 && cd /root && ls && pytest test-assume.py"
test-assume.py
================================================================ test session starts =================================================================
platform linux -- Python 3.7.4, pytest-5.1.1, py-1.8.0, pluggy-0.12.0
rootdir: /root
plugins: assume-2.2.0
collected 3 items                                                                                                                                    

test-assume.py FFF                                                                                                                             [100%]

====================================================================== FAILURES ======================================================================
______________________________________________________________ test_simple_assume[1-1] _______________________________________________________________

tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None

    def reraise(tp, value, tb=None):
        try:
            if value is None:
                value = tp()
            if value.__traceback__ is not tb:
>               raise value.with_traceback(tb)
E               pytest_assume.plugin.FailedAssumption: 
E               1 Failed Assumptions:
E 
E               test-assume.py:7: AssumptionFailure
E               >>      pytest.assume(False)
E               AssertionError: assert False

/usr/local/lib/python3.7/site-packages/six.py:692: FailedAssumption
______________________________________________________________ test_simple_assume[1-0] _______________________________________________________________

tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None

    def reraise(tp, value, tb=None):
        try:
            if value is None:
                value = tp()
            if value.__traceback__ is not tb:
>               raise value.with_traceback(tb)
E               pytest_assume.plugin.FailedAssumption: 
E               2 Failed Assumptions:
E               
E               test-assume.py:5: AssumptionFailure
E               >>      pytest.assume(x == y)
E               AssertionError: assert False
E               
E               test-assume.py:7: AssumptionFailure
E               >>      pytest.assume(False)
E               AssertionError: assert False

/usr/local/lib/python3.7/site-packages/six.py:692: FailedAssumption
______________________________________________________________ test_simple_assume[0-1] _______________________________________________________________

tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None

    def reraise(tp, value, tb=None):
        try:
            if value is None:
                value = tp()
            if value.__traceback__ is not tb:
>               raise value.with_traceback(tb)
E               pytest_assume.plugin.FailedAssumption: 
E               2 Failed Assumptions:
E               
E               test-assume.py:5: AssumptionFailure
E               >>      pytest.assume(x == y)
E               AssertionError: assert False
E               
E               test-assume.py:7: AssumptionFailure
E               >>      pytest.assume(False)
E               AssertionError: assert False

/usr/local/lib/python3.7/site-packages/six.py:692: FailedAssumption
================================================================= 3 failed in 0.31s ==================================================================              
```

**Comment by sorenwacker** [comment] 2021-09-22 20:19
I am facing this today on GitHub. Test run locally.

```
Run pip install pytest
Requirement already satisfied: pytest in /opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages (6.2.5)
Requirement already satisfied: iniconfig in /opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages (from pytest) (1.1.1)
Requirement already satisfied: toml in /opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages (from pytest) (0.10.2)
Requirement already satisfied: packaging in /opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages (from pytest) (21.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages (from pytest) (1.0.0)
Requirement already satisfied: py>=1.8.2 in /opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages (from pytest) (1.10.0)
Requirement already satisfied: attrs>=19.2.0 in /opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages (from pytest) (21.2.0)
Requirement already satisfied: pyparsing>=2.0.2 in /opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages (from packaging->pytest) (2.4.7)
============================= test session starts ==============================
platform linux -- Python 3.8.11, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /home/runner/work/ms-mint/ms-mint, configfile: setup.cfg
plugins: dash-2.0.0, cov-2.12.1
collected 0 items / 15 errors

==================================== ERRORS ====================================
________________ ERROR collecting tests/test__MINT_notebook.py _________________
ImportError while importing test module '/home/runner/work/ms-mint/ms-mint/tests/test__MINT_notebook.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test__MINT_notebook.py:1: in <module>
    from ms_mint.notebook import Mint
E   ModuleNotFoundError: No module named 'ms_mint'
```

**Comment by nicoddemus** [comment] 2021-09-23 12:20
Hi @sorenwacker,

Only that doesn't give us enough information to help you, but basically `pytest` cannot import `ms_mint`. 

How are you installing `ms_mint` in GitHub Actions (I suppose that's what you mean by "GitHub")?

**Comment by sorenwacker** [comment] 2021-09-24 00:21
Hm, that is the package that the tests should test and I did not change the github actions file. It was never necessary to install that package.

**Comment by sorenwacker** [comment] 2021-09-24 00:29
Yes, that worked. I added this to the gh-actions file:

        pip install .

Thanks for your time.
