### ISSUE TITLE
pytest.main(['--collect-only']) error

### ISSUE THREAD

**Issue by wang1150297847** [pytest-dev/pytest#11396] opened 2023-09-06 06:11 UTC
> >old issues :https://github.com/pytest-dev/pytest/issues/11202
> >
> > demo:
> 
> > ```python
> > import pytest
> > 
> > 
> > class TestClass_A:
> >     @pytest.mark.parametrize(
> >         "case_lel,id,",
> >         [
> >             ("测试用例名称P0", 0),
> >             ("测试用例名称P1", 6),
> >             ("hzhzhzhzP0", 1),
> >             ("测试用例名称P2", 2),
> >             ("hzhzhzhzP2", 3),
> >         ],
> >         ids=[("测试用例名称P0"), ("测试用例名称P1"), ("hzhzhzhzP0"), ("测试用例名称P2"), ("hzhzhzhzP2")],
> >     )
> >     def test_demo(self, case_lel, id):
> >         print(id)
> > 
> >
> > 
> > pytest D:\\python_test\\test\\demo8.py::TestClass_A::test_demo --co
> > ====================================================================================== test session starts ======================================================================================
> > platform win32 -- Python 3.10.3, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
> > rootdir: d:\python_test\test
> > plugins: allure-pytest-2.9.43, anyio-3.6.2, Faker-15.2.0, forked-1.3.0, ordering-0.6, parallel-0.0.10, repeat-0.9.1, rerunfailures-10.0,  timeout-2.1.0, xdist-2.3.0
> > collected 5 items                                                                                                                                                                                
> > 
> > <Module demo8.py>
> >   <Class TestClass_A>
> >       <Function test_demo[\u6d4b\u8bd5\u7528\u4f8b\u540d\u79f0P0]>
> >       <Function test_demo[\u6d4b\u8bd5\u7528\u4f8b\u540d\u79f0P1]>
> >       <Function test_demo[hzhzhzhzP0]>
> >       <Function test_demo[\u6d4b\u8bd5\u7528\u4f8b\u540d\u79f0P2]>
> >       <Function test_demo[hzhzhzhzP2]>
> > ```
> > 
> > 
> > 
> > if only one Unicode-encoded test case name,it works.
> > ```
> > if __name__ == "__main__":
> >    case_list = [
> >        "demo.py::TestClass_A::test_demo[\\u6d4b\\u8bd5\\u7528\\u4f8b\\u540d\\u79f0P0]"
> >    ]
> >    for i in case_list:
> >        pytest.main([i, "--co"])
> > 
> >
> >
> > 
> >  C:/Python310/python.exe d:/python_test/test/demo8.py
> > ===================================================================================== test session starts ======================================================================================
> > platform win32 -- Python 3.10.3, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
> > rootdir: d:\python_test\test
> > plugins: allure-pytest-2.9.43, anyio-3.6.2, Faker-15.2.0, forked-1.3.0, ordering-0.6, parallel-0.0.10, repeat-0.9.1, rerunfailures-10.0, > > timeout-2.1.0, xdist-2.3.0
> > collected 1 item                                                                                                                                                                                 
> > 
> > <Module demo8.py>
> >   <Class TestClass_A>
> >       <Function test_demo[\u6d4b\u8bd5\u7528\u4f8b\u540d\u79f0P0]>
> > ```
> >
> > another Unicode-encoded test case name,it works.
> > ```
> > if __name__ == "__main__":
> >    case_list = [
> >        "demo.py::TestClass_A::test_demo[\\u6d4b\\u8bd5\\u7528\\u4f8b\\u540d\\u79f0P1]"
> >    ]
> >    for i in case_list:
> >        pytest.main([i, "--co"])
> > 
> >
> > 
> > 
> > C:/Python310/python.exe d:/python_test/test/demo8.py
> > ===================================================================================== test session starts ======================================================================================
> > platform win32 -- Python 3.10.3, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
> > rootdir: d:\python_test\test
> > plugins: allure-pytest-2.9.43, anyio-3.6.2, Faker-15.2.0, forked-1.3.0, ordering-0.6, parallel-0.0.10, repeat-0.9.1, rerunfailures-10.0, > > timeout-2.1.0, xdist-2.3.0
> > collected 1 item                                                                                                                                                                                 
> > 
> > <Module demo8.py>
> >   <Class TestClass_A>
> >       <Function test_demo[\u6d4b\u8bd5\u7528\u4f8b\u540d\u79f0P1]>
> > ```
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but if more than one Unicode-encoded test case name, only the first Unicode-encoded test case can find,others cann't find.
> > ```
> > if __name__ == "__main__":
> >    case_list = [
> >        "demo.py::TestClass_A::test_demo[\\u6d4b\\u8bd5\\u7528\\u4f8b\\u540d\\u79f0P0]",
> >        "demo.py::TestClass_A::test_demo[\\u6d4b\\u8bd5\\u7528\\u4f8b\\u540d\\u79f0P1]",
> >        "demo.py::TestClass_A::test_demo[\\u6d4b\\u8bd5\\u7528\\u4f8b\\u540d\\u79f0P2]"
> >    ]
> >    for i in case_list:
> >        pytest.main([i, "--co"])
> > 
> >
> >
> > 
> > C:/Python310/python.exe d:/python_test/test/demo8.py
> > ===================================================================================== test session starts ======================================================================================
> > platform win32 -- Python 3.10.3, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
> > rootdir: d:\python_test\test
> > plugins: allure-pytest-2.9.43, anyio-3.6.2, Faker-15.2.0, forked-1.3.0, ordering-0.6, parallel-0.0.10, repeat-0.9.1, rerunfailures-10.0, > > timeout-2.1.0, xdist-2.3.0
> > collected 1 item
> > 
> > <Module demo8.py>
> >   <Class TestClass_A>
> >       <Function test_demo[\u6d4b\u8bd5\u7528\u4f8b\u540d\u79f0P0]>
> > ================================================================================== 1 test collected in 0.02s =================================================================================== 
> > ===================================================================================== test session starts ======================================================================================
> > platform win32 -- Python 3.10.3, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
> > rootdir: d:\python_test\test
> > plugins: allure-pytest-2.9.43, anyio-3.6.2, Faker-15.2.0, forked-1.3.0, ordering-0.6, parallel-0.0.10, repeat-0.9.1, rerunfailures-10.0, timeout-2.1.0, xdist-2.3.0
> > collected 0 items                                                                                                                                                                                
> > ================================================================================= no tests collected in 0.01s ================================================================================== 
> > ERROR: not found: D:\python_test\test\demo8.py::TestClass_A::test_demo[\u6d4b\u8bd5\u7528\u4f8b\u540d\u79f0P1]
> > (no name 'D:\\python_test\\test\\demo8.py::TestClass_A::test_demo[\\u6d4b\\u8bd5\\u7528\\u4f8b\\u540d\\u79f0P1]' in any of [<Module demo8.py>])
> > ===================================================================================== test session starts ======================================================================================
> > platform win32 -- Python 3.10.3, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
> > rootdir: d:\python_test\test
> > plugins: allure-pytest-2.9.43, anyio-3.6.2, Faker-15.2.0, forked-1.3.0, ordering-0.6, parallel-0.0.10, repeat-0.9.1, rerunfailures-10.0, timeout-2.1.0, xdist-2.3.0
> > collected 0 items                                                                                                                                                                                
> > ================================================================================= no tests collected in 0.01s ================================================================================== 
> > ERROR: not found: D:\python_test\test\demo8.py::TestClass_A::test_demo[\u6d4b\u8bd5\u7528\u4f8b\u540d\u79f0P2]
> > (no name 'D:\\python_test\\test\\demo8.py::TestClass_A::test_demo[\\u6d4b\\u8bd5\\u7528\\u4f8b\\u540d\\u79f0P2]' in any of [<Module demo8.py>])    
> > ```       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but if test case name doesn't have Unicode-encoded, it works.
> > ```
> > if __name__ == "__main__":
> >    case_list = [
> >        "demo.py::TestClass_A::test_demo[hzhzhzhzP0]",
> >        "demo.py::TestClass_A::test_demo[hzhzhzhzP2]",
> >    ]
> >    for i in case_list:
> >        pytest.main([i, "--co"])
> > ```
> 
> ```
> platform win32  
> Python 3.10.3, 
> pytest-6.2.4, 
> py-1.10.0, 
> pluggy-0.13.1 
> ```

**Comment by The-Compiler** [comment] 2023-09-06 09:19
Duplicate of #11202

**Closed by The-Compiler** 2023-09-06 09:19 UTC
