### ISSUE TITLE
error: "FixtureRequest" has no attribute "param"

### ISSUE THREAD

**Issue by nipunn1313** [pytest-dev/pytest#9514] opened 2022-01-15 00:13 UTC
Based on the instructions here
https://docs.pytest.org/en/6.2.x/fixture.html#parametrizing-fixtures

I believe that `FixtureRequest.param` is an optional param. It appears to exist at runtime. However, if I try
to access it, mypy gives an error

```
error: "FixtureRequest" has no attribute "param"
```

Using mypy 0.931
Using pytest 6.2.5

Can repro with
```python
@pytest.fixture(params=["a", "b"])
def myfixture(request: pytest.FixtureRequest) -> str:
    return request.param
```

**Comment by tirkarthi** [comment] 2022-01-15 06:26
https://docs.pytest.org/en/6.2.x/reference.html?highlight=fixturerequest#request

>    A request object gives access to the requesting test context and has an optional param attribute in case the fixture is parametrized indirectly.

See also https://github.com/pytest-dev/pytest/issues/8073 which seems to be similar to this issue and https://github.com/pytest-dev/pytest/issues/7469

**Comment by Zac-HD** [comment] 2022-01-16 22:59
Totally reasonable feature request, I'm just closing it as a duplicate of #8073.

**Closed by Zac-HD** 2022-01-16 22:59 UTC
Labels: topic: typing

**Comment by nipunn1313** [comment] 2022-07-14 01:46
I think #8073 scopes up this task quite a bit. The fix here is much smaller than the requirements for #8073.

Recommending reopening this task, and submitted a PR #10133 that fixes it.
