### ISSUE TITLE
pytest does not print chained exception for python 3

### ISSUE THREAD

**Issue by jettify** [pytest-dev/pytest#1278] opened 2015-12-24 15:02 UTC
py.test pytest (2.8.5) does not print chained exceptions, data located in `e.__cause__` and  `e.__context__`.

If I execute this little script using python3 (`python3 test_exception.py`):
```python
def test_x():
    try:
        raise KeyError
    except Exception as e:
        raise RuntimeError from e

if __name__ == '__main__':
    test_x()
```
I get:
```python
Traceback (most recent call last):
  File "py_test.py", line 4, in test_x
    raise KeyError
KeyError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "py_test.py", line 9, in <module>
    test_x()
  File "py_test.py", line 6, in test_x
    raise RuntimeError from e
RuntimeError
```
in case of py.test (`py.test test_exception.py`):
```python
    def test_x():
        try:
            raise KeyError
        except Exception as e:
>           raise RuntimeError from e
E           RuntimeError

py_test.py:6: RuntimeError
```

**Comment by nicoddemus** [comment] 2015-12-24 16:09
Thanks @jettify!

Closing as a duplicate of #138 though. 

This should be tackled soon, because what was blocking this issue was #103, which is a working in progress at #1199.

**Closed by nicoddemus** 2015-12-24 16:09 UTC
