### ISSUE TITLE
Surprising interaction of --pyargs pkg when pkg is a local folder with conftest.py in the current directory

### ISSUE THREAD

**Issue by lesteve** [pytest-dev/pytest#2802] opened 2017-09-27 09:38 UTC
Use case: I am in my dev folder `~/dev/scikit-learn` where the `sklearn` folder contains all the Python code and tests. Under Linux I have been relying on the following:
* `pytest sklearn` will run the tests on the local folder 
* `pytest --pyargs sklearn` will test the installed package in site-packages. Testing the installed package is useful because it is quite easy to forget to include some files in setup.py, e.g. data files.

On Windows it seems like the local folder is always picked whether or not you use `--pyargs`. Of course an easy work-around is to cd into an another folder. 

Is it an undefined behaviour and I was just plain lucky that the behaviour matched my expectations on Linux?

**Comment by nicoddemus** [comment] 2017-09-27 16:44
> On Windows it seems like the local folder is always picked whether or not you use --pyargs.

Is `sklearn` installed in `site-packages` in this case?

**Comment by lesteve** [comment] 2017-09-27 17:44
> Is sklearn installed in site-packages in this case?

Yes. Sorry I wanted to put together a reproducing example but did not get around to it.

**Comment by lesteve** [comment] 2017-09-27 18:25
Ah sorry I think I messed something up along the way so I am going to change my question if I may. It is not specific to Windows at all (same behaviour under Linux) but rather to `--pyargs` interaction with conftest.py.

So my project is like this
```
conftest.py
yaml
├── yaml/__init__.py
└── yaml/test_me.py
```

I was expecting that `pytest --pyargs yaml` would use `yaml` in site-packages but because of the conftest.py, the local folder is always used. I attached a zip of the toy 
[project](https://github.com/pytest-dev/pytest/files/1338304/project.zip).
You need to have pyyaml installed (you can install it via `pip install pyyaml`) which is importable `import yaml` so that the local folder interferes with the package in site-packages.

To reproduce:
```
unzip project.zip
cd project
pytest --pyargs yaml
```

Output:
```
======================================================== test session starts ========================================================
platform linux -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /tmp/project, inifile:
collected 1 item                                                                                                                     

yaml/test_me.py F

============================================================= FAILURES ==============================================================
_______________________________________________________________ test ________________________________________________________________

    def test():
>       raise ValueError('Local package used')
E       ValueError: Local package used

yaml/test_me.py:2: ValueError
===================================================== 1 failed in 0.02 seconds ======================================================
```
rm conftest.py
pytest --pyargs yaml
```
Output:
```
======================================================== test session starts ========================================================
platform linux -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /tmp/project, inifile:
collected 0 items                                                                                                                    

=================================================== no tests ran in 0.01 seconds ====================================================
```

**Comment by nicoddemus** [comment] 2017-09-27 18:28
Ahh OK now I see what's going on.

The problem is that in order to import `conftest.py`, `pytest` has to add the folder that contains `conftest.py` to `sys.path`, that's why it ends picking up your local package instead of the one in site-packages.

There's a more complete explanation here: https://docs.pytest.org/en/latest/pythonpath.html

I'm closing this for now, I believe we got to the heart of your question, but feel free to follow up with more questions if you have any. 👍

**Closed by nicoddemus** 2017-09-27 18:28 UTC
Labels: type: question

**Comment by lesteve** [comment] 2017-09-27 18:39
Right, thanks a whole bunch for your answer, I knew I was going to go back to this page and scratch my head a bit over it. To be perfectly honest, it kind of makes sense now I remember I added conftest.py in the root folder so that the `sklearn` folder was added to sys.path and I could do `pytest doc/**/*.rst` to test doctests in our rst docs ...

Moving over from nose it is one of the more subtle gotchas in my experience (no judgement at all in this sentence just to be clear). I am not entirely sure how it works in detail but I think nose adds the local folder into sys.path.

**Comment by nicoddemus** [comment] 2017-09-27 18:42
> I am not entirely sure how it works in detail but I think nose adds the local folder into sys.path.

IIRC that's the case. The problem is this brings a whole bunch of gotchas with it, that's why pytest decided a long time a go to stay clear of that.

Nowadays the "good practice" is to also use [`tox`](https://tox.readthedocs.io/en/latest/) for proper testing. It will create a package of your project, install it into a virtual environment and run the tests from there. I suggest to take a look. 👍

**Comment by lesteve** [comment] 2017-09-27 21:53
Great, thanks for the answers and the recommendation.
