### ISSUE TITLE
Try/Finally + yield produces I/O operation on closed file when logging

### ISSUE THREAD

**Issue by davido912** [pytest-dev/pytest#10053] opened 2022-06-16 09:15 UTC
**Description**
It would appear to be that there are issues already in regards to this. However, I'm not sure if what I'm facing is identical to the rest.
When running our tests we are getting the following logging errors at the end of the test run:

```
--- Logging error ---
Traceback (most recent call last):
  File "/Users/david.ohayoncontentful.com/Projects/Meltwater/Repositories/icerocket-facebook/src/lib/scraper/scheduler.py", line 178, in backtrack
    yield None
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/david.ohayoncontentful.com/.pyenv/versions/3.10.4/lib/python3.10/logging/__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/Users/david.ohayoncontentful.com/Projects/Meltwater/Repositories/icerocket-facebook/src/lib/scraper/scheduler.py", line 192, in backtrack
    log.info('backtrack(%r) closed.', backtrack_mq_name)
Message: 'backtrack(%r) closed.'
Arguments: ('testbacktrack.0.160747939342',)
```

it can be reproduced with:
```python
import logging

log = logging.getLogger(__name__)
log.setLevel(logging.DEBUG)
handler = logging.StreamHandler()
handler.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)
log.addHandler(handler)


def func_to_test():
    try:
        yield 5
    finally:
        log.info("this is a closure msg")
        log.debug("byebye")

class TestRep:
    def setup(self):
        self.generator = func_to_test()

    def test_rep(self):
        assert next(self.generator) == 5
```
to replicate this, run the above test.

Version: `pytest==7.1.2`

Is this the same as https://github.com/pytest-dev/pytest/issues/5502 or is there any other way to solve this currently?

- [ X] a detailed description of the bug or problem you are having
- [ X] output of `pip list` from the virtual environment you are using
- [ X] pytest and operating system versions
- [ X] minimal example if possible

**Comment by RonnyPfannschmidt** [comment] 2022-06-16 11:41
Stream handlers that copy io capture monkeypatched streams are bound to break, please use the logging plugin instead of custom global state

**Comment by nicoddemus** [comment] 2022-06-26 12:52
The problem is that setting up logging globally (unfortunately that is how the logging tutorial recommends it), will break pytest's logging facilities and there's not really anything pytest can do about this (AFAIK).

So the suggestion is to either: disable pytest logging with `-p no:logging`, or setup your logging not during import time, but some time after main in your application.

For example, if you have this currently:

```python
import logging

log = logging.getLogger(__name__)
log.setLevel(logging.DEBUG)
handler = logging.StreamHandler()
handler.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)
log.addHandler(handler)

def main():
    ...


if __name__ == "__main__":
    main()
```

Do this instead:

```python
import logging

log = logging.getLogger(__name__)
log.setLevel(logging.DEBUG)

def main():
    ...


if __name__ == "__main__":
    
    handler = logging.StreamHandler()
    handler.setLevel(logging.DEBUG)
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    handler.setFormatter(formatter)
    log.addHandler(handler)
    main()
```

For web apps, most framework's have an equivalent "hook" for main where you can setup logging.

This way, when running the tests the above logging setup won't interfere with pytest's own logging handling.

Closing for now, feel free to follow up.

**Closed by nicoddemus** 2022-06-26 12:52 UTC
Labels: plugin: logging
