### ISSUE TITLE
Global variables from pytest_namespace hook doesnt seem to work when xdist is used.

### ISSUE THREAD

**Issue by karthikborkar** [pytest-dev/pytest#1402] opened 2016-02-19 13:59 UTC
To use global variables across my test i have used pytest_namespace hook, Updating these variables seem to work fine without xdist.But when i use xdist to run my test in parallel , These global variables are not updated

Here is my conftest.py file

    def pytest_namespace():
         return  {'my_global_variable': 0}

`

Here is my test file test_dummy.py

    def test_this(self):
         pytest.my_global_variable =  pytest.my_global_variable +1

    def test_this1(self):
         pytest.my_global_variable =  pytest.my_global_variable +1

    def test_this2(self):
         pytest.my_global_variable =  pytest.my_global_variable +1

    def test_this3(self):
         pytest.my_global_variable =  pytest.my_global_variable +1

    def test_this4(self):
         pytest.my_global_variable =  pytest.my_global_variable +1

    def test_this5(self):
         pytest.my_global_variable = pytest.my_global_variable +1

So when i run 
`py.test -v -s path/test_dummy.py`

i see the global variable my_global_variable getting updated correctly

but when i do

`py.test -v -s path/test_dummy.py -n2`

i see the global variable my_global_variable is not updated at all

what iam i missing here?

Python version :  2.7.9

pip list
`
pytest (2.7.0)
pytest-instafail (0.3.0)
pytest-rerunfailures (0.5)
pytest-timeout (0.3)
pytest-xdist (1.13.1)

`

**Comment by nicoddemus** [comment] 2016-02-19 14:34
I tried your example and actually `my_global_variable` is updated, but perhaps not the way you expect: keep in mind that `pytest-xdist` with `-n2` will spawn two workers in separate processes, and each one of them will have their own version of `my_global_variable`.

**Comment by karthikborkar** [comment] 2016-02-19 14:47
Thanks for the quick response.
So I was using global variable to print terminal summary and it wasn't
updating for me when running -n2.. I know it spans  two separate
processes..is there a way to communicate all the result from subprocess
here to get final result ?

**Comment by nicoddemus** [comment] 2016-02-19 14:52
Hmm I'm afraid there's no easy way to send back information from the slaves unfortunately, others please correct me if I'm wrong (sending information from master to slaves can be done using the `config.slaveinput` config dictionary, though).

Could you describe the exact problem you are trying to accomplish? Perhaps with the actual problem others can suggest a different way to accomplish the same thing.

**Comment by karthikborkar** [comment] 2016-02-19 14:54
Basically i want to keep track of some attributes across my tests , i have many test_XXX.py file. and at the end after test run is done. i want to print it using pytest_terminal_summary hook

**Comment by nicoddemus** [comment] 2016-02-19 16:49
Hmmm for this case in specific I would use a file on disk, by creating a temporary directory on the master node and forwarding that to the workers, which can then use that directory to write any data they want (for example in `json`). Then during `pytest_terminal_summary` you can read all generated files and compile them into a single piece of information. 

Here's a quick howto create this shared directory and have a `shared_directory` fixture which can be used by both master and worker nodes equally.

```python
def pytest_configure(config):        
    if is_master(config):
        config.shared_directory = tempdir.mktemp()

def pytest_unconfigure(config):        
    if is_master(config):
        shutil.rmtree(config.shared_directory)


def pytest_configure_node(self, node):
    """xdist hook"""
    node.slaveinput['shared_dir'] = node.config.shared_directory


@pytest.fixture
def shared_directory(request):
    if is_master(request.config):
        reutrn request.config.shared_directory
    else:
        return request.config.slaveinput['shared_dir']


def is_master(config):
    """True if the code running the given pytest.config object is running in a xdist master
    node or not running xdist at all.
    """
    return not hasattr(config, 'slaveinput')
```

HTH

**Comment by karthikborkar** [comment] 2016-02-22 16:32
Thanks, the above solution seem to work

**Comment by nicoddemus** [comment] 2016-02-22 16:35
If there's nothing else, could you please close this issue? :grin:

**Closed** 2016-02-22 16:45 UTC

**Comment by sinaparker** [comment] 2020-08-24 07:45
hello, i have read the code which you write on the reply,but when i am trying  it shows" hookimpl definition: pytest_configure_node(self, node)
Argument(s) {'self'} are declared in the hookimpl but can not be found in the hookspec"
what can i do about this ?is this caused by the new xidst version?

**Comment by nicoddemus** [comment] 2020-08-24 10:42
Is your `pytest_configure_node` implementation declared in a class?

**Comment by sinaparker** [comment] 2020-09-02 00:44
no,but how declare the implemente of  pytest_configure_node? this is the first i am using the hook

**Comment by nicoddemus** [comment] 2020-09-02 12:24
Ahh apologies, my post was incorrect, the correct signature is:

```
def pytest_configure_node(node):
    """xdist hook"""
    node.slaveinput['shared_dir'] = node.config.shared_directory
```

I've updated the original post as well.

**Comment by sinaparker** [comment] 2020-09-03 01:26
ths for your attention,but when i try the newest code in my confest.py,it show more error info like this:
===================================================
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "D:\Program Files\Python36\lib\site-packages\_pytest\main.py", line 236, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "D:\Program Files\Python36\lib\site-packages\_pytest\config\__init__.py", line 911, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "D:\Program Files\Python36\lib\site-packages\pluggy\hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "D:\Program Files\Python36\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "D:\Program Files\Python36\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "D:\Program Files\Python36\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "D:\Program Files\Python36\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "D:\Program Files\Python36\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "E:\tnbs\autotest\SemRec_002\conftest.py", line 22, in pytest_configure
INTERNALERROR>     if xdist.is_xdist_master(config):
INTERNALERROR>   File "D:\Program Files\Python36\lib\site-packages\xdist\plugin.py", line 216, in is_xdist_master
INTERNALERROR>     not is_xdist_worker(request_or_session)
INTERNALERROR>   File "D:\Program Files\Python36\lib\site-packages\xdist\plugin.py", line 204, in is_xdist_worker
INTERNALERROR>     return hasattr(request_or_session.config, "workerinput")
INTERNALERROR> AttributeError: 'Config' object has no attribute 'config'
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Program Files\PyCharm Community Edition 2020.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\Program Files\PyCharm Community Edition 2020.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/tnbs/autotest/SemRec_002/testcase/test_exc.py", line 69, in <module>
    pytest.main(['-sq','-vv','-v','--setup-show','--alluredir=../report/allure-results',__file__])
  File "D:\Program Files\Python36\lib\site-packages\_pytest\config\__init__.py", line 158, in main
    config=config
  File "D:\Program Files\Python36\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "D:\Program Files\Python36\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "D:\Program Files\Python36\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "D:\Program Files\Python36\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "D:\Program Files\Python36\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "D:\Program Files\Python36\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "D:\Program Files\Python36\lib\site-packages\_pytest\main.py", line 289, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "D:\Program Files\Python36\lib\site-packages\_pytest\main.py", line 284, in wrap_session
    config._ensure_unconfigure()
  File "D:\Program Files\Python36\lib\site-packages\_pytest\config\__init__.py", line 916, in _ensure_unconfigure
    self.hook.pytest_unconfigure(config=self)
  File "D:\Program Files\Python36\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "D:\Program Files\Python36\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "D:\Program Files\Python36\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "D:\Program Files\Python36\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "D:\Program Files\Python36\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "D:\Program Files\Python36\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "E:\tnbs\autotest\SemRec_002\conftest.py", line 27, in pytest_unconfigure
    if xdist.is_xdist_master(config):
  File "D:\Program Files\Python36\lib\site-packages\xdist\plugin.py", line 216, in is_xdist_master
    not is_xdist_worker(request_or_session)
  File "D:\Program Files\Python36\lib\site-packages\xdist\plugin.py", line 204, in is_xdist_worker
    return hasattr(request_or_session.config, "workerinput")
AttributeError: 'Config' object has no attribute 'config'
==========================================
is this caused by the version of pytest?
my lib version is :
pytest                 6.0.1
pytest-xdist          2.0.0
also could you tell me the 3rd lib of your code:  
1、tempdir.mktemp()
2、shutil.rmtree
i check on the internet is  "tempfile" and "shutil"  libs,is that correct?
i used like this:
import shutil 
from tempfile import tempdir
but it seems don't have the method mktemp

**Comment by nicoddemus** [comment] 2020-09-03 11:01
Hi @sinaparker,

My bad, indeed it was incorrect, `is_xdist_master` requires a session or request object, not a config. I've updated the example. I also fixed the reference to `tempfile.mkdtemp`.

(btw you might want to check how to [write posts in markdown](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax)).
