### ISSUE TITLE
`from mock import call` breaks test collector

### ISSUE THREAD

**Issue by renstrom** [pytest-dev/pytest#1044] opened 2015-09-21 19:15 UTC
To reproduce:

```bash
$ echo 'from mock import call' > test_foo.py
$ virtualenv env
$ ./env/bin/pip install pytest==2.8.0 mock==1.3.0
$ ./env/bin/py.test test_foo.py
========================== test session starts ==========================
platform darwin -- Python 2.6.6, pytest-2.8.0, py-1.4.30, pluggy-0.3.1
rootdir: /Users/Peter/src/github.com/edgeware, inifile:
collected 0 items / 1 errors

================================ ERRORS =================================
_____________________ ERROR collecting test_foo.py ______________________
env/lib/python2.6/site-packages/_pytest/runner.py:149: in __init__
    self.result = func()
env/lib/python2.6/site-packages/_pytest/main.py:437: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
env/lib/python2.6/site-packages/_pytest/main.py:317: in _memoizedcall
    res = function()
env/lib/python2.6/site-packages/_pytest/main.py:437: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
env/lib/python2.6/site-packages/_pytest/python.py:575: in collect
    return super(Module, self).collect()
env/lib/python2.6/site-packages/_pytest/python.py:435: in collect
    l.sort(key=lambda item: item.reportinfo()[:2])
env/lib/python2.6/site-packages/_pytest/python.py:435: in <lambda>
    l.sort(key=lambda item: item.reportinfo()[:2])
env/lib/python2.6/site-packages/_pytest/python.py:371: in reportinfo
    assert isinstance(lineno, int)
E   assert isinstance(compat_co_firstlineno, int)
======================== 1 error in 0.22 seconds ========================
```

**Comment by renstrom** [comment] 2015-09-21 19:16
Also, just importing `mock` and running `mock.call(...)` works. And importing as an alias doesn't work either `from mock import call as _call`.

**Comment by The-Compiler** [comment] 2015-09-21 20:45
Probably a duplicate of #1035

**Comment by RonnyPfannschmidt** [comment] 2015-09-22 10:37
closing as duplicate

**Closed by RonnyPfannschmidt** 2015-09-22 10:37 UTC

**Comment by sahilthapar** [comment] 2017-10-18 17:25
I'm having the same issue with 
Python 3.6.2
pytest==3.2.2
mock==2.0.0

**Comment by nicoddemus** [comment] 2017-10-18 21:58
@sahilthapar hmm this was expected to be fixed. Could you open a new issue with a minimal reproducible example that demonstrates the problem? Thanks!
