### ISSUE TITLE
Win+Py3.8: Casing of __file__ path elements changed via os.path.realpath

### ISSUE THREAD

**Issue by mbargull** [pytest-dev/pytest#6489] opened 2020-01-17 11:09 UTC
- [x] a detailed description of the bug or suggestion
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

This has been observed in https://github.com/conda-forge/schema-salad-feedstock/pull/22#issuecomment-558498158.

With Python 3.8 on Windows, `os.path.realpath` apparently changes casing of paths.
`_pytest.main` calls `realpath` on paths discovered with `--pyargs` at
https://github.com/pytest-dev/pytest/blob/5.3.2/src/_pytest/main.py#L659
which ultimately changes a module's `__file__` from being `normcase`d. If that `realpath` call is omitted (which is probably not desired?) or encapsulated in a `path.__class__(os.path.normcase( ... ))`, the returned value is the same as with Python 3.7.

The following is a full reproducer that shows the behavior of `os.real.path` and the different values for `__file__` when run via the standard import and `pytest --pyargs`.

```batch
(base) Y:\>conda create --quiet --yes --prefix=.\pytest-5__python-3.8 pytest=5 python=3.8
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: Y:\pytest-5__python-3.8

  added / updated specs:
    - pytest=5
    - python=3.8


The following NEW packages will be INSTALLED:

  atomicwrites       conda-forge/noarch::atomicwrites-1.3.0-py_0
  attrs              conda-forge/noarch::attrs-19.3.0-py_0
  ca-certificates    conda-forge/win-64::ca-certificates-2019.11.28-hecc5488_0
  certifi            conda-forge/win-64::certifi-2019.11.28-py38_0
  colorama           conda-forge/noarch::colorama-0.4.3-py_0
  importlib_metadata conda-forge/win-64::importlib_metadata-1.4.0-py38_0
  more-itertools     conda-forge/noarch::more-itertools-8.1.0-py_0
  openssl            conda-forge/win-64::openssl-1.1.1d-hfa6e2cd_0
  packaging          conda-forge/noarch::packaging-20.0-py_0
  pip                conda-forge/win-64::pip-19.3.1-py38_0
  pluggy             conda-forge/win-64::pluggy-0.13.1-py38_0
  py                 conda-forge/noarch::py-1.8.1-py_0
  pyparsing          conda-forge/noarch::pyparsing-2.4.6-py_0
  pytest             conda-forge/win-64::pytest-5.3.2-py38_0
  python             conda-forge/win-64::python-3.8.1-he1f5543_1
  setuptools         conda-forge/win-64::setuptools-45.0.0-py38_1
  six                conda-forge/win-64::six-1.14.0-py38_0
  sqlite             conda-forge/win-64::sqlite-3.30.1-hfa6e2cd_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_1
  wcwidth            conda-forge/noarch::wcwidth-0.1.8-py_0
  wheel              conda-forge/win-64::wheel-0.33.6-py38_0
  wincertstore       conda-forge/win-64::wincertstore-0.2-py38_1003
  zipp               conda-forge/noarch::zipp-1.0.0-py_0


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

(base) Y:\>conda activate .\pytest-5__python-3.8

(Y:\pytest-5__python-3.8) Y:\>conda info

     active environment : Y:\pytest-5__python-3.8
    active env location : Y:\pytest-5__python-3.8
            shell level : 2
       user config file : C:\Users\x\.condarc
 populated config files : Y:\conda\conda-forge\.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.8.0.final.0
       virtual packages :
       base environment : Y:\conda\conda-forge  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : Y:\conda\conda-forge\pkgs
                          C:\Users\x\.conda\pkgs
                          C:\Users\x\AppData\Local\conda\conda\pkgs
       envs directories : Y:\conda\conda-forge\envs
                          C:\Users\x\.conda\envs
                          C:\Users\x\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.8.0 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False


(Y:\pytest-5__python-3.8) Y:\>pip list
Package            Version
------------------ -------------------
atomicwrites       1.3.0
attrs              19.3.0
certifi            2019.11.28
colorama           0.4.3
importlib-metadata 1.4.0
more-itertools     8.1.0
packaging          20.0
pip                19.3.1
pluggy             0.13.1
py                 1.8.1
pyparsing          2.4.6
pytest             5.3.2
setuptools         45.0.0.post20200113
six                1.14.0
wcwidth            0.1.8
wheel              0.33.6
wincertstore       0.2
zipp               1.0.0

(Y:\pytest-5__python-3.8) Y:\>mkdir pytest-5__python-3.8\Lib\site-packages\dummy

(Y:\pytest-5__python-3.8) Y:\>echo assert False, __file__>pytest-5__python-3.8\Lib\site-packages\dummy\__init__.py

(Y:\pytest-5__python-3.8) Y:\>type NUL>pytest-5__python-3.8\Lib\site-packages\dummy\test_.py

(Y:\pytest-5__python-3.8) Y:\>python -c "import os.path; print(os.path.abspath(r'pytest-5__python-3.8\lib\site-packages\dummy'))"
Y:\pytest-5__python-3.8\lib\site-packages\dummy

(Y:\pytest-5__python-3.8) Y:\>python -c "import os.path; print(os.path.realpath(r'pytest-5__python-3.8\lib\site-packages\dummy'))"
Y:\pytest-5__python-3.8\Lib\site-packages\dummy

(Y:\pytest-5__python-3.8) Y:\>python -c "import dummy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "Y:\pytest-5__python-3.8\lib\site-packages\dummy\__init__.py", line 1, in <module>
    assert False, __file__
AssertionError: Y:\pytest-5__python-3.8\lib\site-packages\dummy\__init__.py

(Y:\pytest-5__python-3.8) Y:\>pytest --quiet --pyargs dummy

============================================================= ERRORS =============================================================
_____________________________ ERROR collecting pytest-5__python-3.8/Lib/site-packages/dummy/test_.py _____________________________
pytest-5__python-3.8\lib\site-packages\py\_path\local.py:701: in pyimport
    __import__(modname)
pytest-5__python-3.8\Lib\site-packages\dummy\__init__.py:1: in <module>
    assert False, __file__
E   AssertionError: Y:\pytest-5__python-3.8\Lib\site-packages\dummy\__init__.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
1 error in 0.12s

(Y:\pytest-5__python-3.8) Y:\>
```

**Comment by asottile** [comment] 2020-01-17 19:18
The capitalized `Lib` is the correct casing of that file (ntfs saves files in a case sensitive manner, but allows case insensitive comparison at the api layer).  The true casing of that file is with capitalized `Lib`.

pytest's python3.8 behaviour is also consistent with how python sets `__file__`:

```
$ ./venv/Scripts/python -c 'import datetime; print(datetime.__file__)'
c:\python37\Lib\datetime.py
```

**Comment by mbargull** [comment] 2020-01-17 22:56
> The capitalized `Lib` is the correct casing of that file

Yes, and I'm not arguing against that.

> pytest's python3.8 behaviour is also consistent with how python sets `__file__`:

Well, that's odd. I'm getting the opposite result:
```
(Y:\pytest-5__python-3.8) Y:\>python -c "import datetime; print(datetime.__file__)"
Y:\pytest-5__python-3.8\lib\datetime.py
```
and the output from above:
```
(Y:\pytest-5__python-3.8) Y:\>python -c "import dummy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "Y:\pytest-5__python-3.8\lib\site-packages\dummy\__init__.py", line 1, in <module>
    assert False, __file__
AssertionError: Y:\pytest-5__python-3.8\lib\site-packages\dummy\__init__.py
```

This is also what we get on the Azure CI in https://github.com/conda-forge/schema-salad-feedstock/pull/22#issuecomment-558498158.

----
Seeing `$ ./venv/Scripts/python` in your example indicates some Unix-y shell. Maybe you get a different result due to Cygwin/MSYS2 special handling? Can rerun it with a native shell?

**Comment by asottile** [comment] 2020-01-17 23:01
the `$` was just so github would highlight it properly, it was a cmd shell

is it possibly because you're using conda and not the standard distributions?

**Comment by mbargull** [comment] 2020-01-17 23:12
Clean install from https://www.python.org/ftp/python/3.8.1/python-3.8.1-amd64.exe:
```
Y:\py3.8>python -c "import datetime; print(datetime.__file__)"
Y:\py3.8\lib\datetime.py
```

**Comment by asottile** [comment] 2020-01-17 23:13
is `y:` some sort of network drive maybe?

**Comment by mbargull** [comment] 2020-01-17 23:16
No
```
C:\WINDOWS\system32>fsutil fsinfo volumeinfo Y:
Volume Name : conda
Volume Serial Number : 0x1a5adde4
Max Component Length : 255
File System Name : NTFS
Is ReadWrite
Not Thinly-Provisioned
Supports Case-sensitive filenames
Preserves Case of filenames
Supports Unicode in filenames
Preserves & Enforces ACL's
Supports file-based Compression
Supports Disk Quotas
Supports Sparse files
Supports Reparse Points
Returns Handle Close Result Information
Supports POSIX-style Unlink and Rename
Supports Object Identifiers
Supports Encrypted File System
Supports Named Streams
Supports Transactions
Supports Hard Links
Supports Extended Attributes
Supports Open By FileID
Supports USN Journal
```

**Comment by mbargull** [comment] 2020-01-17 23:17
I'm still not convinced you ran `cmd` given the single quotes and all..

**Comment by asottile** [comment] 2020-01-17 23:22
I doctored the command for the github formatting, I can get you a screenshot :)

![Screenshot from 2020-01-17 15-21-47](https://user-images.githubusercontent.com/1810591/72652801-1a954580-393d-11ea-87c6-59205cc0358e.png)

**Comment by mbargull** [comment] 2020-01-17 23:31
> I doctored

Ah, sneaky ;).

I wonder in which way our setups differ... I'll try somethings right quick

**Comment by asottile** [comment] 2020-01-17 23:34
> > I doctored
> 
> Ah, sneaky ;).

lol the best part is github didn't even highlight it properly so I did it for nothing :man_facepalming:

**Comment by mbargull** [comment] 2020-01-17 23:42
> github didn't even highlight it properly

Getting proper shell syntax highlighting is something I already gave up on a long time ago ;).

> I wonder in which way our setups differ... I'll try somethings right quick

Nope, no idea. I guessed it might've been something with the `venv`s or whatnot but I just always get lowercase `lib`. Strange.

**Comment by Zac-HD** [comment] 2022-09-27 05:30
Closing this as "probably something weird about the environment"; happy to reopen if we can work out how to reproduce it.

**Closed by Zac-HD** 2022-09-27 05:30 UTC
Labels: platform: windows
