### ISSUE TITLE
Issue deprecation warning when item parameter of pytest_warning_captured is used

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#4049] opened 2018-09-27 11:22 UTC
Follow up to #4036

**Comment by RonnyPfannschmidt** [comment] 2018-12-02 11:49
@nicoddemus pluggy cant support this - we have to deprecate the complete hook and give it a new name

**Comment by nicoddemus** [comment] 2018-12-03 11:44
You are right, not sure what I was thinking

**Comment by RonnyPfannschmidt** [comment] 2018-12-03 11:47
@nicoddemus i propose `pytest_warning_recorded(record)` as a starting point, perhaps also adding a `config` parameter

**Comment by gnikonorov** [comment] 2020-05-23 18:23
Hi, is there an update on this? I tried to use `pytest_warning_captured` as detailed [here](https://docs.pytest.org/en/latest/reference.html#_pytest.hookspec.pytest_warning_captured) and received the error in the attached log. When I tried to use `pytest_warning_recorded(record)` I received a `PluginValidationError` saying the hook name was invalid.

[pytest_warning_captured_usage.log](https://github.com/pytest-dev/pytest/files/4672300/pytest_warning_captured_usage.log)

**Comment by RonnyPfannschmidt** [comment] 2020-05-23 19:13
@gnikonorov as far as I can tell nothing happened

**Comment by gnikonorov** [comment] 2020-05-23 19:20
@RonnyPfannschmidt can I submit a PR for this then?

**Comment by RonnyPfannschmidt** [comment] 2020-05-23 20:16
yes please

**Comment by gnikonorov** [comment] 2020-05-23 20:44
Thank you! I'll try to have the PR up in the next few days

**Comment by gnikonorov** [comment] 2020-05-25 03:17
Hi @RonnyPfannschmidt, I've made a [PR for this](https://github.com/pytest-dev/pytest/pull/7255), but I am a little confused about how to understand the codecov reports. Since I deprecated a hook and replaced it with a new one, I believe I'm maintaining the same test coverage/functionality as before but codecov says I've hit  90.90%. Is it also looking at `hookspec.py` and `reference.rst`?

**Comment by bluetech** [comment] 2020-05-26 08:35
From the log you attached, the error seems to be something different than this issue:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/gnikonorov/.local/share/virtualenvs/pytest-html-k1-ITgOR/lib/python3.6/site-packages/pluggy/callers.py", line 171, in _multicall
INTERNALERROR>     args = [caller_kwargs[argname] for argname in hook_impl.argnames]
INTERNALERROR>   File "/home/gnikonorov/.local/share/virtualenvs/pytest-html-k1-ITgOR/lib/python3.6/site-packages/pluggy/callers.py", line 171, in <listcomp>
INTERNALERROR>     args = [caller_kwargs[argname] for argname in hook_impl.argnames]
INTERNALERROR> KeyError: 'location'
```

It's because one of the call sites of the hook are missing the `location` parameter. I pointed this out in the review of #7255. As also mentioned there, pytest-xdist seems to already have a workaround for this issue. If you fix the `location` problem in pytest, does it work for you?

**Comment by gnikonorov** [comment] 2020-05-26 23:27
Thanks @bluetech you are 100% right. I jumped the gun and assumed that resolving this would fix my issue too. Adding `location=None` resolves the problem. I still think we should add the new hook, but I will also fix this location bug in the new hook.

What do you think @RonnyPfannschmidt?

Relevant log/diff: [when_location_set_to_none.txt](https://github.com/pytest-dev/pytest/files/4685489/when_location_set_to_none.txt)

**Comment by bluetech** [comment] 2020-05-28 08:55
> I will also fix this location bug in the new hook and set it to its proper value ( I'm not sure if None is the correct one, just a test value ).

Can you also fix it in the existing hook (in a separate PR)? (If you prefer, I can do it myself)

**Comment by gnikonorov** [comment] 2020-05-28 12:09
Sure @bluetech, I'll investigate further and make a follow up issue/pr if we need to use a different value. I investigated for a while and `None` seemed fine which is why I used it for the PR associated with this issue.

**Comment by bluetech** [comment] 2020-05-28 12:32
> I investigated for a while and None seemed fine which is why I used it for the PR associated with this issue.

I haven't investigated too much either, but the `location` parameter was added in #5984 (which also introduced the regression) and seems generally useful for the purpose of testing the warning location. So if possible, it will be better to calculate it in the same way it is done in the other hook call site. I haven't checked if that would work.

**Comment by gnikonorov** [comment] 2020-05-28 12:38
I agree, @bluetech. I’ll create an issue for it when I get the time later today

**Comment by bluetech** [comment] 2020-05-31 19:56
The entire hook is deprecated now, replaced by a new hook `pytest_warning_recorded` (pr #7255).

**Closed by bluetech** 2020-05-31 19:56 UTC
Labels: type: deprecation
