### ISSUE TITLE
xfailed test that fails during finalizer is reported twice

### ISSUE THREAD

**Issue by christopherhw** [pytest-dev/pytest#5164] opened 2019-04-24 17:26 UTC
If a that is xfailed fails during a finalizer the test is reported twice. It's reported as skipped and an error. This also results in pytests exit code being 1 in an otherwise successful run.

If a test fails during a finalizer and it's xfailed it should probably only be reported as skipped.

I'm using pytest 3.3.2 on Ubuntu 18.04.1.

The following example should reproduce the problem:
```python
import pytest
  
@pytest.fixture
def will_fail(request):
    def fin():
        assert False, "Finalizer failed."
    request.addfinalizer(fin)

@pytest.mark.usefixtures('will_fail')
def test_example():
    pytest.xfail("This test is xfailed.")
```

**Comment by bluetech** [comment] 2024-02-17 18:10
Closing as duplicate of #9909

**Closed by bluetech** 2024-02-17 18:10 UTC
Labels: type: bug, topic: fixtures, topic: marks
