### ISSUE TITLE
tempdir not removed

### ISSUE THREAD

**Issue by metabyte144** [pytest-dev/pytest#8959] opened 2021-07-30 20:22 UTC
Docu:
https://docs.pytest.org/en/6.2.x/tmpdir.html section "The default base temporary directory" states that " Moreover, entries older than 3 temporary directories will be removed". 

Fact:
That's not the case. I've made a test case: 

```
import pytest
import random
import hashlib


def calcSHA1(filename):
    # calculate a sha1 from file
    BUF_SIZE = 65536
    sha1 = hashlib.sha1()
    try:
        with open(filename, 'rb') as f:
            while True:
                data = f.read(BUF_SIZE)
                if not data:
                    break
                sha1.update(data)
    except Exception:
        raise ValueError  # just using this for illustration
    return sha1.hexdigest()


@pytest.fixture(scope="session")
def test_file(tmpdir_factory):
    fname = tmpdir_factory.mktemp("data").join("testfile.bin")
    with open(fname, "wb") as new_file:
        random.seed(12345)   # fixed random sequence!
        file_len = random.randint(1000, 20000)
        rndbuf = random.randbytes(file_len)
        new_file.write(rndbuf)
    return fname


def test_sha1(test_file):
    print("TEST: test_sha1")
    sha1 = calcSHA1(test_file)
    print(f"test_file={test_file}")
    assert sha1 == 'b4b92d48a3d77a336b3cb12f87de7ecd601dd413', "sha1 is wrong"
```

That just calculates the SHA1 of a file. I wanted to know where it's stored (my full testset has around 100MB) and check if it's automatically deleted. 
 
============================= test session starts =============================
collecting ... collected 1 item

test-tempdir.py::test_sha1 PASSED                                        [100%]TEST: test_sha1
test_file=C:\Users\Gerald\AppData\Local\Temp\pytest-of-Gerald\pytest-9\data0\testfile.bin

============================== 1 passed in 0.02s ==============================

The screenshot below shows that after 8 runs nothing has been deleted.
![tempdir_dir](https://user-images.githubusercontent.com/78042651/127707529-4053a360-5bb9-4374-8ae5-a85372d2e59d.png)

Python: 3.9.1
Pytest: 6.2.4
OS: Windows 8.1

**Comment by symonk** [comment] 2021-07-30 23:09
@metabyte144 Thanks, I'm not sure the logic around this is bullet proof, can you do a quick check for me:

 - delete all the directories in `pytest-of-Gerald`, 
 - run it 4 times
 - Do you observe the same behaviour?

**Comment by metabyte144** [comment] 2021-07-31 09:04
oookay.. so yesterday I let the script run and it just has been piling up the directories. Today I did the same and it deletes the oldest directories as I would expect it to do. I also tried to mix it with the run of the original test case (the above one is a simplification) but it still cleans the old directories. Very weird. Yesterday it was completely reproducable and has never deleted any directory. 

Th lock code looks actually fine to me. Can't tell if it really is but from a review point I don't spot anything bad.

Sorry - there is something wrong but I cannot reproduce it either now..
Thanks for your support :)

**Comment by symonk** [comment] 2021-07-31 09:14
That is perfectly ok @metabyte144 - thanks for responding, I am going to leave this open as I am still puzzled as to how I had 300 directories myself, windows can be quick fickle in teams of pytest deleting files/folders, I will have a closer look at some stage in the future.

**Comment by Zac-HD** [comment] 2021-11-29 00:17
Closing this because the issue seems to be resolved - but please open a new one if you can reproduce it!

**Closed by Zac-HD** 2021-11-29 00:17 UTC
Labels: status: needs information, plugin: tmpdir
