### ISSUE TITLE
pytest 8.0.0 now collects all files in current directory even if you specify test files

### ISSUE THREAD

**Issue by sshane** [pytest-dev/pytest#11974] opened 2024-02-14 00:25 UTC
After https://github.com/pytest-dev/pytest/commit/385796ba494e7ae65d55892d4a358b371ac7a6b6, pytest sends all files in the current directory to every plugin's `pytest_collect_file` hook, even if you are only wanting to run/collect tests from one file. If you have pytest-cpp installed, it means it executes all executable files in the current directory, which isn't desired behavior at all, or at least unexpected.

```
safety/
  test_toyota.py
  test_coverage.sh  # shouldn't be run
```

`pytest test_toyota.py` -> runs test_coverage.sh (which in my case is long running and runs another pytest causing a recursive loop)

Now, this isn't because of pytest per se, but the pytest-cpp plugin which [runs all executable files with `--help`](https://github.com/pytest-dev/pytest-cpp/blob/d25bc69396720aaabb1e6688be68eaaa2bb0f006/src/pytest_cpp/google.py#L28) to discover if it's a certain test suite file. If this new behavior of collecting every file, despite specifying your file filter is intentional, we can close this.

---

A worse case is just:

```
safety/
  test_toyota.py
  test.sh
```

where test.sh has a pytest command inside it with some extra setup:

```
pytest -n auto test_*.py -k 'not Base'
```

currently, it will recursively run itself with `pytest-cpp` installed.

**Comment by bluetech** [comment] 2024-02-14 12:08
This is something I am planning to fix for the 8.1.x timeframe. Closing as duplicate of #11904.

**Closed by bluetech** 2024-02-14 12:08 UTC
