### ISSUE TITLE
Getting TypeError when using --doctest-modules

### ISSUE THREAD

**Issue by immerrr** [pytest-dev/pytest#1148] opened 2015-10-21 07:27 UTC
Got this error while working on jedi. To reproduce it:
- create a virtualenv with python 2.7 (not sure about other versions)
- check out and `pip install -e .` davidhalter/jedi@9b69f3a20f324dc8ea6fdc02e32dad5c009b5670 
- check out and `pip install -e .` pytest master branch.
- run `py.test` in the root of jedi checkout.

It fails with the traceback you can find [here](https://gist.github.com/immerrr/bcdac1667395b0e6527e#file-traceback-txt). I was able to fix the error with a hack you can find [here](https://gist.github.com/immerrr/bcdac1667395b0e6527e#file-doctest-patch), but I doubt it is the proper solution. After the hackaround I was able to see that the error was about a missing fixture
```
file /home/immerrr/sources/pytest/_pytest/doctest.py, line 195
      def func():
        fixture 'clean_jedi_cache' not found
        available fixtures: tmpdir_factory, pytestconfig, cache, recwarn, monkeypatch, record_xml_property, capfd, capsys, tmpdir
        use 'py.test --fixtures [testpath]' for help on them.

/home/immerrr/sources/pytest/_pytest/doctest.py:195
```

So in the end I fixed the process by adding `testpaths = test` to `jedi/pytest.ini`.

**Comment by immerrr** [comment] 2015-10-21 07:35
Note: the original issue was about `AttributeError` instead of `TypeError` because pytest=2.8.2 failed with a different error and in the middle of posting the report I double-checked it using master.

**Comment by immerrr** [comment] 2015-10-21 09:57
FTR: a mixture was missing indeed: it was defined in `test/conftest.py` and doctest plugin couldn't find it when traversing `jedi/` subdirectory.

**Comment by RonnyPfannschmidt** [comment] 2015-10-21 10:17
indeed, fixtures from the test folder do not apply to the jedi folder unless you turn them into a local plugin

**Comment by nicoddemus** [comment] 2015-10-22 02:06
Thanks for the report and diagnosis!

**Comment by RonnyPfannschmidt** [comment] 2015-10-30 08:41
closing as not a bug

**Comment by immerrr** [comment] 2015-10-30 09:37
@RonnyPfannschmidt I think it is a bug. Even though the fixture was missing, doctest plugin misbehaved and raised an internal error while trying to report a user error.

**Closed** 2015-10-30 10:22 UTC
Labels: bug, collection

**Comment by nicoddemus** [comment] 2015-10-30 11:31
@immerrr Ronny created a separate issue for it: #1160

**Comment by immerrr** [comment] 2015-10-30 11:42
@nicoddemus thank you, I've seen it
