### ISSUE TITLE
pytester inline runs pollute global test namespace and create collisions

### ISSUE THREAD

**Issue by DRMacIver** [pytest-dev/pytest#1028] opened 2015-09-20 21:55 UTC
This is an error I encountered when trying to make the Hypothesis build work on 2.8.0. It's easy to work around but I thought you might want to know.

If I put the following code in a file named test_mark.py then I get an error on trying to run it. If I rename the file (e.g. to test_mark2.py), it passes:

``` python
pytest_plugins = str('pytester')


TESTSUITE = """
def test_bar():
    pass
"""


def test_mark(testdir):
    script = testdir.makepyfile(TESTSUITE)
    result = testdir.runpytest(script)
    out = '\n'.join(result.stdout.lines)
    assert '1 passed' in out
```

The error I get is:

```
========================================== test session starts ===========================================
platform linux -- Python 3.4.3, pytest-2.8.0, py-1.4.30, pluggy-0.3.1
rootdir: /home/david/crap, inifile: 
plugins: xdist-1.13.1
collected 1 items 

test_mark.py F

================================================ FAILURES ================================================
_______________________________________________ test_mark ________________________________________________

testdir = <Testdir local('/tmp/pytest-of-david/pytest-22/testdir/test_mark0')>

    def test_mark(testdir):
        script = testdir.makepyfile(TESTSUITE)
        result = testdir.runpytest(script)
        out = '\n'.join(result.stdout.lines)
>       assert '1 passed' in out
E       assert '1 passed' in '============================= test session starts ==============================\nplatform linux -- Python 3.4.3, pyt...asename for your test file modules\n=========================== 1 error in 0.00 seconds ============================\n'

/home/david/crap/test_mark.py:14: AssertionError
------------------------------------------ Captured stdout call ------------------------------------------
============================= test session starts ==============================
platform linux -- Python 3.4.3, pytest-2.8.0, py-1.4.30, pluggy-0.3.1
rootdir: /tmp/pytest-of-david/pytest-22/testdir/test_mark0, inifile: 
plugins: xdist-1.13.1
collected 0 items / 1 errors

==================================== ERRORS ====================================
________________________ ERROR collecting test_mark.py _________________________
import file mismatch:
imported module 'test_mark' has this __file__ attribute:
  /home/david/crap/test_mark.py
which is not the same as the test file we want to collect:
  /tmp/pytest-of-david/pytest-22/testdir/test_mark0/test_mark.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
=========================== 1 error in 0.00 seconds ============================
======================================== 1 failed in 0.03 seconds ========================================
```

Note: I have tried deleting the __pycache__ directory, as well as tried this in an entirely fresh directory.

I originally thought this might be whenever I had the same name as one of pytest's tests that themselves used this functionality, but that doesn't seem to be the case. I haven't found any other names that produce this behaviour.

**Comment by nicoddemus** [comment] 2015-09-20 23:45
Hi @DRMacIver,

I guess the problem is that your file is named `test_mark.py`, which is importable because it is in the current directory: `testdir` will use the name of the test function to generate a python file to run your code in a temporary directory (`/tmp/pytest-of-david/pytest-22/testdir/test_mark0`), but here you also used `test_mark` for the function name so it generates the file `/tmp/pytest-of-david/pytest-22/testdir/test_mark0/test_mark.py`, which confuses the pycache import system. 

A quick workaround would be to rename the `test_mark` function to something else, or pass the argument to `makepyfile` as a keyword argument, which makes `testdir` use the keyword as the file name in the temporary directory:

```python
def test_mark(testdir):
    testdir.makepyfile(test_mark2=TESTSUITE)
    result = testdir.runpytest()
    result.stdout.fnmatch_lines(['*1 passed*']) 
```

This problem only happens in `2.8.0`, but works fine in `2.7.+`. The reason seems to be the new `--runpytest=` option, which now defaults to `inprocess` rather than `subprocess` as the former is significantly faster. 

So other workarounds could be to run pytest passing the `inprocess` option:

```
py.test test_mark.py -p pytester --runpytest=subprocess
```

Or add to your `pytest.ini` file:

```ini
[pytest]
addopts = -p pytester --runpytest=subprocess
```

**Comment by DRMacIver** [comment] 2015-09-21 08:11
Oh yes, of course. It didn't occur to me that it could just be the name of the function.

I was planning to work around it by just renaming the file, but I might rename the function instead. Thanks.

**Comment by nicoddemus** [comment] 2015-09-21 21:54
If you don't have more questions, would you mind closing this then? :smile:

**Comment by DRMacIver** [comment] 2015-09-22 07:26
Why? It seems pretty clearly a bug even if it's an easy to work around one.

**Comment by RonnyPfannschmidt** [comment] 2015-09-22 10:26
we should error out with a more helpful message or ensure pytester no longer pollutes

**Comment by Zac-HD** [comment] 2023-11-28 06:39
Retested on pytest-7.3.1, and it passes now 🙂

**Closed by Zac-HD** 2023-11-28 06:39 UTC
Labels: type: bug, plugin: pytester
