### ISSUE TITLE
Regression: UnicodeEncodeError with non-ascii characters in parametrized tests

### ISSUE THREAD

**Issue by sloria** [pytest-dev/pytest#1086] opened 2015-09-29 15:16 UTC
On pytest 2.8.1 on Python 2.7.10, a `UnicodeEncodeError` is raised .

Code to reproduce:

```python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import pytest

@pytest.mark.parametrize('s',
[
    'josé@blah.com',
    'δοκ.ιμή@παράδειγμα.δοκιμή',
])
def test_non_ascii(s):
    assert bool(s)
```

This did not occur with pytest 2.8.0

**Comment by nicoddemus** [comment] 2015-09-29 16:22
Thanks for the report! I will take a look as soon as possible.

**Comment by nicoddemus** [comment] 2015-09-29 16:23
Hmm closing as duplicate of #1085, both reported nearly at the same time. :smile:

**Closed by nicoddemus** 2015-09-29 16:23 UTC
Labels: bug

**Comment by nicoddemus** [comment] 2015-09-30 01:47
PR open at #1092
