### ISSUE TITLE
Test entire directory donsen't work like doc said

### ISSUE THREAD

**Issue by buxx** [pytest-dev/pytest#2048] opened 2016-11-09 10:50 UTC
Documentation say:

> pytest somepath      # run all tests below somepath

But for this structure:

    .
    ├── README.md
    └── tests
        ├── __init__.py
        ├── __pycache__
        │   ├── __init__.cpython-35.pyc
        │   └── test.cpython-35-PYTEST.pyc
        └── test.py

and:

    cat tests/test.py 
    def test_machin():
        assert 'foo' == 'bar'

Why i can't test it with following command ?

    pytest ./tests
    ======================= test session starts =======================
    platform linux -- Python 3.5.2, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
    rootdir: /home/bux/Projets/synergine2, inifile: 
    collected 0 items 
    
    ================== no tests ran in 0.00 seconds ===================

Note the following command is working:

```
pytest ./tests/*
======================= test session starts =======================
platform linux -- Python 3.5.2, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /home/bux/Projets/synergine2, inifile: 
collected 1 items 

tests/test.py F

============================ FAILURES =============================
___________________________ test_machin ___________________________

    def test_machin():
>       assert 'foo' == 'bar'
E       assert 'foo' == 'bar'
E         - foo
E         + bar

tests/test.py:2: AssertionError
==================== 1 failed in 0.05 seconds =====================
```

**Comment by RonnyPfannschmidt** [comment] 2016-11-09 10:55
`test.py` does not matc hthe pattern of `test_*.py` please name your test files accordingly

**Comment by RonnyPfannschmidt** [comment] 2016-11-09 10:55
btw, the reason the tests run with the shell glob is, if py.test is passed actual files, it wont filter based on the filename match

**Comment by nicoddemus** [comment] 2016-11-09 11:16
Yep, working as intended so I'm closing this for now. @buxx feel free to reopen if you have further questions.

**Closed by nicoddemus** 2016-11-09 11:16 UTC
Labels: question

**Comment by buxx** [comment] 2016-11-09 12:03
Thank's for replies !
