### ISSUE TITLE
Why is addfinalizer broken in this case ?

### ISSUE THREAD

**Issue by viralmutant** [pytest-dev/pytest#6644] opened 2020-01-31 17:27 UTC
This is more of a question than a bug

I am using pytest 4.0.0 and observing strange behavior with `addfinalizer` in this code. This is pretty much a small example of the entire framework(complex) which is implemented

```
class Command():
  '''
    There are multiple such classes
  '''
  def __init__(self, parent, cmd):
    self.parent = parent
    self.cmd = cmd

  def __getattr__(self, attr):
    self.attr = attr
    return self.general

  def general(self, *args):
    cmd_string = self.cmd + " " + self.attr
    for arg in args:
      if arg is not None:
        cmd_string += " {}".format(arg)
    resp = self.parent.execute(cmd_string)
    return resp

class Dynamic():
  def __getattr__(self, cmd):
    self.__setattr__(cmd, Command(self, cmd))
    return self.__getattribute__(cmd)

  def execute(self, cmd):
    print(cmd)

class Fixit():
  def setup_class(cls):
    cls.dynamic = Dynamic()

  @pytest.fixture
  def fix_one(self, request):
    def _inner():
      print("Fix one")
    request.addfinalizer(self.dynamic.help.one)
    return _inner

  @pytest.fixture
  def fix_two(self, request):
    def _inner():
      print("Fix two")
    request.addfinalizer(self.dynamic.help.two)
    return _inner

class Test(Fixit):
  def test_broken(self, fix_one, fix_two):
    print("This is broken")
    fix_one()
    fix_two()
```

This is what the test produces
```
# pytest -s -k test_broken
This is broken
Fix one
Fix two
.
help two
help two
```
**As it is evident, the `teardown` of `fix_two` is called twice. Why is that the case ?**

**Comment by nicoddemus** [comment] 2020-01-31 23:17
Hi @viralmutant,

The finalizers are being called correctly, the problem is in the code:

```python
>>> d = Dynamic()
>>> f1 = d.help.one
>>> f2 = d.help.two
>>> f1()
help two
>>> f2()
help two
```

The problem is here:

```python
    def __getattr__(self, attr):
        self.attr = attr
        return self.general
``` 

When `f1 = d.help.one` is executed, `self.attr` is set to `"one"`, and `self.general` is returned.

`general()` uses `self.attr` to build its `cmd` string:

```python
    def general(self, *args):
        cmd_string = self.cmd + " " + self.attr
```

So when time `f2 = d.help.two` is executed, `self.attr` is set to `"two"`.

Naturally, when they are all called, `general` will use `self.attr`, which is `"two"`.

The fix is to make each `__getattr__` return a new method with `attr` bound to it, instead of storing it in `self`:

```python
    def __getattr__(self, attr):
        return partial(self.general, attr=attr)

    def general(self, *args, attr):
        cmd_string = self.cmd + " " + attr
        for arg in args:
            if arg is not None:
                cmd_string += " {}".format(arg)
        resp = self.parent.execute(cmd_string)
        return resp
```

This produces the correct result:

```
collected 1 item

test_fix.py This is broken
Fix one
Fix two
.help two
help one
```

Hope this helps. Closing this for now, but feel free to follow up with further questions. 👍

**Closed by nicoddemus** 2020-01-31 23:17 UTC

**Comment by viralmutant** [comment] 2020-02-01 15:03
Thank you for the analysis :)
This issue is not seen if I instead use yield
```
@pytest.fixture
def fix_one(self, request):
    def _inner():
        print("Fix one")
        #request.addfinalizer(self.dynamic.help.one)
    yield _inner
    self.dynamic.help.one()
```
What confused me is that documentation says:
> Both yield and addfinalizer methods work similarly by calling their code after the test ends

so I was expecting them to give same output

**Comment by nicoddemus** [comment] 2020-02-01 16:35
> so I was expecting them to give same output

They usually have the same result, but when you use `yield`, the evaluation order changes because you will call `self.dynamic.help.one()` self.dynamic.help.two()` immediately after the yield, instead of delaying it for later.
