### ISSUE TITLE
Contribution guide indicates use of Python 3.7 but linting fails on Python < 3.8

### ISSUE THREAD

**Issue by DrGFreeman** [pytest-dev/pytest#8829] opened 2021-06-30 04:09 UTC
The [Contribution getting started](https://docs.pytest.org/en/stable/contributing.html#preparing-pull-requests) docs, under *Preparing Pull Requests / Long version / 5. Run all the tests* indicate *You need to have Python 3.7 available in your system* however the linting checks fail on Python3.7.

The same steps pass when using Python 3.8 or 3.9.

The guide should be updated to indicate Python 3.8 or higher.

#### Steps to reproduce

1. Create and activate a virtual environment using Python 3.7
    ```
    $ python3.7 -m venv .venv
    $ source .venv/bin/activate
    ```
1. Follow instructions in contributing guide
    ```
    $ pip install pre-commit tox
    $ pre-commit install
    ```
1. Run linting checks
    ```
    $ tox -e linting
    ```

#### Expected behavior
Linting checks pass

#### Actual Behavior
mypy checks fail:

```
tox -e linting
linting recreate: /home/jul/git/pytest/.tox/linting
linting installdeps: pre-commit>=2.9.3
linting installed: appdirs==1.4.4,cfgv==3.3.0,distlib==0.3.2,filelock==3.0.12,identify==2.2.10,importlib-metadata==4.6.0,nodeenv==1.6.0,pre-commit==2.13.0,PyYAML==5.4.1,six==1.16.0,toml==0.10.2,typing-extensions==3.10.0.0,virtualenv==20.4.7,zipp==3.4.1
linting run-test-pre: PYTHONHASHSEED='2690685351'
linting run-test: commands[0] | pre-commit run --all-files --show-diff-on-failure
black....................................................................Passed
blacken-docs.............................................................Passed
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Fix python encoding pragma...............................................Passed
Check Yaml...............................................................Passed
Debug Statements (Python)................................................Passed
flake8...................................................................Passed
Reorder python imports...................................................Passed
pyupgrade................................................................Passed
setup-cfg-fmt............................................................Passed
type annotations not comments............................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

testing/example_scripts/unittest/test_unittest_asyncio.py:2: error: Module "unittest" has no attribute "IsolatedAsyncioTestCase"  [attr-defined]
testing/test_entry_points.py:1: error: Module "_pytest.compat" does not explicitly export attribute "importlib_metadata"; implicit reexport disabled  [attr-defined]
src/_pytest/config/__init__.py:49: error: Module "_pytest.compat" does not explicitly export attribute "importlib_metadata"; implicit reexport disabled  [attr-defined]
testing/test_config.py:17: error: Module "_pytest.compat" does not explicitly export attribute "importlib_metadata"; implicit reexport disabled  [attr-defined]
testing/acceptance_test.py:9: error: Module "_pytest.compat" does not explicitly export attribute "importlib_metadata"; implicit reexport disabled  [attr-defined]
src/_pytest/unraisableexception.py:37: error: Name "sys.UnraisableHookArgs" is not defined  [name-defined]
src/_pytest/unraisableexception.py:38: error: Name "sys.UnraisableHookArgs" is not defined  [name-defined]
src/_pytest/unraisableexception.py:40: error: Name "sys.UnraisableHookArgs" is not defined  [name-defined]
src/_pytest/unraisableexception.py:46: error: Module has no attribute "unraisablehook"  [attr-defined]
src/_pytest/unraisableexception.py:47: error: Module has no attribute "unraisablehook"  [attr-defined]
src/_pytest/unraisableexception.py:57: error: Module has no attribute "unraisablehook"  [attr-defined]
src/_pytest/threadexception.py:37: error: Name "threading.ExceptHookArgs" is not defined  [name-defined]
src/_pytest/threadexception.py:38: error: Name "threading.ExceptHookArgs" is not defined  [name-defined]
src/_pytest/threadexception.py:40: error: Name "threading.ExceptHookArgs" is not defined  [name-defined]
src/_pytest/threadexception.py:44: error: Module has no attribute "excepthook"  [attr-defined]
src/_pytest/threadexception.py:45: error: Module has no attribute "excepthook"  [attr-defined]
src/_pytest/threadexception.py:55: error: Module has no attribute "excepthook"  [attr-defined]
Found 17 errors in 7 files (checked 201 source files)

rst......................................................................Passed
changelog filenames..................................(no files to check)Skipped
py library is deprecated.................................................Passed
py.path usage is deprecated..............................................Passed
ERROR: InvocationError for command /home/jul/git/pytest/.tox/linting/bin/pre-commit run --all-files --show-diff-on-failure (exited with code 1)
______________________________________________________________ summary ______________________________________________________________
ERROR:   linting: commands failed
```

- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
```
Package            Version
------------------ --------
appdirs            1.4.4
cfgv               3.3.0
distlib            0.3.2
filelock           3.0.12
identify           2.2.10
importlib-metadata 4.6.0
nodeenv            1.6.0
packaging          20.9
pip                21.1.3
pluggy             0.13.1
pre-commit         2.13.0
py                 1.10.0
pyparsing          2.4.7
PyYAML             5.4.1
setuptools         47.1.0
six                1.16.0
toml               0.10.2
tox                3.23.1
typing-extensions  3.10.0.0
virtualenv         20.4.7
zipp               3.4.1
```
- [x] pytest and operating system versions
pytest: main branch - 1d6755340348a8ca538313309609e8fb7036b224
OS: Ubuntu 18.04.5 LTS
- [x] minimal example if possible

**Comment by The-Compiler** [comment] 2021-06-30 06:43
I believe we should tell mypy to always target the lowest Python version we support:

```diff
diff --git a/setup.cfg b/setup.cfg
index 0e86f10e7..ee8b95eaa 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -103,3 +103,4 @@ warn_return_any = True
 warn_unreachable = True
 warn_unused_configs = True
 no_implicit_reexport = True
+python_version = 3.6

```

which means those errors will show up no matter which Python version mypy is invoked with. Then, we should rewrite our checks (or perhaps add `# type: ignore`) comments to fix any errors.

That way, mypy would also tell us if we accidentally start using typing features which aren't actually available with Python 3.6.

**Comment by Zac-HD** [comment] 2021-07-04 09:44
This is a little fiddly because `mypy` also searches for installed type annotations (or type-annotated packages), so for best results we'd want to have a Python environment with all the dependencies set up at whichever `python_version` that specifies.

I could see some value in running `mypy --python-version=3.{6,7,8,9} ...` in CI however; if nothing else it would show us what kind of warnings contributors are likely to run into.  The downside is that pinning all the versions would be a pain - that's why I haven't done this for Hypothesis.

**Comment by The-Compiler** [comment] 2021-07-04 10:00
@Zac-HD I don't follow. Type annotations for third-party packages typically won't change based on Python versions, no? And if they would, surely mypy can tell statically and will follow those conditionals based on `python_version`?

**Comment by Zac-HD** [comment] 2021-07-04 10:10
[See the `--python-version` docs](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-python-version):

> This flag will attempt to find a Python executable of the corresponding version to search for PEP 561 compliant packages. If you’d like to disable this, use the `--no-site-packages` flag (see Import discovery for more details).

And setting it up so that the Python environment of each version is sufficiently pinned and reproducible to keep long-term bisecting useful would be pretty tricky.

-------------

To make this explicit, I'd run with *no* `python_version` config, but consider adding a CI job to run `mypy` on each supported version of Python.

**Comment by Zac-HD** [comment] 2023-06-18 19:11
Closing this as not worth fixing before Python 3.7 reaches end of life next week: https://devguide.python.org/versions/

**Closed by Zac-HD** 2023-06-18 19:11 UTC
Labels: type: docs, type: infrastructure
