### ISSUE TITLE
Getting started document is showing identical object reference for 2 tests for "pytest -k TestClassDemoInstance -q" command

### ISSUE THREAD

**Issue by amittendulkar** [pytest-dev/pytest#8398] opened 2021-03-04 11:27 UTC
While referring to the below getting started document at the website,

https://docs.pytest.org/en/stable/getting-started.html

I got confused with the output of the `pytest -k TestClassDemoInstance -q` command in the website. The description mentions that each test will get unique instance of the class. However the output of the above command is showing the same instance of the class for the two tests which is confusing,

Pasting the output from the website for quick reference,

```
$ pytest -k TestClassDemoInstance -q
FF                                                                   [100%]
================================= FAILURES =================================
______________________ TestClassDemoInstance.test_one ______________________

self = <test_class_demo.TestClassDemoInstance object at 0xdeadbeef>

    def test_one(self):
>       assert 0
E       assert 0

test_class_demo.py:3: AssertionError
______________________ TestClassDemoInstance.test_two ______________________

self = <test_class_demo.TestClassDemoInstance object at 0xdeadbeef>

    def test_two(self):
>       assert 0
E       assert 0

test_class_demo.py:6: AssertionError
========================= short test summary info ==========================
FAILED test_class_demo.py::TestClassDemoInstance::test_one - assert 0
FAILED test_class_demo.py::TestClassDemoInstance::test_two - assert 0
2 failed in 0.12s
```

Notice the `0xdeadbeef` address for both tests which are showing identical object references. Am I missing something?

**Comment by RonnyPfannschmidt** [comment] 2021-03-04 11:51
That's part of keeping the docs stable, unfortunately we are not yet using unique items for unique addresses

**Comment by The-Compiler** [comment] 2021-03-04 11:54
Duplicate of #7646

**Closed by The-Compiler** 2021-03-04 11:54 UTC
