### ISSUE TITLE
log_format in pytest.ini has no effect

### ISSUE THREAD

**Issue by dickreuter** [pytest-dev/pytest#4474] opened 2018-11-28 14:32 UTC
When I use log_format in pytest.ini it has no effect on the output

[pytest]
log_level = DEBUG
log_print=True
log_format = %(asctime)s %(message)s

The output contains no timestamp,

**Comment by j19sch** [comment] 2019-01-06 14:35
@dickreuter Does the output contain any logging? Because when I use the pytest.ini you provide, I see no logging records in the out at all. When I change `log_print=True` to `log_cli=True` I do get logging records in the output:
```
================================================ test session starts =================================================
platform linux -- Python 3.6.7, pytest-4.0.2, py-1.7.0, pluggy-0.8.0 -- /home/jss/workspace/tmp/venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/jss/workspace/tmp, inifile: pytest.ini
collected 1 item                                                                                                     

test_logging.py::test_my_test 
--------------------------------------------------- live log call ----------------------------------------------------
15:34:12 logging something yay
PASSED                                                                                                         [100%]

============================================== 1 passed in 0.00 seconds ==============================================
```

**Comment by nicoddemus** [comment] 2019-01-10 22:11
Using your `pytest.ini` file, I get the asctime just fine:

```

    def test():
        logging.debug('hello')
>       assert 0
E       assert 0

.tmp\log\test_foo.py:6: AssertionError
---------------------------------------- Captured log call ----------------------------------------
20:10:59 hello
```

@dickreuter could you please provide a reproducible example?

**Comment by nicoddemus** [comment] 2019-01-10 22:12
@j19sch the log is only shown if the test fails, similar to captured stdout/stderr.

**Comment by nicoddemus** [comment] 2019-05-01 14:22
Closing for now.

**Closed by nicoddemus** 2019-05-01 14:22 UTC
Labels: plugin: logging, status: needs information
