### ISSUE TITLE
#8516 fix causes other issues elsewhere

### ISSUE THREAD

**Issue by cjw296** [pytest-dev/pytest#10757] opened 2023-02-22 13:18 UTC
[8516](https://github.com/pytest-dev/pytest/pull/8516) includes a hard coded `~0o077`:

https://github.com/pytest-dev/pytest/pull/8516/files#diff-10ee70cc91700b16983baadc71b08d4239920ea83c1041a06adbb4302ae80c5bR145

This is also arguably wrong in that it re-permissions a directory potentially not even created by the current text (think pytest-xdist, etc) and breaks some existing use cases for these fixtures...

In our case, we have tests that ssh to localhost as a different user to the one running the tests and then work inside a directory created inside the one created by the `tmp_path` fixtures. Since this change, those tests are broken and we can no longer use the `tmp_path` fixture as a result.

Please could this specific change be reverted or, alternatively, something added so that we can turn this off?

**Comment by RonnyPfannschmidt** [comment] 2023-02-22 13:56
closing as duplicate of #10738

@BeyondEvil started working on a fix

**Closed** 2023-02-22 13:57 UTC
