### ISSUE TITLE
Better trace reporting for chained exceptions

### ISSUE THREAD

**Issue by moorecm** [pytest-dev/pytest#1122] opened 2015-10-07 21:04 UTC
Consider a test that raises an exception, after catching some other exception, and chaining them:

def test_that_raises():
    try:
        raise Exception('I want to know the type of exception and this message somewhere")
    except Exception as ex:
        raise Exception('A new custom exception that is more general') from ex

The test report shows the second Exception instance and its information but does not include the chained exception and its information.  This is important for debugging and Python 3.4 appears to show a nice trace of both if left uncaught (outside of pytest).

**Comment by The-Compiler** [comment] 2015-10-07 21:07
This seems to be a duplicate of #138.

**Closed by The-Compiler** 2015-10-07 21:07 UTC

**Comment by moorecm** [comment] 2015-10-07 21:14
Agreed.  Thanks!
