### ISSUE TITLE
Setting --pdbclass should not enable --pdb

### ISSUE THREAD

**Issue by sloria** [pytest-dev/pytest#2365] opened 2017-04-13 14:37 UTC
Currently when you pass the `--pdbcls` option, the `--pdb` behavior is automatically enabled. This is not intuitive. I want to be able to set `--pdbcls=IPython.core.debugger:Pdb` in my `setup.cfg` without always using the debugger when I run tests.

The problem appears to lie [here](https://github.com/pytest-dev/pytest/blob/7dfdfa58133926b3acfb17ca9298d7669784a6d8/_pytest/debugging.py#L23):

```python
    if config.getvalue("usepdb") or config.getvalue("usepdb_cls"):
        config.pluginmanager.register(PdbInvoke(), 'pdbinvoke')
         #...
```

Debugger behavior is enabled even if `--pdb` is not necessarily passed.

Would the maintainers be open to changing this?

**Comment by chrisseto** [comment] 2017-04-13 14:40
In the mean time, you can work around this by adding the following to `conftest.py`

```python
def pytest_configure(config):
    if config.option.usepdb:
        config.option.usepdb_cls = 'IPython.core.debugger:Pdb'  # Or your favorite pdb variant
```

**Comment by RonnyPfannschmidt** [comment] 2017-04-13 15:06
this one is a nice first contribution

**Comment by nicoddemus** [comment] 2017-04-13 15:36
Duplicate of #1948 and fixed in #1952.

This will be available in `3.1.0` which should be released soon.

**Closed by nicoddemus** 2017-04-13 15:36 UTC
Labels: bug, easy, help wanted

**Comment by RonnyPfannschmidt** [comment] 2017-04-13 15:48
@nicoddemus @hpk42 i think this is a perfect example of why we need way more and way more often done feature releases

**Comment by nicoddemus** [comment] 2017-04-13 15:58
Yeah I agree 👍
