### ISSUE TITLE
transfer_markers missing from pytest_asyncio

### ISSUE THREAD

**Issue by IgorJakovljevic** [pytest-dev/pytest#4612] opened 2019-01-07 09:18 UTC
From the version 4.1.0 we are getting errors in our test cases that the transfer markers are no longer part of the pytest_asyncio.

The only solution provided for this is to revert back to the previous version:
https://stackoverflow.com/questions/54064971/importerror-cannot-import-name-transfer-markers-when-testing-with-pytest

We are experiencing this issue in the bitbucket pipelines running a Linux system. Also, locally in the WSL environment. Python version is 3.6  

```
import pytest
@pytest.mark.asyncio()
async def test_asyncio():
    x = 1
    assert x == 1
```

The error that we get is the following:
```
from _pytest.python import transfer_markers
ImportError: cannot import name 'transfer_markers'
```

**Comment by blueyed** [comment] 2019-01-07 11:06
@RonnyPfannschmidt closed a similar issue somewhere already, but I could not find it now.

**Comment by blueyed** [comment] 2019-01-07 11:41
Duplicate of https://github.com/pytest-dev/pytest-asyncio/issues/104.

**Closed by blueyed** 2019-01-07 11:41 UTC
