### ISSUE TITLE
pytest leaks logging output

### ISSUE THREAD

**Issue by xoviat** [pytest-dev/pytest#3026] opened 2017-12-13 19:14 UTC
Over at pyinstaller, we finally got parallel testing to work on windows after the new release came out. However, there are still problems with the logging plugin (which at least works most of the time now rather than throwing an INTERNALERROR).  Notably, the logging plugin leaks messages when pytest-xdist is enabled:

```
[gw0] [ 61%] SKIPPED tests/functional/test_libraries.py::test_pil_PyQt4[onefile] 
tests/functional/test_libraries.py::test_pil_plugins[onedir] imphook.py                 474 WARNING  Hidden import "MySQLdb" not found!
imphook.py                 474 WARNING  Hidden import "psycopg2" not found!
imphook.py                 474 WARNING  Hidden import "MySQLdb" not found!
imphook.py                 474 WARNING  Hidden import "psycopg2" not found!
imphook.py                 474 WARNING  Hidden import "sqlalchemy.sql.functions.func" not found!
imphook.py                 474 WARNING  Hidden import "sqlalchemy.sql.functions.func" not found!
[gw0] [ 62%] PASSED tests/functional/test_libraries.py::test_pil_plugins[onedir] 
tests/functional/test_libraries.py::test_pil_plugins[onefile] 
[gw0] [ 62%] PASSED tests/functional/test_libraries.py::test_pil_plugins[onefile] 
tests/functional/test_libraries.py::test_unidecode[onefile] 
[gw0] [ 63%] PASSED tests/functional/test_libraries.py::test_unidecode[onefile] 
tests/functional/test_hooks/test_django.py::test_django[onedir] 
[gw1] [ 64%] PASSED tests/functional/test_libraries.py::test_pandas_extension[onedir] 
tests/functional/test_libraries.py::test_pandas_extension[onefile] 
```

Reproducing this issue is easy: it occurs on virtually [every](https://ci.appveyor.com/project/matysek/pyinstaller/build/2862/job/yhleg9o4pl7xshr4) test run with verbose logging output. However, it's much trickier to figure out exactly why it's happening. I can monkeypatch the installed pytest to print out any information that you may need.

**Comment by nicoddemus** [comment] 2017-12-13 19:48
@xoviat as @thisch mentioned this is a duplicate of #3009.

For now, a workaround which you can use is to [set `log_cli_level` to a high number (`9999`)](https://docs.pytest.org/en/latest/logging.html#live-logs) so it effectively disables the "live logs" feature.

I'm closing this for now; unfortunately this might have to wait for 3.4 because it might require a change of default values, so it can't go into a bug fix release 😕

**Closed by nicoddemus** 2017-12-13 19:48 UTC

**Comment by xoviat** [comment] 2017-12-13 19:53
It's not by any means an urgent problem, and it's not worth the time to change configuration in PyInstaller. It's just something that should disappear one day when the next pytest major release rolls out.
